### PR TITLE
Remove piece of incomplete documentation

### PR DESCRIPTION
**Pull request by andreabedini**
Virtual modules are discussed right below in the library section.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by andreabedini** [comment]
I need to check if this is library pkg field or not.

**Comment by BinderDavid** [comment]
Is anything preventing this from being merged? This TODO still exists in the docs, and the field is already discussed in the package description section. I don't want to open another PR if this one is already open.

**Comment by ulysses4ever** [comment]
@andreabedini do you want to connect this to the Ready state (it's currently Draft)? Also, there's a docs build failure?

**Comment by ulysses4ever** [comment]
@Mergify rebase

**Comment by ulysses4ever** [comment]
Looks like this party of the proper is related:

```
/home/runner/work/cabal/cabal/doc/buildinfo-fields-reference.rst:507: WARNING: cabal:pkg-field reference target not found: virtual-modules
```

**Comment by BinderDavid** [comment]
The section was removed in #9400

**Pull request closed without merging**
