### PR TITLE
Stop recommending detailed-0.9, no one actually believes that.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by dcoutts** [comment]
Yeah, can't recommend it until we have tools to use it (and updated API to 1.0).

**Comment by ttuegel** [comment]
In light of #3578, I would go so far as to deprecate it.

**Comment by tfausak** [comment]
I grabbed the index of packages from Hackage and searched over them for `detailed-0.9`. Some people are using it, but not many.

``` sh
> find hackage -name '*.cabal' | wc -l
   71454
> find hackage -name '*.cabal' | xargs grep detailed-0.9 | wc -l
     677
> find hackage -name '*.cabal' | xargs grep exitcode-stdio-1.0 | wc -l
   30098
```

Those are back of the napkin numbers. I didn't parse the Cabal files, so there could be false positives. I also checked every version of every package, so packages with many versions would skew the numbers. But `exitcode-stdio-1.0` is roughly 44 times more popular than `detailed-0.9`.

**Comment by ttuegel** [comment]
> Actually... do we know if anyone is currently actually using it?

Yes, a few people are using it. I get bug reports sometimes. However, almost no one manages to use it *correctly* because the interface does things like inventing cooperative multithreading in an unintuitive way. This is, in part, a documentation problem. But, the interface is just hard to use: it does much where it should do little, and little where it should do much. As I remarked in #3578, after several years experience with `detailed-0.9`, it's now clear that there is a more useful way forward.

**Comment by BardurArantsson** [comment]
OK, I was just curious.

(FWIW, I certainly agree with deprecating it -- was mainly just wondering if the more aggressive step of outright removal in 2.0 could be justified. Perhaps not in this case.)

**Pull request merged**
