### PR TITLE
Add bkpcabal01 regression test-case

### PR DESCRIPTION
**Pull request by hvr**
This exemplifies the bpkcabal01 regression (introduced via #5863); @ezyang is aware of this

See e.g. failure at

- https://travis-ci.org/haskell/cabal/jobs/504058651#L4431
- https://travis-ci.org/haskell/cabal/jobs/504058649#L3944

### CODE REVIEW

**Comment by 23Skidoo** [comment]
> bkpcabal01

This implies the existence of `bkpcabal02`, `03`, and so on. Why not pull in them all?

**Comment by hvr** [comment]
> This implies the existence of bkpcabal02, 03, and so on.

Not necessarily... it was primarily to make a connection to the same-name testcase in GHC's testsuite :-)

> Why not pull in them all?

We should do it; I just haven't reviewed them yet to see if they're actually distinct from backpack tests we already have in cabal's testsuite....

**Comment by ezyang** [comment]
Many of the GHC tests are intended to exercise specific things that GHC is more likely to break, like recompilation avoidance. It would be nice if we could easily run tests in both places, but this has to be balanced with copy pasting.

**Comment by ezyang** [comment]
OK, I have a pretty good guess for what the problem is: ISTR in #5863 I only updated Cabal, but I feel like maybe I also have to update the logic in cabal-install too. Looking.

**Comment by ezyang** [comment]
Fixing this is a little tricky. Will look at it more tomorrow.

**Comment by ezyang** [comment]
Fix pushed. It passes my local CI, let's see what Travis says.

**Comment by hvr** [comment]
I really wish we had a GHC 8.2.3 point-release to fix stuff like the "unknown package: hole" regressions, as I'm stuck on GHC 8.2.* for the foreseeable future for many of the projects I work on... and so far my option is to use an unofficially patched GHC 8.2.3 :-/

**Comment by ezyang** [comment]
Thank you! Looks like this is good to go.

**Pull request merged**
