### PR TITLE
Remove local options from global program options

### PR DESCRIPTION
**Pull request by patrickdoc**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

---

Local options for compiler related flags are 1) applied to all packages and 2) cached. Both of which seem incorrect.

This PR removes those options from the pre-configured program DB. Note that options are still applied correctly here: https://github.com/haskell/cabal/blob/7d66cea65279ceabc474e8d354475735c0bfb94f/cabal-install/src/Distribution/Client/ProjectPlanning.hs#L1914

There are lots of related issues around weird behavior trying to apply ghc-options:
- #7816 
- #3891
- #3883 
- #3579 
- #1176 

This PR makes this `cabal.project` stanza work as intended, applying the `ghc-options` to all/only local packages:
```
program-options
    ghc-options: -Werror
```

and removes the need for this workaround:
```
package local-foo
  ghc-options: -Werror

package local-bar
  ghc-options: -Werror
```

### CODE REVIEW

**Comment by Mikolaj** [comment]
This is amazing! However, people have already got used to the wrong behaviour, so let's make sure we change it once and don't ask them to re-adjust repeatedly. Is the desired semantics completely clear or do we need to ask users, discuss again on the tickets you mentioned, etc.?

**Comment by jneira** [comment]
It is somewhat weird this did not break any test. I think we should add some sort of regression test to exercise the change and have evidences it fixes those issues

**Comment by patrickdoc** [comment]
Tests added to demonstrate old behavior/verify fix. Before the fix, tests failed with:
```
    program options local:    FAIL (1.93s)
      tests/IntegrationTests2.hs:1579:
      p
      expected: Nothing
       but got: Just ["-fno-full-laziness"]
      Use -p '/program options/&&/program options local/' to rerun this test only.
```

Here `p` is a tarball (remote) package which should _not_ have local options applied to it. But, as the test demonstrates, local options are being applied to remote packages.

I need to double check, but I believe command-line options are also passed into the "local" portion of the project config, which means this would also affect that. I think command line only affecting local packages _is_ the intended behavior, but as you mentioned it might break some use cases.

To recreate old behavior, this still works:
```
package *
    ghc-options: -Werror
```

**Review by gbaz — APPROVED** [review]

**Review by jneira — APPROVED** [review]
great fix, thanks!

**Review by Mikolaj — APPROVED** [review]
Good job. Let me try to merge this.

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Pull request merged**
