### PR TITLE
Fix cabal-version 3.4 description in cabal init

### LINKED ISSUE #8254: Wrong cabal-version 3.4 description in cabal init
On cabal HEAD, I'm getting this on cabal init -i:

```
Please choose version of the Cabal specification to use:
[...]
   6) 3.4   (+ support for 'pkg:sublib' syntax, active repo configuration, rich index-state syntax)
```

but

* "pkg:sublib syntax" has been there for a while. In 3.4 it's the _only_ syntax supported for sublibraries, so it isn't "support for pkg:lib" syntax, but rahter "dropped support for "lib" syntax for sublibraries in build-depends
* active repo configuration is a cabal-install feature that shouldn't be bound to a specific cabal-version
* same for index-state

Rather, the new mixin syntax and "optional default-language" should be mentioned, see https://cabal.readthedocs.io/en/3.6/file-format-changelog.html#cabal-version-3-4

### PR DESCRIPTION
**Pull request by fgaz**
Fixes #8254

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Comment by Mikolaj** [comment]
Hah, actually I missed that fgaz already requested the backport. Now CI got stuck, so I reran something.

**Comment by Mikolaj** [comment]
@mergify refresh

**Pull request merged**
