### PR TITLE
bootstrap.sh: bump HTTP, async, and hashable

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ezyang** [comment]
To make CI work again you also need the commit from https://github.com/haskell/cabal/issues/4566

**Comment by ilovezfs** [comment]
@ezyang Thanks! I've cherry-picked that commit.

**Comment by 23Skidoo** [comment]
LGTM, merging.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
