### PR TITLE
Bump dependency on process

### PR DESCRIPTION
**Pull request by robx**
Compare the discussion in #8208.

### CODE REVIEW

**Comment by robx** [comment]
It turns out that process-1.6.14.0 depends on base-4.10 (so GHC 8.2). (That lower bound came with [this PR](https://github.com/haskell/process/pull/207) and is probably not due to incompatibility, but just because CI doesn't test GHC versions earlier than 8.2.)

**Comment by Mikolaj** [comment]
I think we are going to need another RC, in which case there's going to be enough time to dogfood (and userfood) this change.

**Review by Mikolaj — APPROVED** [review]
That's brave so late in the release process, but seems unavoidable.

**Review by ulysses4ever — APPROVED** [review]

**Review by jneira — APPROVED** [review]
lgtm, thanks, let's see what is the behaviour in Windows (not sure when I will have time to give a try)

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.8

**Comment by Mikolaj** [comment]
I've just tried cabal from https://gitlab.haskell.org/haskell/cabal/-/jobs/1108769 and I no longer see the spurious process messages. Was worth it. :)

**Comment by Mikolaj** [comment]
It seems we need to bump up the process package one notch again due to https://github.com/NorfairKing/feedback/issues/2

I think it's not grave enough to derail 3.8.1.0, but let's backport for the benefit of the hypothetical 3.8.2.0.

**Comment by Mikolaj** [comment]
> It seems we need to bump up the process package one notch again due to [NorfairKing/feedback#2](https://github.com/NorfairKing/feedback/issues/2)

Let me do that in a new PR.

**Pull request merged**
