### PR TITLE
RFC: Common stanzas

### PR DESCRIPTION
**Pull request by phadej**
See the last commit

---

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Attempt on https://github.com/haskell/cabal/issues/2832

**Comment by phadej** [comment]
I have redone the PR. Ping @23Skidoo @hvr.

There's internal note, I'll write a user guide section about common stanzas tomorrow if that behavior is ok.

Difference to previous is that you **cannot** say

```
library:
  build-depends: foo
  include common-stanza
```

includes should be first in stanza:
```
library:
  include common-stanza
  build-depends: foo
```

**Comment by 23Skidoo** [comment]
@phadej That restriction seems reasonable to me, in fact I think that it improves readability.

**Comment by phadej** [comment]
Two questions:

- Should common stanzas be defined before use (currently: no. Done in separate pass)
- Should common stanzas be able to reference other common stanzas? (currently: no)

Easy to implement are:
- No/No: current
- Yes/Yes: we can parse common stanzas as we go, in single pass. Parsing common stanza is not much different than parsing other stanzas
- Yes/No: even simpler than above

Fourth variant is difficult, because with "Define everywhere + reference others (No/Yes):" we can write cycles:
```
common foo
  include bar

common bar
  include foo
```

**Comment by 23Skidoo** [comment]
I'd say that requiring common stanzas to be defined before use is fine (provided that the error message is helpful). Regarding inheritance -- do you want to allow only

```
common common-stanza
    include another-common-stanza
    ...
```

or also

```
common common-stanza
    include common-stanza-a
    include common-stanza-b
    ...
```

?

**Comment by phadej** [comment]
You can `include` as many common stanzas as you like. There is no technical reason to limit that.

**Comment by phadej** [comment]
To clarify the previous question, it can be posed also as *Do we want to allow including stanzas from other stanzas?*. If **yes**, than we have to require **define-before-use**.

**Comment by 23Skidoo** [comment]
> Do we want to allow including stanzas from other common stanzas?

IMO it can be useful, so I'm +1.

One question: since IIRC list fields have monoid semantics, should there be a way to explicitly set a list field to `[]`? For example, IIUC,

```
common foo
    cpp-options: -foo

common bar
    cpp-options: -bar

common foobar
    include foo
    include bar

common barfoo
    include bar
    include foo
```

will result in `foobar` having `cpp-options: -foo -bar`, and `barfoo` having `cpp-options: -bar -foo`.

Should it be possible to do something like

```
common foo
    cpp-options: -foo

common bar
    include foo
    cpp-options := -bar

common baz
    include bar
```

and have `baz`'s `cpp-options` be set to `-bar` only?

**Comment by phadej** [comment]
@23Skidoo 

> Should it be possible to do something like
```
common bar
    include foo
    cpp-options := -bar
```

That's technically challenging because that alters Cabal's lexical syntax, which is very major change.
For that example one could factor *common* (pun-intended) parts of `foo` into `quux` and have

```
common quux:
    ...

common foo
    include quux
    cpp-options: -foo

common bar
    include quux
    cpp-options := -bar

common baz
    include bar
```

**Comment by hvr** [comment]
> One question: since IIRC list fields have monoid semantics, should there be a way to explicitly set a list field to []?

What about e.g.

```
common bar
    include foo
    !cpp-options: -bar
```

?

However, I feel like we can postpone this, and it at some later spec-version incrementally, when have gained more experienced/feedback with the basic support. (But we can surely spend some thought on how we could do it at some point in the future of course)

**Comment by 23Skidoo** [comment]
> However, I feel like we can postpone this, and add it at some later spec-version incrementally, when have gained more experienced/feedback with the basic support.

Yeah, it's totally fine to postpone this. I like the !cpp-options proposal.

**Comment by phadej** [comment]
Last minute changes, but with docs:

screenshot from 2017-12-12 18-09-28

**Comment by gbaz** [comment]
do we need a docs tweak? from reddit: "Unless I'm mistaken, it appears that import has to be the first thing in a stanza, but this isn't mentioned anywhere."

(https://www.reddit.com/r/haskell/comments/85tuly/latest_hackage_deployment/dw4mf1j/)

**Comment by ekmett** [comment]
I was just bitten by precisely the same thing @gbaz mentioned here.

**Comment by domenkozar** [comment]
Doc change: https://github.com/haskell/cabal/pull/5610

**Pull request merged**
