### PR TITLE
Split the monolithic Init.hs module into 5 sub-modules.

### PR DESCRIPTION
**Pull request by m-renaud**
Init.Command - Main cabal init logic that ties everything together.
Init.Defaults - Default values for items not specified in config or arguments
Init.FileCreators - All the createXyz functions which write files (LICENSE, Main.hs, etc.)
Init.Prompt - Utilities for prompting the user for selections
Init.Utils - Misc utilities shared across the above modules

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by m-renaud** [comment]
FYI @phadej previous PR was automatically closed when I reset the branch to fix the merge conflict. Was easier just to create a new branch and PR.

**Comment by m-renaud** [comment]
Huh, interesting CI failures:

`fatal: reference is not a tree: df13421f2d5c60a4846e7de763a7bfa1adbcae06`

:confused:

**Comment by m-renaud** [comment]
Looks like it may be caused by a race condition in GitHub actions: https://github.com/actions/checkout/issues/23

**Comment by phadej** [comment]
@m-renaud try to force push, that should fix that. Thanks for upstream reference.

**Comment by m-renaud** [comment]
Sigh, looks like a lot of the checks are hanging now..

**Comment by phadej** [comment]
I restarted linux jobs, will merge if they are green.

**Comment by m-renaud** [comment]
Closing this PR since it was merged in #6650.

**Pull request closed without merging**
