### PR TITLE
Make cabal-install a library.

### PR DESCRIPTION
**Pull request by ezyang**
TODO: We should put an admonition somewhere that the library is
unstable; basically, we reserve the right to break backwards
compatibility at any point in time; but I didn't know where
the best place to put it was.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
One downside of this patchset is that we are no longer testing with asserts. But maybe we should just turn on asserts when we build the binaries in the first place.

**Comment by 23Skidoo** [comment]
/cc @dcoutts 

@ezyang Are you OK with not merging this until the 2.0 branch is created?

**Comment by BardurArantsson** [comment]
Could we get an explanation for the rationale if it *isn't* to be able to depend on it?

(Regardless of warnings you slap on things, once the cat's out of the bag, it's *very* hard to stuff it back in. If previous experience is anything to go by -- like it or not -- people *will* start depending on cabal-install and suddenly it's *your* fault if anything breaks. Doesn't matter if you had great big warnings on everything.)

**Comment by 23Skidoo** [comment]
@BardurArantsson Making CI build times shorter is the main reason.

**Comment by 23Skidoo** [comment]
Re: where to put the warning, I suggest the synopsis field, preferably in bold, so it's right in your face when you're accessing http://hackage.haskell.org/package/cabal-install

**Comment by BardurArantsson** [comment]
I would go so far as to suggest that, in addition to doc warnings, cabal-install (the library) would have to be compiled with some flag to not fail to compile as a dependency without extra work. WDYT?

**Comment by ezyang** [comment]
I'm not sure how we'd go about implementing that. One possibility is to make the library non-buildable without an explicit flag. But we still need the executable to be buildable, so we'd have to copy paste all of the deps / macro stuff to the executable stanza. Might not be too bad.

**Comment by ezyang** [comment]
Here's an updated variant of the patch which only builds the library with the lib flag. I adjusted `cabal.project` so that developers using new-build automatically build with this flag; people still using sandboxes/old-style (e.g., Appveyor) need to provide it explicitly.

**Comment by BardurArantsson** [comment]
@ezyang Fantastic! I guess all that's needed then is to add an admonition to the generated docs? (I'm assuming nobody's actually going to be uploading to Hackage, but can't be too careful! :))

(Only a little nitpick, but I'd have named the flag something *really* crazy like "yes-i-really-understand-that-im-doing-something-wrong-by-building-as-a-library", but I understand why you went with a shorter name :).)

Looking forward to seeing the build time gainz! :)

**Comment by ezyang** [comment]
I don't really want to have to add a header to each module in cabal-install. Are you suggesting we put it in the description maybe?

**Comment by BardurArantsson** [comment]
Oh, yes, just in the overall description, sorry for being unclear. Given the flag I think the danger should (now) be minimal that anyone makes the intention of making it a library :).

**Comment by ezyang** [comment]
I went to modify the description, but actually, aren't we asking for trouble if we mention that there's a library? Ideally, we just don't want the module listing to show up on Hackage. I don't know if we can actually make that happen.

**Comment by BardurArantsson** [comment]
Isn't there a flag which marks a package as "deprecated"? Maybe that's an option, but then again if it causes warnings when installing (or just makes it un-installable), then maybe not.

I kind of buy the argument that "the less attention, the better", given the existence of the flag... maybe just make the flag description even more in-your-face about "DO NOT USE THIS", etc.? :)

**Comment by ezyang** [comment]
Unfortunately, it looks like Hackage isn't smart enough to respect the `buildable` field, see: https://hackage.haskell.org/package/ezyang-unbuildable-library-test-1.0/candidate so I'll just modify synopsis.

**Comment by ezyang** [comment]
I just realized there is one important downside to this patch: if you are building the cabal executable without the lib flag with new-build, recompilation won't work (because I didn't relist all of the modules in the executable stanza in this case). We can fix this by listing every module twice but I kind of don't want to. Maybe this is fine because no new-build developer will build without the lib flag? What do people think.

**Comment by ezyang** [comment]
OK I decided I don't care.

**Comment by ezyang** [comment]
(Merged).

**Pull request closed without merging**
