### PR TITLE
CI for building doc with sphinx

### PR DESCRIPTION
**Pull request by andreasabel**
Simplified from agda/agda/.github/workflows/user-manual.yml

Simple minded.  Builds doc by
- installing python
- `make users-guide`
- upload-artifact

Maybe something more sophisticated could be done later where we push to `ghpages` or something.

Tested by downloading the artifact and having a rough look.

See new job __Users guide__ in the checks below.  Should maybe also switched to "Required".

### CODE REVIEW

**Comment by Mikolaj** [comment]
Amazing. Yes, given our experiences, I think doc building should be required.

**Review by fgaz — APPROVED** [review]
Looks good! This should be subsumed by readthedocs' pull request integration, but until we figure out what's blocking it, it makes sense to have this.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergifyio rebase

**Comment by Mikolaj** [comment]
I abused my privilege to cut the CI race condition. :)

**Pull request merged**
