### PR TITLE
Upgrade zlib <0.7

### PR DESCRIPTION
**Pull request by phadej**
Supersedes https://github.com/haskell/cabal/pull/2620.

### CODE REVIEW

**Comment by edsko** [comment]
Wait, this looks iffy to me. We ignore that final chunk always? I figured we'd have a check if it was empty or not. I would really like a comment from @dcoutts on this.

**Comment by dcoutts** [comment]
Edsko has pointed out that the empty chunk is probably a bug in zlib-0.6.1 and indeed is likely the cause of a reported segfault. I'll look into the zlib bug and then check and merge one of these zlib cabal patches.

**Comment by edsko** [comment]
So it turns this _is_ in fact correct. That bytestring argument to `DecompressStreamEnd` is trailing garbage after and should in fact be ignored. This is good to go.

**Comment by dcoutts** [comment]
Rebased to squash the earlier patches together and merged. 17959b8ca32c8086dfcd63a3d56e7b4208a8262d

Thanks @fisx and @phadej !

**Comment by grayjay** [comment]
I'm getting a failure from one of the new tests with zlib-0.5.4.2 and version 1.2.8 of the zlib C library:

    Distribution.Client.GZipUtils
      maybeDecompress:           OK
      decompress plain:          FAIL
        *** Failed! Exception: 'Codec.Compression.Zlib: premature end of compressed stream' (after 1 test): 
        []
        Use --quickcheck-replay '0 TFGenR 0000000E8566AA1300000000000F4240000000000000DF7700000009502F9000 0 1 1 0' to reproduce.
      decompress zlib:           OK
        +++ OK, passed 100 tests.
      decompress gzip:           OK
        +++ OK, passed 100 tests.

**Comment by 23Skidoo** [comment]
@grayjay Can you please open a ticket?

**Comment by grayjay** [comment]
I just opened #2704.

**Comment by 23Skidoo** [comment]
Thanks!

**Pull request closed without merging**
