### PR TITLE
Backing up only when overwritting to allow cabalisation

### LINKED ISSUE #7810: `cabal init` can no longer cabalize an existing project
`cabal init` version 3.6.2 (and before) can be instructed to build a cabal file around an existing application `app/Main.hs`.
`cabal init` from master does not seem to be able to do this.

Reproducer script:
```sh
#!/bin/sh

DIR=$(mktemp -d)
cd $DIR
mkdir app
cat > app/Main.hs <<EOF
module Main where
main :: IO ()
main = putStrLn "I was there before cabal init ran!"
EOF
${CABAL:-cabal} init -v0 -n --package-name=hello-cabal --exe --application-dir=app --main-is=Main.hs
tree
cabal run -v0
```

Testing with `cabal-3.6.2`:
```
$ CABAL=cabal-3.6.2 ./reproduce.sh
...
.
├── CHANGELOG.md
├── app
│   └── Main.hs
└── hello-cabal.cabal

1 directory, 3 files
I was there before cabal init ran!
```
This is the expected behavior: a cabal package `hello-cabal.cabal` is built around `app/Main.hs`, and running via this cabal package runs this `Main.hs`.

Testing with current `master`:
```
$ ./reproduce.sh
.
├── CHANGELOG.md
├── app
│   └── Main.hs
├── app.save0
│   └── Main.hs
└── hello-cabal.cabal

2 directories, 4 files
Hello, Haskell!
```
This replaces the existing `app/Main.hs` with a standard template that prints `Hello, Haskell!` (and puts the user code into `app.save0`).

### PR DESCRIPTION
**Pull request by ptkato**
Fixes #7810.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by fgaz** [comment]
Can we have a regression test?

**Comment by Kleidukos** [comment]
@ptkato ping? :)

**Comment by ptkato** [comment]
Yes, I added the test, but it seems that there's something wonky in the interaction between the `cabal-testsuite` and `cabal init`; the test won't work, it throws me an error and I'm clueless as to what it is supposed to mean:

```
init.test.hs: /path/to/cabal: createProcess: chdir: does not exist (No such file or directory)
```

I think I'm likely missing something within the test setup.

**Comment by ptkato** [comment]
I think I found the culprit. `cabal` (from the cabal-testsuite prelude) doesn't consider `init` at all:

https://github.com/haskell/cabal/blob/2ae46a33dc27fa9dbeea700db069621600050e8e/cabal-testsuite/src/Test/Cabal/Prelude.hs#L280-L291

I believe that simply adding `init` to that list should fix the problem.

**Review by Kleidukos — APPROVED** [review]
LGTM!

**Review by gbaz — APPROVED** [review]

**Pull request merged**
