### PR TITLE
Use the cli flags in fetching packages in building a project config 

### PR DESCRIPTION
**Pull request by gbaz**
fixes a logic bug.

resolves https://github.com/haskell/cabal/issues/7775

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Doh. Well tracked down.

**Comment by bacchanalia** [comment]
does this need a changelog?

**Comment by Mikolaj** [comment]
> does this need a changelog?

A good questions. Was this bug introduced since 3.6.2? I guess not?

**Review by Kleidukos — APPROVED** [review]

**Comment by jneira** [comment]
@Mergifyio rebase master

**Comment by andreasabel** [comment]
Merged without regression test?

**Comment by Mikolaj** [comment]
Yes, let's add the test you describe in the issue and a changelog too.

I guess we need to stop approving PRs meaning "good to go as soon as you add finishing touches", because then we forget, see an approved PR and merge as is.

**Comment by Mikolaj** [comment]
I made a fuss on the Matrix/IRC channel.

**Pull request merged**
