### PR TITLE
Fix #3440.

### LINKED ISSUE #3440: cabal-install 1.24 fails to bootstrap on openSUSE 11.4
I just tried bootstrapping cabal-install 1.24 with GHC 8.0.1 on openSUSE 11.4 and here's what I got:

```
# ./bootstrap.sh
Using gcc for C compiler. If this is not what you want, set CC.
./bootstrap.sh: line 76: [: too many arguments
Using /usr/lib64/gcc/x86_64-suse-linux/4.5/collect2
/usr/lib64/gcc/x86_64-suse-linux/4.5/../../../../x86_64-suse-linux/bin/ld instead.
Checking installed packages for ghc-8.0.1...
deepseq is already installed and the version is ok.
binary is already installed and the version is ok.
time is already installed and the version is ok.
Cabal is already installed and the version is ok.
transformers is already installed and the version is ok.
mtl-2.2.1 will be downloaded and installed.
text-1.2.2.1 will be downloaded and installed.
parsec-3.1.9 will be downloaded and installed.
network-2.6.2.1 will be downloaded and installed.
old-locale-1.0.0.7 will be downloaded and installed.
old-time-1.1.0.3 will be downloaded and installed.
HTTP-4000.3.3 will be downloaded and installed.
zlib-0.6.1.1 will be downloaded and installed.
random-1.1 will be downloaded and installed.
stm-2.4.4.1 will be downloaded and installed.
async-2.1.0 will be downloaded and installed.
base16-bytestring-0.1.1.6 will be downloaded and installed.
base64-bytestring-1.0.0.1 will be downloaded and installed.
cryptohash-sha256-0.11.7.1 will be downloaded and installed.
ed25519-0.0.5.0 will be downloaded and installed.
tar-0.5.0.1 will be downloaded and installed.
hashable-1.2.4.0 will be downloaded and installed.
hackage-security-0.5.1.0 will be downloaded and installed.

Downloading mtl-2.2.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15391  100 15391    0     0  37486      0 --:--:-- --:--:-- --:--:-- 42167
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1749    0  1749    0     0   4713      0 --:--:-- --:--:-- --:--:--  5332
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Setup: Unrecognised flags:
/usr/lib64/gcc/x86_64-suse-linux/4.5/../../../../x86_64-suse-linux/bin/ld

Error during cabal-install bootstrap:
Configuring the mtl package failed.
```

Bootstrapping with GHC 7.10.3 goes a step further but also errors:

```
./bootstrap.sh
Using gcc for C compiler. If this is not what you want, set CC.
./bootstrap.sh: line 76: [: too many arguments
Using /usr/lib64/gcc/x86_64-suse-linux/4.5/collect2
/usr/lib64/gcc/x86_64-suse-linux/4.5/../../../../x86_64-suse-linux/bin/ld instead.
Checking installed packages for ghc-7.10.3...
deepseq is already installed and the version is ok.
binary is already installed and the version is ok.
time is already installed and the version is ok.
Cabal-1.24.0.0 will be downloaded and installed.
transformers is already installed and the version is ok.
mtl-2.2.1 will be downloaded and installed.
text-1.2.2.1 will be downloaded and installed.
parsec-3.1.9 will be downloaded and installed.
network-2.6.2.1 will be downloaded and installed.
old-locale-1.0.0.7 will be downloaded and installed.
old-time-1.1.0.3 will be downloaded and installed.
HTTP-4000.3.3 will be downloaded and installed.
zlib-0.6.1.1 will be downloaded and installed.
random-1.1 will be downloaded and installed.
stm-2.4.4.1 will be downloaded and installed.
async-2.1.0 will be downloaded and installed.
base16-bytestring-0.1.1.6 will be downloaded and installed.
base64-bytestring-1.0.0.1 will be downloaded and installed.
cryptohash-sha256-0.11.7.1 will be downloaded and installed.
ed25519-0.0.5.0 will be downloaded and installed.
tar-0.5.0.1 will be downloaded and installed.
hashable-1.2.4.0 will be downloaded and installed.
hackage-security-0.5.1.0 will be downloaded and installed.

Downloading Cabal-1.24.0.0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  428k  100  428k    0     0   668k      0 --:--:-- --:--:-- --:--:--  795k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14292    0 14292    0     0  35760      0 --:--:-- --:--:-- --:--:-- 39810
[ 1 of 84] Compiling Distribution.Simple.Program.Internal ( Distribution/Simple/Program/Internal.hs, Distribution/Simple/Program/Internal.o )
[ 2 of 84] Compiling Distribution.Compat.MonadFail ( Distribution/Compat/MonadFail.hs, Distribution/Compat/MonadFail.o )
[ 3 of 84] Compiling Distribution.Compat.GetShortPathName ( Distribution/Compat/GetShortPathName.hs, Distribution/Compat/GetShortPathName.o )
[ 4 of 84] Compiling Distribution.GetOpt ( Distribution/GetOpt.hs, Distribution/GetOpt.o )
[ 5 of 84] Compiling Distribution.Compat.Binary ( Distribution/Compat/Binary.hs, Distribution/Compat/Binary.o )
[ 6 of 84] Compiling Distribution.Compat.Semigroup ( Distribution/Compat/Semigroup.hs, Distribution/Compat/Semigroup.o )
[ 7 of 84] Compiling Distribution.Lex ( Distribution/Lex.hs, Distribution/Lex.o )
[ 8 of 84] Compiling Distribution.TestSuite ( Distribution/TestSuite.hs, Distribution/TestSuite.o )
[ 9 of 84] Compiling Distribution.Simple.PreProcess.Unlit ( Distribution/Simple/PreProcess/Unlit.hs, Distribution/Simple/PreProcess/Unlit.o )
[10 of 84] Compiling Distribution.Simple.CCompiler ( Distribution/Simple/CCompiler.hs, Distribution/Simple/CCompiler.o )
[11 of 84] Compiling Distribution.PackageDescription.Utils ( Distribution/PackageDescription/Utils.hs, Distribution/PackageDescription/Utils.o )
[12 of 84] Compiling Distribution.Compat.ReadP ( Distribution/Compat/ReadP.hs, Distribution/Compat/ReadP.o )
[13 of 84] Compiling Distribution.ReadE ( Distribution/ReadE.hs, Distribution/ReadE.o )
[14 of 84] Compiling Distribution.Verbosity ( Distribution/Verbosity.hs, Distribution/Verbosity.o )
[15 of 84] Compiling Distribution.Text ( Distribution/Text.hs, Distribution/Text.o )
[16 of 84] Compiling Distribution.ModuleName ( Distribution/ModuleName.hs, Distribution/ModuleName.o )
[17 of 84] Compiling Distribution.System ( Distribution/System.hs, Distribution/System.o )
[18 of 84] Compiling Distribution.Version ( Distribution/Version.hs, Distribution/Version.o )
[19 of 84] Compiling Distribution.License ( Distribution/License.hs, Distribution/License.o )
[20 of 84] Compiling Distribution.Package ( Distribution/Package.hs, Distribution/Package.o )
[21 of 84] Compiling Distribution.Simple.GHC.IPIConvert ( Distribution/Simple/GHC/IPIConvert.hs, Distribution/Simple/GHC/IPIConvert.o )
[22 of 84] Compiling Language.Haskell.Extension ( Language/Haskell/Extension.hs, Language/Haskell/Extension.o )
[23 of 84] Compiling Distribution.Compiler ( Distribution/Compiler.hs, Distribution/Compiler.o )
[24 of 84] Compiling Distribution.Simple.InstallDirs ( Distribution/Simple/InstallDirs.hs, Distribution/Simple/InstallDirs.o )
[25 of 84] Compiling Distribution.PackageDescription ( Distribution/PackageDescription.hs, Distribution/PackageDescription.o )
[26 of 84] Compiling Distribution.Compat.Exception ( Distribution/Compat/Exception.hs, Distribution/Compat/Exception.o )
[27 of 84] Compiling Distribution.Compat.Internal.TempFile ( Distribution/Compat/Internal/TempFile.hs, Distribution/Compat/Internal/TempFile.o )
[28 of 84] Compiling Distribution.Compat.CopyFile ( Distribution/Compat/CopyFile.hs, Distribution/Compat/CopyFile.o )
[29 of 84] Compiling Distribution.Simple.Utils ( Distribution/Simple/Utils.hs, Distribution/Simple/Utils.o )
[30 of 84] Compiling Distribution.PackageDescription.Configuration ( Distribution/PackageDescription/Configuration.hs, Distribution/PackageDescription/Configuration.o )
[31 of 84] Compiling Distribution.PackageDescription.Check ( Distribution/PackageDescription/Check.hs, Distribution/PackageDescription/Check.o )
[32 of 84] Compiling Distribution.ParseUtils ( Distribution/ParseUtils.hs, Distribution/ParseUtils.o )
[33 of 84] Compiling Distribution.InstalledPackageInfo ( Distribution/InstalledPackageInfo.hs, Distribution/InstalledPackageInfo.o )
[34 of 84] Compiling Distribution.Simple.GHC.IPI642 ( Distribution/Simple/GHC/IPI642.hs, Distribution/Simple/GHC/IPI642.o )
[35 of 84] Compiling Distribution.PackageDescription.Parse ( Distribution/PackageDescription/Parse.hs, Distribution/PackageDescription/Parse.o )
[36 of 84] Compiling Distribution.Simple.Command ( Distribution/Simple/Command.hs, Distribution/Simple/Command.o )
[37 of 84] Compiling Distribution.Simple.Compiler ( Distribution/Simple/Compiler.hs, Distribution/Simple/Compiler.o )
[38 of 84] Compiling Distribution.Simple.GHC.ImplInfo ( Distribution/Simple/GHC/ImplInfo.hs, Distribution/Simple/GHC/ImplInfo.o )
[39 of 84] Compiling Distribution.Simple.PackageIndex ( Distribution/Simple/PackageIndex.hs, Distribution/Simple/PackageIndex.o )
[40 of 84] Compiling Distribution.Utils.NubList ( Distribution/Utils/NubList.hs, Distribution/Utils/NubList.o )
[41 of 84] Compiling Distribution.Compat.Environment ( Distribution/Compat/Environment.hs, Distribution/Compat/Environment.o )
[42 of 84] Compiling Distribution.Simple.Program.Find ( Distribution/Simple/Program/Find.hs, Distribution/Simple/Program/Find.o )
[43 of 84] Compiling Distribution.Simple.Program.Types ( Distribution/Simple/Program/Types.hs, Distribution/Simple/Program/Types.o )
[44 of 84] Compiling Distribution.Simple.Program.Run ( Distribution/Simple/Program/Run.hs, Distribution/Simple/Program/Run.o )
[45 of 84] Compiling Distribution.Simple.Program.Builtin ( Distribution/Simple/Program/Builtin.hs, Distribution/Simple/Program/Builtin.o )
[46 of 84] Compiling Distribution.Simple.Program.Db ( Distribution/Simple/Program/Db.hs, Distribution/Simple/Program/Db.o )
[47 of 84] Compiling Distribution.Simple.Program ( Distribution/Simple/Program.hs, Distribution/Simple/Program.o )
[48 of 84] Compiling Distribution.Simple.Program.Strip ( Distribution/Simple/Program/Strip.hs, Distribution/Simple/Program/Strip.o )
[49 of 84] Compiling Distribution.Simple.Setup ( Distribution/Simple/Setup.hs, Distribution/Simple/Setup.o )
[50 of 84] Compiling Distribution.Simple.LocalBuildInfo ( Distribution/Simple/LocalBuildInfo.hs, Distribution/Simple/LocalBuildInfo.o )
[51 of 84] Compiling Distribution.Simple.Build.Macros ( Distribution/Simple/Build/Macros.hs, Distribution/Simple/Build/Macros.o )
[52 of 84] Compiling Distribution.Simple.BuildPaths ( Distribution/Simple/BuildPaths.hs, Distribution/Simple/BuildPaths.o )
[53 of 84] Compiling Distribution.Simple.Build.PathsModule ( Distribution/Simple/Build/PathsModule.hs, Distribution/Simple/Build/PathsModule.o )
[54 of 84] Compiling Distribution.Simple.BuildTarget ( Distribution/Simple/BuildTarget.hs, Distribution/Simple/BuildTarget.o )
[55 of 84] Compiling Distribution.Simple.HaskellSuite ( Distribution/Simple/HaskellSuite.hs, Distribution/Simple/HaskellSuite.o )
[56 of 84] Compiling Distribution.Simple.JHC ( Distribution/Simple/JHC.hs, Distribution/Simple/JHC.o )
[57 of 84] Compiling Distribution.Simple.Program.Ar ( Distribution/Simple/Program/Ar.hs, Distribution/Simple/Program/Ar.o )
[58 of 84] Compiling Distribution.Simple.Test.Log ( Distribution/Simple/Test/Log.hs, Distribution/Simple/Test/Log.o )
[59 of 84] Compiling Distribution.Simple.UHC ( Distribution/Simple/UHC.hs, Distribution/Simple/UHC.o )
[60 of 84] Compiling Distribution.Simple.Program.GHC ( Distribution/Simple/Program/GHC.hs, Distribution/Simple/Program/GHC.o )
[61 of 84] Compiling Distribution.Simple.GHC.Internal ( Distribution/Simple/GHC/Internal.hs, Distribution/Simple/GHC/Internal.o )
[62 of 84] Compiling Distribution.Simple.Program.HcPkg ( Distribution/Simple/Program/HcPkg.hs, Distribution/Simple/Program/HcPkg.o )
[63 of 84] Compiling Distribution.Simple.LHC ( Distribution/Simple/LHC.hs, Distribution/Simple/LHC.o )
[64 of 84] Compiling Distribution.Simple.Program.Hpc ( Distribution/Simple/Program/Hpc.hs, Distribution/Simple/Program/Hpc.o )
[65 of 84] Compiling Distribution.Simple.Hpc ( Distribution/Simple/Hpc.hs, Distribution/Simple/Hpc.o )
[66 of 84] Compiling Distribution.Simple.Program.Ld ( Distribution/Simple/Program/Ld.hs, Distribution/Simple/Program/Ld.o )
[67 of 84] Compiling Distribution.Simple.GHC ( Distribution/Simple/GHC.hs, Distribution/Simple/GHC.o )
[68 of 84] Compiling Distribution.Simple.GHCJS ( Distribution/Simple/GHCJS.hs, Distribution/Simple/GHCJS.o )
[69 of 84] Compiling Distribution.Simple.Install ( Distribution/Simple/Install.hs, Distribution/Simple/Install.o )
[70 of 84] Compiling Distribution.Simple.Program.Script ( Distribution/Simple/Program/Script.hs, Distribution/Simple/Program/Script.o )
[71 of 84] Compiling Distribution.Simple.Register ( Distribution/Simple/Register.hs, Distribution/Simple/Register.o )
[72 of 84] Compiling Distribution.Compat.CreatePipe ( Distribution/Compat/CreatePipe.hs, Distribution/Compat/CreatePipe.o )
[73 of 84] Compiling Distribution.Simple.Test.ExeV10 ( Distribution/Simple/Test/ExeV10.hs, Distribution/Simple/Test/ExeV10.o )
[74 of 84] Compiling Distribution.Simple.Test.LibV09 ( Distribution/Simple/Test/LibV09.hs, Distribution/Simple/Test/LibV09.o )
[75 of 84] Compiling Distribution.Simple.PreProcess ( Distribution/Simple/PreProcess.hs, Distribution/Simple/PreProcess.o )
[76 of 84] Compiling Distribution.Simple.Configure ( Distribution/Simple/Configure.hs, Distribution/Simple/Configure.o )
[77 of 84] Compiling Distribution.Simple.Build ( Distribution/Simple/Build.hs, Distribution/Simple/Build.o )
[78 of 84] Compiling Distribution.Simple.Haddock ( Distribution/Simple/Haddock.hs, Distribution/Simple/Haddock.o )
[79 of 84] Compiling Distribution.Simple.SrcDist ( Distribution/Simple/SrcDist.hs, Distribution/Simple/SrcDist.o )
[80 of 84] Compiling Distribution.Simple.UserHooks ( Distribution/Simple/UserHooks.hs, Distribution/Simple/UserHooks.o )
[81 of 84] Compiling Distribution.Simple.Bench ( Distribution/Simple/Bench.hs, Distribution/Simple/Bench.o )
[82 of 84] Compiling Distribution.Simple.Test ( Distribution/Simple/Test.hs, Distribution/Simple/Test.o )
[83 of 84] Compiling Distribution.Simple ( Distribution/Simple.hs, Distribution/Simple.o )
[84 of 84] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Setup: Unrecognised flags:
/usr/lib64/gcc/x86_64-suse-linux/4.5/../../../../x86_64-suse-linux/bin/ld

Error during cabal-install bootstrap:
Configuring the Cabal package failed.
```

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fix [provided by @mvkorpel](https://github.com/haskell/cabal/issues/3440#issuecomment-227134861).

/cc @geoff-codes

### CODE REVIEW

**Comment by ezyang** [comment]
Can we have a comment explaining why this is not necessary? I'm imagining some future developer refactoring this code, losing the break, and testing on Linux and thinking it works.

**Comment by instantepiphany** [comment]
@ezyang From the issue that this fix is for, https://github.com/haskell/cabal/issues/3440, the patch has a comment that falling back to `ld` may be ok. FYI.

**Comment by ezyang** [comment]
I mean code comment ;)

**Comment by instantepiphany** [comment]
Yeah, I mean @23Skidoo could add that into the PR 👅

**Comment by 23Skidoo** [comment]
The `break` in the `else` branch is needed for those cases when both `$CC -print-prog-name=collect2` and `$CC -print-prog-name=ld` return an absolute path. Otherwise `LINK` get set to `"/foo/bar/collect2 /baz/quux/ld"`.

**Comment by 23Skidoo** [comment]
Added a comment.

**Pull request merged**
