### PR TITLE
Allow limiting the scope of '--allow-newer'. 

### LINKED ISSUE #2756: Extend `--allow-newer` to limit scope to single packages
When trying to fixup cabal-metadata by empirical trial & error tweaks of inter-package depedencies, it's sometimes useful to lift the upper bound only for a single package rather than for _every_ package, as other packages may rely on automatic cabal flags toggled by version ranges (which `--allow-newer` sometimes breaks) or we actually want all other constraints to remain intact to keep the solver from picking a bad install-plan that may result if _all_ packages ignore that specific upper bound.

So, I hereby propose to enhance the `--allow-never` feature to allow to specify which package a constraint relaxation shall apply to. Here's a suggested backward-compatible syntax:

```
--allow-newer foo:base,lens,bar:time
```

whose meaning would be
- drop any upper bound for `base` specified by package `foo`,
- drop any upper bound for `lens` specified by any package
- drop any upper bound for `time` specified by package `bar`

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #2756.

### CODE REVIEW

**Comment by hvr** [comment]
@23Skidoo :+1:

one question though, does the allow-newer field only allow `True`/`False`? @dcoutts: as the new `cabal.project` features allows per-package flags; it'd be neat if we could then write something like

```
-- applies to all
with-compiler: /opt/ghc/8.0.1/bin/ghc
-- corresponds to `--allow-newer: ghc-prim`
allow-newer: ghc-prim
tests: False

-- corresponds to `--allow-never aeson:base,aeson:process`
package aeson
   allow-newer: base,process

**Comment by 23Skidoo** [comment]
> one question though, does the `allow-newer` field only allow `True`/`False`?

Yes, but I can change it if you want.

**Comment by 23Skidoo** [comment]
> Yes, but I can change it to also support the full syntax if you want.
Done.

**Pull request merged**
