### PR TITLE
Improve --test/benchmark-options test accuracy

### PR DESCRIPTION
**Pull request by DanielG**
Just a quick fixup for #6224

### CODE REVIEW

**Comment by phadej** [comment]
Can this be rebased on top of current `master`?

**Comment by gbaz** [comment]
This pr just improves the accuracy of a test. Its sat around for no good reason -- if it builds we should merge.

**Review by gbaz — APPROVED** [review]

**Comment by gbaz** [comment]
Hrm... and it doesn't pass!

@DanielG thoughts?

**Comment by Mikolaj** [comment]
@DanielG: humble ping? :)

**Comment by Mikolaj** [comment]
@DanielG: humble ping 2? :)

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Comment by Mikolaj** [comment]
Ooh, it didn't fix itself. :(

What's exactly going on here? Where perhaps the tests fixed by somebody else a bit differently and that's why this fails?

**Comment by Mikolaj** [comment]
@Mergifyio rebase

**Comment by Mikolaj** [comment]
It didn't fix itself again; how come? :(

**Comment by ulysses4ever** [comment]
@Mergify rebase

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
That's unacceptable. Errors don't fix themselves after enough time. We need a programming language in which they do.

**Comment by Mikolaj** [comment]
That's more like it! :)

@DanielG: could you kindly verify that the version that passed the tests and got merged is as intended? Thank you for your work.

**Comment by Mikolaj** [comment]
@DanielG: ping?

**Pull request merged**
