### PR TITLE
Bump a number of dependencies

### PR DESCRIPTION
**Pull request by ffaf1**
Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Comment by fgaz** [comment]
Workflow with constraints: https://github.com/haskell/cabal/actions/runs/7756697472

**Comment by fgaz** [comment]
Looks like rere is blocking containers 0.7 https://github.com/haskell/cabal/actions/runs/7756730946/job/21154646718#step:13:25

**Comment by ulysses4ever** [comment]
Why don't you allow-newer it for everything?

**Comment by fgaz** [comment]
Then I wouldn't discover dependencies with stricter bounds. We can also try to allow-newer everything and bump in advance, either is fine with me

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by ffaf1** [comment]
@mergify backport 3.10

**Pull request merged**
