### PR TITLE
Add -Wunused-packages to the packages

### PR DESCRIPTION
**Pull request by Kleidukos**
Cabal, Cabal-syntax, cabal-install

Depends on https://github.com/haskell/cabal/pull/9662

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Not sure if these should go into .cabal files or the project files, but I don't mind either.

**Review by geekosaur — APPROVED** [review]

**Comment by ulysses4ever** [comment]
https://github.com/haskell/cabal/pull/9662 was merged so I take the liberty to auto-rebase and see if this passes.

**Comment by Kleidukos** [comment]
CI says "tar is an extraneous dependency". I read that cabal arrived there while trying to build cabal-install (Failed to build cabal-install-3.11.0.0).

There are two entries for tar in cabal-install's cabal file, none of them seem to be redundant because build fails when I remove either one of them.

**Comment by philderbeast** [comment]
@Kleidukos the `#if MIN_VERSION_tar(_, _, _)` conditionals will only be available if `tar` is a dependency.

**Comment by Kleidukos** [comment]
Ah, GHC doesn't know that when doing dependency analysis…

**Comment by philderbeast** [comment]
I tried the fix from https://github.com/haskell/cabal/pull/9557#issuecomment-1873301715 and it works for `ghc-8.10.7`.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
Job [Validate macos-latest ghc-9.8.1](https://github.com/haskell/cabal/actions/runs/7887688095/job/21523507553?pr=9663#logs) got cancelled after 4h. Let me restart.

**Pull request merged**
