### PR TITLE
Docs: make Sphinx stricter

### PR DESCRIPTION
**Pull request by andreasabel**
Added flags to sphinx-build to make it stricter:
- `-n`: more warnings
- `-W`: warnings to errors
- `-E`: rebuild

This will hopefully prevent errors creeping in to the docs (e.g. broken references such as #7469).

Thanks to these flags, I fixed two issues (see additional commits).

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Not nearly enough experience on my part, but LGTM. Citing from IRC:

> somebody asked (here? on gibhub) if we build docs as part of CI; we don't, right? should we? I guess we should, unless it takes forever?

**Comment by Mikolaj** [comment]
OK, got the question and the answer, so we now need a PR: https://github.com/haskell/cabal/pull/7586#issuecomment-907874571

**Comment by andreasabel** [comment]
@fgaz wrote:
> I think we shouldn't have `-W` in the makefile, only in CI (like it's done for `-Werror` for haskell code).

Is the Makefile shipped?  I thought it is developers only.

> So in the makefile:
> 
> ```makefile
> SPHINX_FLAGS += -n --keep-going -E
> ```

Can I then still override the flags with `make SPHINX_FLAGS= users-guide`?

**Comment by fgaz** [comment]
> Is the Makefile shipped? I thought it is developers only.

that's right, but I still think it'd be nicer to not fail on warnings when writing docs so that one can still preview them while fixing the warnings (like for haskell). 

> Can I then still override the flags with make SPHINX_FLAGS= users-guide?

yes. from what I understand `make users-guide SPHINX_FLAGS=...` overrides, while `SPHINX_FLAGS=... make users-guide` makes the `+=` append

**Review by fgaz — APPROVED** [review]
By the way that above is just a weak preference so I'll just give an approve. It can also be done later when someone adds CI for the guide

**Review by emilypi — APPROVED** [review]

**Comment by andreasabel** [comment]
@fgaz
> but I still think it'd be nicer to not fail on warnings when writing docs so that one can still preview them while fixing the warnings

If it turns out that `-W` is a nuisance to developers, it can be changed back.  
Note also that with `--keep-going` you will still see _all_ the errors (at least so it is promised).  An advantage of `-W` by default (as opposed to just in the CI) is a quicker feedback cycle (if it passes locally, it also passed the CI).

**Comment by Mikolaj** [comment]
Thank you!

**Pull request merged**
