### PR TITLE
Revert workaround to filter JavaScriptFFI out on GHC versions where G…

### PR DESCRIPTION
**Pull request by JoshMeredith**
A previous Cabal MR (https://github.com/haskell/cabal/pull/3997) added a workaround for GHC incorrectly returning `JavaScriptFFI` in the list of `ghc --supported-extensions` (https://gitlab.haskell.org/ghc/ghc/-/issues/11214).

With the upstreaming of GHCJS into the GHC JavaScript backend, this should be fixed in GHC (https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10505) so that non-JavaScript targets don't returning this extension, allowing the workaround to be reverted in Cabal for newer GHC versions.

### CODE REVIEW

**Comment by Kleidukos** [comment]
@JoshMeredith Hi! Is this something that you plan on backporting to the other minor releases? Will we have to perform a version check on GHC from cabal-install to make sure that the caller's GHC has incorporated your patch?

**Comment by JoshMeredith** [comment]
No current plans for this to be backported in GHC, so I believe the major version check I've included in this MR will have to stay around.

The JavaScript backend doesn't actually use this language extension (it works without it), so there's not a strong need for this to be fixed in that way - but the existence of it is preventing the JavaScript backend from reaching full Cabal support.

**Review by hsyl20 — APPROVED** [review]

**Review by Kleidukos — APPROVED** [review]

**Comment by Kleidukos** [comment]
@JoshMeredith jolly good. Shall I let you put the "squash + merge me" label?

**Comment by JoshMeredith** [comment]
@Kleidukos I'd be excited to add the label, but I'm not sure I have access to do so

**Pull request merged**
