### PR TITLE
cabal-testsuite.cabal: bump custom-setup bounds on Cabal(-syntax) after the release

### PR DESCRIPTION
**Pull request by ulysses4ever**
**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Huh, doctests and one quick job fail. Any ideas why?

**Comment by geekosaur** [comment]
It looks like doctest and field syntax reference are still using cabal 3.10.3.0 (ghcup default?), whereas everything else is using 3.12.1.0.

**Comment by ulysses4ever** [comment]
Great catch, thanks a lot! We should always say "latest" for cabal-install in ghcup configs.

**Review by Mikolaj — APPROVED** [review]

**Comment by mpickering** [comment]
It seems to me the bug here is that we specify `cabal-version: latest` in `setup-haskell`. My opinion is that it's better to pin this to something specific and update it in an orderly way (otherwise you get these situations where CI is completely broken and blocking patches).

**Comment by mpickering** [comment]
I pushed another commit to fix the quick jobs.

**Review by mpickering — APPROVED** [review]

**Comment by ulysses4ever** [comment]
thanks everyone for pushing it over the line! Sadly, the holiday caught me off-guard and I couldn't finish it in a timely manner.

**Comment by ulysses4ever** [comment]
@mergify backport 3.12

**Pull request merged**
