### PR TITLE
Auto-approve Dependabot PRs

### PR DESCRIPTION
**Pull request by peterbecich**
**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

Suggestion to auto-approve Dependabot PRs

Copied from:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request

This works fine in `hackage-server`: https://github.com/haskell/hackage-server/pull/1289

This will not auto-merge Dependabot PRs; that's documented here: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
This does not constitute administrative approval; I'd rather leave that to someone else.

**Comment by ulysses4ever** [comment]
As simple as it looks like on the surface, it's not entirely clear that we want to auto-approve **all** Dependabot suggestions. Consider discussion on https://github.com/haskell/cabal/pull/8807 for example

**Review by Mikolaj — CHANGES_REQUESTED** [review]
Let's discuss more before we merge this.

**Comment by ffaf1** [comment]
I see some convenience in this, but there are risks (breaking stuff by auto mis-approvals, more stuff that breaks in CI). I don’t think the former is worth the latter.

**Comment by geekosaur** [comment]
For what it's worth, xmonad regularly sees CI breakage from dependabot updates because Haskell-CI hasn't caught up with it yet or because it's not compatible with older platforms we test on. (See for example https://github.com/xmonad/xmonad/pull/491#issuecomment-1903702327.)

**Pull request closed without merging**
