### PR TITLE
Get rid of uploading, see if we are in time limit.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
It looks like we'll need upload shenanigans for OS X.

**Comment by 23Skidoo** [comment]
Closing for now, feel free to reopen if needed.

**Comment by ezyang** [comment]
New version only gets rid of uploading for Linux.

**Comment by 23Skidoo** [comment]
Travis still red, closing for now. Feel free to reopen.

**Pull request closed without merging**
