### PR TITLE
Pass some haddock flags to dependencies

### PR DESCRIPTION
**Pull request by kokobd**
In #8104 and #395, we found that some haddock flags specified on command line args are not passed down to dependencies. This PR aims to fix the behavior. It works, but I'm not sure this is the intended position to modify. And I will add some tests later.

---
* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by Mikolaj** [comment]
`Legacy.hs` certainly does not inspire confidence, but I have no idea where else it could be passed, either. @Kleidukos: any hints about how cabal invokes haddock for dependencies and how to pass options there that are present in the original `cabal haddock ...` invocation?

**Comment by Kleidukos** [comment]
No unfortunately I do not know this part at all

**Comment by coot** [comment]
@Mikolaj the `haddock` command is using `commandLineFlagsToProjectConfig`; the `build` command, on the other hand, is indeed using a different code path, it gets the flags from `ElaboratedConfiguredPackage`.

**Review by coot — APPROVED** [review]
LGTM

**Comment by kokobd** [comment]
@coot build command calls `commandLineFlagsToProjectConfig` indirectly. See the call hierarchy:
image

I tested it by calling `buildAction` in my tool.

**Review by Mikolaj — CHANGES_REQUESTED** [review]
It would be wonderful if this fixed the issues. Where can I see the proof that it indeed does so (at least one case)? Could you re-enable a known failing test, modify an existing test or write a new test to exemplify that? Might I also ask for tiny changelog file? Please yell if you get stuck.

**Comment by kokobd** [comment]
@Mikolaj I'm not aware of an existing test for this case. Is it suitable to add a test case in `cabal-install/tests/IntegrationTest2` to exercise [`buildAction`](https://hackage.haskell.org/package/cabal-install-3.8.1.0/docs/Distribution-Client-CmdBuild.html#v:buildAction) directly?

> Might I also ask for tiny changelog file?

Sure, I will.

**Comment by Mikolaj** [comment]
> Is it suitable to add a test case in cabal-install/tests/IntegrationTest2 to exercise [buildAction](https://hackage.haskell.org/package/cabal-install-3.8.1.0/docs/Distribution-Client-CmdBuild.html#v:buildAction) directly?

Yes, of course. Myself I'd probably copy-paste and modify one of the tests that come up with

    git grep "cabal.*haddock"

but I'm very clueless about out test infrastructure even after all these months tripping over it.

**Comment by kokobd** [comment]
@Mikolaj Added tests for `--haddock-quickjump` and `--haddock-hoogle` under `cabal-testsuite`. The test framework is complex, but awesome ;)

Need to mention that before this PR, `--haddock-quickjump` is not passed to dependencies (the content of `cabal-hash.txt` file of dependencies shows that). But `doc-index.json` is generated. Not sure what code makes it work.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
> @Mikolaj Added tests for `--haddock-quickjump` and `--haddock-hoogle` under `cabal-testsuite`. The test framework is complex, but awesome ;)

Isn't it? I'm in awe myself.

> Need to mention that before this PR, `--haddock-quickjump` is not passed to dependencies (the content of `cabal-hash.txt` file of dependencies shows that). But `doc-index.json` is generated. Not sure what code makes it work.

I remember encountering some bugs related to that (e.g., haddocks for cabal-3.8.1 not building at all with new GHCs; also the need to add --quickjump manually somewhere) and tickets about them. May be worth a search in our issue tracker to cross-check.

**Comment by kokobd** [comment]
Okay, it's failing for MacOS and Windows, and retrying doesn't work. I will look into that.

**Comment by ulysses4ever** [comment]
Just FYI  "Validate windows-latest ghc-9.0.2" is a known flaky test. It's most likely has nothing to do with your changes.

**Comment by Mikolaj** [comment]
It seems we are hitting the problem of non-isolated store here (on Windows at least). I took the liberty of rerunning the tests.

**Comment by Mikolaj** [comment]
Hmm, exactly the same errors. Strange.

**Comment by kokobd** [comment]
really "deterministic" lol

**Comment by ulysses4ever** [comment]
Maybe we should fast track #8460.

**Comment by Mikolaj** [comment]
Fast-tracked. To benefit, this PR needs to rebase on master.

**Comment by kokobd** [comment]
Added `squash+merge me` label. It will be merged once the CI passes

**Comment by kokobd** [comment]
Can we backport this to 3.8?

**Comment by Mikolaj** [comment]
This looks rather safe and is a bugfix, so in principle we can. Especially if a user requests so. Let me create a backport and perhaps we can get another pair of eyes to have a look before it's merged.

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
