### PR TITLE
Report process output decoding errors in context

### PR DESCRIPTION
**Pull request by dcoutts**
It turns out that in rawSystemStdInOut any IO errors, including text
decoding, occurring while collecting the output (stderr or stdout) do
not get reported immediately, but only later if/when the output is
consumed. This is because the exceptions happened in the threads forked
to force the output, but if the main thread looks at the output later
then the exception is reported again.

This leads to very confusing results. In particular we had a case where
the configure process did not fail until writing out the LocalBuildInfo
because that was the first point that forced the output. So the distance
from when the exception really occurred and the fact that the exception
message does not include the name of the program run means that this is
then a pain to track down.

This patch makes sure that any exceptions arising from forcing the
program output occur immediately and with an error message that includes
the name of the program in question.

### CODE REVIEW

**Comment by dcoutts** [comment]
Here's the kind of confusing log we saw http://lpaste.net/162524

Relevant snippet:

    No uhc found
    Setup.exe: fd:4: invalid argument
    Setup.exe: fd:4: hGetContents: invalid argument (invalid byte sequence)

The `No uhc found` is reporting the last program, which is the last thing that happens at the end of `configure`. The next thing to happen in `D.Simple` is to write out the local build info (`dist/saved-config`).

Without this patch, the behaviour in ghci is:

```
> (_,_,e) <- rawSystemStdInOut maxBound "./fail.sh" [] Nothing Nothing Nothing False
("./fail.sh",[])
```

Note how since we don't force the output, the exception is not triggered here. With this patch the behaviour is:

```
(_,_,e) <- rawSystemStdInOut maxBound "./fail.sh" [] Nothing Nothing Nothing False
("./fail.sh",[])
*** Exception: output of ./fail.sh: hGetContents: invalid argument (invalid byte sequence)
```

Note that it fails, and note that the location is no longer `fd:4` but `output of ./fail.sh`.

If GHC exposed the `InvalidArgument` IOErrorType then we could catch this specifically, but it doesn't.

**Comment by 23Skidoo** [comment]
LGTM, may be worth adding a test.

**Comment by dcoutts** [comment]
@23Skidoo test added. Only slightly annoying thing there is it's actually slightly hard to make a portable test where we can find a suitable program to run that will produce binary output that's not UTF8. This test relies on ghc being in the $PATH. Hopefully that's portable enough.

**Comment by 23Skidoo** [comment]
Great, thanks. I think that `ghc -e` will work for our purposes.

**Comment by 23Skidoo** [comment]
Fails on GHC 7.4:

```
tests/UnitTests/Distribution/Simple/Utils.hs:53:10:
    Ambiguous occurrence `try'
    It could refer to either `System.IO.Error.try',
                             imported from `System.IO.Error' at tests/UnitTests/Distribution/Simple/Utils.hs:13:1-22
                          or `Control.Exception.try',
                             imported from `Control.Exception' at tests/UnitTests/Distribution/Simple/Utils.hs:14:27-29
                             (and originally defined in `Control.Exception.Base')
```

Also fails on Windows:
```
Unit Tests
  Distribution.Simple.Utils
    rawSystemStdInOut reports text decoding errors:   FAIL (0.86s)
      expected IO decoding exception
```
Environment seems to be set up correctly on AppVeyor (`ghc` is in `PATH`).

**Comment by 23Skidoo** [comment]
In principle we can drop support for GHC 7.4.

**Comment by dcoutts** [comment]
7.4 I can fix. Interesting that it does not fail on windows. I wonder if it's a locale/codepage thing.

**Comment by dcoutts** [comment]
So this is what I get on windows in ghci:

```
rawSystemStdInOut normal "ghc" ["-e", "Data.ByteString.putStr (Data.ByteString.pack [255])"] Nothing Nothing Nothing False
("\160","",ExitSuccess)
```
160? Yes, from testing on windows in GHCi we find that on windows the `localeEncoding` is CP437 and when doing `hGetChar` on a file containing only byte 255 it returns '\160'. With the file handle explicitly in utf8 mode then we get the expected failure.

So it turns out that [Windows code page 437](https://en.wikipedia.org/wiki/Code_page_437) is one of the old ones covering all 256 8-bit codes, so everything is valid. It maps into Unicode and 255 just happens to map to unicode char 160.

So this means with the default locale on windows we cannot provoke an IO decoding failure here. The original bug report I saw was also on windows, so perhaps somehow they had managed to get a different default locale. I'm not sure how the locale is determined by ghc on windows.

So one fix is to allow the test to get no failure (we'd also see this behaviour on unix systems if you change the locale to a non-utf8 one), or we extend our process API to allow us to control the expected encoding, so rather than just binary and locale text mode we could also explicitly select utf8 output.

**Comment by dcoutts** [comment]
Amended and pushed twice, hopefully it's testing the right version.

So I'm just skipping the test when the locale encoding is not UTF-8.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
