### PR TITLE
Fix build with GHC < 7.8 (binary < 0.7)

### PR DESCRIPTION
**Pull request by ttuegel**
This is still a work-in-progress.

First I am changing the Travis tests to build Cabal against each GHC version out-of-the-box, i.e., no updating with cabal-install before building the Cabal library. We need to test this way if we are going to support it. Right now, I'm just making this pull request to check that the new tests fail.

### CODE REVIEW

**Comment by ttuegel** [comment]
Fixes #2322 by copying two modules from `binary`: `Data.Binary.Generic` and `Data.Binary.Class`. On GHC 7.8, or if `binary >= 0.7` is available, we just use `binary`. Also changes the Travis tests to catch this issue.

@tibbe This is ready to go into `master` and `1.22` branches, if you agree that this is the right way to solve the problem. The other way is to write many boilerplate instances for when we don't have a version of binary with generics. I think this is less maintenance in the long-run. When we drop support for GHC 7.6 in 2016, we can just delete the copied modules.

**Comment by 23Skidoo** [comment]
I agree that this is preferable to writing those instances by hand.

**Comment by tibbe** [comment]
/cc @kolmodin just in case.

Looks good to me. Thanks for fixing.

**Comment by kolmodin** [comment]
Looks good to me.

**Pull request merged**
