### PR TITLE
Cabal.cabal: Add missing files

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
```
tests/PackageTests/CabalMacros/my.cabal
tests/PackageTests/Regression/T3294/Main.hs
```

These files are not in the repo, they are probably auto-generated by the test suite.

**Comment by erikd** [comment]
Oops, fixed.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by ezyang** [comment]
Thanks for the catch. I wonder if we can get Travis to check for these files too.

**Comment by 23Skidoo** [comment]
See #1746. This check is on the wishlist, but it shouldn't be specific to our Travis setup.

**Pull request merged**
