### PR TITLE
Fix #10042 Don't recommend deprecated/removed 'extensions:' field

### LINKED ISSUE #10042: Cabal (the library) advises use of `extensions:` when that field is deprecated
Motivation: https://github.com/commercialhaskell/stack/issues/6589

If a Cabal file uses `ghc-options:` to set language extensions, Cabal (the library) will advise the use of `extensions:` even when `extensions:` has been deprecated in favour of `default-extensions:`.

EDIT: This appears to be true even if the `cabal-version:` specifies a Cabal package format version that no longer supports `extensions:` at all.

### PR DESCRIPTION
**Pull request by mpilgrem**
Related issue:
* #10042

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary. Not necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included. None needed.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*) None needed.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by mpilgrem** [comment]
I think the CI is failing for reasons unconnected with this pull request.

**Comment by geekosaur** [comment]
Yes, we're working on it.

**Review by ulysses4ever — APPROVED** [review]
Awesome!

**Comment by ulysses4ever** [comment]
@geekosaur I dummy know that anyone is working on the changelog.d/GHC 9.10 failure btw! Maybe you could give it a try? Hécate suggested that instead of building it, we could just download a bindists...

**Comment by mpilgrem** [comment]
I've rebased on `master`.

**Comment by ulysses4ever** [comment]
@mpilgrem awesome! Per CONTRIBUTING.md, do you want to apply a merge label (either merge me or squash+merge). Squashing makes more sense, I think.

**Comment by mpilgrem** [comment]
I've tidied-up manually.

**Comment by ulysses4ever** [comment]
@mergify backport 3.12

**Pull request merged**
