### PR TITLE
Unbreak the build on AppVeyor.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Take 2.

### CODE REVIEW

**Comment by grayjay** [comment]
@23Skidoo Thanks for uploading the binary. I'm trying to update my previous branch that downloaded GHC and cabal separately: https://github.com/grayjay/cabal/tree/appveyor-newer-ghc-and-cabal

**Comment by 23Skidoo** [comment]
Apparently when you run `7z x cabal.tar.gz` it unpacks only the `cabal.tar` file.

**Comment by grayjay** [comment]
Now it's failing to download the packages: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.73

**Comment by 23Skidoo** [comment]
@grayjay Maybe the problem is that AppVeyor needs a 64-bit binary? The one I uploaded is 32-bit, but the one that comes with Haskell Platform is 64-bit (since it's from `HaskellPlatform-2014.2.0.0-x86_64-setup.exe`).

**Comment by 23Skidoo** [comment]
Something funky is going on:

```
ansi-terminal-0.6.2.3 failed while downloading the package. The exception was:
DeleteFile
"C:\\Users\\appveyor\\AppData\\Roaming\\cabal\\packages\\hackage.haskell.org\\ansi-terminal\\0.6.2.3\\curl-headers2812.txt":
permission denied (The process cannot access the file because it is being used
by another process.)
```

**Comment by grayjay** [comment]
I don't know.  I looked back at the other builds that I tried, and I think that all of the cabal binaries that failed to download the index were 32-bit.

**Comment by 23Skidoo** [comment]
OK, I'll build a 64-bit binary then.

**Comment by 23Skidoo** [comment]
The 64-bit binary seems to be able to download packages. Yay!

**Comment by grayjay** [comment]
Great!

**Comment by 23Skidoo** [comment]
So now it fails when trying to configure `network`:

```
cabal: Entering directory 'C:\Users\appveyor\AppData\Local\Temp\1\cabal-tmp-2404\network-2.6.2.1'
Configuring network-2.6.2.1...
configure: WARNING: unrecognized options: --with-compiler
checking build system type... x86_64-pc-msys
checking host system type... x86_64-pc-msys
checking for gcc... C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin\gcc.exe
checking whether the C compiler works... no
configure: error: in `/tmp/cabal-tmp-2404/network-2.6.2.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
cabal: Leaving directory 'C:\Users\appveyor\AppData\Local\Temp\1\cabal-tmp-2404\network-2.6.2.1'
Failed to install network-2.6.2.1
```

**Comment by grayjay** [comment]
`network` works with GHC 7.10.3: https://ci.appveyor.com/project/grayjay/cabal

**Comment by 23Skidoo** [comment]
Thanks, changed the script to use GHC 7.10.3.

**Comment by 23Skidoo** [comment]
And it finally passed!

**Comment by grayjay** [comment]
I can reproduce the network configure error locally with `cabal-install-1.24.0.0`, but not `cabal-install-1.22.6.0`.  I think it can't handle the spaces in the path to gcc.

**Comment by 23Skidoo** [comment]
That's #1634. So it's still broken? Maybe we need to add a workaround.

**Comment by 23Skidoo** [comment]
Filed an issue: #3185.

**Comment by grayjay** [comment]
Thanks.  It looks like 1.22 was able to configure network because it used `--with-gcc` instead of `CC`.  The configure script ignored `--with-gcc` and found `gcc` on the path.

**Pull request merged**
