### PR TITLE
Try to fix AppVeyor (2.4).

### PR DESCRIPTION
**Pull request by 23Skidoo**
Like #5486, but for 2.4. See https://github.com/haskell/cabal/commit/123291c0939789aa7c3e4970c4a22adf50c0a9ee#comments.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
This is what seems to be the problem:

```
[__1] rejecting: cabal-testsuite:setup.Cabal-2.4.0.0 (constraint from maximum
version of Cabal used by Setup.hs requires <2.4)
```

This constraint comes from `setupMaxCabalVersionConstraint` in [`D.C.ProjectPlanning`](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/ProjectPlanning.hs):

```
    -- As we can't predict the future, we also place a global upper
    -- bound on the lib:Cabal version we know how to interact with:
    --
    -- The upper bound is computed by incrementing the current major
    -- version twice in order to allow for the current version, as
    -- well as the next adjacent major version (one of which will not
    -- be released, as only "even major" versions of Cabal are
    -- released to Hackage or bundled with proper GHC releases).
    --
    -- For instance, if the current version of cabal-install is an odd
    -- development version, e.g.  Cabal-2.1.0.0, then we impose an
    -- upper bound `setup.Cabal < 2.3`; if `cabal-install` is on a
    -- stable/release even version, e.g. Cabal-2.2.1.0, the upper
    -- bound is `setup.Cabal < 2.4`. This gives us enough flexibility
    -- when dealing with development snapshots of Cabal and cabal-install.
    --
    setupMaxCabalVersionConstraint =
      alterVersion (take 2) $ incVersion 1 $ incVersion 1 cabalVersion
```

On Travis, we are using `cabal-install-head` and apparently don't bump into this constraint (though on HEAD/2.5, I actually think that we should -- not sure what's going here). So we should upgrade `cabal-install` on AppVeyor to a fresher snapshot, and maybe add an option for `new-build` to ignore the `maxCabalVersionConstraint`.

**Comment by hvr** [comment]
@23Skidoo btw, @Mistuke's https://hub.zhox.com/posts/chocolatey-introduction/ describes how to get access to `cabal-head` which correspond to `cabal-install-head`

**Comment by 23Skidoo** [comment]
@Mistuke How do I install a combination of a stable GHC and a pre-release `cabal` with `choco`? No matter what I try, stable `ghc` pulls in stable `cabal`, which overrides the pre-release one.

**Comment by 23Skidoo** [comment]
Figured it out: just install `cabal-head` after `ghc`. Still, the fact that `ghc` pulls in unneeded stable `cabal` is mildly annoying.

**Comment by 23Skidoo** [comment]
Now there's a test that needs to be fixed...

**Comment by Mistuke** [comment]
@23Skidoo `choco install ghc -y --ignore-dependencies` will skip the stable `cabal` install.

**Comment by 23Skidoo** [comment]
Yay, looks like it worked. BTW, we seem to have a test that fails intermittently -- `CustomPlain`.

**Pull request merged**
