### PR TITLE
Add sitemap.xml to Cabal User Guide.

### PR DESCRIPTION
**Pull request by m-renaud**
This gives search engines more info about the structure of the pages, and which
pages to give more weight to, such as "latest" and "stable" versions of the docs
compared to older versions, or preferring a canonical latest/ page instead of
latest/index.html to avoid duplication in search results.

### CODE REVIEW

**Comment by phadej** [comment]
Does this have to be maintained by hand? Then it's no-go.

**Comment by m-renaud** [comment]
I'm not sure I follow? You need some way of specifying metadata about the content of the site, the alternative could be some script that reads metadata from individual files that you tag in RST somehow, or to use some other config file which contains the same information. In general, site structure changes pretty infrequently so I don't think its too onerous to add a new entry to the sitemap if a new page is added. Otherwise it can remain the same. Even a slightly out of date sitemap is significantly better than no sitemap at all.

**Comment by m-renaud** [comment]
If you're asking about the `<lastmod>` tag that's not particularly important, but can be useful if you want to force a re-crawl of the content.

**Comment by phadej** [comment]
I'm afraid adding "one more thing" which can cause stuff to work or not. I guess there are tools to verify that sitemaps are up to date. Such development documentation have to be written before I'll be comfortable.

Also, there is https://docs.readthedocs.io/en/stable/guides/sitemaps.html

> Read the Docs automatically generates a sitemap for each project that hosts to improve results when performing a search on these search engines. 

Which generates: https://cabal.readthedocs.io/sitemap.xml

What's wrong with that? If you want to recommend latest over stable, that's indeed something we can discuss in an issue.

**Comment by phadej** [comment]
@m-renaud ping

**Comment by m-renaud** [comment]
Sorry for the delay, the one that's auto-generated doesn't have any of the sub-pages, although it appears search engines still do the right thing with the sub-pages so maybe it's fine :shrug: 

I'm fine with closing this issue since I don't have tonnes of spare time right now.

**Pull request closed without merging**
