### PR TITLE
Bump upper bound on bytestring

### PR DESCRIPTION
**Pull request by bgamari**
Admit bytestring-0.11

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
@Mistuke if you are interested, this one has the same

```
Access violation in generated code when executing data at 0xcf88

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x6bfdd60	0xcf88
```

which I have been seeing lately. (I have no idea if it's the same access violation every time, but it's the 8.8.4 job).

**Comment by phadej** [comment]
### cryptohash-sha256-0.11.101.0

```
src/Crypto/Hash/SHA256.hs:93:44:
    Module `Data.ByteString.Internal' does not export `ByteString(PS)'
```

### base16-bytestring-0.1.1.7

```
Data/ByteString/Base16.hs:38:9:
    Not in scope: data constructor `PS'
    Perhaps you meant `BS' (imported from Data.ByteString.Internal)
```

**Comment by emilypi** [comment]
@phadej i'll revise to `< 0.12`

**Comment by emilypi** [comment]
Just as a follow up, older `base16-bytestring`s `<1.0` are bound to `bytestring <0.11`.

**Comment by Bodigrim** [comment]
@phadej could we possibly move this forward, at least with respect to `Cabal`? 
`cryptohash-sha256-0.11.102.0` has been released.

**Comment by emilypi** [comment]
@Bodigrim are we blocked on `resolv`, or is that just a problem unto itself?

**Comment by Bodigrim** [comment]
(I do not know much about Cabal, this is just a cursory glance, feel free to point that I'm saying nonsence)

There are `Cabal` package and `cabal-install` tool. `Cabal` depends only on boot packages, all of which are now ready for `bytestring-0.11` if I'm not terribly missing something.

`cabal-install` has much more dependencies. It is still blocked by `resolv` indeed, but this is just a question of revision, no new release is strictly needed. (Can someone possibly ask Hackage Trustees? https://github.com/haskell-hvr/resolv/pull/10 has been lingering open long enough)

My understanding is that @phadej prefers to relax `bytestring` bounds for `Cabal` and `cabal-install` simultaneously. This makes sense, but if `cabal-install` is delayed, bumping `Cabal` only is also very much beneficial. I want to update GHC `bytestring` submodule to 0.11 branch, before 9.2 feature freeze, but this requires all other submodules being compatible with it.

**Comment by emilypi** [comment]
>  It is still blocked by resolv indeed, but this is just a question of revision, no new release is strictly needed. (Can someone possibly ask Hackage Trustees? haskell-hvr/resolv#10 has been lingering open long enough)

Ah right, that one was just a revision. I think I can try haranguing a trustee into getting it done for us. 

> I want to update GHC bytestring submodule to 0.11 branch, before 9.2 feature freeze, but this requires all other submodules being compatible with it.

Am I correct in reading this as  "this is blocking work on GHC"?

**Comment by emilypi** [comment]
Okay, @mightybyte has made the necessary revision. That should unblock us all.

**Comment by phadej** [comment]
> before 9.2 feature freeze, but this requires all other submodules being compatible with it.

With GHC-9.0 not even released...

I'm sorry, but I find that hardly motivating.

**Comment by Bodigrim** [comment]
> With GHC-9.0 not even released...

At least in theory these are independent processes. Given how overdue is 9.0, I would not be terribly surprised if 9.2 change freeze comes pretty soon after 9.0 release. 

> though it would be nice to have things moving

All right, what is missing now? I'm keen to get it moving.

**Comment by phadej** [comment]
@Bodigrim I'm not participating in Cabal development at the moment. I'm hanging around to see Cabal-3.4.0.0 shipped with GHC-9.0, and after that I don't know what happens.

**Comment by bgamari** [comment]
I usually prefer not to merge without a maintainer's approval but, given this has been stuck for five months now and the 9.2 window is quickly closing, I am going to go ahead and merge this.

**Comment by emilypi** [comment]
@bgamari thanks for that - +1 from me

**Pull request merged**
