### PR TITLE
Bump upper bound on process

### PR DESCRIPTION
**Pull request by bgamari**
This is necessary for GHC 8.2.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
You should also update `cabal-install.cabal`.

**Comment by 23Skidoo** [comment]
I canceled the CI build because `process-1.6` is not on Hackage.

**Comment by bgamari** [comment]
I didn't bump `cabal-install` since I haven't tested that `cabal-install` actually builds. I think we should keep these two bumps independent.

Also, it would probably be best to hold off a bit on merging this: I'm waiting to hear back from @snoyberg on whether the he intends to bump the `process` version number back down to 1.5 before the next release.

**Comment by snoyberg** [comment]
I definitely don't intend to bump back down to 1.5; though the latest change to the process package was to an internal module only, it's still a breaking change, so I'm going to be proceeding with version 1.6.

**Comment by 23Skidoo** [comment]
@bgamari 
> I didn't bump `cabal-install` since I haven't tested that `cabal-install` actually builds.

If it doesn't build with this change, CI will catch it. But I'd wait until `process-1.6` is on Hackage.

**Comment by snoyberg** [comment]
It's on Hackage now.

**Comment by bgamari** [comment]
Can we merge this please?

**Comment by 23Skidoo** [comment]
Can we also bump `cabal-install`'s dependency on `process` at the same time? From what I remember of looking at the changes in `process-1.6`, it should work. If it doesn't, CI should catch any failures.

**Comment by bgamari** [comment]
I've updated the `cabal-install` dependency and it appears to pass CI.

**Pull request merged**
