### PR TITLE
Bring back old types of {hscolour,haddock}Pref and haddockForHackage.

### LINKED ISSUE #4123: Incompatible API change in Cabal 1.24.1.0 / PVP Violation
It appears as if Cabal 1.24.1.0 introduced a non-backward compatible change;

I noticed this because when `cabal-install-1.24.0.0` is  compiled with `Cabal-1.24.1.0`  one  ends up with the following compile error:

```
[106 of 106] Compiling Main             ( Main.hs, /tmp/matrix-worker/1479637119/dist-newstyle/build/x86_64-linux/ghc-7.10.3/cabal-install-1.24.0.0/build/cabal/cabal-tmp/Main.o )

Main.hs:904:35:
    Couldn't match type ‘Cabal.HaddockTarget’ with ‘Bool’
    Expected type: Flag Bool
      Actual type: Flag Cabal.HaddockTarget
    In the second argument of ‘($)’, namely
      ‘haddockForHackage haddockFlags’
    In the first argument of ‘when’, namely
      ‘(fromFlagOrDefault False $ haddockForHackage haddockFlags)’

Main.hs:1106:69:
    Couldn't match expected type ‘Cabal.HaddockTarget’
                with actual type ‘Bool’
    In the first argument of ‘Flag’, namely ‘True’
    In the ‘haddockForHackage’ field of a record
```

Further investigation reveals that the culprit appears to be a0b495661853c273a10e50b91559524d9bf8aeee

which changed the type-signatures in `Distribution.Simple.BuildPaths`:

```
-hscolourPref :: FilePath -> PackageDescription -> FilePath
+hscolourPref :: HaddockTarget -> FilePath -> PackageDescription -> FilePath
```

```
-haddockPref :: FilePath -> PackageDescription -> FilePath
+haddockPref :: HaddockTarget -> FilePath -> PackageDescription -> FilePath
```

This is a serious breach of API contract, especially since `Setup.hs` scripts are still rather fragile to such kinds of API breakages.

IMO, we should undo this API breakage, and release a Cabal 1.24.1.1 (& cabal-install-1.24.0.2) ASAP, and blacklist-deprecate Cabal 1.24.1.0 

/cc @bgamari since depending on the resolution of this issue, GHC 8.0.2, may need to update to version different from Cabal 1.24.1.0

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #4123.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@rthomas If people agree that this is an acceptable fix, we'll need a new Cabal lib release from the 1.24 branch.

**Comment by 23Skidoo** [comment]
@dcoutts @hvr @ezyang @bennofs Any objections to this?

**Comment by 23Skidoo** [comment]
This appears to be only a partial fix to #4123, since a0b495661853c273a10e50b91559524d9bf8aeee also contains the following change:

```
-    haddockForHackage   :: Flag Bool,
+   haddockForHackage   :: Flag HaddockTarget,
```

**Comment by hvr** [comment]
@23Skidoo we should also try comparing the API between 1.24.0.0 and 1.24.1 with something like https://hackage.haskell.org/package/hackage-diff to make sure there weren't other non-backward compat changes that snuck in

**Comment by 23Skidoo** [comment]
Pushed an updated fix.

**Comment by 23Skidoo** [comment]
@hvr I tried that, but the result was somewhat disappointing:

```
$ hackage-diff Cabal 1.24.1.0 1.24.0.0
Downloading / Reading Hoogle DBs...
Parsing Hoogle DBs...
endOfInput
```

Filed an issue (https://github.com/blitzcode/hackage-diff/issues/6).

**Comment by 23Skidoo** [comment]
All right, I'm merging this.

**Comment by 23Skidoo** [comment]
@rthomas Ping.

**Comment by phadej** [comment]
@23Skidoo try `hackage-diff --mode=builddb`

**Comment by 23Skidoo** [comment]
@phadej Here's the result:

```
$ hackage-diff --mode=builddb Cabal 1.24.0.0 1.24.1.0        
Downloading Cabal-1.24.0.0...
Downloading Cabal-1.24.1.0...
Processing Cabal-1.24.0.0...
  Creating Sandbox
  Installing Dependencies
  Configuring
  Building Haddock
Processing Cabal-1.24.1.0...
  Creating Sandbox
  Installing Dependencies
  Configuring
  Building Haddock

--- Diff for | 1.24.0.0 → 1.24.1.0 | ---

· Distribution.Compat.Binary
· Distribution.Compat.ReadP
· Distribution.Compat.Semigroup
· Distribution.PackageDescription.Utils
· Distribution.Simple.CCompiler
· Distribution.Simple.PreProcess.Unlit
· Distribution.Simple.Program.Internal
· Distribution.TestSuite

[+ Added] [- Removed] [× Modified] [· Unmodified]
```

Looks kinda strange to be honest. /cc @blitzcode

**Comment by bgamari** [comment]
@23Skidoo, when do you think we'll be able to get a new 1.24 release?

**Comment by 23Skidoo** [comment]
@bgamari I'll do it today.

**Pull request merged**
