### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by DanielG**
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]

**Review by m-renaud — APPROVED** [review]
LGTM, thanks!

**Comment by Mikolaj** [comment]
Let me merge, because other PRs depend on it. Kind reviewers, please open new PRs with fixes if something is not quite right in this quickfix.

**Comment by fendor** [comment]
Thank you very much, I indeed forgot to check whether the docs compile correctly, sorry!

**Review by andreasabel — COMMENTED** [review]
I can confirm that the docs now build without error.  Thanks for the quick fix!

**Pull request merged**
