### PR TITLE
Cleanup around subprocess helpers

### PR DESCRIPTION
**Pull request by robx**
This is intended to be a mostly-no-op change to provide a basis for a clean take of #7921. The guiding principle was to reduce the number of `createProcess` calls and collect them in `Distribution.Simple.Utils`.

Functional changes should be limited to:
- slightly more consistent logging of command execution
- more consistently applying the same subprocess defaults (`delegate_ctlc` and `enable_process_jobs`)

One of the last commits removes some obsolete functions that I'd previously deprecated. I'm a bit unsure if we need to deprecate these mostly-internal functions.

All those `rawSystem` helpers still feel a bit messy and I'm sure there's more that could be done, but I think this should already be a step forward, and will allow switching to some kind of bracketed `withProcess` in the context of #7921 much easier, and hence easier to review.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by robx** [comment]
Just to note that there's a test that gets stuck, will investigate.

**Comment by robx** [comment]
Alright, fingers crossed this should be ready for review now. The commits are also in a reasonable state now.

**Review by Mikolaj — APPROVED** [review]
Uhm, lots of removals, great. I assume this is exercised by many tests and it doesn't add any new functionality, so nothing new needs to be tested.

**Review by jneira — APPROVED** [review]
lgtm, thanks for the cleanup

**Comment by Mikolaj** [comment]
CI jobs are stuck due to https://github.com/haskell/cabal/pull/8000 not merged yet, so let me merge manually. BTW. I forgot to rebase this one and caused git commit diagram art. Sorry about that.

**Pull request merged**
