### PR TITLE
Mention password-command option in upload --help

### PR DESCRIPTION
**Pull request by v0d1ch**

### CODE REVIEW

**Comment by v0d1ch** [comment]
I copy pasted the issue title there. I can update it if you want. I didn't bother in the first place since the change is very trivial.

**Comment by phadej** [comment]
The commit message should explain why the change is made. I don't understand it. Neither there is reference to the issue.

**Comment by v0d1ch** [comment]
Oh I just realized this work has already been done here https://github.com/haskell/cabal/pull/6313.
What I don't know is why the pr was closed if the changes didn't go in.

**Comment by v0d1ch** [comment]
@phadej should we close this one?

**Comment by phadej** [comment]
We should merge this, but I still need to check something. Sorry for forgetting this one for a while.

**Comment by phadej** [comment]
Merged in #6680

**Pull request closed without merging**
