### PR TITLE
Refine "doingTH" check to include checking for QuasiQuotes

### PR DESCRIPTION
**Pull request by duog**
Addresses #4580. I have not added a test for this. I could easily modify or duplicate the tests in cabal-tests/PackageTests/TemplateHaskell if you think it worthwhile.
Note that ghc-8.2 is smart enough to not need this logic, I'm not sure when those smarts were added.
I verified this works by modifying those tests to have QuasiQuotes in their cabal files, and running them with ghc-7.6.3.

### CODE REVIEW

**Comment by ezyang** [comment]
LGTM. Can we get a test? I can assist if it is non-obvious but https://github.com/haskell/cabal/tree/master/cabal-testsuite should give you a start.

Also, minor bikeshedding: shouldn't `usesTemplateHaskellOrQQ` be named based on the invariant it checks, rather than its implementation details? That would make it more robust to future changes. (This is easy enough to fix later so don't feel obligated to do anything.)

**Comment by duog** [comment]
Test won't be a problem, I'll just copy tests/PackageTests/TemplateHaskell. As I noted above, It would only actually fail on older ghcs though.

I agree it should be based on the invariant it checks, but I couldn't come up with anything better. The analogous function in ghc is named needsTemplateHaskellOrQQ. I used "uses" to match the vocabulary of surrounding functions.

**Comment by 23Skidoo** [comment]
LGTM as well, merging!

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
