### PR TITLE
bootstrap: fix v1 command

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
If we still need that line, then we have to prefix `sandbox` with `v1-`. Or should we just delete the line?

**Comment by 23Skidoo** [comment]
Hmm, why is everything red.

**Comment by tuncer** [comment]
Job | Error
------------ | -------------
https://travis-ci.org/haskell/cabal/jobs/511562018#L3182 | timeout
https://travis-ci.org/haskell/cabal/jobs/511562012#L776 | network
https://travis-ci.org/haskell/cabal/jobs/511562008#L776 | network
https://travis-ci.org/haskell/cabal/jobs/511562019#L2855 | Rts.h (throws warnings in other jobs)
https://travis-ci.org/haskell-pushbot/cabal-binaries/builds/511581421#L735 | network
https://travis-ci.org/haskell-pushbot/cabal-binaries/builds/511577608#L735 | network

**Comment by 23Skidoo** [comment]
This is now green, merging.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
