### PR TITLE
Solver: Support dependencies on sub-libraries (issue #6039) (3rd iteration)

### PR DESCRIPTION
**Pull request by fgaz**
Adds check overrides to #6812 / #6047

/cc @phadej @grayjay

### CODE REVIEW

**Comment by fgaz** [comment]
Oh, [ci skip] doesn't work anymore :-/

**Comment by phadej** [comment]
No. There is no easy check that [ci skip] tagged commit would be safe. CI is fast and reliable enough to just build everything.

**Comment by fgaz** [comment]
I do see that it's waaay faster than before, thanks for that! And just to be clear, I'm merging this once it's green

**Comment by grayjay** [comment]
Thanks for finishing my PR!

**Pull request merged**
