### PR TITLE
Fix #8928 Conclude setup messages with an ellipsis

### LINKED ISSUE #8928: ".." added by `Distribution.Backpack.DescribeUnitId.setupMessage'`, not full stop or ellipsis?
A very minor UI point: the `".."` added to the end of setup messages by `setupMessage'` is neither a full stop (`"."`) nor an ellipsis (`"..."`) - see the `where` statement in the code extract further below. Is that intentional, or a bug? If a bug, I'll raise a pull request to change it to an ellipsis. It results in output like:
~~~text
Preprocessing library for foo-0.1.0.0..
Building library for foo-0.1.0.0..
~~~

~~~haskell
-- | Print a Setup message stating (1) what operation we are doing,
-- for (2) which component (with enough details to uniquely identify
-- the build in question.)
--
...
setupMessage' verbosity msg pkgid cname mb_insts = withFrozenCallStack $ do
    noticeDoc verbosity $
      case mb_insts of
...
        _ ->
          msg_doc <+> for_doc

  where
    msg_doc = text msg <+> text (showComponentName cname)
    for_doc = text "for" <+> pretty pkgid <<>> text ".."
~~~

### PR DESCRIPTION
**Pull request by mpilgrem**
* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Thank you!

I'm seeing a good bunch of reference tests results holding the `..`, so you will have to run the test suite with `--accept` locally to update them. Details on running the test should be in https://github.com/haskell/cabal/blob/master/cabal-testsuite/README.md  Or you could `sed`...

**Comment by mpilgrem** [comment]
@ulysses4ever, I took the search and replace route. After a couple of false starts, the checks now pass.

**Review by ulysses4ever — APPROVED** [review]
Terrific!

**Comment by Kleidukos** [comment]
@mpilgrem Hi, do you need help with rebasing this PR? I can offer my help.

**Comment by mpilgrem** [comment]
@Kleidukos, I had not spotted that. I'll look at it over the coming weekend and let you know.

**Review by ffaf1 — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@mpilgrem thanks a lot for updating the PR and sorry it took so long to get all the approvals! There is a couple tests that have been added in the meantime and they have to be fixed, see the CI but I think the relevant bit is:

```
UNEXPECTED FAIL: 
PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.test.hs 
PackageTests/MultiRepl/EnabledClosure/cabal.test.hs 
PackageTests/MultiRepl/EnabledSucc/cabal.test.hs
```

**Comment by ulysses4ever** [comment]
@mpilgrem thanks a lot for attending to it! One thing for the future: normally, we don't manually merge PRs but rather employ a merge bot. So, when you get 2 approvals and a green CI, you're expected to put one of the two labels: `merge-me` or `squash+merge`, and the bot will merge it after a two-day delay (a precautionary measure).

**Comment by mpilgrem** [comment]
@ulysses4ever, sorry - I did not appreciate that (about merging).

**Pull request merged**
