### PR TITLE
Restore BC for rewriteFile

### PR DESCRIPTION
**Pull request by ezyang**
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [X] Any changes that could be relevant to users have been recorded in the changelog.
* [X] The documentation has been updated, if necessary.
* [X] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by hvr** [comment]
@23Skidoo I'm utterly confused now... are you aware of @phadej's  5797013fa552268e726d19d4c4d326621ecd833c ?

**Comment by 23Skidoo** [comment]
Did I forget to backport that into `master`? Then I guess we should rename `rewriteFileV` to `rewriteFile'`.

**Comment by hvr** [comment]
@23Skidoo what's the difference between `rewriteFileV` and Cabal 2.0's `rewriteFileEx`? Why don't we just  revert this one, and instead cherry-pick 5797013 ?

**Comment by phadej** [comment]
Aren't `rewriteFileV` and `rewriteFileEx` the same function. I don't care about the name, but let's use `rewriteFileEx` as it's in released `Cabal` already.

My bad, I didn't backport myself either.

**Comment by 23Skidoo** [comment]
Fixed in 552ae22bdc7a265bd57b131f3749e239476bd7ca.

**Comment by phadej** [comment]
@23Skidoo thanks!

**Pull request merged**
