### PR TITLE
Derive NFData instance for GenericPackageDescription.

### PR DESCRIPTION
**Pull request by peti**
Define NFData instance for GenericPackageDescription. GenericPackageDescription contains a whole lot of other types, each of which requires NFData instances, too. All the definitions rely on the respective Generic instance via `genericRnf`.

A unit test to verify that the NFData instance can find bottoms in GPD has been added.

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

### CODE REVIEW

**Comment by hvr** [comment]
> but "Generic" gives them all to us for free.

You have to be very careful here though... that's only true for `build-depends: deepseq ^>= 1.4.0.0`! (if you want to use `Generic` with older `deepseq` versions, see the compat notes in its haddocks)

(I know how you meant "for free", but I'd nitpick there's a minor cost involved: compile time + object size)

**Comment by peti** [comment]
@hvr, I see what you mean. I edited all definitions to use the `genericRnf` function provided by Cabal's internal compat code to make sure the code works properly with deepseq versions prior to 1.4.

@phadej, I added the bottom-chasing unit test you requested.

**Comment by phadej** [comment]
Fails with GHC-7.4.2:

```
tests/UnitTests/Distribution/Types/GenericPackageDescription.hs:36:3:
    Ambiguous occurrence `catch'
    It could refer to either `Distribution.Compat.Prelude.Internal.catch',
                             imported from `Distribution.Compat.Prelude.Internal' at tests/UnitTests/Distribution/Types/GenericPackageDescription.hs:6:1-43
                             (and originally defined in `System.IO.Error')
                          or `Control.Exception.catch',
                             imported from `Control.Exception' at tests/UnitTests/Distribution/Types/GenericPackageDescription.hs:11:1-24
                             (and originally defined in `Control.Exception.Base')
```

Docs of `Control.Exception.catch`, https://hackage.haskell.org/package/base-4.5.0.0/docs/Control-Exception.html#v:catch  in `base-4.5` say

> Note that the Prelude also exports a function called catch with a similar type to catch, except that the Prelude version only catches the IO and user families of exceptions (as required by Haskell 98).

Later `Prelude` don't export `catch`. I'd `import qualified Control.Exception as C`  and use `C.catch` to avoid ambiguity.

**Comment by peti** [comment]
`catch` name clash is fixed by 29cf7b9f5bcd05b5ce84588f2a6529e15addd0bb. Or so I hope. :-)

**Comment by phadej** [comment]
@peti: 
```
Not in scope: data constructor `ErrorCall'
    Perhaps you meant `C.ErrorCall' (imported from Control.Exception)
```

**Comment by peti** [comment]
Yeah, I force-pushed a fix.

**Comment by phadej** [comment]
Seems meta check fails. I'll merge this manually later today.

**Pull request merged**
