### PR TITLE
Add darwin aarch64 support to CI

### PR DESCRIPTION
**Pull request by hasufell**
https://gitlab.haskell.org/maerwald/cabal/-/pipelines/40563 all green

### CODE REVIEW

**Review by emilypi — APPROVED** [review]
Thanks @hasufell :muscle:

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergifyio update

**Comment by Mikolaj** [comment]
Huh, is there a way to tell mergify to rebase instead of merge?

**Comment by emilypi** [comment]
@Mikolaj you'll need a different tag. Right now, the update method for the `merge me` tag is `rebase`, but the merge strategy is a dumb merge. You can add a variation here: https://github.com/haskell/cabal/blob/master/.github/mergify.yml

**Comment by Mikolaj** [comment]
thank you, so I made a mistake; I should have just added the `merge me` label and it would rebase fine

**Comment by jneira** [comment]
> 
> 
> Huh, is there a way to tell mergify to rebase instead of merge?

just in case you want to use it for other case: https://docs.mergify.io/commands/#rebase

**Comment by Mikolaj** [comment]
@Mergifyio rebase

**Comment by Mikolaj** [comment]
huh, I hoped it would remove the merge commit

**Comment by hasufell** [comment]
Nothing beats the command line with a non-machine merge commit that is GPG signed. ;)

**Comment by emilypi** [comment]
Boo - we're not nerds!

**Pull request merged**
