### PR TITLE
Bump Cabal version to 3.6.0.0

### PR DESCRIPTION
**Pull request by bgamari**
Merely bumps the version.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by bgamari** [comment]
Pinging @emilypi.

**Comment by emilypi** [comment]
Taking a look at the bootstrap.py problems

**Comment by bgamari** [comment]
Thanks @emilypi !

**Comment by emilypi** [comment]
@bgamari i've branched off 3.6 separately so I'm closing this

**Pull request closed without merging**
