### PR TITLE
add gitlab ci integration to cabal

### PR DESCRIPTION
**Pull request by emilypi**
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by gbaz — APPROVED** [review]

**Comment by emilypi** [comment]
@mergifyio backport 3.6

**Review by Mikolaj — COMMENTED** [review]
Indeed, safe.

**Comment by jneira** [comment]
What is the motivation or purpose of statring use gitlab? asking cause there is a suggestion in hls to move some jobs there.
I see some bash code which can be reused, has gitlab something like actions?
I hope i am nos asking for too much

**Comment by phadej** [comment]
So this builds release artifacts but doesn't use `release.py`. Should `release.py` be removed?

**Pull request merged**
