### PR TITLE
Solver: Support dependencies on sub-libraries (issue #6039)

### PR DESCRIPTION
**Pull request by phadej**
Rebased #6047

### CODE REVIEW

**Comment by phadej** [comment]
@fgaz what else is needed to be done to make `PackageTests/MultipleLibraries/Successful/cabal.test.hs` pass on GHC-8.6.5?

**Comment by phadej** [comment]
Also remember to write a chengelog entry (See `changelog.d` directory).

**Comment by phadej** [comment]
@grayjay do you have 2FA enabled on GitHub. Looks like you are not a collaborator of Cabal anymore (so I cannot assign issues to you). I'd like to add you back.

**Comment by fgaz** [comment]
@grayjay I see you didn't pass `--allow-depending-on-private-libs` to Cabal to override the visibility checks.

As per https://github.com/haskell/cabal/pull/6047#issuecomment-566529491 we should either do that or fail early, otherwise this still fails late in the build on <8.8

**Comment by phadej** [comment]
Looks like there's a conflict. I'll rebase again shortly.

**Comment by phadej** [comment]
rebased.

**Comment by fgaz** [comment]
And here's the line that should be changed:

https://github.com/haskell/cabal/blob/06c3eff242154cdf6b3d1bbaffcfc1a5cbea9da8/cabal-install/Distribution/Client/ProjectPlanning.hs#L3415-L3417

Ideally we'd set it to true only for GHC <8.8, so that we'd still have Cabal's sanity checks for newer GHCs

**Comment by fgaz** [comment]
This should work. Please take a look @phadej

**Comment by fgaz** [comment]
@phadej I just force-with-lease pushed and only later realized that this is your branch, sorry

**Comment by phadej** [comment]
Can I disallow that globally. I never opted-in for that

**Comment by phadej** [comment]
I repushed my version. Sorry for the lsot commit @fgaz, but with over hunded people with write access, I cannot permit pushing to *my repository*.

**Comment by phadej** [comment]
And allow edit by maintainers setting doesn't seem to be preserved. :(

**Comment by fgaz** [comment]
> Sorry for the lsot commit

Nothing lost :) I opened another pr with my change: #6836

> over hunded people

Wow, a hundred already? That's a lot

Sorry for pushing on your branch, I saw the "Add more commits by pushing to the pr-6047 branch on phadej/cabal." message and assumed it was ok to do that.

I can't help but notice that this is yet another flaw in the PR model. Multiple people cannot iterate on a patch without opening a million prs.

**Comment by phadej** [comment]
collaboration needs communication, pushing into branches "owned" by others without an agreement is not polite.

**Comment by grayjay** [comment]
> @grayjay do you have 2FA enabled on GitHub. Looks like you are not a collaborator of Cabal anymore (so I cannot assign issues to you). I'd like to add you back.

@phadej I enabled 2FA and then tried to accept your invitation, but it had expired.  Could you please resend it?

**Pull request closed without merging**
