### PR TITLE
Remove makeAbsolute

### PR DESCRIPTION
**Pull request by ttuegel**
Replaces #4208. We do not actually care about canonicity of paths, but
makeAbsolute is not available in older versions of directory.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
CI failure is due to `-Werror`.

**Comment by 23Skidoo** [comment]
Specifically,

```
[ 99 of 132] Compiling Distribution.Client.Nix ( Distribution\Client\Nix.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Nix.o )
Distribution\Client\Nix.hs:23:1: warning: [-Wunused-imports]
    The import of `<.>' from module `System.FilePath' is redundant
<no location info>: error: 
Failing due to -Werror.
```

**Comment by ttuegel** [comment]
What's the procedure for a timed-out build?

**Comment by phadej** [comment]
@ttuegel it still caches the deps, so restart usually lets the job pass. Restarted it (OSX boxes are slow).

**Comment by ezyang** [comment]
Sometimes Travis machines run a lot slower than normal, in which case a restart helps. But if we are consistently hitting the time limit we'll need to slice up the jobs some more.

**Comment by ttuegel** [comment]
It hit the timeout on Darwin again. Are you sure it's caching dependencies? The log doesn't look that way, or maybe I don't understand what it's supposed to cache.

**Comment by ezyang** [comment]
Yeah, I guess we are just over the limit. Slicin' time.

**Comment by 23Skidoo** [comment]
OK, I think I'll just merge this. If this works on OS X with 7.10.3 and on Linux with 8.0.1, it should work on OS X with 8.0.1 as well.

**Pull request merged**
