### PR TITLE
Bump directory upper bound

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Hmm, I thought I've already did that.

**Comment by 23Skidoo** [comment]
Yep, this patch is already applied. Would be nice if GitHub web UI told me that.

@bgamari Try rebasing your branch against current master.

**Comment by ezyang** [comment]
Oh that's why GH was unable to merge it :)

**Comment by ezyang** [comment]
Note that Cabal HEAD with GHC requires this patch to time: https://github.com/haskell/time/pull/58

**Comment by 23Skidoo** [comment]
> Oh that's why GH was unable to merge it :)

Hmm, seems to have worked when I pressed the "merge" button, and it looks like it did the correct thing (a no-op merge commit).

**Comment by ezyang** [comment]
I should be more clear: I asked GH to rebase and push the commits ;)

**Comment by 23Skidoo** [comment]
I forgot that GH can do that sort of thing nowadays.

**Pull request merged**
