### PR TITLE
Stop using Data.Monoid.{First,Last}

### PR DESCRIPTION
**Pull request by sjakobi**
Both will be deprecated in GHC 8.8.

This is part of https://gitlab.haskell.org/ghc/ghc/merge_requests/842.

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [X] Any changes that could be relevant to users have been recorded in the changelog.
* [X] The documentation has been updated, if necessary.
* [X] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

### CODE REVIEW

**Comment by sjakobi** [comment]
@23Skidoo would you mind taking another look at this?

I've switched to adding versions of `Data.Semigroup.{First,Last}` which can easily be removed once `Cabal` can rely on the original versions from `base`.

I also needed to add a version of `Maybe` with the modern `Monoid` instance. I went with the `Option'` name as I hoped that it would create less confusion than something like `Maybe'`.

Sadly I believe these compatibility hacks have reduced ergonomics. I'd like to get some feedback on whether this still looks acceptable or if it is too clunky already.

**Comment by sjakobi** [comment]
Not sure why Travis failed. :/ The warnings that I could find in the logs looked unrelated to my changes.

**Comment by 23Skidoo** [comment]
Seems to be green now?

**Comment by merijn** [comment]
I think all the primed names are kinda ugly, but I don't see any obvious problems in the part of my code that was touched

**Comment by 23Skidoo** [comment]
OK, let's merge then. @hvr, please shout if you disagree.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
