### PR TITLE
Test issue 6627

### PR DESCRIPTION
**Pull request by phadej**
Another try

### CODE REVIEW

**Comment by phadej** [comment]
Even worse, in GHC-8.8.3 job:

```
cabal.exe: Failed to build Diff-0.4.0. The failure occurred during the
configure step. The build process terminated with exit code 11
Failed to build StateVar-1.2 (which is required by rere-0.1). The failure
occurred during the configure step. The build process terminated with exit
code 11
```

**Comment by phadej** [comment]
@Mistuke, do you have any ideas what could change (in recent Windows) to cause that?

**Comment by phadej** [comment]
GitHub Actions upgraded `VisualStudio/16.4.5` to `VisualStudio/16.5.0`, could that cause some weird errors?

**Comment by Mistuke** [comment]
@phadej there are some reports that 8.8.3 segfaults on startup, but haven't been able to reproduce this yet. This may be another instance of that.

**Comment by phadej** [comment]
@Mistuke hmm. It fails with GHC-8.8.3 and GHC-8.6.5 (8.10.1 fails for other reasons)

## 8.6.5

```
D:\a\cabal\cabal\cabal-testsuite\PackageTests\CustomPreProcess\setup.cabal.dist\work\dist\setup\setup.exe configure --verbose=verbose +nowrap +markoutput --builddir=setup.cabal.dist\work\dist --ghc --with-compiler=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.6.5\bin\ghc.exe --prefix=D:\a\cabal\cabal\cabal-testsuite\PackageTests\CustomPreProcess\setup.cabal.dist\usr --global --package-db=clear --package-db=global --package-db=C:\SR\ghc-8.6.5\package.db --package-db=D:\a\cabal\cabal\dist-newstyle\packagedb\ghc-8.6.5 --enable-deterministic --ipid=internal-preprocessor-test-0.1.0.0 --dependency=base=base-4.12.0.0 --dependency=base=base-4.12.0.0 --dependency=base=base-4.12.0.0 --dependency=directory=directory-1.3.3.0 --disable-tests --exact-configuration --disable-benchmarks --with-ghc=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.6.5\bin\ghc.exe --with-haddock=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.6.5\bin\haddock.exe




*** unexpected failure for cabal-testsuite\PackageTests\CustomPreProcess\setup.test.hs
```

I don't think that `configure` runs GHC.

## 8.8.3 fails due

```
cabal.exe: Failed to build Diff-0.4.0. The failure occurred during the
configure step. The build process terminated with exit code 11
Failed to build StateVar-1.2 (which is required by rere-0.1). The failure
occurred during the configure step. The build process terminated with exit
code 11
```

`Diff` and `StateVar` are `build-type: Simple` packages, in the run at least `base-compat` is successfully built.

Is error code 11 indicator of segfault on Windows?

**Comment by Mistuke** [comment]
> 
> Is error code 11 indicator of segfault on Windows?

Not usually no, 11 is usually a bad image, but GHC returns `SIGSEGV` for segfault which is indeed `11`. So if it's coming from a Haskell program then it's a segfault if not it's a bad exe/dll.

Can you run it with -v3 to find out?

**Comment by Mistuke** [comment]
or get the `config.log`?

**Comment by phadej** [comment]
The latest run (windows 8.8.3) jobs shows:

```
Starting     Glob-0.10.0 (lib)

Access violation in generated code when writing 0x0

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x461da80	0x37f7b66 C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.8.3\bin\ghc.exe+0x33f7b66
 * 0x461da88	0x3277bb9 C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.8.3\bin\ghc.exe+0x2e77bb9
 * 0x461da90	0x5
 * 0x461da98	0x5
 * 0x461daa0	0x3d7dc22 C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.8.3\bin\ghc.exe+0x397dc22
 * 0x461daa8	0xe9f58a0
```

and 

```
Failed to build Glob-0.10.0 (which is required by test:cabal-benchmarks from
cabal-benchmarks-3). The build process terminated with exit code 11
```

I'll push another commit which builds with `-v3`, a lot of output to be expected...

**Comment by Mistuke** [comment]
The segfaults reported has a lot of people complaining it happened during configuring of `Setup.hs`.  I wonder if this is reproducible on AppVeyor since you can remote desktop into that.

**Comment by phadej** [comment]
@Mistuke looks like that appveyor haven't failed once yet.

**Comment by jneira** [comment]
* We tried to enable ci for ghc-8.8.4 and windows in github recently and segfaults continued being throwed so we decided to remove the combination from the test matrix
* Closing as the error is not being reproduced for now. See #6629

**Pull request closed without merging**
