### PR TITLE
Avoid partial `Data.List.last` in autogenerated `Paths_<pkg>.hs`

### PR DESCRIPTION
**Pull request by mpilgrem**
Motivation (in part):
* [STAN](https://hackage.haskell.org/package/stan) complains about use of partial `Data.List.last`
* https://github.com/haskell/core-libraries-committee/issues/292

I have reasoned that this minor refactoring is correct, but I am not sure how to test it. EDIT: What I have done is:
* unit tested `lastChar` in GHCi; and
* tested that a separate copy of the module does compile. 

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions). N/A

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by Bodigrim** [comment]
Would it work if Cabal is driving a very old GHC (or non-GHC Haskell implementation) which does not yet have `Data.List.NonEmpty` in `base`? I think it's better to inline
```
lastM :: [a] -> Maybe a 
lastM = foldr (\x -> Just . fromMaybe x) Nothing
```
(The existence of `fromMaybe` is guaranteed by [Haskell Report 2010](https://www.haskell.org/onlinereport/haskell2010/haskellch21.html#x29-25500021))

**Comment by geekosaur** [comment]
I did think about that, but I also think nobody bothers to care about non-GHC any more (I think Data.List.NonEmpty is in all the ghcs we support). That ship sailed long ago, sadly.

**Comment by mpilgrem** [comment]
The stated GHC support window for `Cabal` is five years, which means GHC 8.8.2 (released 16 January 2020) on. GHC 8.8.2 comes with `base-4.13.0.0`, which exposes `Data.List.NonEmpty`.

The Cabal project does not identify any support for non-GHC compilers of Haskell.

**Comment by Bodigrim** [comment]
> The stated GHC support window for `Cabal` is five years, which means GHC 8.8.2 (released 16 January 2020) on. GHC 8.8.2 comes with `base-4.13.0.0`, which exposes `Data.List.NonEmpty`.

My understanding always was that this is a support window for GHC to compile Cabal sources, not which GHC can be driven by Cabal. Changing `Paths_<pkg>.hs` affects the latter. Could this be clarified in `CONTRIBUTING.md`?

IIRC Cabal 3.12 was happily able to drive GHC 7.0 and such.

**Comment by geekosaur** [comment]
We stopped being able to test anything before 8.0 because ghcup's only 7-series for Ubuntu segfaults during install.

**Comment by mpilgrem** [comment]
@Bodigrim, you are correct - I misunderstood `CONTRIBUTING.md` (which is clear, now you point it out).

**Review by Bodigrim — APPROVED** [review]

**Comment by mpilgrem** [comment]
@geekosaur, second attempt at this submitted, hopefully meeting @Bodigrim's observation.

The 'required' CI 'Quick jobs / Meta checks' is failing at step 'Check that diff is clean'. I do not know what that is testing, or why it is failing.

**Comment by geekosaur** [comment]
I saw that, and I don't know either (I can't figure out how a commit pushed to GitHub could fail that check??).

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
And I just checked out your branch locally, and it's clean here. (Both the diff against `master` (and `HEAD^`) and the `git diff-files -p` check that's failing.)

@Mikolaj, @Kleidukos do either of you know what's going on here?

**Comment by ulysses4ever** [comment]
@mpilgrem you'll have to update https://github.com/haskell/cabal/blob/master/templates/Paths_pkg.template.hs according to your changes to Z.hs. See, for example, the previous instance of such an coordinated update: https://github.com/haskell/cabal/commit/cc8d5dfe3a5c48ac0e8e62d62933da55d1470043

**Comment by Mikolaj** [comment]
> Would it work if Cabal is driving a very old GHC (or non-GHC Haskell implementation) which does not yet have `Data.List.NonEmpty` in `base`? 

Thinking aloud, if it's driving a compiler, not compiling with it, `NonEmpty` should work fine regardless whether it's supported by the compiler. What would matter if some compiler options were missing, but that's very unrelated.

Also thinking aloud, tests would be great, but there's no way to test this, except for adding a STAN run to CI or checking for a new GHC warnings to the same effect (though I don't remember the new warnings complain about `last`).

**Comment by geekosaur** [comment]
Sigh. Still got merged prematurely.

**Pull request merged**
