### PR TITLE
Upgrade Tasty to 1.0 and update appveyor.yml.

### PR DESCRIPTION
**Pull request by phadej**
Rebased version of #5014 

---

Also set an upper bound on Tasty, because it tends to break things
when updated.

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
@23Skidoo we cannot yet force `tasty >= 1.0`, as that needs `hackage-repo-tool` to lift it's `optparse-applicative < 0.14` upper bound.

**Comment by phadej** [comment]
Note: we should update `QuickCheck` too, and it's (kind of also) blocked on `hackage-security`

**Comment by 23Skidoo** [comment]
I think everyone in the haskell/cabal team has commit access to hackage-security.

**Comment by 23Skidoo** [comment]
Closing in favour of #5149.

**Pull request closed without merging**
