### PR TITLE
Bump version numbers to 3.10.3.0

### PR DESCRIPTION
**Pull request by Kleidukos**
Bump versions to 3.10.3.0

### CODE REVIEW

**Comment by Kleidukos** [comment]
I'm trying to update the bootstrap files with 9.4.8 (instead of 9.4.5) and I'm getting this error:

```
src/Main.hs:22:1: error:
    Ambiguous module name ‘Distribution.Types.PackageName’:
      it was found in multiple packages:
      Cabal-3.6.3.0 Cabal-syntax-3.10.2.0
   |
22 | import qualified Distribution.Types.PackageName as C
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Main.hs:23:1: error:
    Ambiguous module name ‘Distribution.Types.Version’:
      it was found in multiple packages:
      Cabal-3.6.3.0 Cabal-syntax-3.10.2.0
   |
23 | import qualified Distribution.Types.Version as C
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mpickering** [comment]
You need to remove the `3.2.0.0` Cabal dependency clause in `cabal-bootstrap-gen.cabal` (see #9722)

**Comment by Kleidukos** [comment]
@mpickering thank you. I imagine we should wait for your PR to be merged and then backport it to 3.10?

**Comment by Mikolaj** [comment]
In that case, maybe we'd force-merge https://github.com/haskell/cabal/pull/9722 before the delay passes?

**Comment by mpickering** [comment]
I don't think that CI changes are suitable to back-port in general, it is much safer to apply just the changes needed to the CI configuration on the local branch so that there is less potential for change between minor releases.

In this case we certainly don't want to copy the bootstrap plans, those are likely to be wrong for the 3.10 branch!

**Comment by Kleidukos** [comment]
@mpickering yes, of course. :) 
Btw, what made you understand that Cabal 3.2.0.0 had to go? The error message mentions Cabal-3.6.3.0, so I'm a bit confused.

**Comment by mpickering** [comment]
> @mpickering yes, of course. :) Btw, what made you understand that Cabal 3.2.0.0 had to go? The error message mentions Cabal-3.6.3.0, so I'm a bit confused.

Ah I think you need to delete 3.4 and 3.6 as well, because 3.8 is the first version where `Cabal` depended on `Cabal-syntax`, so if you choose `3.6` then you also need to satisfy the `Cabal-syntax` dependency (so it chooses 3.10) and you get this clash.

Another way to fix this is to probably delete the explicit `Cabal-syntax` dependency

**Comment by Mikolaj** [comment]
CI died in the https://github.com/haskell/cabal/issues/9700 way. I'd propose to disable this one test on branch 3.10 in this very PR and continue (there are some more steps in CI that get cancelled due to this failure). Releasing with a broken CI is unfortunate, but that's only a single test with a relatively old GHC, ao it's likely to be a fluke and releasing promptly has much higher priority IMHO.

**Comment by Kleidukos** [comment]
@Mikolaj just so I understand, you approve bypassing the branch protection?

**Comment by Mikolaj** [comment]
No, I propose disabling the failing test in the CI script.

**Review by Mikolaj — APPROVED** [review]
LGTM

**Pull request merged**
