### PR TITLE
[ docs ] fix typo in cabal update’s help

### PR DESCRIPTION
**Pull request by ulysses4ever**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ffaf1 — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@mergify backport 3.8

**Comment by Mikolaj** [comment]
Let me rebase to see if the recent CI workaround unblocks merging.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
2 days have passed, but CI halted merging, so let me merge by hand and also experiment with CI and the backport of this PR.

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
