### PR TITLE
Update stack resolver

### PR DESCRIPTION
**Pull request by flip111**
For https://github.com/haskell/cabal/issues/6525

### CODE REVIEW

**Comment by m-renaud** [comment]
The referenced issue was closed before this PR was merged in, was that a mistake? Is this still a problem or can we close this PR?

**Comment by flip111** [comment]
you can merge this PR

**Comment by m-renaud** [comment]
I'll defer to @phadej here, although I noticed that the change uses a nightly resolver and specific hashes for the deps. Would it be possible to select a more recent LTS and released versions of the libraries?

**Comment by flip111** [comment]
> Would it be possible to select a more recent LTS and released versions of the libraries?

I couldn't get this to work. But it might be possible

**Comment by gbaz** [comment]
closing this as outdated. whatever resolver this was set to work against is not nearly the current one anymore. (and in general i think when prs to update resolvers come in, they should be against lts and not nightly if at all possible)

**Pull request closed without merging**
