### PR TITLE
testsuite: Add test for #9334

### PR DESCRIPTION
**Pull request by mpickering**
This adds a test which checks that v2-run works with profiling.

```
cabal v2-run --enable-profiling Main.hs
```

which is the same one as is run in ghcup-ci.

This test fails on recent GHC versions on GHCUp CI so hopefully also on cabal CI.

https://github.com/haskell/ghcup-metadata/actions/runs/6369779959/job/17290326630#step:3:15214

### CODE REVIEW

**Review by andreabedini — APPROVED** [review]
👍

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
> This test fails on recent GHC versions on GHCUp CI so hopefully also on cabal CI.

But it doesn't fail on our CI? I'm confused...

**Comment by mpickering** [comment]
> > This test fails on recent GHC versions on GHCUp CI so hopefully also on cabal CI.
> 
> But it doesn't fail on our CI? I'm confused...

I don't know.. it might only fail with 9.6.3 (which is not currently tested).

**Comment by mpickering** [comment]
I rebased onto master, where 9.6.3 tests are run on windows, so we will perhaps see if there is a problem there!

**Comment by ulysses4ever** [comment]
No luck so far: windows-9.6.3 succeeded

**Comment by gbaz** [comment]
One wild guess.

The failing line is `cabal --verbose=0 run --enable-profiling ./main.hs -- +RTS -s`

I don't think the verbosity flag is the problem, and in sufficiently recent cabals `run` is the same as `-run`, but note that the faling line A) miscapitalizes main.hs, and B) calls it with a "./" prefix. I wonder if either of these is the cause of the failure?

**Comment by mpickering** [comment]
I tried to recreate that situation in the test. The file I added is `main.hs` (like the ghcup CI script) and also call it in the same way (with the ./ prefix). 

I will further modify the test to look for `Main.p_o` .. because I imagine that actually `main.p_o` is getting created. It's also possible this is fixed on master, and broken on 3.10 branch.

**Comment by gbaz** [comment]
hrm, maybe we should try to diagnose also by prs against ghcup's ci that tweaks the calls a bit? its very hard to see what might be happening. are they using the same or different windows images?

**Comment by mpickering** [comment]
I have added a second unit test which uses randomised testing to check the filepaths are valid.

**Comment by mpickering** [comment]
I deliberately rewrote my code away from the hlint suggestion so it was nicer to document the clauses. I don't intend to change it back.

**Comment by mpickering** [comment]
The test passes on windows, because `%` is in fact a valid character for a filepath. It just seems that some programs/contexts will interpret `%` as an environment variable marker. Do I augment my test with an ad-hoc check for `%` as well?

**Comment by ulysses4ever** [comment]
Re hlint: could you use `{-# HLINT ignore "Use &&" #-}` (or whatever the name of the suggestion, I haven't checked), so that the CI stays green, and you get your preferred style?

**Comment by ulysses4ever** [comment]
> Do I augment my test with an ad-hoc check for % as well?

Yes, we live in a world where specs are not followed, and we have to acknowledge it, I think.

**Comment by Mikolaj** [comment]
@mpickering: would you like any help with that one?

**Comment by alt-romes** [comment]
Matthew thinks that this was ultimately not testing the right thing, so we are better off dropping the patch.

**Pull request closed without merging**
