### PR TITLE
Use munch1 to parse Language

### LINKED ISSUE #8507: Trailing spaces break cabal HEAD
```
$ cabal unpack bimap-0.5.0
Downloading  bimap-0.5.0
Downloaded   bimap-0.5.0
Unpacking to bimap-0.5.0/
$ cd bimap-0.5.0
bimap-0.5.0$ cabal build
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: bimap (user goal)
[__0] rejecting: bimap-0.5.0 (conflict: requires unknown language Haskell98 ;
did you mean Haskell98?)
[__0] rejecting: bimap-0.4.0, bimap-0.3.3, bimap-0.3.2, bimap-0.3.1,
bimap-0.3.0, bimap-0.2.4, bimap-0.2.3, bimap-0.2.2, bimap-0.2.1, bimap-0.2,
bimap-0.1 (constraint from user target requires ==0.5.0)
[__0] fail (backjumping, conflict set: bimap)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: bimap
```

Apparently Cabal HEAD is confused by trailing spaces in `default-language` field:
```cabal
  default-language:    Haskell98   
```

Cabal 3.8.1.0 works fine on this example.

### PR DESCRIPTION
**Pull request by ffaf1**
Closes #8507 

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] No relevant user change (regression).
* [x] No documentation needed (regression).

Now with regression test.

### CODE REVIEW

**Comment by jneira** [comment]
many thanks, a fix with such tiny change is great but a regression test will be required imo, such bug should not arise again never

**Comment by ulysses4ever** [comment]
For the test: using a web browser, I can’t see any trailing space there. Are you sure your editor doesn’t strip those?

**Review by ulysses4ever — APPROVED** [review]
Looks good, thanks for the swift action!

**Comment by ffaf1** [comment]
Alas CI complains — correctly — about extra whitespace.

**Comment by ulysses4ever** [comment]
https://github.com/haskell/cabal/blob/a5106bed5a197e9f670a0949f803e714ad4ef403/fix-whitespace.yaml#L90

**Comment by ffaf1** [comment]
Thanks that did it, ready for review.

**Review by jneira — APPROVED** [review]
lgtm, thanks!

**Comment by ulysses4ever** [comment]
I realized the delay doesn't work for the squash label. It's easy to fix in the Mergify config but meanwhile let me play Mergify

**Comment by ulysses4ever** [comment]
@Mergify backport 3.8

**Comment by ulysses4ever** [comment]
No need in backporting this because the original change was not applied to 3.8.

**Pull request merged**
