### PR TITLE
Fix some `v2-install` options

### LINKED ISSUE #5788: cabal new-install doesn't support --ghc-options
```
$ cabal new-install --ghc-options='-fllvm -optlo-O2 -j +RTS -A64m -n2m -RTS' all
cabal: unrecognized 'new-install' option `--ghc-options=-fllvm -optlo-O2 -j
```

### PR DESCRIPTION
**Pull request by harpocrates**
Fixes #5788 by

  - adding `--ghc-options` (actually the full suite of configure-related options
    already available to other `v2-*` commands, but `--ghc-options` is the one
    most folks care about)
  - prefixing haddock related options with `haddock-`

The fact that `Distribution.Client.Setup` and `Distribution.Simple.Setup` both
export a bunch of functions that are identically named _and_ have similar
functionality is probably going to continue to cause bugs of this sort...

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by hasufell** [comment]
Will there be a point release for this?

**Comment by 23Skidoo** [comment]
Well, 3.0 should be out fairly soon now, but maybe. I've cherry-picked this patch to the `2.4` branch.

**Comment by 23Skidoo** [comment]
I noticed that `--ghc-options` is missing from the `help v2-install` output, unlike `v1-install`, for which we have:

```
The flags --with-PROG and --PROG-option(s) can be used with the following programs:
  alex ar c2hs cpphs doctest gcc ghc ghc-pkg ghcjs ghcjs-pkg greencard haddock
  happy haskell-suite haskell-suite-pkg hmake hpc hsc2hs hscolour jhc ld
  pkg-config runghc strip tar uhc
```

**Comment by hvr** [comment]
@phadej @23Skidoo I've been wondering about backporting this to the 2.4 branch; I'm just a bit hesitant as this can reasonably be considered a "breaking change" in the CLI, even though it's fixing something that was clearly wrong in the CLI... any opinions whether we should or should not consider this for the `cabal` 2.4.2 point rls?

**Comment by 23Skidoo** [comment]
I'm +1 on backporting.

**Pull request merged**
