### PR TITLE
Add make style-modified

### PR DESCRIPTION
**Pull request by phadej**
As it runs fourmolu only on the modified files, it's a lot faster.

### CODE REVIEW

**Review by ffaf1 — APPROVED** [review]
Extremely useful.

**Comment by phadej** [comment]
I wonder if `make style` should be changed to `git ls-files` too.

**Comment by ulysses4ever** [comment]
Yeah, that would be a friendlier default for `make style`.

**Comment by phadej** [comment]
ping

**Review by andreabedini — APPROVED** [review]
👍

**Comment by phadej** [comment]
Since the merge delay the conflict was introduced. This is a frustrating. (And my other PR isn't merged, which may conflict further).

**Comment by phadej** [comment]
@ulysses4ever could you resolve the conflict, as you introduced the conflicting change in https://github.com/haskell/cabal/pull/9011 but for some reason that got merged first.

I won't have time to look into this for the next two weeks at least.

**Comment by phadej** [comment]
I won't. I don't like people pushing into branches in my fork. (I actually use these branches as base of further work). The updates are stupid feature from GitHub (and GitLab). Feel free to *pull* the changes into own branches.

**Pull request closed without merging**
