### PR TITLE
Bump versions and deps on master branch to 3.11 and regenerate bootstrap files

### PR DESCRIPTION
**Pull request by Mikolaj**
This is a counterpart of https://github.com/haskell/cabal/pull/8799 but for master branch. Now it should not break CI, because cabal 3.10 is already on Hackage, so it can be performed. The opposite, it should fix some other problems on CI due to stable release change.

### CODE REVIEW

**Comment by Mikolaj** [comment]
And 3.10 is apparently too new yet for the Custom setup in cabal-testsuite. Perhaps it needs to wait until GHA provides it (not just ghcup)? In any case, let me downgrade to make it work again. The funny thing is, 3.10.1.0 works fine on 3.10 branch, but that's probably, because it takes it from in-place build.

**Comment by ulysses4ever** [comment]
Well, my comment didn't take this into account: https://github.com/haskell/actions/issues/202#issuecomment-1466388442

**Comment by Mikolaj** [comment]
I'm not sure about my hypothesis, either, but setting it to 3.10 failed and, I think, not even on Windows. Let's see...

**Comment by Mikolaj** [comment]
I invalidated your both reviews. I apologise --- I did not expect I will have to update bootstrap files in the same PR, hence I asked for reviews so early.

**Comment by Kleidukos** [comment]
no worries :+1:

**Review by Kleidukos — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
OK, all bootstraps passed and one validate did and nothing failed. Let me try to extra commit.

**Comment by Mikolaj** [comment]
Hah, @ulysses4ever: I see I need to steal your https://github.com/haskell/cabal/pull/8840/commits/e6e07e8c9d233e63c585be9037180ec58091617d

**Comment by Mikolaj** [comment]
Job "Validate ubuntu-20.04 ghc-prerelease" fails with lots of mentions of "setup.Cabal-3.9.0.0/installed-3.9.0.0". How come? It has to come from CI cache, right? Because it doesn't have access to cabal 3.9 from anywhere else. If so, clearing the cache should be enough or switching to 9.6.1.

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Pull request merged**
