### PR TITLE
The release cleanup action requires a token

### PR DESCRIPTION
**Pull request by geekosaur**
See https://github.com/haskell/cabal/actions/runs/12415183173/job/34666846889

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Comment by ulysses4ever** [comment]
Doesn't seem like it helped? https://github.com/haskell/cabal/actions/runs/12448218422/job/34753867653

**Comment by ulysses4ever** [comment]
I guess the commit I referenced as an implementation of this was a stale one. Unfortunately, I killed the latest one that actually worked, so now I'm rediscovering all the pain I had to go through while trying to fix it: https://github.com/liudonghua123/delete-release-action/issues/1#issuecomment-2465672712

**Comment by ulysses4ever** [comment]
Funnily, `prerelease-lts` and `prerelease-head` have different indentation...

**Comment by ulysses4ever** [comment]
Follow-up: https://github.com/haskell/cabal/pull/10662

**Comment by geekosaur** [comment]
> Funnily, `prerelease-lts` and `prerelease-head` have different indentation...

Yep, we hit that one earlier and I mentioned that I'd fixed it in the CI rewrite.

**Pull request merged**
