### PR TITLE
Add PHONY rules for lint and lint-json

### LINKED ISSUE #10583: Add a lint rule to makefile
We have this recipe for running HLint producing JSON output, added in #10421. Please follow up and make this a rule.

https://github.com/haskell/cabal/blob/c3a9dd7722335900619d64ad19be79ec5b7cf402/Makefile#L54-L57

### PR DESCRIPTION
**Pull request by philderbeast**
Fixes #10583, adding `PHONY` rules for `lint` and `lint-json`.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
I'm generally not sure how much profit we get from such simplistic one-line, three-four-words make rules. This saves very little but makes Makefile bigger and harder to maintain. But I'm not opposed to it. Myself, I don't really use the Makefile.

One more thing I always say about new targets in the Makefile: consider updating the CI to use these targets if you don't want them to bitrot right away.

**Comment by philderbeast** [comment]
> This saves very little

It can save time:

```
$ time hlint .
No hints

________________________________________________________
Executed in   92.47 secs    fish           external
   usr time   92.32 secs    0.00 micros   92.32 secs
   sys time    0.26 secs  931.00 micros    0.26 secs

$ time hlint -j .
No hints

________________________________________________________
Executed in   18.43 secs    fish           external
   usr time  337.22 secs  704.00 micros  337.22 secs
   sys time    3.58 secs  165.00 micros    3.58 secs
```

**Comment by ulysses4ever** [comment]
> It can save time:

I'm not saying `hlint -j` vs `hlint`, I'm saying `hlint -j` vs `make hlint`.

> `I had but we use haskell-actions/hlint-run for this in CI.`

Yes, this is my usual beef with GitHub actions that run things -- they foster diverging workflows locally vs. in CI, I think it's a bad design. I wish CI only used setup-actions and running stuff was done via make targets -- we'd have a single source of truth to work with.

**Comment by philderbeast** [comment]
> I'm not saying `hlint -j` vs `hlint`, I'm saying `hlint -j` vs `make hlint`.

I was showing the time saving by running the recipe for the `lint` rule versus running `hlint .` naively without adding that option. Sorry I wasn't clearer about that timing comparison.

```makefile
.PHONY: lint
lint: ## Run HLint
	hlint -j .
```

**Comment by philderbeast** [comment]
> Yes, this is my usual beef with GitHub actions that run things -- they foster diverging workflows locally vs. in CI, I think it's a bad design. I wish CI only used setup-actions and running stuff was done via make targets -- we'd have a single source of truth to work with.

@ulysses4ever I agree. It can be hard to run github actions locally without hassle (having tried [nektos/act](https://github.com/nektos/act)).

**Comment by ulysses4ever** [comment]
> Sorry I wasn't clearer about that timing comparison.

It's okay, maybe it was me who wasn't clear enough. Just to reiterate: I doubt that adding a make target as small as `lint` (only have one line) is beneficial: it saves minimal typing (you'll type `make lint` instead of `hlint -j .`) at the cost of blowing the Makefile. But again, I'm not blocking it on this ground...

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
> I'm generally not sure how much profit we get from such simplistic one-line, three-four-words make rules. This saves very little but makes Makefile bigger and harder to maintain. But I'm not opposed to it. Myself, I don't really use the Makefile.

I think having a documented single source of truth for local checks is an advantage over developers having to dig to find out how we use it locally. CI using it is of course the obvious next step after that, but IIRC I was a bit worried about the way the CI actions worked and didn't want to sit down and research why they looked weird.

**Comment by geekosaur** [comment]
Admittedly I've put more effort into documenting it in `CONTRIBUTING.md` in order to encourage its use. The counterpoint to your worry is the number of times people on yesterday's call said they push stuff up to CI and see if it fails instead of checking locally first (/cc @mpickering), which to me is wasted time. (Yes, I was doing that with the API checks, but my worry there was always irreproducibility on the dev's machine and in fact I _still_ don't entirely trust that a dev on Windows or an M1/M2 Mac will get the same result as someone on Ubuntu 24.04.)

**Comment by ulysses4ever** [comment]
>  The counterpoint to your worry is the number of times people on yesterday's call said they push stuff up to CI and see if it fails instead of checking locally first, which to me is wasted time. 

Sorry, I'm a bit lost here:

- what is a wasted time?
- if people "simply" use CI, how does it counter my worry that the Makefile bitrots, and inflating it only limits the hope of someone actually cleaning it up?

I'd prefer 0 bitrot in this repository. I think it's confusing to unsuspected people and therefore harmful. That's why I always bring up this point about exercising the Makefile in CI. Core devs that show up on the calls can do whatever --- they will find their way around bitrot. It's the rest 99% who I'm worried about.

**Comment by philderbeast** [comment]
Label merge+no rebase is necessary when the pull request is from an organisation.

**Comment by geekosaur** [comment]
I think the only way CI wins for something that can _easily_ be checked locally (which is the point of the `Makefile` rules) is if you can leave it to run overnight — but you can also do that in a terminal session locally.

**Comment by philderbeast** [comment]
I've been struggling to find what is failing with CI validate runs for #10546. One benefit of running locally is that it is about 30x faster.

**Pull request merged**
