### PR TITLE
Backpack (comment fixes)

### PR DESCRIPTION
**Pull request by askeblad**
https://github.com/haskell/cabal/pull/7882 resubmitted

Cabal-syntax/src/Distribution/Backpack.hs

### CODE REVIEW

**Comment by askeblad** [comment]
@grayjay can you review

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by askeblad** [comment]
@fgaz looks like we need 2 reviewers

**Review by fgaz — APPROVED** [review]
Thanks!

**Comment by fgaz** [comment]
Actually could you change the commit message to something more descriptive like:

```
Fix OpenUnitId comment

* IndefUnitId (data constructor) was previously incorrectly renamed to
  OpenUnitId (type constructor) instead of DefiniteUnitId
* fix typo
```

I'd change it myself, but for some reason I don't have access to this branch (usually maintainers can push to pr branches)

**Comment by askeblad** [comment]
changed cabal/.git/COMMIT_EDITMSG

**Comment by Mikolaj** [comment]
Yay, it worked. I normally do this via `git commit --amend`. Could you also rebase, given that your branch is not writable, so we can't auto-rebase with MergifyIO?

**Comment by askeblad** [comment]
```
$ which vi
which: no vi in (/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/libexec/kf5:/usr/lib64/qt5/bin)
$ ln -sf /usr/bin/vim ~/.local/bin/vi
$ export PATH=~/.local/bin:${PATH}
$ cd /tmp/cabal
```

`git commit --amend`

edit and save file

`git push -f origin master`

<hr>

> something like

does not work

**Comment by Mikolaj** [comment]
Oh, yes, the `amend` commands you cited look great.

If the rebase doesn't work, perhaps this is needed first:

    git remote add upstream git@github.com:haskell/cabal.git

In the worst case we can try the `Rebase and Merge` button, but then there's no link to the PR in git history, so that's sub-optimal (and it needs to be done manually).

**Comment by askeblad** [comment]
```sh
$ cd /tmp/cabal
$ git remote add upstream https://github.com/haskell/cabal.git
$ git fetch -q upstream
$ git rebase upstream/master
Successfully rebased and updated refs/heads/master.
$ 
```

`git push -f origin master`

**Comment by Mikolaj** [comment]
Perfect. Merged. Thank you.

**Pull request merged**
