### PR TITLE
Add MHS as a recognized compiler.

### PR DESCRIPTION
**Pull request by augustss**
The title says it all.

### CODE REVIEW

**Review by geekosaur — COMMENTED** [review]
Does this need additional code for compiler support? (cf. `Distribution.Simple.{GHC,HaskellSuite,…}`)

**Comment by augustss** [comment]
I don't care about additional code right now.  I just want to have mhs be recognized as a valid Haskell compiler to be used in .cabal files.

To build things with mhs I use mcabal anyway.

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
Looks like a hash needs to be updated:
```
  Distribution.Utils.Structured
    GenericPackageDescription:                                           FAIL (0.02s)
      tests/UnitTests/Distribution/Utils/Structured.hs:31:
      expected: 5a48c6570cbcf96af4c51f38962e37b5
       but got: f6306d42af1d4f88b269cbd6a7879e6d
      Use -p '/Distribution.Utils.Structured.GenericPackageDescription/' to rerun this test only.
    LocalBuildInfo:                                                      FAIL (0.02s)
      tests/UnitTests/Distribution/Utils/Structured.hs:31:
      expected: 6d668de33d7b4d5df3830e65e6941373
       but got: 214d441d7d9bf881624984de13980b37
      Use -p '/LocalBuildInfo/' to rerun this test only.
```

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
Actually, @geekosaur was right all along --- the hashes need to be updated to the ones given in https://github.com/haskell/cabal/actions/runs/8908155162/job/24463289224?pr=9878. @augustss: I'm afraid that's the task of the PR author. We'd also need a tiny changelog file: https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog. I think, we can skip a test in this case, but it never hurts to add one. Thank you for the PR!

**Comment by augustss** [comment]
Is there any chance this fix could be merged soon?
I'm not asking for very much, just that one more compiler is recognized so I can upload my packages that has 'impl(mhs)' in them.
Or should I just give up and pretend my compiler is called ghc?

**Comment by ffaf1** [comment]
@augustss , for this to be merged you need to update the hashes, like @geekosaur suggested.

I would also add a simple comment to specify what MHS is longhand,

**Comment by augustss** [comment]
I've added a comment, added a changelog entry, and updated the checksums.

**Review by ulysses4ever — APPROVED** [review]

**Review by ffaf1 — APPROVED** [review]

**Comment by ulysses4ever** [comment]
It's been sitting for a while, so I take the liberty and apply the delay-passed label.

**Comment by ulysses4ever** [comment]
@mergify backport 3.12

**Comment by ulysses4ever** [comment]
@Mergify refresh

**Comment by augustss** [comment]
Thanks!

**Comment by Bodigrim** [comment]
Too late now, but adding new constructors constitutes a breaking change. It should not have happened without bumping a major version of `Cabal-syntax` package:
* https://hackage.haskell.org/package/Cabal-syntax-3.12.0.0/docs/Distribution-Compiler.html#t:CompilerFlavor
* https://hackage.haskell.org/package/Cabal-syntax-3.12.1.0/docs/Distribution-Compiler.html#t:CompilerFlavor

**Pull request merged**
