### PR TITLE
Improve Haddock markups (fixes #4703)

### LINKED ISSUE #4703: Seemingly incorrect Haddock generation for BuildInfo
While viewing the Haddocks, I see the following:
screen shot 2017-08-17 at 9 52 55 am

Looks like Haddock is having trouble parsing the markup here, and has put the docs for `buildTools` into the `buildable` docs. Happy to send a PR to fix this up, just confirming I'm not missing something first.

### PR DESCRIPTION
**Pull request by snoyberg**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM, feel free to merge. I canceled all Travis builds except one, since this only touches comments.

**Comment by snoyberg** [comment]
Cool, thanks @23Skidoo for the lightning response 😄

**Comment by 23Skidoo** [comment]
In the future please don't hesitate to push minor fixes such as this one directly to `master`.

**Comment by snoyberg** [comment]
Noted, thanks

**Pull request merged**
