### PR TITLE
Give `cabal-install` the Wcompat treatment

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by hvr** [comment]
Btw, if don't need to support GHC < 7.4 we can leverage `Generic`-based deriving for many of the tedious boilerplate-y `Semigroup`/`Monoid` instances in `Cabal` and `cabal-install`... assuming we can derive `Generic` for the respective types.

**Comment by 23Skidoo** [comment]
Yes, we should do that, but after the 1.24 release.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by hvr** [comment]
btw, we're currently using cabal install 1.22 in the Travis job for GHC HEAD... but GHC 8.0/HEAD requires at least 1.23 ; see also https://phabricator.haskell.org/D1892

**Comment by 23Skidoo** [comment]
Yes, I know it's broken.

**Pull request merged**
