### PR TITLE
Use lukko for file-locking

### PR DESCRIPTION
**Pull request by phadej**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
```
OFD.hsc:162:16: error: ‘F_OFD_SETLKW’ undeclared (first use in this function)
```

I wonder what causes that.

**Comment by arybczak** [comment]
What's the advantage over previous solution?

**Comment by phadej** [comment]
@arybczak are there some problems?

The reasons was to reduce the code duplication in `cabal-install` and `hackage-security`, and pain of tracking changes in GHC locking code semantics.

**Comment by arybczak** [comment]
No, I was just curious because I wrote the original locking code ;)

**Pull request merged**
