### PR TITLE
Revert " Rerun dependency solver to generate a better error message (issue #4823)."

### PR DESCRIPTION
**Pull request by 23Skidoo**
Reverts haskell/cabal#5012

### CODE REVIEW

**Comment by phadej** [comment]
Commit message should say why we do this revert.

ping @grayjay

**Comment by 23Skidoo** [comment]
@phadej Will do. See my comment in #5012 for now.

**Comment by 23Skidoo** [comment]
OK, this unborks AppVeyor at least...

**Comment by grayjay** [comment]
I'm looking into the failure now.  I think it's a test-only issue.

**Comment by grayjay** [comment]
#5133 fixed the test failure.

**Pull request closed without merging**
