### PR TITLE
Simplify to avoid a typo

### PR DESCRIPTION
**Pull request by philderbeast**
I found a typo reading the test suite readme and ended up shortening a sentence to avoid it.

### CODE REVIEW

**Review by ffaf1 — APPROVED** [review]

**Review by geekosaur — APPROVED** [review]

**Comment by philderbeast** [comment]
@ulysses4ever, we'll need the label tweak to get this one through, won't we, same as #9264?

Screen Shot 2023-10-27 at 6 28 43 AM

**Comment by ulysses4ever** [comment]
@philderbeast I'm surprised that no one has granted you permissions to manage labels. I'll fix it today. Thanks!

**Comment by ulysses4ever** [comment]
@Mergify refresh

**Comment by Mikolaj** [comment]
@philderbeastm, you have the rare and powerful Write access to the repo. while Triage suffices to add labels. Are you sure you can't add labels to your PRs?

**Comment by Mikolaj** [comment]
@philderbeast, you have the rare and powerful Write access to the repo. while Triage suffices to add labels. Are you sure you can't add labels to your PRs?

**Comment by ulysses4ever** [comment]
@Mikolaj with no explicit permissions, I'm pretty sure you can't change labels even on your own PRs.

**Comment by Mikolaj** [comment]
I'm missing something. Is this the label changing we are talking about? 
image

**Comment by ulysses4ever** [comment]
Yes, it is. Write permission is enough to do that. Triage as well. No permission is not enough. I thought that you suggested above that no permission is supposed to be enough to change labels on your own PRs, which is not the case (I think). If you didn't suggest that, then I misread you, and I apologize.

**Comment by Mikolaj** [comment]
No, I didn't intend to suggest that. Phew, great, so we have a common understanding of how it's supposed to work. :) I'm just worried something is broken (or I'm misunderstanding github), given that @philderbeast had the Write permission for some time, but apparently was not able to change labels (or else, why @ulysses4ever needed to do that personally?).

**Comment by ulysses4ever** [comment]
Oh, so I misread you in another way also: I didn’t get / know that @philderbeast had the permissions! In that case I can’t explain it in any way other than that the GitHub UI is confusing (I very much believe in that), and Phil missed the button.

**Comment by geekosaur** [comment]
I can confirm that you can'[t add labels even on your own PRs if you don't have repo permissions of some kind.

**Comment by Mikolaj** [comment]
> I can confirm that you can'[t add labels even on your own PRs if you don't have repo permissions of some kind.

Good to know, but it's not the situation we are trying to understand, because Phil did have the permissions (at least since a few days ago, when I checked).

**Pull request merged**
