### PR TITLE
Allow "cycles" through test suite dependencies (VERSION TWO)

### PR DESCRIPTION
**Pull request by ezyang**
This is a version of #3232 updated for HEAD.

CC @edsko

### CODE REVIEW

**Comment by 23Skidoo** [comment]
If the tests pass, can you please squash fix-up commits with the original ones? Would be nice to avoid having broken commits in history.

**Comment by ezyang** [comment]
There's still a bug in this PR though, `cabal install` in the sandbox is not idempotent. In the integration test, if I run it the second time, here's what I get:

```
      In order, the following will be installed:
      A-2 *test (via: T-1) (reinstall) (changes: T-1 added)
      T-1 (via: A-2) (reinstall) (changes: A-1 -> 2)
```
@23Skidoo Of course.

**Comment by grayjay** [comment]
The log from the third run looks like #3203.

**Comment by ezyang** [comment]
(I guess, at some point, we should move this to a branch on `origin` so @edsko can push to it.)

**Comment by 23Skidoo** [comment]
So I think I won't delay the first 1.24 release for this. If @kosmikus thinks that this PR should go into 1.24, I think it can be made a part of a point release. Which means that 1.24 is now good to go.

**Comment by kosmikus** [comment]
Independently of the first 1.24 release, I'd like to understand better what is going on here. There's quite a bit of history, and perhaps someone who has been following that more closely than I have can provide a good summary of what the status here is? @ezyang ?

**Comment by ezyang** [comment]
I don't really know how the patch internally works, but I know that the obvious test for the feature (cabal installing a package with a cyclic dependency in a sandbox) doesn't work properly. So someone needs to dig in and figure out why it's failing and then fix it.

**Comment by 23Skidoo** [comment]
> the obvious test for the feature (cabal installing a package with a cyclic dependency in a sandbox) doesn't work properly. So someone needs to dig in and figure out why it's failing and then fix it.

@edsko, can you look into it?

**Comment by edsko** [comment]
@23Skidoo the solver part of this is working, as far as I can tell. I'm not sure what's going on with the sandbox, some additional check somewhere I think. I don't know when I'll get a chance to look at that; perhaps somebody who is more familiar with the sandboxing stuff would be able to identify the problem more quickly?

**Comment by 23Skidoo** [comment]
> I don't know when I'll get a chance to look at that; perhaps somebody who is more familiar with the sandboxing stuff would be able to identify the problem more quickly?

I'll try to take a look at this next month.

**Comment by hvr** [comment]
@ezyang I wanted to to try this PR to see whether it fixes the issues I have with a couple of packages (`time`, `bytestring`, `binary`, `cassava`, ...) but sadly this PR has bitrotted  and needs to be rebased with the merge-conflicts resolved...

**Comment by 23Skidoo** [comment]
Closing in favour of #3402.

**Comment by 23Skidoo** [comment]
@hvr See #3402 for an updated version.

**Comment by hvr** [comment]
@23Skidoo thanks!

**Pull request closed without merging**
