### PR TITLE
Use cabal-install 2.0 on Travis for the 2.0 branch as well

### PR DESCRIPTION
**Pull request by 23Skidoo**
This is f3ade3fea60a8eadc90c0b0eaba20bcca7aceb1d cherry-picked to the 2.0 branch.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Seems to be failing [because of](https://travis-ci.org/haskell/cabal/jobs/259545699#L2915):

```
$ cabal check
These warnings may cause trouble when distributing the package:
* 'ghc-options: -main-is' is not portable.
```

However, [on `master` we get](https://travis-ci.org/haskell/cabal/jobs/259618292#L2073):

```
$ cabal check
No errors or warnings could be found in the package.
cabal check took 0 seconds.
```

idk why there is a difference.

**Comment by 23Skidoo** [comment]
I can reproduce this locally, however. My hypothesis is that `-fmonolithic` business in `master` tricks `cabal check` into accepting the `master` version of `cabal-install.cabal` with no warnings.

**Comment by 23Skidoo** [comment]
I wonder whether the "`-main-is` is not portable" check still makes sense. It was originally added in 2008 by @dcoutts (commit 39c03860055116afa365cc5e6610f85b4e4116df).

**Comment by hvr** [comment]
> I wonder whether the "-main-is is not portable" check still makes sense. 

I'd argue that `ghc-options` is not portable ;-)

**Comment by ezyang** [comment]
> I can reproduce this locally, however. My hypothesis is that -fmonolithic business in master tricks cabal check into accepting the master version of cabal-install.cabal with no warnings.

Haha. We should file a proper ticket for this.

**Pull request merged**
