### PR TITLE
Exclude broken 'Validate windows-latest ghc-8.4.4' job that cancels CI

### PR DESCRIPTION
**Pull request by Mikolaj**
See https://github.com/haskell/cabal/pull/8115#issuecomment-1113136131 and later comments.

### CODE REVIEW

**Comment by jneira** [comment]
lgtm but what about some brief comment about?

**Comment by Mikolaj** [comment]
Sure. We currently have

```
        exclude:
          # lot of segfaults caused by ghc bugs
          - os: "windows-latest"
            ghc: "8.8.4"
          - os: "windows-latest"
            ghc: "8.4.4"
```

Where would you put "it also throws segfaults"?

**Comment by Mikolaj** [comment]
@jneira: thanks

@andreabedini: how about you?

**Comment by andreabedini** [comment]
I’m ok with this change but disabling all tests on windows on GHC 8.8.4 and 8.4.4 means we cannot claim to support that configuration. I think we are discussing this in some other thread but perhaps this is a reminder we need to have sour support story straight.

my 2c, good work team!

**Comment by Mikolaj** [comment]
That's a good point. We currently claim in CONTRIBUTING.md:

```
Our GHC support window is five years for the Cabal library and three years for cabal-install: that is, the Cabal library must be buildable out-of-the-box with the dependencies that shipped with GHC for at least five years. The Travis CI checks this, so most developers submit a PR to see if their code works on all these versions of GHC. cabal-install must also be buildable on all supported GHCs, although it does not have to be buildable out-of-the-box. 
```

We could change "The Travis CI checks this" to "Our Github Actions CI setup checks this (except for a couple of GHC/OS combinations that crash too readily)". Any other place we need to touch?

**Comment by andreabedini** [comment]
@Mikolaj I just set to rephrase that paragraph and spent 30 minutes finding the GHC release dates :facepalm: I guess the best we have is the [blog](https://www.haskell.org/ghc/blog.html).

**Comment by andreabedini** [comment]
I left a comment in #8108

**Pull request merged**
