### PR TITLE
When generating `Paths` modules, define functions when used

### PR DESCRIPTION
**Pull request by GuillaumeGen**
This addresses #8219 

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by fgaz** [comment]
The module you edited is generated, you should edit the source instead.

Also please restore the pull request template and address the items

**Comment by GuillaumeGen** [comment]
> The module you edited is generated
I saw this mistake when reading the log of the continuous integration, should be fixed now.

I also added the pull request template.

**Comment by fgaz** [comment]
> I do not think that such a small change should go in the Changelog, should it?

It fixes a bug, so it should have a changelog entry

> Regarding testing, I have no idea of how to write a test for it. If you have some indications on the strategy, it would be very welcome.

you could add a test in `cabal-testsuite/PackageTests/PathsModule`

**Comment by GuillaumeGen** [comment]
I added a changelog file. For the test, my question was more "Do you know what could be a relevant test for this modification?" rather "Where should I add my test?".
As I explained in #8219 this issue stroke me when I was running an external program (gazelle_haskell_modules) and I do not know precisely what caused this.

**Comment by GuillaumeGen** [comment]
After further exploration, it happens that this bug happens whenever one tries to generate a Paths_ module with the option `--enable-relocatable`, hence writing a test was quite straightforward finally.

**Comment by Mikolaj** [comment]
There is some obvious keyword to skip a test on Windows that apparently doesn't support relocatable gizmos. Feel free to use that.

**Comment by GuillaumeGen** [comment]
Is there anything expected from me for this pull request to move forward?

**Review by Mikolaj — APPROVED** [review]
Congrats, it seems to test fine now. Great job, We need a second review to merge.

**Comment by ulysses4ever** [comment]
I guess, @jneira has had a lot of stuff on his plate lately, and haven't got to this yet. And I'm afraid I'm completely out of my depth here, so I don't feel confident approving (I'd love to!). 

I have a question, though: is this related to the `--relocatable` specifically? If yes, could you by any chance look into improving the docs for it while you're on it? The [current doc](https://cabal.readthedocs.io/en/latest/cabal-project.html?highlight=relocatable#cfg-field-relocatable) is terrible imo, and anything would be an improvement.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@GuillaumeGen, @tweag (?), could you kindly rebase and/or permit maintainers to update this branch? Thank you!

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
Oh, yes, now I see mergify couldn't merge it due to the missing permissions.

**Comment by GuillaumeGen** [comment]
Thanks a lot for making this go forward!
I just rebased. Is it sufficient?

**Comment by GuillaumeGen** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
I think it's not enough to enable mergify to take care of the PR, but enough for me to now merge manually. Thank you again for the PR!

**Comment by GuillaumeGen** [comment]
Thanks a lot!

**Pull request merged**
