### PR TITLE
use a liberal import of Control.Exception to grab the new ErrorCall pattern in base

### PR DESCRIPTION
**Pull request by bgamari**
This is a prerequisite for GHC Phabricator [D861](https://phabricator.haskell.org/D861).

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Can't we do something like

```
#if __GLASGOW_HASKELL__ >= 711
import Control.Exception (pattern ErrorCall)
#endif
```

instead? Explicit imports give us forwards compat and help navigating code.

**Comment by bgamari** [comment]
@gridaphobe, what say you?

**Comment by gridaphobe** [comment]
Sure, that ought to work too (we'd also need to enable `PatternSynonyms` of course). I try to avoid using CPP personally, which is why I used the full import, but I don't have a strong opinion there.

(I'm not at my computer ATM so I haven't tried to compile anything)

**Comment by bgamari** [comment]
@gridaphobe, do you think you could give this a shot?

**Comment by gridaphobe** [comment]
Sure, I'll do it later today.

**Comment by gridaphobe** [comment]
@23Skidoo is this better?

@bgamari I validated the new patch against the rest of [D861](https://phabricator.haskell.org/D861), so we should be good to go once it's merged.

**Comment by 23Skidoo** [comment]
@gridaphobe Looks OK. You sure that the `ErrorCall (..)` import doesn't trigger a warning on GHC 7.11? We strive to be warning-free.

**Comment by gridaphobe** [comment]
Ah, it did indeed, fixed!

**Comment by 23Skidoo** [comment]
Great, thanks. Merging.

**Pull request merged**
