### PR TITLE
Unknown build-tools are looked up on the PATH -- fix and test

### PR DESCRIPTION
**Pull request by Ericson2314**
This covers most of what was completed from https://github.com/haskell/cabal/pull/4241

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Windows failure seems to be genuine.

**Comment by Ericson2314** [comment]
@23Skidoo yeah its going to take a couple of pushes. Sorry I should have a WIP, I opened this to get CI.

**Comment by Ericson2314** [comment]
Ok, I think Travis is going to pass. Is this windows failure meaningful?

**Comment by Ericson2314** [comment]
Only failure is a timeout.

**Pull request merged**
