### PR TITLE
Try to resolve unused-packages warnings

### PR DESCRIPTION
**Pull request by andreabedini**
The `-Wunused-packages` flag was [introduced](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-packages) in GHC 8.10.

Somehow, we see warnings only in [GHC 9.2](https://github.com/haskell/cabal/runs/5228622591?check_suite_focus=true#step:8:1428) and not in earlier versions of GHC (e.g. [GHC 8.10.7](https://github.com/haskell/cabal/runs/5228622712?check_suite_focus=true)).

I had a look at the plan and the difference seems to be minimal and unrelated (although I am no expert and I might be wrong).

Locally this build with a bunch of GHC versions. I'm submitting this to test in the CI.

### CODE REVIEW

**Comment by andreabedini** [comment]
@Mikolaj @jneira The GitHub UI is failing badly here (as someone else noticed in another PR) the three. I think all workflow pass but the PR still gets a red mark.

https://github.com/haskell/cabal/actions/runs/1880004377
https://github.com/haskell/cabal/actions/runs/1880004378
https://github.com/haskell/cabal/actions/runs/1880004379
https://github.com/haskell/cabal/actions/runs/1880004380
https://github.com/haskell/cabal/actions/runs/1880004381

This only removes the extra pacakges, doing so it uncovers another issue with GHC 9.2 which I will address separately.

**Comment by Mikolaj** [comment]
At least one of the failure is probably due to pattern checker being much better in GHC 9.* and so giving incomparable results. We have no chance of keeping -Werror for pattern warnings in both GHC 9 and 8. Perhaps let's turn off -Werror for pattern warnings altogether and turn it on only after GHC 8.* is no longer in CI.

**Review by Mikolaj — APPROVED** [review]
This seems to be the old non-deterministic bug I was talking about. Depending on how the build goes (e.g., some conditional blocks that depend on which packages the solver chooses) some of these packages may be required or not. I was thinking how to make the build deterministic, but you have a point that simply removing the packages must make it deterministic (in the worst case it would fail, depending on how much of the determinism is wired into the solver). Let's hope it works in all setups. If not, we'll fix.

**Review by Kleidukos — APPROVED** [review]
Jetzt geht's los!

**Comment by andreabedini** [comment]
Thanks @Kleidukos!

@Mikolaj you might find rejoice reading [this](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-packages).

> The option [-Wunused-packages](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-packages) warns about packages, specified on command line via [-package ⟨pkg⟩](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#ghc-flag--package%20%E2%9F%A8pkg%E2%9F%A9) or [-package-id ⟨unit-id⟩](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#ghc-flag--package-id%20%E2%9F%A8unit-id%E2%9F%A9), but were not loaded during compilation. Usually it means that you have an unused dependency.
>
> You may want to enable this warning on a clean build or enable [-fforce-recomp](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/separate_compilation.html#ghc-flag--fforce-recomp) in order to get reliable results.

I think the pattern matching error is trivial:

https://github.com/haskell/cabal/blob/fd73c3a6274932f950e68aa31f41125dfef0fc95/cabal-install/src/Distribution/Client/ProjectPlanning.hs#L1730-L1739

Those lines have been like that for about six year!

**Comment by Mikolaj** [comment]
Oh, do you mean the non-determinism of the error was caused by GHA using a cache? That would be good. I feared this is a more complex problem. And the spurious pattern match won't cause 8.10.7 to complain when we remove it? That's also great news. I've had patterns that 8.10.7 required but 9.2.1 (rightly, but for very tricky reasons) called spurious, so that's a relief as well. Yay, aren't we lucky today?

**Comment by andreabedini** [comment]
> Oh, do you mean the non-determinism of the error was caused by GHA using a cache?

I just meant, it's known to be unreliable. We don't cache our own build, only the dependencies (the cabal store) so I don't think GHA is the culprit

I'll test the pattern match thing tomorrow.

> Yay, aren't we lucky today?

:heart: lovely to hear, it's been a long day :heart:

**Pull request merged**
