### PR TITLE
LHC uses the HaskellSuite and no longer needs special support.

### PR DESCRIPTION
**Pull request by Lemmih**
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

This patch removes all references to LHC.

### CODE REVIEW

**Comment by Lemmih** [comment]
Anyone available for a code review? It'll be quick as I'm just deleting unused code.

**Comment by 23Skidoo** [comment]
Looks all right, but there are [compile failures in the test suite on Windows](https://ci.appveyor.com/project/23Skidoo/cabal/build/%235136%20(master)#L1287):

```
[21 of 22] Compiling UnitTests.Distribution.Client.ProjectConfig ( tests\UnitTests\Distribution\Client\ProjectConfig.hs, dist\build\unit-tests\unit-tests-tmp\UnitTests\Distribution\Client\ProjectConfig.o )
tests\UnitTests\Distribution\Client\ProjectConfig.hs:733:58: error:
    * Data constructor not in scope: LHC :: CompilerFlavor
    * Perhaps you meant one of these:
        `GHC' (imported from Distribution.Simple.Compiler),
        `UHC' (imported from Distribution.Simple.Compiler),
        `JHC' (imported from Distribution.Simple.Compiler)
```

**Comment by 23Skidoo** [comment]
There's a failing Windows test that seems to work on master. Might still be unrelated to this change.

**Comment by Lemmih** [comment]
Pretty sure that's unrelated to my changes. What should I do to make sure?

**Comment by 23Skidoo** [comment]
AppVeyor build passed, so let's consider that failure a fluke/unrelated issue.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
