### PR TITLE
fix more typos

### PR DESCRIPTION
**Pull request by askeblad**
comportamento incompatibile con le abitudini sociali accettate

@andreabedini same as #8099 absent modification of the following files

Cabal-syntax/src/Distribution/Fields/Pretty.hs
Cabal-syntax/src/Distribution/Types/LibraryVisibility.hs
Cabal/ChangeLog.md
cabal-install/changelog
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.test.hs
release-notes/Cabal-3.6.1.0.md
release-notes/cabal-install-3.4.0.0.md

### CODE REVIEW

**Comment by andreabedini** [comment]
@askeblad I think we are getting all confused by your behaviour.

> comportamento incompatibile con le abitudini sociali accettate
> zachowanie niezgodne z przyjętymi zwyczajami towarzyskimi
> behavior inconsistent with accepted social habits (from above via Google Translate, matches the Italian)

Are you just picking random languages to communicate? and random people to tag?

I still believe you are working in good will. We spent a fair bit of time on #8099. Allow me some time to recharge before I look at this again.

**Comment by emilypi** [comment]
Closing due to previous PRs being low quality, continuing on with this low priority spam

**Comment by andreabedini** [comment]
@emilypi don't close it. I am happy to look after it.

**Comment by emilypi** [comment]
Good luck @andreabedini - OP has been blocked from interacting with this project. If you'd like to shepherd their PRs, by all means. The other one they closed was also a candidate.

**Review by andreasabel — APPROVED** [review]
Looks correct.

**Comment by andreasabel** [comment]
Validate windows-latest ghc-9.2.1 workflow breaks, but error is non-telling...
https://github.com/haskell/cabal/runs/6257470760?check_suite_focus=true#step:14:222
```
UNEXPECTED OK: PackageTests\ForeignLibs\setup.test.hs
\033[0;31m<<< D:\a\cabal\cabal\dist-newstyle-validate-ghc-9.2.1\build\x86_64-windows\ghc-9.2.1\cabal-testsuite-3\build\cabal-tests\cabal-tests.exe --builddir=/d/a/cabal/cabal/dist-newstyle-validate-ghc-9.2.1/build/x86_64-windows/ghc-9.2.1/cabal-testsuite-3 -j2 --with-ghc=ghc --hide-successes \033[0m (674/674 sec, 1)
```
@Mergifyio rebase

**Comment by andreasabel** [comment]
@Mergifyio rebase

**Comment by andreasabel** [comment]
@askeblad: Please make sure to tick the _Allow edits from maintainers_ box when opening a PR.  (Otherwise automatic rebase isn't possible.)

**Review by emilypi — APPROVED** [review]
LGTM pending rebase to master

**Comment by andreasabel** [comment]
Workflow __ Validate windows-latest ghc-8.10.7__ fails but I think it is not related to this PR because the same problems have been reported at #8120:
- https://github.com/haskell/cabal/pull/8120#issuecomment-1114796283
- https://github.com/haskell/cabal/pull/8120#issuecomment-1115265656

**Comment by andreasabel** [comment]
@emilypi wrote:
> OP has been blocked from interacting with this project.

Emily, I have some understanding for feeling irritated by the communication style of this contributor.  But I also wonder whether this step was necessary.  I have merged PRs with typo-fixes from this contributor on other projects hosted on `haskell` before.  Maybe you want to reconsider.
My question: was this user blocked just from `haskell/cabal` or from all of `haskell`?

**Comment by emilypi** [comment]
Far from just being irritated - the contributor has done the following: 

- Randomly ping the wrong people on several projects (totally, fine, a mistake is a mistake)
- Harass for getting PRs approved within 24 hours of submission (not so fine, poor etiquette)
- Submitted *automated* PRs that were incorrect, taking up our time (not fine, period)
- Pinged people from within those PRs across entire github orgs, seemingly at random and with no reasoning given (e.g. Plan 9, not okay in my book because they don't seem to be active stakeholders). 
- Refused to answer critique in a meaningful way, often skipping right past our feedback
- Started speaking in different languages on those PRs
- Seemingly *mocked* one of the maintainers by saying something pithy in the maintainer's native language
- Abandoned the incorrect PRs that we spent time on, closing them
- Opened up new, orthogonal PRs continuing the alternative language nonsense. 

This is disruptive and a waste of my and the maintainers' time. I'll double check that he's not banned from the entire org, and just `haskell/cabal`, but low-effort, incorrect, time-consuming, disrespectful PRs are a ban in my book.

**Comment by andreasabel** [comment]
I agree this justifies a ban.  Thank you for taking the time to document this decision, @emilypi! Your comment here can serve as reference if someone like me comes back with questions about the case.

**Comment by emilypi** [comment]
Generally, I do not publicly air these issues out of respect. You can assume that decisions made by maintainers are made with due thought and at least some professionalism. Publicly second-guessing us creates a situation where there needs to be a public answer, which we'd rather not do unless it's pressing.

**Pull request merged**
