### PR TITLE
Validate hackage-security/pull/306

### PR DESCRIPTION
**Pull request by philderbeast**
> [!WARNING]
> Do not merge

This is a test using our CI of https://github.com/haskell/hackage-security/pull/306

### CODE REVIEW

**Comment by Mikolaj** [comment]
A bit hard to see where the CI error is. Is it here?

> D:\a\cabal\cabal\cabal-testsuite\PackageTests\NewBuild\CmdClean\Orphan\cabal.dist\work\.\dist\src\hackage-s_-974be1f1dd0de4b1\.git\objects\pack\pack-525ad7df162bf06777b170436f2399ef7dcd789d.rev: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:DeleteFile "\\\\?\\D:\\a\\cabal\\cabal\\cabal-testsuite\\PackageTests\\NewBuild\\CmdClean\\Orphan\\cabal.dist\\work\\dist\\src\\hackage-s_-974be1f1dd0de4b1\\.git\\objects\\pack\\pack-525ad7df162bf06777b170436f2399ef7dcd789d.rev": permission denied (Access is denied.)

There's a chance this is a transient Windows hiccup, so perhaps rerun once?

**Comment by andreasabel** [comment]
CI also runs on draft PRs, does it?  
So this could be converted to draft...

**Comment by andreasabel** [comment]
> which seems like `cabal update` tries to run `git`. ???

Well, this `cabal.project` uses a `source-repository-package`: https://github.com/cabalism/cabal/blob/399b5473549688e50c8f214315c760cc91f3cfb0/hackage-security.config#L1-L5

I seem to remember that `cabal update` also updates these.
The docs could be more explicit about this: https://cabal.readthedocs.io/en/3.10/cabal-commands.html#cabal-update

However, I do not know why `cabal` fails to invoke `git` in a `haskell-actions/setup`.

**Comment by andreasabel** [comment]
> However, I do not know why `cabal` fails to invoke `git` in a `haskell-actions/setup`.

Well, this workflow uses a docker that may not have `git`: https://github.com/haskell/cabal/actions/runs/8164469354/job/22319778944?pr=9656#step:4:30
```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

This could be a simple explanation.

**Comment by philderbeast** [comment]
> Well, this `cabal.project` uses a `source-repository-package`: https://github.com/cabalism/cabal/blob/399b5473549688e50c8f214315c760cc91f3cfb0/hackage-security.config#L1-L5
> 
> I seem to remember that `cabal update` also updates these. The docs could be more explicit about this: https://cabal.readthedocs.io/en/3.10/cabal-commands.html#cabal-update

I wouldn't expect that, especially when pinning to a commit hash. I'll have to check this. That "remote package repository" and "source repository package" are different things that sound similar doesn't help (especially when source repositories are usually remote too).

**Comment by philderbeast** [comment]
Thanks for checking the failures @andreasabel. I don't intend to pursue the failures further. Tests without git or setup failures are all passing and I think that is good enough of a check for the `hackage-security` changes.

**Pull request closed without merging**
