### PR TITLE
Replace Boilerplate Monoid/Semigroup instances with generics

### PR DESCRIPTION
**Pull request by hvr**
addresses #3169

### CODE REVIEW

**Comment by hvr** [comment]
@dcoutts @23Skidoo There's a few instances that we can't rewrite yet without more refactoring. Specifically those which have `Bool` flags without `Data.Monoid.All` or `Data.Monoid.Any` `newtype`-wrappers to guide the `Monoid` derivation.

**Comment by hvr** [comment]
Oh, and the `Semigroup` instances for `TestSuite`/`Executable`/`Benchmark` are partial via `error`!

```haskell
instance Semigroup Executable where
  a <> b = Executable{
    exeName    = combine' exeName,
    modulePath = combine modulePath,
    buildInfo  = combine buildInfo
  }
    where combine field = field a `mappend` field b
          combine' field = case (field a, field b) of
                      ("","") -> ""
                      ("", x) -> x
                      (x, "") -> x
                      (x, y) -> error $ "Ambiguous values for executable field: '"
                                  ++ x ++ "' and '" ++ y ++ "'"

```

**Comment by hvr** [comment]
Interesting... the `cabal-install` changes seem to cause integration-test failures

**Comment by 23Skidoo** [comment]
Nice! Boolean flags should use `Any`, I think.

**Comment by hvr** [comment]
> Nice! Boolean flags should use `Any`, I think.

there are a few cases which have it inverted:

```haskell
instance Semigroup Library where
 -- ...
       libExposed     = libExposed a && libExposed b, -- so False propagates
```

```haskell
instance Semigroup BuildInfo where
  a <> b = BuildInfo {
    buildable           = buildable a && buildable b,
   -- ...
 }
```

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by hvr** [comment]
@23Skidoo what are your plans re 1.24 branch? I mostly want to know to decide what to do about the nix-local branch

**Comment by 23Skidoo** [comment]
@hvr Well, I didn't want to backport this into 1.24 initially, but it's probably not a very big deal after all. And merges will be easier. I just need to find a way to download all custom setup scripts from Hackage to check that #3195 didn't break anything.

**Comment by hvr** [comment]
That shouldn't be too hard:

```bash
cabal list --simple | awk '{ print $1 }' | uniq
```

gives you a list of all package names,

and

```bash
curl -s --fail http://hackage.haskell.org/package/$PKGNAME/src/Setup.lhs || curl -s --fail http://hackage.haskell.org/package/$PKGNAME/src/Setup.hs
```

tries to retrieve you the latest version of `$PKGNAME`'s Setup.lhs or Setup.hs

you could also try to be more clever and look at the .cabal files first (e.g. from your 01-index.tar ball) before downloading the Setup.(l)hs files...

**Comment by 23Skidoo** [comment]
> you could also try to be more clever and look at the .cabal files first (e.g. from your 00-index.tar ball) and check for the build-type before downloading the Setup.(l)hs files...

Yep, that's what I want to do.

**Comment by hvr** [comment]
In that case:

```bash
cd $TMP
tar xf ~/.cabal/packages/hackage.haskell.org/00-index.tar.gz 
find -name '*.cabal' | xargs grep -li '^build-type:.*custom' | cut -f2 -d/ | uniq
```

**Comment by 23Skidoo** [comment]
@hvr Thanks! That was easier than I expected. Uploaded the results to https://github.com/23Skidoo/all-custom-setups. And it turns out `llvm-general` actually uses `configPrograms` in its setup script.

**Comment by hvr** [comment]
@23Skidoo I think that specific case in llvm-general can be made more compatible by providing a function `configPrograms_` with the old type-sig (as it's only used as a function, rather than a field-record-label). and name the actual field differently, e.g. `configPrograms_`

**Comment by 23Skidoo** [comment]
Yes, it should work given that the script doesn't use explicit import lists.

**Comment by hvr** [comment]
@23Skidoo btw, @dcoutts tells me he "used to have a script to try compiling all custom Setup.hs scripts with old and new Cabal lib version to look for breakages"

did you try to compile those Setup.hs files or did you just `grep` for configPrograms?

**Comment by 23Skidoo** [comment]
@hvr Just grepped.

**Comment by hvr** [comment]
@23Skidoo fwiw, if you're still worried about merging to 1.24, you could try merging only the cabal-install parts, or we could simply back out the `ConfigFlags` instance from the part merged to 1.24

**Comment by 23Skidoo** [comment]
@hvr Cherry-picked all your patches into 1.24.

**Pull request merged**
