### PR TITLE
Mergify and actions upgrades

### PR DESCRIPTION
**Pull request by geekosaur**
Mergify is requiring different queues for different merge strategies as of mid-September.
`actions/upload-artifact@v3` and `actions/download-artifact@v3` are being removed in November.

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by geekosaur** [comment]
I did a quick audit of the other actions we use in our workflows; it looks like only `upload-artifacts` has changed.

**Comment by geekosaur** [comment]
BTW, the summary still complains about the configuration. This is because it uses the Mergify configuration on `master`, not the one in this PR. "Configuration changed" validates the one in this PR, and is clean.

**Review by ulysses4ever — APPROVED** [review]
Thanks! 

Some unfortunate repetition with Mikolaj but that's not an issue: we can't have too much @Mikolaj!!!

**Comment by geekosaur** [comment]
Sadly, while there is a `defaults` section it doesn't apply to `queue_rules`.

**Review by Mikolaj — APPROVED** [review]
At least we have a competent bot! :D

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Pull request merged**
