### PR TITLE
Implement --cabal-file, allows multiple Cabal files in directory

### PR DESCRIPTION
**Pull request by ezyang**
This is primarily intended for use with the Cabal test suite (allowing
us to easily specify multiple Cabal packages for the same Haskell source
files), but maybe some end-users will find it useful as well.  If there
are multiple Cabal files in the current working directory, --cabal-file
(for configure) allows you to disambiguate which one to build with.

There's a big hack to handle the BOM check, as it is inconvenient to
plumb the flag value all the way to the check code.  Some bigger
refactoring needed, see #3552.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by phadej** [comment]
So `cabal check` doesn't support `--cabal-file` atm?

**Comment by ezyang** [comment]
Yes, and supporting it would require quite a bit of faffing about.

**Comment by 23Skidoo** [comment]
Bikeshedding: we might want to call it `--package-description` in case we later add support for other package description formats (e.g. hpack).

/cc @dcoutts

**Comment by ezyang** [comment]
OK, sure (although it's hard to imagine the library getting support for hpack; it's more of a cabal-install thing.)

**Comment by phadej** [comment]
I'd keep it as `--cabal-file`, and if we later would like to add `--package-description` we can, yet `--cabal-file` would be always parsed as cabal file (e.g. we could add `--hpack-file` too)

 `--package-description` needs to guess, and sometimes you really want the tool you use not to guess at all, just do what it's told. 

*note to myself:* verify what automatic reconfiguration can be disabled with some flag

**Comment by ezyang** [comment]
Well, I have the patch to put it either way.

**Comment by hvr** [comment]
Please take into account we'll also need a way to specify the `cabal.project` file location when designing a name for this

**Comment by ezyang** [comment]
Well... `--cabal-project` for that one?

**Comment by hvr** [comment]
Alright, we'd have 

 - `--config-file` to specify an alternative `~/.cabal/config` 

 - (suggested) `--cabal-file` to speficy an alternative `*.cabal` file

but then, for consistency, I'd suggest

 - `--project-file` to specify  a non-default `cabal.project` file

**Comment by 23Skidoo** [comment]
@ezyang BTW, don't we need a note in the manual about `--cabal-file`?

**Comment by ezyang** [comment]
Well, I wasn't intending for it to be a user-visible feature. If we put it in the manual, we need to teach cabal-install how to handle it too, because cabal-install also reads in cabal files itself.

**Comment by 23Skidoo** [comment]
There should be a place for documenting non-user-visible features like `--exact-configuration` and this one, but I guess this will have to wait until someone rewrites the user guide.

**Comment by 23Skidoo** [comment]
Added a line to the changelog (858981e7d2eb57148872ad581ed5e70ecd9fe671).

**Pull request merged**
