### PR TITLE
Cabal: Allow binary 0.10

### PR DESCRIPTION
**Pull request by bgamari**
This will be necessary for GHC 8.6. Please do cherry-pick into the stable branch.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also cherry-picked to `2.4`.

**Comment by hvr** [comment]
@bgamari what's the breaking change in binary-0.10? I'm failing to see the justification for this major bump

**Comment by kolmodin** [comment]
Sorry, it turns out there is no breaking change. The release could also have had version number 0.8.6.0. I should make another release with that number.

**Pull request merged**
