### PR TITLE
cabal-testsuite: check return code of `runghc Setup.hs`

### PR DESCRIPTION
**Pull request by bennofs**
This PR fixes a bug in the cabal-testsuite, where the result of calling `runghc Setup.hs`
wasn't checked for failure.

I also wrote a regression test for this, however that test depends on the fact that failing
tests throw `ErrorCall`, and I'm not sure if it's good to rely on that in a test. I haven't
found any other way to check whether a test fails though, since `fails` only checks that all
assertions fail, while in this case I want to check that there actually is an assertion. In
other words, `fails (return ())` succeeds, which is not what we need in this case.

### CODE REVIEW

**Comment by ezyang** [comment]
Thank you, nice catch.

It is indeed not good to rely on ErrorCall, but in this case it's pretty harmless because we defined `assertFailure`, so it would be an easy matter to update the test if there is a problem. I'd definitely put a comment saying that it's a hack though.

Looking at how the bug arose, maybe we (I?) should refactor the test prelude so that everything that fails does so with exceptions, so that you can't forget to handle them.

**Comment by 23Skidoo** [comment]
Looks like we've now got a failing test on Windows.

**Comment by bennofs** [comment]
@23Skidoo yeah, but that seems pretty unrelated to my changes? That test seems to be instable in general, I've got a really weird travis failure with that test previously (with some garbage unicode characters appearing in the output for the package name).

**Comment by 23Skidoo** [comment]
Yes, your change just exposed a test that was already failing. It looks like it was @ezyang who wrote that test, so I'll defer to him the decision whether to disable the test or fix it.

**Comment by bennofs** [comment]
@23Skidoo well, that's an integration test for cabal-install, which shouldn't even depend on `cabal-testsuite`, I thought? How could that test be affected by this change?

**Comment by 23Skidoo** [comment]
My mistake. I restarted the build, maybe it'll pass this time.

We should open a ticket about the flaky test, here's the log: https://gist.github.com/23Skidoo/01d15a0c3c1f0582c5b6da57b1c815e6

**Comment by ezyang** [comment]
The Windows flaking should go away if you rebuild, that's the known #4005 problem (we could probably also suppress it here by passing `-j1` to new-build)

Travis ran out of time. Let's fix #4277

**Pull request merged**
