### PR TITLE
Guard PackageInfo behind cabal-version: 3.10

### PR DESCRIPTION
**Pull request by andreabedini**
This is a fix to ffa9f01b3bf0eccf2318bdd3e644ccc175b8a0e0 which introduced a new Cabal functionality without protecting it behind a new cabal-version, therefore breaking forward compatibility.

I am marking this as a draft because I have just emulated other checks without knowing how it works. That said, the example in https://github.com/haskell/cabal/issues/9331#issue-1943336403 gets be rejected.

TODOs:

- [ ] Add the above example as a test.
- [ ] Review #8534 once again. Examples of dubious changes are:
  - https://github.com/haskell/cabal/pull/8534/files#diff-e7de9e3ea39b2b822f7c716a94940ed5934b74d85f30e270abffadcc7c61c4f7R1 this cabal-version is rejected now
  - https://github.com/haskell/cabal/pull/8534/files#diff-160a5ec6d22111593cbcb0b6ba2484d6615e3e0366ad986dffe7206648a24e81R1951-R1953
    `cabal-version <2.2 + PackageInfo_module + default-extensions` should never trigger.

Note: This adds the constructor `CabalSpecV3_10` to `CabalSpecVersion` and is therefore a breaking change to `Cabal-syntax`.

Closes: #9331

### CODE REVIEW

**Comment by andreabedini** [comment]
Also to discuss is how to release this. As noted above it's a breaking change to Cabal-syntax. So we cannot really release it as a patch release.

**Comment by fgaz** [comment]
I think the only way is to disable the new functionality unconditionally in a patch release, then enable it conditionally in the next major release (so on cabal-version >= 3.11)

**Comment by gbaz** [comment]
doesn't it make sense to keep the other check too?

**Comment by andreabedini** [comment]
AFAIK this was resolved in other PRs.

**Pull request closed without merging**
