### PR TITLE
Implement init-config 

### PR DESCRIPTION
**Pull request by psibi**
See #2553

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Looks OK in principle, but I'd make it a `user-config` subcommand instead. Also, please add a note to the changelog and update the documentation (it's under `Cabal/doc`).

/cc @dcoutts

**Comment by psibi** [comment]
@23Skidoo Added changelog. Not sure where exactly to add it's documentation since all of the documentation inside `Cabal/doc` seems to have a different purpose (There is no documentation related to a specific command there). And adding `init-config` there, seems to be little ambiguous. Let me know the filename of the doc files (.md), if you want me to add that to a specific file.

**Comment by bgamari** [comment]
It unfortunately seems that #2640 implements this same feature.

**Comment by 23Skidoo** [comment]
Closing in favour of #3095.

**Pull request closed without merging**
