### PR TITLE
Fix #3294, work around buggy relinking by removing link target.

### LINKED ISSUE #3294: GHC 7.6 and earlier have buggy relinking avoidance
You can see the problem in the Travis failure https://travis-ci.org/haskell/cabal/builds/121240033 for #3289 which has a simple recompilation test.

The proximal patch which introduced this bug is the fix for #842, which separated the build and linking steps (if you don't separate these steps, GHC will correctly relink.)

One obvious fix is this: if GHC is too old, pass `-fforce-recomp` to the linking command. Unfortunately, this does not work: the linking command will subsequently attempt to rebuild all of the modules again. Something like https://ghc.haskell.org/trac/ghc/ticket/11807#ticket would work but obviously the old version of GHC will not have it.

Another fix: we can remove the result of linking before we link it. This does appear to work, assuming we can figure out what it is we are linking.

In the case that there are no C source files that depend on FFI exports, I think there is one more way that this can be fixed: we should revert to pre-#842 and do compilation and linking in one go. This will obviously make the GHC code more complicated, but I suspect it will pay its way: we'll also get faster compilation for new versions of GHC since we don't have to call GHC twice. Duncan previously claimed that the performance hit from calling GHC a second time should not be large, but actually there is a substantial performance hit when module graphs are large, as GHC recomputes the module graph on every computation (one of the reasons why Shake is so much faster.)

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by dcoutts** [comment]
Removing the link target seems an ok workaround for now.

**Comment by ezyang** [comment]
The Travis failures are quite puzzling.

**Comment by ezyang** [comment]
So, as far as I can tell, this test nondeterministically passes or fails.

**Comment by ezyang** [comment]
OK, the problem is file modification time calibration. I'll just crib cabal-install's fix for the problem.

**Comment by ezyang** [comment]
OK, pushed some fixes to check for file modification time.

**Comment by 23Skidoo** [comment]
LGTM.

**Pull request merged**
