### PR TITLE
Backport a bunch of patches to the 2.0 branch

### PR DESCRIPTION
**Pull request by 23Skidoo**
Preparing for the 2.0 point release...

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Not sure why the test output changed (5c4ec078b2bce25c73789e25e06331dbaa4a6b17), seems to be not the case in `master`.

**Comment by 23Skidoo** [comment]
```
GHCi runtime linker: fatal error: I found a duplicate definition for symbol
   fps_reverse
whilst processing object file

   /home/travis/.cabal/store/ghc-7.4.2/bytestring-0.10.8.2-45a5149b4862658365e03d6bcce81ec92ecccb767cd5df0de8882538a40bf3ca/lib/libHSbytestring-0.10.8.2-45a5149b4862658365e03d6bcce81ec92ecccb767cd5df0de8882538a40bf3ca.a
This could be caused by:
   * Loading two different object files which export the same symbol
   * Specifying the same object file twice on the GHCi command line
   * An incorrect `package.conf' entry, causing some object to be
     loaded twice.

GHCi cannot safely continue in this situation.  Exiting now.  Sorry.
GHCi exited with ExitFailure 1 (use -v for more information)
```

I think that this should be fixable by nuking the Travis cache, but @ezyang might be interested to look into coming up with a proper fix.

**Comment by grayjay** [comment]
> Not sure why the test output changed (5c4ec07), seems to be not the case in master.

#4599 changed some of the conflict counts on master.

**Comment by 23Skidoo** [comment]
@grayjay Thanks! Do you want that patch backported as well?

**Comment by 23Skidoo** [comment]
Nuking the store fixed the error in https://github.com/haskell/cabal/pull/4760#issuecomment-328905882. From looking at the code, to fix that properly one would need to invoke `ghci` with `-hide-all-packages` and package IDs in [`Test.Cabal.Server.startServer`](https://github.com/haskell/cabal/blob/master/cabal-testsuite/Test/Cabal/Server.hs#L213).

**Pull request merged**
