### PR TITLE
Allow tar-0.6

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by ulysses4ever** [comment]
What a speed! It's not even on Hackage yet. How did you test it? It's a major version bump, so it would be unwise to merge it without trying...

**Comment by TristanCacqueray** [comment]
Oops my bad, I though the version was already published. I had to pull the repository's HEAD to build with ghc-9.6 for https://github.com/haskell/cabal/pull/8726#issuecomment-1472868209

**Comment by ulysses4ever** [comment]
I see. I'm afraid we wouldn't want to allow unreleased versions. The reason is simple: they may add breaking features before the release...

**Comment by andreasabel** [comment]
The other reason is that we would not actually test building with `tar-0.6`, and we should if we bump the upper bound.

**Pull request closed without merging**
