### PR TITLE
Check that all internal libraries have a name.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks, I had this patch but you beat me to it!

**Comment by ezyang** [comment]
Note that it's actually pretty impossible for this happen unless you have a Custom script, because the parser, if a stanza is missing, will always put it in `library`. So there isn't actually a way for a user to (easily) trigger it.

**Comment by 23Skidoo** [comment]
What will happen if there are two non-internal `library` sections?

**Comment by ezyang** [comment]
Presently, parse error, you cannot declare library twice.

**Comment by 23Skidoo** [comment]
Would be nice to make unnamed sublibraries non-representable, but it looks like that'd entail too much boilerplate.

**Pull request merged**
