### PR TITLE
[WIP] Version check build tool depends

### LINKED ISSUE #5532: check doesn't warn on build-tool-depends with pre-2.0 spec versions
`build-tool-depends` was new in 2.0, but `cabal check` doesn't warn if you use it with an earlier spec version. It ought to, since it likely won't be doing what the user wants if it's used with an old version of Cabal.

This should be easy for a newcomer: the relevant module is `Distribution.PackageDescription.Check`, and there are several examples of warning about constructs if the spec version is too low in there already.

### PR DESCRIPTION
**Pull request by mgsium**
Adds a version warning when using `build-tool-depends` with pre-2.0 cabal (fixes #5532)

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by gbaz** [comment]
This seems like an easy fix. Just requires a changelog and should be ready to merge?

**Comment by mgsium** [comment]
Newcomer here - I might need some guidance. What do you suggest doing?

**Comment by phadej** [comment]
i think https://github.com/haskell/cabal/issues/5532 is simply wontfix.

**Comment by mgsium** [comment]
In that case, I'll close for now.

**Pull request closed without merging**
