### PR TITLE
Show full config file contents when option test fails

### PR DESCRIPTION
**Pull request by cbclemmer**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

To fix a problem with [this pr](https://github.com/haskell/cabal/pull/8955) I sent the whole file contents of the default config (whatever that is based on the current build) to the error output so that I could see what needed to be fixed. This will probably be useful whenever the test breaks again, so I'm making a PR for it from @Mikolaj 's comment.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Thanks a lot.

**Comment by Mikolaj** [comment]
Note to whomever reviews this: this commit is already included in the backport of the original PR, so the PR doesn't need to be backported to 3.10.

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
This, i think, is my personal record for the number of times i asked the bot to rebase. I wish the bot exhibited more self-sufficiency...

Thanks @cbclemmer for another great contribution to Cabal!

**Pull request merged**
