### PR TITLE
Add support for request headers in getHttp

### PR DESCRIPTION
**Pull request by edsko**
Function `putHttpFile` already allowed for request headers; we just do the same thing in `getHttp` as is done in `putHttpFile`.

### CODE REVIEW

**Comment by ezyang** [comment]
LGTM!

**Comment by 23Skidoo** [comment]
Yes, looks good.

**Comment by BardurArantsson** [comment]
> Not that it has much to do with this PR specifically, but shouldn't there be some encoding/escaping going on here?

(That was me.)

/cc @edsko 

... or anyone else? I mean, if I'm wrong, then fine, but please tell me so and explain why. I don't think it's particularly constructive to just ignore questions.

**Comment by 23Skidoo** [comment]
@BardurArantsson If you have a test case in which absence of escaping causes problems in practice, please file a ticket. According to my understanding, headers are just ASCII key/value pairs.

**Comment by BardurArantsson** [comment]
Wow, sorry about the tone of my comment. It came out much more querulously than I intended.

**Comment by edsko** [comment]
It will depend I guess on what exactly the headers are used for. I just did in my PR what was already done in the existing transport, and for the headers that I am using that was good enough. I suppose some escaping might be necessary under certain circumstances (spaces? quotes?) but otoh getting all escaping right in all shells might not be so easy.

**Comment by dcoutts** [comment]
There's no problem with embedded spaces in passing out to curl etc. The process infrastructure is quite safe when it comes to keeping the structure of lists of args. So embedded spaces etc are not a problem.

**Pull request merged**
