### PR TITLE
Add support for automatic profiling detail levels, with reasonable defaults

### PR DESCRIPTION
**Pull request by dcoutts**
This is based on top of @ttuegel's patch set "Enable reasonable default profiling options" #2555

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Build fails on Travis.

**Comment by dcoutts** [comment]
Doh, moved some code before committing. Fixed.

**Comment by dcoutts** [comment]
@23Skidoo well spotted, thanks.

**Comment by 23Skidoo** [comment]
New options also need to be documented.

**Comment by 23Skidoo** [comment]
LGTM.

**Comment by dcoutts** [comment]
Updated the user guide, and fixed the thing @23Skidoo spotted. So now if the build works it should be ok to merge.

**Comment by 23Skidoo** [comment]
Great. I think you also need to update the changelog entry.

**Comment by dcoutts** [comment]
Yep, will add the changelog as another patch.

**Pull request merged**
