### PR TITLE
Testing readthedocs' pr integration (do not merge)

### PR DESCRIPTION
**Pull request by fgaz**

### CODE REVIEW

**Comment by fgaz** [comment]
@Mikolaj it works \o/

https://readthedocs.org/projects/cabal/builds/14708732/

**Comment by Mikolaj** [comment]
Yay! How do we wire it into CI? Or do we keep the new CI docs check in CI and use this one only for people that want to see the actual results of doc changes? Does it email somebody when it fails or just show a broken page?

**Comment by fgaz** [comment]
We could mark it as required and remove the github actions one. Before that we'd have to reflect the flags from the makefile to readthedocs, eg. https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning

> Does it email somebody when it fails or just show a broken page?

it shows a failed check in the CI section like github actions

**Comment by Mikolaj** [comment]
Got it. That's great news. Let's keep them both until we are sure they work consistently and the check by @andreasabel is completely subsumed by the ultimate check using Read The Docs.

**Comment by Mikolaj** [comment]
Or does #7638 introduce more/stricter checks and they can't be ported to readthedocs server proper? Or can/should it introduce stricter checks? Is it worth keeping another CI job?

**Comment by fgaz** [comment]
I don't know yet, I didn't check in depth

**Comment by andreasabel** [comment]
@fgaz You could try to run it on a PR that broke links in the docs, e.g., #7498.  
To prevent doc formatting issues (broken links etc.) I think there should be a CI check that fails in that case.

**Pull request closed without merging**
