### PR TITLE
Add file perm bits to current mode rather than overriding

### LINKED ISSUE #7560: Cabal does not respect the setgid bit when creating directories
When using `cabal install` to install packages on a Linux machine it creates quite a number of directories while building and installing components. It works pretty well until you want to use `CABAL_DIR` (or `dist-newstyle` directory) with a set `setgid` bit. In this case some of the directories created by cabal do not inherit the `setgid` bit of the parent directory (as in the following example):

```
$ export CABAL_DIR=/scratch/cabal
$ cabal update
Config file path source is default config file.
Config file /scratch/cabal/config not found.
Writing default configuration to
/scratch/cabal/config
Downloading the latest package list from hackage.haskell.org
$ cabal install zlib
# ... Output omitted ...
$
```
which gives the following under `/scratch/cabal`:
```
$ ll /scratch/cabal
total 28
drwxrwsr-x 5 user grp 4096 Aug 20 14:57 ./
drwxrwsr-x 7 user grp 4096 Aug 20 14:54 ../
-rw-rw-r-- 1 user grp 5508 Aug 20 14:55 config
drwxrwsr-x 3 user grp 4096 Aug 20 14:57 logs/
drwxrwsr-x 3 user grp 4096 Aug 20 14:55 packages/
drwxr-xr-x 3 user grp 4096 Aug 20 14:57 store/ # <== No setgid bit
$ ll /scratch/cabal/store
drwxr-xr-x 3 user grp  4096 Aug 20 14:57 ./
drwxrwsr-x 5 user grp  4096 Aug 20 14:57 ../
drwxr-xr-x 4 user user 4096 Aug 20 14:58 ghc-8.10.6/
$
```
where the `store` directory is created without the `setgid` bit. Thus, the files and directories under `store` have a different group, which could be rather bothersome when user's primary group has a strict disk quota enforced.

It seems that this behavior is related to the definition of the `createDirectoryVerbose` function which calls `setDirOrdinary` after a directory is created. In turn, the `setDirOrdinary` function calls `c_chmod` to set the permissions of the directory in question to `0o755` apparently clearing the `setgid` bit.

It would be really nice to have cabal to be able to recognize this kind of situation and set (or keep) the `setgid` bit accordingly. Or maybe it's already possible?

### PR DESCRIPTION
**Pull request by DanielG**
Fixes #7560

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by DanielG** [comment]
This should be ready for review now.

**Review by jneira — APPROVED** [review]
lgtm, although there are no tests, the pr has been tested manually by the issue reporter so it is ok for me (out of curiosity, would be hard to add those tests?)

**Comment by DanielG** [comment]
> lout of curiosity, would be hard to add those tests?

Setting any of the upper bits including setgid needs root, so we'd have to setup something using `fakeroot` if we really wanted to test this :)

**Comment by jneira** [comment]
@emilypi @fgaz do you think it could be merged?

**Review by emilypi — APPROVED** [review]
LGTM, though, can we get a changelog @DanielG?

**Comment by fgaz** [comment]
CI got stuck again... let's see if this time it starts

**Comment by Mikolaj** [comment]
I'm afraid it's stuck again and blocks the queue.

**Comment by Mikolaj** [comment]
@Mergifyio refresh

**Comment by Mikolaj** [comment]
@Mergifyio refresh

**Pull request merged**
