### PR TITLE
Fix haddock via Setup.hs with internal libraries

### PR DESCRIPTION
**Pull request by brandonchinn178**
Fixes https://github.com/haskell/cabal/issues/1919

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by brandonchinn178** [comment]
I wrote a test that failed and then made _a_ fix that made it pass. I'm not sure if this is the correct fix, though. Would love guidance on an alternate fix

**Comment by Mikolaj** [comment]
Hi @brandonchinn178! Thank you for the test that shows there is a problem and for the fix. Does anybody have any comments?

The CI failure seems to be not a random breakage, but related to haddocks, so probably there is some more work to do.

**Comment by brandonchinn178** [comment]
Sorry forgot to commit the output for `cabal-testsuite` with `--with-cabal` specified. Updated.

**Review by Mikolaj — APPROVED** [review]
LGTM. Let's hope this fixes the stack use case.

**Comment by Mikolaj** [comment]
@brandonchinn178: lure one more reviewer with cookies.

**Comment by brandonchinn178** [comment]
@hsenag @int-e @mietek it seems like you three are the last contributors to comment on the issue. Any of you able/willing to review this?

**Comment by hsenag** [comment]
@brandonchinn178 I tried your branch and I still get the error, but I'm not sure if I did the right things to actually use the dev `cabal-install`/`Cabal`. I pointed at `eb2dd41` in a `source-repository-package` stanza in `cabal.project`, as well as building `cabal-install` from your branch and running that binary.

Regardless, I'm not really able to review your code itself, but once I can verify it fixes my problem I'd be happy to give a thumbs-up on that basis.

**Comment by Mikolaj** [comment]
@hsenag: I'm afraid you might have used Cabal library from hackage. That's why README says to run `cabal install --project-file=cabal.project.release cabal-install` and the project file mentions `packages: Cabal/` (which needs to be from the same branch/commit). I think the easiest way to to clone Brandon's fork and branch, e.g., with

    git checkout -b brandonchinn178-chinn/haddock master
    git pull https://github.com/brandonchinn178/cabal.git chinn/haddock

and run the cabal command above in there.

**Comment by Mikolaj** [comment]
@hsenag: ping?

**Comment by hsenag** [comment]
@Mikolaj sorry for the delay, I've kicked off going through the steps now. Feel free to ping me again in a day or two if I don't report back.

**Comment by hsenag** [comment]
I'm still seeing the failure. What I've done this time:

- Checked out eb2dd41552195bb6813050818c4cc4687a9a64e1 into `~/temp/cabal`.
- In `~/temp/cabal`, run `cabal install --project-file=cabal.project.release cabal-install --installdir=../bin`
- In my project folder (a recent version of darcs), added `~/temp/cabal/Cabal` to `packages`
- In my project folder, blew away `dist-newstyle` then ran `~/temp/bin/cabal v2-haddock test:darcs-test --enable-tests --enable-documentation --haddock-tests`

and I still get
```
Running Haddock on test suite 'darcs-test' for darcs-2.17.1..
setup: internal error when calculating transitive package dependencies.
Debug info: []
```

**Comment by Mikolaj** [comment]
Oh.

So we have a repro. Thank you @hsenag.

@brandonchinn178: are you able to reproduce the failure with darcs-2.17.1? Would you like me to try?

**Comment by brandonchinn178** [comment]
I use Stack primarily, so I'm not sure how much help I'll be in debugging Cabal invocations. If you could take a look, that'd be great. Thanks!

**Comment by hsenag** [comment]
FYI I've now verified that this also happens with `darcs-2.16.4` from hackage. Steps were to `cabal unpack` it, then add a `cabal.project` containing `packages: . ~/temp/cabal/Cabal`, then run the `v2-haddock` command.

**Comment by Mikolaj** [comment]
@hsenag: I confirm your results, both with and without the `cabal.project` file. 

However, I see `Build-Type: Custom` and I know custom setup files are usually a different can of worms. BTW, is the custom setup still necessary in the darcs package? Is there a ticket somewhere specifically about similar problems with Custom setups?

@brandonchinn178: did you intend to fix this for `build-type: Simple` or `Build-Type: Custom` or both? Can the fix be extended to Custom?

Here's the -v2 log of the run without `cabal.project`:

<details>

```
~/ttt/darcs-2.16.4$ ~/temp/bin/cabal -v2 v2-haddock test:darcs-test --enable-tests --enable-documentation --haddock-tests
this build was affected by the following (project) config files:
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built:
 - darcs-2.16.4 *test (first run)
creating /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build
creating /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/tmp
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/cache
whenReRegister: nothing to register
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup
/home/mikolaj/.ghcup/bin/ghc --make -fbuilding-cabal-package -odir /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup -hidir /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup -i -i/home/mikolaj/ttt/darcs-2.16.4/. -optP-include -optP/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup/setup_macros.h -hide-all-packages -no-user-package-db -package-db /home/mikolaj/.cabal/store/ghc-8.10.7/package.db -package-db /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/packagedb/ghc-8.10.7 -package-id Cabal-3.2.1.0 -package-id base-4.14.3.0 -package-id directory-1.3.6.0 -package-id filepath-1.4.2.1 -package-id process-1.6.13.2 /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup/setup.hs -o /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup/setup -threaded
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup/setup
haddock --verbose=2
--builddir=/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4
--tests test:darcs-test
darcs log -a --from-tag 2.16.4 --count
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/build/global-autogen
/home/mikolaj/.ghcup/bin/haddock --ghc-version
/home/mikolaj/.ghcup/bin/ghc --print-libdir -hide-all-packages
/home/mikolaj/.ghcup/ghc/8.10.7/bin/ghc-pkg-8.10.7 init /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/package.conf.inplace
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/build/darcs-test
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/build/darcs-test/autogen
creating
/home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/build/darcs-test/autogen
Preprocessing test suite 'darcs-test' for darcs-2.16.4..
Running Haddock on test suite 'darcs-test' for darcs-2.16.4..
CallStack (from HasCallStack):
  $, called at libraries/Cabal/Cabal/Distribution/Simple/Haddock.hs:255:13 in Cabal-3.2.1.0:Distribution.Simple.Haddock
  haddock, called at libraries/Cabal/Cabal/Distribution/Simple.hs:636:35 in Cabal-3.2.1.0:Distribution.Simple
  haddockHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:139:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
  haddockHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:139:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
  cmd_hook, called at libraries/Cabal/Cabal/Distribution/Simple.hs:497:9 in Cabal-3.2.1.0:Distribution.Simple
  cmd_hook, called at libraries/Cabal/Cabal/Distribution/Simple.hs:516:4 in Cabal-3.2.1.0:Distribution.Simple
  hookedActionWithArgs, called at libraries/Cabal/Cabal/Distribution/Simple.hs:495:5 in Cabal-3.2.1.0:Distribution.Simple
  hookedAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:360:3 in Cabal-3.2.1.0:Distribution.Simple
  haddockAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:187:50 in Cabal-3.2.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:125:42 in Cabal-3.2.1.0:Distribution.Simple
  $, called at /home/mikolaj/ttt/darcs-2.16.4/dist-newstyle/build/x86_64-linux/ghc-8.10.7/darcs-2.16.4/setup/setup.hs:36:8 in main:Main
setup: internal error when calculating transitive package dependencies.
Debug info: []

CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:379:14 in Cabal-3.7.0.0-543aaa840f170abad978ace330d2fed5d9915f52f7fc73a0f5f6df83df6a5532:Distribution.Simple.Utils
Error: cabal: Failed to build documentation for darcs-2.16.4-inplace.
```

**Comment by brandonchinn178** [comment]
The function I edited should be the single entrypoint for everything. Short of a custom Setup.hs script that overrides the haddock hook with some completely adhoc function, my fix should still apply. I'll try to download the darcs code today and take a look at the Setup.hs script

**Comment by Mikolaj** [comment]
I'm afraid it does override a whole lot:

```
  haddockHook = \ pkg lbi hooks flags ->
                let verb = fromFlag $ haddockVerbosity flags
                 in commonBuildHook haddockHook pkg lbi hooks verb >>= ($ flags) ,
```

**Comment by hsenag** [comment]
It might just be on us to update the hook then, if so apologies for the noise. We have been trying to get rid of our custom setup but there are still a few pieces left.

**Comment by brandonchinn178** [comment]
@hsenag do your comments mean that you're unable to verify that this PR is correct, since the darcs repo does its own stuff with Cabal hooks?

@int-e @mietek are either of you able to review this change?

**Comment by hsenag** [comment]
> @hsenag do your comments mean that you're unable to verify that this PR is correct, since the darcs repo does its own stuff with Cabal hooks?

Based on my tests on the darcs repo, the problem still happens with your changes. But hopefully it should be possible to update our hook to take account of your changes? I didn't have a chance to take a deeper look to figure that out yet, though it's on my TODO list. If you can point me in the right direction it would probably speed that up :-)

**Comment by Mikolaj** [comment]
@brandonchinn178, @hsenag: how about, to avoid mutual blocking, we merge this PR and test, fix, amend, etc., as needed, later on?

**Comment by hsenag** [comment]
> @brandonchinn178, @hsenag: how about, to avoid mutual blocking, we merge this PR and test, fix, amend, etc., as needed, later on?

I'd be very happy with that, and I never intended to block this PR.

If I understood the start of the discussion about whether it fixed the darcs case, it was because @brandonchinn178 needed a second reviewer and that I could review from the point of view of a user whose problem was fixed. Without that, and without knowing the `cabal` code, I'm not sure my review would be worth much. But given this has been languishing for a while, I could provide that approval anyway?

**Comment by Mikolaj** [comment]
> But given this has been languishing for a while, I could provide that approval anyway?

That would be very much appreciated indeed. :)

**Review by hsenag — APPROVED** [review]

**Comment by hsenag** [comment]
> But given this has been languishing for a while, I could provide that approval anyway?

Turns out it doesn't help because I'm not a reviewer with write access :-(

**Comment by Mikolaj** [comment]
> Turns out it doesn't help because I'm not a reviewer with write access :-(

That's fine --- I can force-merge regardless. :)

**Review by Kleidukos — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
@hsenag, @Kleidukos: thank you so much.

@brandonchinn178: once you rebase and fix the conflicts, let's merge!

**Comment by brandonchinn178** [comment]
Done!

**Pull request merged**
