### PR TITLE
'user-config init': Print the default 'remote-repo' correctly.

### LINKED ISSUE #3867: Incorrect default listed in .cabal/config file for secure (in HEAD)
The config file created by `user-config init` lists:

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: False
  -- root-keys:
  -- key-threshold:
```

However, subsequently running `cabal update -v` confirms that it _is_ in fact using secure access to the repository by default.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #3867.

~~This is WIP -- I also need to fix pretty-printing of multiline fields:~~ 
```
repository hackage.haskell.org                                                                                                                        
  url: http://hackage.haskell.org/                                                                                                                    
  -- secure: True                                                                                                                                     
  -- root-keys: fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0                                                                      
                1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42                                                                      
                2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3                                                                      
                0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d                                                                      
                51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921                                                                      
  -- key-threshold: 3 
```

~~So please don't merge yet.~~ Should be now ready to go in.

### CODE REVIEW

**Comment by hvr** [comment]
does fixing the pretty-printing of multiline fields also fix the output of `user-config diff` which only shows a single root-key at most?

**Comment by 23Skidoo** [comment]
@hvr Not sure.

**Comment by dcoutts** [comment]
@23Skidoo I wonder if we want to include the root keys and threshold fields at all. It's better for most people to use the defaults rather than fixed values. That's because we can change the defaults, and if people fix to old values then they can end up not being able to bootstrap. The counter-argument would be that it's important for people to know the values used and should have the option to manually set and manually upgrade the root keys used.

That said, the root keys actually in use can change any any time without user intervention anyway, since the policy is to accept any root.json that is signed by keys we already trust (from a previous root.json). So the keys here are only for bootstrapping from an initial state.

**Comment by 23Skidoo** [comment]
@dcoutts I don't have a strong preference towards one or the other, though skipping them means less work for me.

**Comment by dcoutts** [comment]
@23Skidoo so I'd be totally happy if this were the output:

    repository hackage.haskell.org  
      url: http://hackage.haskell.org/
      -- secure: True

**Comment by 23Skidoo** [comment]
@dcoutts If I'm running a proprietary secure Hackage, I do need to specify a different set of root keys in `~/.cabal/config`, right?

**Comment by dcoutts** [comment]
@23Skidoo you do yes. It's only the central server where you don't need to specify them since we ship them with cabal.

**Comment by ezyang** [comment]
Yeah, I'm pretty OK with not putting in the keys.

**Comment by 23Skidoo** [comment]
Updated. I've decided to go with:

```
repository hackage.haskell.org                                                                                                                        
  url: http://hackage.haskell.org/                                                                                                                    
  -- secure: True                                                                                                                                     
  -- root-keys:                                                                                                                                       
  -- key-threshold: 3
```

to make things more obvious for proprietary Hackage users.

**Comment by 23Skidoo** [comment]
Has anyone seen this before:
```
Generating manual page
/home/travis/build/haskell/cabal/dist-newstyle/build/cabal-install-1.25.0.0/build/cabal/cabal.1
...
Warning: Could not list sources of the package 'cabal-install'.
Warning: Exception was: user error (The package 'cabal-install' requires Cabal
library version >=1.18.0 && >=1.10 but no suitable version is installed.)
cabal new-build cabal-install:cabal cabal-install:integration-tests cabal-install:integration-tests2 cabal-install:unit-tests cabal-install:solver-quickcheck took 250 seconds.
----
```
? [Happens on 7.6.3](https://travis-ci.org/haskell/cabal/jobs/161440882). I'll try restarting the build, but would be nice to fix the underlying issue.

**Comment by dcoutts** [comment]
Not seen that. Looks like it's failing when calling `sdist --list-sources`.

(I'll repeat my opinion, stated in full elsewhere, that we should move on from calling `sdist --list-sources` and construct the file monitor spec directly from the .cabal file)

**Comment by 23Skidoo** [comment]
> (I'll repeat my opinion, stated in full elsewhere, that we should move on from calling `sdist --list-sources` and construct the file monitor spec directly from the .cabal file)

For the record, I'm +1 on this, we'll just need to deprecate sdist hooks.

**Pull request merged**
