### PR TITLE
cabal init -i should autodetect author name and maintainer email

### LINKED ISSUE #8255: cabal init doesn't autodetect author name and maintainer email
**Describe the bug**

cabal init doesn't autodetect author name and maintainer email. the old init implementation did, and i found it pretty useful

**To Reproduce**

```
$ cabal init
[...]
Author name? [optional] 
Maintainer email? [optional] 
[...]
```

**Expected behavior**

```
[...]
Author name? [default: Name Surname] 
Maintainer email? [default: user@example.com]
[...]
```

(detected from git iirc)

**System information**
 - cabal HEAD
 - NixOS, but my git config is in the usual place

**Additional context**

cc @ptkato @emilypi

### PR DESCRIPTION
**Pull request by ulysses4ever**
fix #8255

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by jneira** [comment]
looks good, but a test to ensure the behaviour is not lost again would be great
not sure about status of init tests, specially for the interactive mode, iirc they were rewritten/refactored by @ptkato recently

**Comment by ptkato** [comment]
Yes, anything that involves IO (any function defined in the `Interactive` typeclass) in any capacity will require a tuning of the unit tests from cabal-install.

By the by, the reasoning behind not having those in the interactive bits from the get go, was just a separation of concerns, leaving all the guessing to the non-interactive part, while the interactive part would rely entirely on the user input; but at this point, that reasoning is not relevant to this change, since it is more of a convenience.

**Comment by ulysses4ever** [comment]
Wow, that's a lot `Exception: NonEmpty.fromList: empty list` for such a small change!
https://github.com/haskell/cabal/runs/7185707221?check_suite_focus=true

**Comment by andreasabel** [comment]
Yes, please a test!

**Review by emilypi — COMMENTED** [review]
LGTM pending a test

**Comment by ulysses4ever** [comment]
First I need to figure how to fix the current 18 failing tests. I'm not sure I manage it quite that fast.

In a nutshell, every call to an external process (we call `git config` to guess name/email) in the `PurePrompt` monad (used in the tests) simply takes an element of the list of inputs
https://github.com/haskell/cabal/blob/5159ffbc8ab42e242ccd404cef594787bb08d65e/cabal-install/src/Distribution/Client/Init/Types.hs#L377
this messes up with the inputs as setup before this change.

**Comment by ptkato** [comment]
Yes, you need to find where in the chain of functions this is called, to add to each faulting test the missing input string (to the input list), in the correct order.

**Comment by ulysses4ever** [comment]
I added the test in a separate commit. Please, review.

**Review by emilypi — APPROVED** [review]
LGTM - nice job @ulysses4ever

**Review by Mikolaj — APPROVED** [review]
Thanks a lot.

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Comment by ulysses4ever** [comment]
@Mikolaj do you think we could backport it to 3.8?

**Comment by Mikolaj** [comment]
> @Mikolaj do you think we could backport it to 3.8?

We absolutely should.

**Comment by ulysses4ever** [comment]
I'm not well versed in the process here. Let me know if I can help to make this happen.

**Comment by Mikolaj** [comment]
This should fire once the PR is merged and then the review/CI/merge repeats for the backport PR.

**Pull request merged**
