### PR TITLE
Change Cabal's GHC support window to GHC 6.12 or later

### PR DESCRIPTION
**Pull request by ezyang**
JUST THE LATEST PATCH, it was based off of #3066, but I think it should not be difficult to commute earlier. See #3108 for some rationale.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
> JUST THE LATEST PATCH

Can you please cherry-pick it into a new branch based off `master` and run `push -f`?

**Comment by 23Skidoo** [comment]
Though I think this should wait until after 1.24, if it's fine with you.

**Comment by ezyang** [comment]
Yeah, I didn't bother cherry-picking it because I'm pretty sure this is post 1.24.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
