### PR TITLE
Support transformers-0.6 and mtl-2.3

### LINKED ISSUE #8144: Support transformers-0.6 and mtl-2.3
Looks like that relaxing bounds is enough.

### PR DESCRIPTION
**Pull request by Bodigrim**
Resolves #8144. 

Tested with 
```
cabal build all -c 'transformers >= 0.6' --allow-newer='rere:transformers'
```

~~Depends on https://github.com/haskell/hackage-security/pull/289~~

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
@Bodigrim: so is a new release of hackage-security needed for that to work  though it did not fail yet, as of writing this, but I see my old PR doing the same did: https://github.com/haskell/cabal/pull/8149#issuecomment-1191520485)?

I can release hackage-security now, it's a walk in the part compared to a cabal release.

**Comment by Bodigrim** [comment]
@Mikolaj a new release of `hackage-security` would be helpful, yes.

**Comment by Mikolaj** [comment]
@Bodigrim: done: https://hackage.haskell.org/package/hackage-security-0.6.2.3

**Comment by ulysses4ever** [comment]
Did you make sure that mtl 2.3 actually realizes (e.g. building with cabal.project.local containing `constraints: mtl == 2.3` and appropriate allow-newer if needed)? Otherwise bumping its bound may bring surprises down the road.

**Comment by Bodigrim** [comment]
@ulysses4ever `transformers >= 0.6` implies `mtl >= 2.3`, but I also checked it explicitly.

**Comment by ulysses4ever** [comment]
Ah, cool, thanks!

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
@Bodigrim: feel free to set the merge_me label.

**Comment by Bodigrim** [comment]
May I ask for a force-merge, without waiting 2 days, please? Unfortunately, I have plenty of other work depending on this (and #8608).

**Comment by Mikolaj** [comment]
Sure, what's the worst that can happen? Emergency merging due to others depending on this PR.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
(the rebase was actually spurious --- mergify would do it on its own, if needed)

**Pull request merged**
