### PR TITLE
Prepends >= to cabal versions older than 1.12

### LINKED ISSUE #8206: cabal init --cabal-version 1.10 generates "cabal-version: 1.10" instead of "cabal-version: >=1.10"
**Describe the bug**
cabal init --cabal-version 1.10 generates "cabal-version: 1.10" instead of "cabal-version: >=1.10"

**To Reproduce**

```
$ cabal init -n --cabal-version=1.10 p

Warning: Cabal spec versions < 1.18 do not support extra-doc-files. Doc files will be treated as extra-src-files.

Log: Guessing dependencies...

Log: Using cabal specification: 1.10

Warning: unknown license type, you must put a copy in LICENSE yourself.

Log: Creating fresh file CHANGELOG.md...

Log: Creating fresh directory ./app...

Log: Creating fresh file app/Main.hs...

Log: Creating fresh file p.cabal...

Warning: No synopsis given. You should edit the .cabal file and add one.

Info: You may want to edit the .cabal file and add a Description field.
$ cd p
$ grep cabal-version: p.cabal
cabal-version:      1.10
$ cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: No 'category' field.
Warning: The 'license' is AllRightsReserved. Is that really what you want?
Warning: p.cabal:1:25: With 1.10 or earlier, the 'cabal-version' field must
use range syntax rather than a simple version number. Use 'cabal-version: >=
1.10'.
Warning: The following errors will cause portability problems on other
environments:
Warning: No 'synopsis' or 'description' field.
Warning: Hackage would reject this package.
```

**Expected behavior**
`cabal-version: >=1.10`

**System information**
cabal 3.8.1.0-rc1

cc @emilypi @ptkato

### PR DESCRIPTION
**Pull request by ptkato**
Closes #8206. I updated one of the golden tests so it detects this stuff.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thanks!

**Review by Mikolaj — APPROVED** [review]
Thanks a lot!

**Comment by ulysses4ever** [comment]
@ptkato as usual, the PR author is expected to put the `squash+merge` label when happy with the state of things. Do you want to do it?

**Comment by Mikolaj** [comment]
Let me try to prod mergify manually.

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Kleidukos** [comment]
@Mikolaj All PRs for which the delay had passed have been merged :+1:

**Pull request merged**
