### PR TITLE
Tell zlib not to use pkg-config

### PR DESCRIPTION
**Pull request by chreekat**
(In GitLab CI)

 [GitLab pipeline status](https://gitlab.haskell.org/haskell/cabal/-/commits/b/zlib-no-pkg-config)

### CODE REVIEW

**Comment by chreekat** [comment]
Hm, something weird happening on the Windows build. Looks like something else is trying to restart it, too, but I don't know what (or who?)

**Comment by Kleidukos** [comment]
@chreekat would you mind adding this badge to the README? <3

**Review by Mikolaj — APPROVED** [review]
Thank you.

**Review by Kleidukos — APPROVED** [review]

**Comment by chreekat** [comment]
The bug could also be with zlib.

In 0.6.3.0, zlib uses the vendored libz C library on Windows. In 0.7.0.0, when disabling pkg-config, it just uses `extra-libraries: z`, claiming in a comment that "On Windows, zlib is shipped with GHC starting from 7.10".

I'm gonna see if going back to using the vendored libz fixes the Windows build.

**Comment by chreekat** [comment]
Lord almighty, the Darwin job is building LLVM or something?! Amazing

**Comment by chreekat** [comment]
GitLab CI passed, so I will send to the bot.

**Comment by Mikolaj** [comment]
@mergify backport 3.12

**Pull request merged**
