### PR TITLE
Increase urllib.request.urlopen timeout in bootstrap.py to fix CI

### PR DESCRIPTION
**Pull request by Mikolaj**
Again trying to fix bootstrap job currently broken on CI via explicitly setting a timeout. I think the past attempt #8576 helped, but the lag has grown since. But I may be wrong.

### CODE REVIEW

**Comment by Mikolaj** [comment]
So far so good. Perhaps 10s is enough. Until next time.

**Review by ffaf1 — APPROVED** [review]
Dobry

**Comment by Kleidukos** [comment]
dobrze.

**Comment by ulysses4ever** [comment]
Хорошо!

**Review by ulysses4ever — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Should probably emergency-merge

**Comment by Mikolaj** [comment]
Emergency merging.

**Comment by Mikolaj** [comment]
@mergify rebase

**Pull request merged**
