### PR TITLE
`package-constraints` by package file

### PR DESCRIPTION
**Pull request by jasagredo**
Solves #8912 #9477

# Manual QA

By adding a field `package-constraints` in a cabal file and a list of dependencies with version ranges, for each of those dependencies, any dependency declaration that was unbounded will be set to the one on `default-constraints`:

```
package-constraints:
  x > 5

library a 
  build-depends: x

library b 
  build-depends: x >5.5

library c
  build-depends: y
```

Should be understood as:

```
library a 
  build-depends: x >5

library b 
  build-depends: x >5.5 && >5

library c
  build-depends: y
```

If the stanza is omitted, then nothing changes wrt previous version.

Notice this should not influence:
- `build-tool-depends`
- `pkgconfig-depends`
- transitive dependencies

--------------------------------------------------

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by jasagredo** [comment]
I requested reviews from some devs, feel free to dismiss otherwise, thanks!

**Review by geekosaur — CHANGES_REQUESTED** [review]

**Review by Mikolaj — COMMENTED** [review]
This a very visible new feature that will be used by all so, I think, on top of a technical review of the implementation (and the discussion of the design in the original ticket), it would be good to ask the prospective users (RFC somewhere?). I think mentioning this on the fortnightly devs chat may be a good start.

Alternatively, mark it as experimental for one major version, gather feedback from that and change at will (since it's experimental).

**Comment by jasagredo** [comment]
Back to draft because it doesn't work in the presence of conditionals

**Review by andreabedini — CHANGES_REQUESTED** [review]
See the note I have left in the RFC.

In terms of implementation, this should be done in the solver, not in the parser. We should keep the parser faithful to what is written (and we already fail to do so) and the solver already has logic to traverse the GPD and merge the component dependencies toghether (see `convCondTree` in `Distribution.Solver.Modular.IndexConversion`).

**Comment by gbaz** [comment]
I don't tend to think this should be done in the solver, because that is complex enough as is, and this need not be done there. I would prefer this were kept in the syntax tree as-is, but applied/simplified before sent to the solver.

**Comment by jasagredo** [comment]
Ah I understand your point. I would need some guidance on where to put this and how to carry the constraints all the way there, but yeah, seems reasonable.

**Review by geekosaur — CHANGES_REQUESTED** [review]

**Comment by jasagredo** [comment]
Obsoleted by #9570

**Pull request closed without merging**
