### PR TITLE
Take more care with special characters in paths to configure scripts

### PR DESCRIPTION
**Pull request by quasicomputational**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

Includes two new tests, one making sure that the warnings are emitted and one that tickles the original problem of #5386 on Windows (backslash path delimiters followed by numbers being interpreted by sed).

### CODE REVIEW

**Comment by quasicomputational** [comment]
Ugh, it's not triggering on AppVeyor as I'd hoped. I might need to get my hands on a Windows machine and figure out why it's not breaking.

**Comment by angerman** [comment]
Here's the shortest receipt I came up with to reproduce it. Doesn't even use haskell at all:
```
mkdir \\1 && cd \\1
cabal unpack network && cd network-*
mkdir build && cd build
../configure
```

**Comment by snoyberg** [comment]
I'm not following why my original approach of using a relative filepath and setting the working directory wouldn't work instead (I didn't follow the comment on the original issue either). That approach restores something close to the Cabal 2.0 behavior, and works for filepaths with backslashes in them.

**Comment by quasicomputational** [comment]
We need warnings anyway even if we use relative paths; paths with backslashes are actually broken. Quoting the autoconf docs:

> These restrictions apply not only to the files that you distribute, but also to the absolute file names of your source, build, and destination directories.

This patch doesn't implement all of that, but it gets us started.

That's mostly independent of whether we want to go back to relative paths or not to invoke the configure script, but AFAIK there's no other known breakage due to that.

**Comment by angerman** [comment]
@snoyberg, your patch from https://github.com/haskell/cabal/issues/5386#issuecomment-398044552 would run `configure` in the projects root directory (where the cabal file is located).  Preventing this was the original motivation behind the change.  Stipping configure from dirtying the source tree and instead to generating its files in the build folder.

If configure generates file `a`
```
pkg $ ./configure
```
Will produce `pkg/a`

However
```
pkg/build-ghcX.Y $ ../configure
```
Will produce `pkg/build-ghcX.Y/a`

**Comment by snoyberg** [comment]
I didn't glean that from the patches I was reviewing, my mistake. OK, I guess this regression in behavior is simply inherent then, and we'll have to work around Cabal downstream.

**Comment by quasicomputational** [comment]
@snoyberg What's left to work around after we make backslashes not be a problem? If it's not too complicated we can probably do something in Cabal.

**Comment by snoyberg** [comment]
> after we make backslashes not be a problem

If that's the case, then everything's fine. I guess I simply don't understand how this solution works. If this makes it that `runghc Setup.hs configure` works inside `c:\1\foo`, then it does in fact solve the problem and no downstream workaround will be necessary (excluding workarounds for already-shipped Cabal versions).

**Comment by quasicomputational** [comment]
The added test `cabal-testsuite/PackageTests/T5386` exercises that exact case and it works now. The fix is nothing more sophisticated than turning backslashes separating components into slashes on Windows, which is a legitimate operation and one we need to do anyway if we're not going to issue five million false positive warnings about bogus characters in paths.

**Comment by quasicomputational** [comment]
Oh, oops, I changed something in the docs and got it wrong. One second!

**Comment by quasicomputational** [comment]
OK, squashed and pushed it to master. Thank you to @snoyberg for chasing the bug down from such an obscure situation, and for suggesting the fix!

**Comment by snoyberg** [comment]
Thanks @quasicomputational for taking the ball on this and fixing it so promptly, and better than I would have 👍

**Pull request closed without merging**
