### PR TITLE
Update default-language & avoid default-extensions

### PR DESCRIPTION
**Pull request by hvr**
This upgrades the `default-language: Haskell98` to `Haskell2010`
and removes `default-extensions: RankNTypes, FlexibleContexts`
in favor of adding `LANGUAGE` pragmas where needed.

Moroever, this also drops `LANGUAGE` pragmas which become redundant due
to `Haskell2010` (specifically, `EmptyDataDecls`,
`ForeignFunctionInterface` and `PatternGuards`)

Finally, an `other-extensions` specification is put in place for the
`Cabal` library component.

This helps loading up files directly in GHCi, such as e.g. `ghci Setup.hs`

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Looks like you also need to add `RankNTypes` to `D.C.CreatePipe`.

**Comment by hvr** [comment]
@23Skidoo yeah, I missed a few pragmas needed only for GHC 7.10

**Comment by 23Skidoo** [comment]
@hvr Feel free to merge once it's green.

**Comment by 23Skidoo** [comment]
@hvr This seems to have broken AppVeyor: https://ci.appveyor.com/project/ezyang/cabal/build/1.0.1501/.

**Comment by hvr** [comment]
@23Skidoo  `Build not found or access denied.` :-/

coincidentally, this fixed my PPA build (which bootstraps via `ghc --make Setup.hs` and was failing before)

**Comment by 23Skidoo** [comment]
> `Build not found or access denied.` :-/

Apparently due to the trailing slash in the URL. Thanks for the fix!

**Pull request merged**
