### PR TITLE
Cherry-pick "Don't recompile C files unless needed"

### PR DESCRIPTION
**Pull request by lukexi**
Not sure if there's a plan for another 1.22 release, but if so it would be great to have this on board.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
We'll probably do another patch level Cabal release if there will be a GHC 7.10.3.

**Comment by 23Skidoo** [comment]
Any idea about what causes the Travis failures?

**Comment by lukexi** [comment]
Hmm, looks like it's a bunch of unrelated failures?

```
The command "git clone -b pr-base48 https://github.com/hvr/ansi-wl-pprint ../ansi-wl-pprint" failed 3 times.
```
and knockon effects thereof...

**Comment by 23Skidoo** [comment]
OK, can you please rebase against `1.22` and do a `push -f`?

**Comment by lukexi** [comment]
Looks like we're all good now.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by lukexi** [comment]
Great, thanks Mikhail!

**Pull request merged**
