### PR TITLE
Freeze solver goal order in two more unit tests

### PR DESCRIPTION
**Pull request by grayjay**
See #3489 and #3510.

@kosmikus Do you think we should specify the goal order for these two tests?  I wasn't completely sure.

### CODE REVIEW

**Comment by kosmikus** [comment]
@grayjay Perhaps both, actually? I think for these situations, we want to make sure we find the right install plan both if the goal order is the fixed one, but also in practice (with whatever goal order the solver actually picks).

**Comment by grayjay** [comment]
I updated it to test both goal orders.

**Comment by kosmikus** [comment]
LGTM.

**Comment by grayjay** [comment]
Thanks!  I'll merge it.

**Pull request merged**
