### PR TITLE
Do not use shallow clones for `source-repository-package`s

### LINKED ISSUE #10605: New git invocation changes the behaviour of source-repository-package
Building https://github.com/Kleidukos/get-tested/ used to work perfectly, with a `source-repository-package` that reads:

```
source-repository-package
  type: git
  location: https://github.com/goodlyrottenapple/tasty-test-reporter 
  tag: b704130
```

[b704130](https://github.com/goodlyrottenapple/tasty-test-reporter/commit/b704130545aa3925a8487bd3e92f1dd5ce0512e2).

However, with the latest `cabal-head`, I get this result:

```
❯ cabal build                          
Warning: this is a debug build of cabal-install with assertions enabled.
Created semaphore called cabal_semaphore_0 with 2 slots.
Cloning into '/home/hecate/Projects/get-tested/dist-newstyle/src/tasty-tes_-b16926c1aaf24d94e61a2dd23f73b43c646945927c2a595c777e30f60e9d2040'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 24 (delta 0), reused 17 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 230.02 KiB | 4.60 MiB/s, done.
fatal: couldn't find remote ref b704130
```

And with the long hash:

```
Warning: this is a debug build of cabal-install with assertions enabled.
Created semaphore called cabal_semaphore_0 with 2 slots.
From https://github.com/goodlyrottenapple/tasty-test-reporter
 * branch            b704130545aa3925a8487bd3e92f1dd5ce0512e2 -> FETCH_HEAD
warning: refname 'b704130545aa3925a8487bd3e92f1dd5ce0512e2' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,

  git switch -c $br $(git rev-parse ...)

where "$br" is somehow empty and a 40-hex ref is created. Please
examine these refs and maybe delete them. Turn this message off by
running "git config advice.objectNameWarning false"
HEAD is now at b704130 add cabal file
Configuration is affected by the following files:
- cabal.project
Resolving dependencies...
Build profile: -w ghc-9.10.1 -O2
In order, the following will be built (use -v for more details):
 - ansi-terminal-1.1.2 (lib) (requires build)
 - cabal-doctest-1.0.11 (lib) (requires download & build)
```

@alt-romes I believe you're the last person to touch how `cabal-install` calls git. Could you please investigate this?

### PR DESCRIPTION
**Pull request by 9999years**
Fixes #10605

Includes a regression test.

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by philderbeast** [comment]
I checked out this branch, installed `cabal-install` from it and reran a timing test against amazonka, same as https://github.com/haskell/cabal/issues/10605#issuecomment-2523258225. This gives slow results. I ran it twice after cleaning and got 82s and 84s. I reran the same test twice using `cabal-install` from the master branch and got times of, 16s each time.

**Comment by 9999years** [comment]
@philderbeast Yes, that's what I'm expecting. It might be possible to keep the shallow clone behavior in some cases without introducing regressions, but let's fix the regressions first.

**Comment by alt-romes** [comment]
I've commented this in https://github.com/haskell/cabal/issues/10605#issuecomment-2541241444, but to re-iterate here:

It seems to me that we can easily fix the regression by only reverting to the previous behaviour (full clones) when the hash is not given in full.

**Comment by 9999years** [comment]
@alt-romes That seems reasonable, although I do worry (as with all roll-forward fixes) that we'll be introducing another bug or missing some edge case as we do so. Would you put up a PR for it?

**Comment by alt-romes** [comment]
> @alt-romes That seems reasonable, although I do worry (as with all roll-forward fixes) that we'll be introducing another bug or missing some edge case as we do so. Would you put up a PR for it?

I can appreciate that concern, and still think the cost of being that conservative here seems quite high. Since the regression seems well define, let's try fixing it specifically. I'll make a PR, including your regression test.

**Pull request closed without merging**
