### PR TITLE
Fix whitespace issue in changelog

### PR DESCRIPTION
**Pull request by alt-romes**
**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by alt-romes** [comment]
@geekosaur here it is

**Review by geekosaur — CHANGES_REQUESTED** [review]
We need a PR template, please.

**Comment by alt-romes** [comment]
Added

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
High priority because in some sense `master` is currently broken / doesn't pass CI since `changelog.d` was added to the whitespace check. See https://github.com/haskell/cabal/pull/10639#issuecomment-2545283158.

**Review by philderbeast — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
If nobody objects I will expedite the merge in a moment, as @geekosaur suggests.

**Comment by geekosaur** [comment]
Just set `merge me`, Mergify already knows about `priority: high`.

**Pull request merged**
