### PR TITLE
[ mergify ] allow 1 approver for backports

### PR DESCRIPTION
**Pull request by ulysses4ever**
Trying to be more lenient to backport PRs...

I also took liberty to restrict normal mergify merges to `master`. If you think it's not ok, let me know and I'll revert.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
I also took liberty to restrict normal mergify merges to `master`. If you think it's not ok, let me know and I'll revert.

**Review by Mikolaj — APPROVED** [review]
Thank you for both. If rebase is too hard, there's always the big red button to override.

**Comment by ulysses4ever** [comment]
After little experimenting on my own fork, I figured `author=mergify` doesn't work for some reason. So, instead I propose to use a separate label, e.g. `merge backport`. Technically `merge me` could be reused but with a higher chance of confusion.

**Comment by ulysses4ever** [comment]
This PR on my fork demonstrates that it's viable https://github.com/ulysses4ever/cabal/pull/8

**Comment by Mikolaj** [comment]
User confusion? Machine confusion? Not a big deal, but with `merge me` it would be one less label to remember.

**Comment by ulysses4ever** [comment]
All right, reusing merge-me then.

**Comment by ulysses4ever** [comment]
Hmm, I'm curious: why Mergify doesn't peak it up. The 2 day buffer rule hasn't been merged yet, so it's not that...

**Comment by Mikolaj** [comment]
IMHO, let's merge manually.

**Comment by Mikolaj** [comment]
I forgot, does it need a backport?

**Comment by ulysses4ever** [comment]
@Mikolaj I don't think so. As per the docs, the config used is always from the repo's default branch.

**Comment by Mikolaj** [comment]
Got it. Thank you.

**Pull request merged**
