### PR TITLE
Solver: Check whether components are buildable in the current environment.

### PR DESCRIPTION
**Pull request by grayjay**
This commit handles the most common case of issue #5325 by checking that each
component that is required as a dependency is buildable in the current
environment, where environment refers to the compiler, os, arch, and global flag
constraints.  The solver records whether each component is buildable in the
package's PInfo during index conversion.  Then it checks that each required
component is buildable in the validation phase, similar to the check for missing
components.

The buildable check can give false-positives, because it only considers flags
that are set by unqualified flag constraints, and it doesn't check whether the
intra-package dependencies of a component are buildable.  The check is also
incomplete because it is performed before any automatic flags are assigned.  It
is possible for the solver to later choose a value for a flag that makes the
package unbuildable.

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

/cc @hvr @phadej

### CODE REVIEW

**Comment by phadej** [comment]
I used this patch in `servant`'s CI, and it fixes the issue there. So :+1: from me, solves my problem :)

**Comment by phadej** [comment]
I have dogfooded this for over a week, so I guess @hvr.

Herbert: what's your experiences, let's merge this!

**Comment by hvr** [comment]
@grayjay hrm... so `yesod-0.0.0.2` pkg spec appears ill-specified anyway, as toggling the flag results in the lib-component's `build-depends` being disabled as well, and since this is a cabal-version:1.6 description, it means that the exe component becomes effectively unusable as well as it e.g. loses its implicit `build-depends` on `base` as well.

**Comment by grayjay** [comment]
The build-depends field isn't under the conditional, so it might work with older versions of cabal that required dependencies for unbuildable components.

**Pull request merged**
