### PR TITLE
gitlab-ci/brew.sh/curl: use LCD feature set

### PR DESCRIPTION
**Pull request by chreekat**
Use the lowest common denominator features available on supported platforms.

### CODE REVIEW

**Comment by chreekat** [comment]
Failures unrelated to my PR :)

**Review by Mikolaj — APPROVED** [review]
Thank you.

**Comment by Mikolaj** [comment]
Restarting twice did not help. I think CI cache reset helps sometimes. Let me try that.

**Comment by Mikolaj** [comment]
I've just killed all Validate cache for this PR (and then some). Let me restart CI again...

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Review by geekosaur — APPROVED** [review]

**Comment by ulysses4ever** [comment]
This probably could be excused from the two day delay...

**Comment by Mikolaj** [comment]
Thank you all. Yes, good idea, let's fast-track this. 

@chreekat, @Kleidukos, if you don't mind I'm going to impersonate and fake labels, and the same for the backport.

**Comment by Mikolaj** [comment]
Let me now try to restart rtd that failed, probably also randomly.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Pull request merged**
