### PR TITLE
Replacement for VersionTags

### PR DESCRIPTION
**Pull request by zilinc**
see :
https://ghc.haskell.org/trac/ghc/ticket/2496#comment:19
https://ghc.haskell.org/trac/ghc/ticket/2496#comment:20

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Related: #1506.

**Comment by 23Skidoo** [comment]
Why do you need this in Cabal when you can just do:

```
module Notes (notes) where

notes :: String
notes = ...
```

in your project ?

**Comment by zilinc** [comment]
@23Skidoo I basically want to achieve the same thing as #1506, but more general and user-customisable. I don't see how the `Notes` modules accomplish this. Could you elaborate?

**Comment by 23Skidoo** [comment]
#1506 requires quite a lot more than what you've implemented. Right now your code is just a roundabout way to export a string from a module.

**Comment by zilinc** [comment]
@23Skidoo Well, what I implemented alone doesn't do any of #1506, but at in my case, I used to do 
```
buildHook pkg buildInfo hooks flags = do
    let pId = package pkg
         ver = pkgVersion pId
    hash <- readProcess "git" ["rev-parse", "--short=10", "HEAD"] []
    let hash' = init hash  -- get rid of the newline
         newVer = ver { versionTags = [hash'] }
         newPId = pId { pkgVersion = newVer }
         newPkg = pkg { package = newPId }
    buildHook simpleUserHooks newPkg buildInfo hooks flags
```
in Setup.hs. With `versionTags` deprecated, I can just do it in the same way as before. It essentially just moves the versionTags field outside Version datatype.

**Comment by zilinc** [comment]
Using it for revision control is just the motivation. This pull request is in fact to provide a field for any extra info associated with the package (which also covers the usage of `versionTags`), with git hash being an instance.

**Comment by 23Skidoo** [comment]
But you could just generate a `Notes` module in your `buildHook`, there's no need to add a field for this.

**Comment by zilinc** [comment]
I do agree with you (@23Skidoo) that users can generate their own modules using the hook. But nothing would be absolutely necessary. I think the matter is how often/many people are using that field (c.f. https://ghc.haskell.org/trac/ghc/ticket/2496#comment:21). On the other hand however, cabal's pkg-descr does lack of a field for extra info.

**Comment by 23Skidoo** [comment]
I just don't see why you need this to be a part of the package description if you won't be editing the value of this field by hand in the `.cabal` file. I also doubt the usefulness of "notes" given its vague semantics ("a metadata string in a format that is different from package to package") - automated tools won't be able to process it in a useful way.

So, I'm -1 on this.

Note that we already have a `source-repository` stanza, which looks like a more appropriate place for revision information.

/cc @dcoutts

**Comment by zilinc** [comment]
@23Skidoo I'm personally neutral on it. It doesn't stall my work. I was just asking for broader options.

**Comment by zilinc** [comment]
I have a seemingly similar problem to #1319 . I tried to generate a file alongside Paths_<pkg> from Setup.hs (due to the de facto rejection of this PR) but I need duplicate some work done in `Distribution.Simple.Build`. As far as I can see, Paths_<pkg> is generated by `writeAutogenFiles` function, whose upper level functions do the preparation, e.g. create the autogen directory. I can't think of an easy way to overwrite `writeAutogenFiles` function along. What's related to #1319 is, however, a different problem. Apart from the git revision I wanted, I'd also like to have build time info. I use Data.Time and its function `defaultTimeLocale`, which is exported from different packages before and after time-1.5, with the new one from time but the old one from old-locale. So that I'd like to achieve some conditional compilation of Setup.hs. So if I understand correctly, there's no support right now for this. Am I correct?

**Comment by 23Skidoo** [comment]
> So if I understand correctly, there's no support right now for this. Am I correct?

Sorry for getting back to you so late. We now have [setup dependencies](http://www.well-typed.com/blog/2015/07/cabal-setup-deps/).

**Comment by 23Skidoo** [comment]
I think I'll close this one, but if someone is willing to implement #1506 -- patches welcome.

**Pull request closed without merging**
