### PR TITLE
Fix checkRelocatable for deps when prefix is not subdir of pkgroot

### LINKED ISSUE #4291: Relocatable is broken because some double dots in a path are not interpreted (GHC 8.0 only)
Installing some packages as relocatable is not working. For example:

```
host ~ $ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library

host ~ $ rm -rf ~/.cabal ~/.ghc

host ~ $ cabal update
Config file path source is default config file.
Config file /tmp/cabal-bug/.cabal/config not found.
Writing default configuration to /tmp/cabal-bug/.cabal/config
Downloading the latest package list from hackage.haskell.org

host ~ $ cabal install --enable-relocatable StateVar
Resolving dependencies...
Downloading stm-2.4.4.1...
Configuring stm-2.4.4.1...
Building stm-2.4.4.1...
Installed stm-2.4.4.1
Downloading StateVar-1.1.0.4...
Configuring StateVar-1.1.0.4...
Failed to install StateVar-1.1.0.4
Build log ( /tmp/cabal-bug/.cabal/logs/StateVar-1.1.0.4.log ):
cabal: Entering directory '/tmp/cabal-tmp-22691/StateVar-1.1.0.4'
Configuring StateVar-1.1.0.4...
cabal: Library directory of a dependency:
"/tmp/cabal-bug/.ghc/x86_64-linux-8.0.1/../../.cabal/lib/x86_64-linux-ghc-8.0.1/stm-2.4.4.1-4z2NRWnB0NIIUvSJsHW0kF"
is not relative to the installation prefix:
"/tmp/cabal-bug/.cabal"
cabal: Leaving directory '/tmp/cabal-tmp-22691/StateVar-1.1.0.4'
cabal: Error: some packages failed to install:
StateVar-1.1.0.4 failed during the configure step. The exception was:
ExitFailure 1
```
The issue is that the double dots in the string `/tmp/cabal-bug/.ghc/x86_64-linux-8.0.1/../../.cabal/lib/x86_64-linux-ghc-8.0.1/stm-2.4.4.1-4z2NRWnB0NIIUvSJsHW0kF` are not interpreted before checking if `/tmp/cabal-bug/.cabal` is a prefix.

### PR DESCRIPTION
**Pull request by watashi**
Closes #4291

This can be broken when we explicitly set a prefix outside of pkgroot, even for ghc > 8.0. To repro:

```
$ cd /tmp
$ cabal get pandoc
$ cd pandoc-2.4
$ cabal sandcastle init
$ cabal install --only-dependencies --enable-relocatable --prefix=/tmp/prefix
...
Configuring blaze-markup-0.8.2.2...
cabal: Library directory of a dependency:
"/tmp/pandoc-2.4/.cabal-sandbox/../../prefix/lib/x86_64-linux-ghc-8.6.2/blaze-builder-0.4.1.0-KrFxFv3kgua3BTNMsMBadC"
is not relative to the installation prefix:
"/tmp/prefix"
```

We can fix it by simply canonicalize the path before comparing.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
OK, it's green and @christiaanb approved it, so let's go.

**Comment by 23Skidoo** [comment]
Merged, thanks! Still would be nice if a test case could be added.

**Comment by watashi** [comment]
I will figure out how to write a test case for this :-)

**Pull request merged**
