### PR TITLE
Add RequiredTypeArguments to known extensions

### PR DESCRIPTION
**Pull request by int-index**
The extension is introduced in the accepted [GHC Proposal #281](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0281-visible-forall.rst). It hasn't been implemented in GHC yet, but I think it's fine if Cabal knows about it ahead of time.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Yes, thanks a lot for the patch!

You'll have to --accept the failing test to update the hash. In general, it may be worthwhile to look at a previous commit touching this list (I think the hash is the only gotcha by I may miss something).

**Comment by int-index** [comment]
`cabal run cabal-tests -- --accept` had no effect. Is there some other way to specify `--accept`?

**Comment by ffaf1** [comment]
I suspect you need to tweak hexadecimals here:

https://github.com/haskell/cabal/blob/519d2b444b45765ecca13dd515490a6a69750a8f/Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs#L21-L33

Alas it is not picked up by `--allow`, a bit of a pain.

**Comment by ffaf1** [comment]
Also why not adding it here too

https://github.com/haskell/cabal/blob/f13a1896df55dba891d0a942dcc4b66f3643b462/editors/vim/syntax/cabal.vim#L141-L147

**Comment by int-index** [comment]
Is there something else I need to fix?

**Review by ffaf1 — APPROVED** [review]

**Comment by ffaf1** [comment]
Nope but relaunch CI (force push?) since there is a weird macos-latest failure.

**Comment by ulysses4ever** [comment]
And the author should apply the "merge me" label when they think the patch is good to merge. This will take it over to the bot. The bot will sit on it two days.

**Comment by int-index** [comment]
I have restarted the failing CI jobs a couple of times but they failed every time. The error message is the same every time:

```
Error: cabal: Could not resolve dependencies:
[__0] trying: bytestring-0.11.3.1 (user goal)
[__1] unknown package: data-array-byte (dependency of bytestring)
[__1] fail (backjumping, conflict set: bytestring, data-array-byte)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: bytestring, data-array-byte
```

I'm not entirely sure what `data-array-byte` is, seems like some sort of compatibility layer: https://hackage.haskell.org/package/data-array-byte. Admittedly, I don't see how it's related to my patch.

**Comment by Mikolaj** [comment]
Indeed, the CI failure is probably caused by a test checking out master of `bytestring` which has now changed to require another package. We are going to fix this ASAP in another PR (checking out a particular old tag), but for now let me just force-merge this PR, since the relevant tests pass. @int-index: thanks a lot!

**Comment by Mikolaj** [comment]
@mergify rebase

**Pull request merged**
