### PR TITLE
CI: fix-whitespace: show violations (verbose mode)

### PR DESCRIPTION
**Pull request by ulysses4ever**
**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
👍🏽

**Review by ffaf1 — APPROVED** [review]
Happened to me once, wondered why “verbose” was not on.

**Comment by ulysses4ever** [comment]
Thanks all!

I'm unsure about backports: do we want them or not?

**Comment by ffaf1** [comment]
Imho not necessary, backported PRs should be free of whitespace problems in any case.

**Comment by ulysses4ever** [comment]
Agreed! Thanks again!

**Pull request merged**
