### PR TITLE
Add changelog for #7279 and #8006

### PR DESCRIPTION
**Pull request by jneira**
Progress towards #8040
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [😄] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).

### CODE REVIEW

**Comment by jneira** [comment]
Maybe it deserves a more detailed description but i am not inspired right now

**Review by Mikolaj — APPROVED** [review]
10/10

**Review by robx — APPROVED** [review]

**Comment by jneira** [comment]
@Mergifyio rebase master

**Comment by Mikolaj** [comment]
CI seems to be stuck, so let's merge manually.

**Comment by Mikolaj** [comment]
More precisely, mergifyIO was stuck --- the CI job about queues.

**Pull request merged**
