### PR TITLE
Fix #6835 (instantiating a Hackage indefinite package with an inplace package doesn't work)

### LINKED ISSUE #6835: Unable to build with backpack modules from unpacked-containers package
**Describe the bug**

I have the following cabal file:

```
cabal-version:       2.0
name:                unpacked-example
version:             0.1.0.0
build-type:          Simple

library example
  default-language: Haskell2010
  hs-source-dirs: example
  exposed-modules: Int
  build-depends: base

executable unpacked-set-example
  default-language: Haskell2010
  main-is: example/Main.hs
  build-depends: base, unpacked-containers, example
  mixins: unpacked-containers (Set as Int.Set) requires (Key as Int)
```
And the following source files:

```
$ cat example/Int.hs 
module Int where

type Key = Int
```

```
$ cat example/Main.hs 
module Main where

import Int.Set

ten :: Set
ten = fromList [1..10]

main :: IO ()
main = print ten
```

I can't build it and cannot figure out what is wrong. Here is the cabal build message:

```
$ cabal v2-build
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - unpacked-containers-0 (lib with Key=unpacked-example-0.1.0.0-inplace-example:Int) (requires build)
 - unpacked-example-0.1.0.0 (exe:unpacked-set-example) (first run)
Starting     unpacked-containers-0 (lib)

Failed to build unpacked-containers-0. The failure occurred during the
configure step.
Build log (
/Users/harendra/.cabal/logs/ghc-8.8.3/npckd-cntnrs-0-8f491d38+B2PfsuvwtufFrJw0XqUoXM.log
):
Configuring library instantiated with
  Key = unpacked-example-0.1.0.0-inplace-example:Int
for unpacked-containers-0..
Warning: The package has an extraneous version range for a dependency on an
internal library: unpacked-containers -any && ==0. This version range includes
the current package but isn't needed as the current package's library will
always be used.
Error:
    The following packages are broken because other packages they depend on are missing. These broken packages must be rebuilt before they can be used.
planned package unpacked-containers-0 is broken due to missing package unpacked-example-0.1.0.0-inplace-example

cabal: Failed to build unpacked-containers-0 (which is required by
exe:unpacked-set-example from unpacked-example-0.1.0.0). See the build log
above for details.
```

**To Reproduce**

Run `cabal v2-build` with above configuration.

**Expected behavior**

cabal build should succeed or print a message which can clearly pinpoint what is wrong. I tried going through the docs as well, but could not figure out what is wrong here. Did many trial and errors as well, but no luck with compiling this example.

**System information**
 - Operating system: Mac OSX
 - cabal version: 3.2
 - ghc version: 8.8.3

### PR DESCRIPTION
**Pull request by ezyang**
Fix #6835

Fixes the bug by accurately tracking when instantiations refer to
inplace packages, and adjusting previously non-inplace packages to be
inplace when this occurs.  See comment in ProjectPlanning.hs for more
details.

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

```
~/Dev/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.5.0.0/x/cabal/build/cabal/cabal test
```

Also synthetic package tests

### CODE REVIEW

**Comment by Mikolaj** [comment]
@danidiaz: would you like to review this PR?

**Comment by ezyang** [comment]
CI failures are because I forgot to remove some notice-level debug output

**Comment by ezyang** [comment]
Now with package tests!

**Review by danidiaz — APPROVED** [review]

**Comment by Mikolaj** [comment]
Repeating from IRC:

> 17:16 < mikolaj_> on another note, we have AppVeyor CI that sometimes fails, nothing unusual, net outages, etc., e.g., here https://github.com/haskell/cabal/pull/7413
> 17:16 < mikolaj_> how do we restart AppVeyor run (I can't, apparently)?
> 17:17 < mikolaj_> why is it using cabal 2.4.1.0? Generally, what purpose does it server? Just some general Windows testing?

**Comment by ezyang** [comment]
oh wow, merge requires TWO approving reviews, intruiging

**Review by Mikolaj — APPROVED** [review]
I can't tell I understand all the subtleties here, but LGTM. Thanks a lot of the extensive notes and the test. :)

**Review by emilypi — APPROVED** [review]

**Comment by fgaz** [comment]
> [x]  Any changes that could be relevant to users have been recorded in the changelog.

I don't see the entry though? @ezyang could you add one in another pr?

**Comment by fgaz** [comment]
And this is a bugfix so:

@Mergifyio backport 3.6

**Comment by ezyang** [comment]
> I don't see the entry though? @ezyang could you add one in another pr?

Oh do we do bugfixes in changelog? I'll try to remember to do this over the weekend

**Comment by emilypi** [comment]
Yeah, we do, thanks @ezyang!

**Pull request merged**
