### PR TITLE
Conditionally omit `TemplateHaskell` from set of supported extensions

### PR DESCRIPTION
**Pull request by hvr**
This emulates what GHC>=8 will do on its own for older GHC versions.

This is particularly useful in combination with #2644 allowing the
solver to toggle flags depending on the availability of
`-XTemplateHaskell`.

For instance, cross-compilers and/or unregisterised GHC builds often
don't have TemplateHaskell support. Having support for toggling flags
based on availability of `-XTemplateHaskell` allows `cabal` to
support such environments with less manual intervention.

### CODE REVIEW

**Comment by hvr** [comment]
See also https://phabricator.haskell.org/D1484

/cc @bgamari

**Comment by phadej** [comment]
Would be nice to have a package test for that...

**Comment by 23Skidoo** [comment]
LGTM. 

@phadej 
Coming up with a test for this may be hard because you need a non-standard GHC.

**Comment by phadej** [comment]
@23Skidoo Ah indeed. Pity. Have to live without test then.

**Pull request merged**
