### PR TITLE
Refactoring installplan

### PR DESCRIPTION
**Pull request by 23Skidoo**
#2733 with conflicts resolved. Just checking that the Travis build passes. CR comments are in #2733.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
OK, should build now.

**Comment by 23Skidoo** [comment]
Added a patch making type signatures less verbose.

**Comment by 23Skidoo** [comment]
I think I'm going to merge this now. @dcoutts, if you don't like the `Generic*` names, feel free to change them.

**Comment by dcoutts** [comment]
That's great. Thanks very much.

**Pull request merged**
