### PR TITLE
D.C.Compat.Process.readProcessWithExitCode: also catch permission errors

### LINKED ISSUE #1613: cabal init failed without git installed
Package name? [default: ttt]
Package version? [default: 0.1.0.0]
Please choose a license:
- 1) (none)
  ...
  12) Other (specify)
  Your choice? [default: (none)]
  cabal: git: does not exist

Heuristics.hs
readProcessWithExitCode "git" ["config", "", ""] "" will jump out directly if createProcess fail to find the executable.

### PR DESCRIPTION
**Pull request by byorgey**
Closes #1613.  See the discussion there.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM. Feel free to merge once CI is green.

**Comment by byorgey** [comment]
Thanks.  @mention-bot is pretty cool.  Is that something that has been explicitly enabled for this repo, or is it just something github has started doing recently?

**Comment by 23Skidoo** [comment]
> Is that something that has been explicitly enabled for this repo, or is it just something github has started doing recently?

The former. See https://github.com/facebook/mention-bot#mention-bot-.

**Comment by byorgey** [comment]
Ah, I see, thanks!

**Pull request merged**
