### PR TITLE
Add strikethrough text support

### LINKED ISSUE #8216: docs: RST rendering fails for STRIKEOUT in cabal.project
5602231A-6378-4055-AA60-6A847D79393B

I wish I knew RST well enough to just submit a patch — it’s probably a one-char fix, or?..

### PR DESCRIPTION
**Pull request by ffaf1**
Closes #8216

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).

### CODE REVIEW

**Comment by ffaf1** [comment]
I had to rework some lines slightly since [nested inline markup is impossible](https://docutils.sourceforge.io/FAQ.html#is-nested-inline-markup-possible).

**Review by Mikolaj — APPROVED** [review]
I have no clue about sphinx, but if it works, it's fine.

**Comment by SilverRainZ** [comment]
Hi @ffaf1, I am the author of sphinxnotes-strike, thanks for using it.

Just FYI, [nested inline markup is possible](https://silverrainz.me/blog/sphinxnotes-comboroles.html#sphinxnotes-strike) now.

**Comment by ffaf1** [comment]
Fantastic @SilverRainZ, thanks for letting us know!

**Pull request merged**
