### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by amigalemming**
remove duplicate .docker/validate-8.6.5.dockerfile

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ffaf1 — APPROVED** [review]

**Comment by Mikolaj** [comment]
Let me ask mergify to merge this in 2 days. @amigalemming: thank you; let us know if you'd like to contribute more and could use some help, e.g., you can pick up one of the newcomer tickets or scratch your personal itch, if you have any with cabal.

**Comment by Mikolaj** [comment]
Doh, CI stopped this once again. Let me rebase...

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
I think I fixed CI (again). Let me rebase.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@amigalemming: success! thank you!

**Pull request merged**
