### PR TITLE
Generate Paths module using zinza template

### PR DESCRIPTION
**Pull request by phadej**
This breaks `absolute` and `relocatable` variants. Let me see if we have any tests for them (maybe on windows).

### CODE REVIEW

**Comment by angerman** [comment]
O_o

**Comment by phadej** [comment]
@angerman 

> O_o

?_?

**Comment by phadej** [comment]
This is a step cleaninh up the `Paths_<pkg>` module implementation, so it can be changed. Concatenating strings manually is not 2020.

**Comment by angerman** [comment]
I only read
> This breaks `absolute` and `relocatable` variants.

and was confused. I still believe the Paths module should not exist, but I'm hard pressed to offer a sensible alterntive.

**Pull request merged**
