### PR TITLE
Restore GHCJS "-build-runner" option

### LINKED ISSUE #6175: v2-test with GHCJS doesn't work
**Describe the bug**

`cabal-install` (or `Cabal`?) doesn't know how to run tests.

**To Reproduce**

Take e.g. `splitmix` package

```
$ cabal v2-test
...
cabal: Error: Could not find test program
"/code/public-haskell/splitmix/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/splitmix-0.0.3/t/examples/build/examples/examples".
Did you build the package first?
```

That's close, but one needs to do something like:

```
% node /code/public-haskell/splitmix/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/splitmix-0.0.3/t/examples/build/examples/examples.jsexe/all.js
SMGen 142593372 1604540297
```

I'm not sure how GHCJS finds `node` executable, does it just looks in the PATH?

**Expected behavior**

Tests should run.

**System informataion**
 - Operating system: Ubuntu-18.04
 - `cabal-install-3.0`, `ghcjs-8.4` from HVR's ppa:ghc and ppa:ghcjs

### LINKED ISSUE #6361: Cabal does not understand the peculiarities of ghcjs executables
A `ghcjs` "executable" is a collection of files in a subdirectory.  The subdirectory is where the normal executable would be, but it has the extension `.jsexe` and contains `all.js` among other files.  To run the program the `node` or `nodejs` interpreter is passed the path to the `all.js` file.  So suppose I try to run the cabal executable `program-version` as follows
```
$ cabal --ghcjs new-run --project client.project program-version
Resolving dependencies...
Up to date
/home/dsf/git/happstack-ghcjs/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/appraisalscribe-data-2.50/x/program-version/build/program-version/program-version: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
That is, the path `...build/foo/foo` should actually be `...build/foo/foo.jsexe/all.js`, and that path needs to be an argument to `node`.  So the actual command to run it is this:
```
$ node /home/dsf/git/happstack-ghcjs/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/appraisalscribe-data-2.50/x/program-version/build/program-version/program-version.jsexe/all.js
```
Similarly, the new-install command needs a similar change:
```
$ cabal --ghcjs new-install --project client.project program-version
$ ls -l /home/dsf/.cabal/bin/program-version
lrwxrwxrwx 1 dsf dsf 133 Nov 17 16:02 /home/dsf/.cabal/bin/program-version -> ../store/ghcjs-8.6.0.1/appraisalscribe-data-2.50-767e264c71ed2a76eace42907fa2cad47204ca13760ab010754526422c1cd733/bin/program-version
$ ls -lL /home/dsf/.cabal/bin/program-version
ls: cannot access '/home/dsf/.cabal/bin/program-version': No such file or directory
```
The actual location:
```
$ ls -lL /home/dsf/.cabal/store/ghcjs-8.6.0.1/appraisalscribe-data-2.50-767e264c71ed2a76eace42907fa2cad47204ca13760ab010754526422c1cd733/bin/
total 4
drwxr-xr-x 2 dsf dsf 4096 Nov 17 16:02 program-version.jsexe
```

### PR DESCRIPTION
**Pull request by runeksvendsen**
For all executable components (exe/test/bench), GHCJS must be passed the "-build-runner" option. Otherwise, cabal-install will throw an error of the format below:

```
Linking <executable_path_that_regular_ghc_would_produce>.jsexe [...]
[...]
cabal: Error: Could not find test program
"<executable_path_that_regular_ghc_would_produce>".
Did you build the package first?
```

Fixes #6175, fixes #6361

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

## Testing

**UPDATE: An automatic test has been added. See conversation below.**

~~I would really like to add an automatic test for this stuff, so this regression doesn't occur again. I've looked at the source code, without luck, to see if I could find where to add such a test. If someone can tell me the proper place to add this test please let me know.~~

I tested the change by running `cabal --ghcjs test` for both `cabal-install` built with and without this patch. See below for the difference in output between `cabal-unpatched` and `cabal-patched`.

```
$ cabal-unpatched --ghcjs test
...
Linking /home/rsvendsen/code/reflex-platform/tmp/call-stack/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/call-stack-0.4.0/t/spec/build/spec/spec.jsexe (Data.CallStackSpec,Example,Main,Paths_call_stack,Util)
Running 1 test suites...
cabal: Error: Could not find test program
"/home/rsvendsen/code/reflex-platform/tmp/call-stack/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/call-stack-0.4.0/t/spec/build/spec/spec".
Did you build the package first?

cabal: Tests failed for test:spec from call-stack-0.4.0.


$ cabal-patched clean


$ cabal-patched --ghcjs test
...
Linking /home/rsvendsen/code/reflex-platform/tmp/call-stack/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/call-stack-0.4.0/t/spec/build/spec/spec.jsexe (Data.CallStackSpec,Example,Main,Paths_call_stack,Util)
Running 1 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to:
/home/rsvendsen/code/reflex-platform/tmp/call-stack/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/call-stack-0.4.0/t/spec/test/call-stack-0.4.0-spec.log
1 of 1 test suites (1 of 1 test cases) passed.
```

### CODE REVIEW

**Comment by runeksvendsen** [comment]
Copying the test `PackageTests/NewBuild/CmdTest/OptionsFlag` to `PackageTests/NewBuild/CmdTest/GHCJSTmp` and adding the arguments `--verbose=3 --ghcjs --dry-run` to the `cabal v2-test` command (in [cabal.test.hs](https://github.com/haskell/cabal/blob/b9212713f8b3ec15285d2bb1ca7f17ec9d4a0046/cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/cabal.test.hs)) results in the error below.

@Mikolaj any ideas on how we can make it work without GHCJS being available?

```
$ dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-testsuite-3/build/cabal-tests/cabal-tests cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --with-cabal="./dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.6.0.0/x/cabal/build/cabal/cabal"
/Users/rune/.ghcup/ghc/8.10.4/bin/runghc-8.10.4 -- '--ghc-arg=-i' '--ghc-arg=-no-user-package-db' '--ghc-arg=-package-db' '--ghc-arg=/Users/rune/.cabal/store/ghc-8.10.4/package.db' '--ghc-arg=-package-db' '--ghc-arg=/Users/rune/Obsidian/code/cabal/dist-newstyle/packagedb/ghc-8.10.4' '--ghc-arg=-package-id' '--ghc-arg=Cabal-3.6.0.0-inplace' '--ghc-arg=-package-id' '--ghc-arg=sync-2.2.3-dcaa59d1' '--ghc-arg=-package-id' '--ghc-arg=base-4.14.1.0' '--ghc-arg=-package-id' '--ghc-arg=cabal-testsuite-3-inplace' '--ghc-arg=-package-id' '--ghc-arg=clck-0.8.2-2fe2d422' '--ghc-arg=-package-id' '--ghc-arg=exceptions-0.10.4' '--ghc-arg=-package-id' '--ghc-arg=filepath-1.4.2.1' '--ghc-arg=-package-id' '--ghc-arg=ptprs-pplctv-0.16.1.0-afac325a' '--ghc-arg=-package-id' '--ghc-arg=process-1.6.9.0' '--ghc-arg=-package-id' '--ghc-arg=transformers-0.5.6.2' cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --builddir /Users/rune/Obsidian/code/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-testsuite-3 cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --with-cabal ./dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.6.0.0/x/cabal/build/cabal/cabal
# cabal v2-test
+ /Users/rune/Obsidian/code/cabal/./dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.6.0.0/x/cabal/build/cabal/cabal v2-test '-vverbose +markoutput +nowrap' --builddir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/./dist --project-file cabal.project -j1 '--test-option=1' '--test-options="2 3"' '--test-option=4' '--test-options="5 6"' '--verbose=3' --ghcjs --dry-run
File monitor 'config' changed: first run
Project settings changed, reconfiguring...
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist/cache
this build was affected by the following (project) config files:
-
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.project
File monitor 'improved-plan' changed: first run
File monitor 'elaborated-plan' changed: first run
File monitor 'compiler' changed: first run
Compiler settings changed, reconfiguring...
/Users/rune/.ghcup/bin/ghc --numeric-ghcjs-version
/Users/rune/.ghcup/bin/ghc returned ExitFailure 1 with error message:
ghc: unrecognised flag: --numeric-ghcjs-version

Usage: For basic information, try the `--help' option.
Warning: cannot determine version of /Users/rune/.ghcup/bin/ghc :
""

cabal: The program 'ghcjs' version >=0.1 is required but the version of
/Users/rune/.ghcup/bin/ghc could not be determined.

cabal.test.hs: Command /Users/rune/Obsidian/code/cabal/./dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.6.0.0/x/cabal/build/cabal/cabal v2-test '-vverbose +markoutput +nowrap' --builddir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/./dist --project-file cabal.project -j1 '--test-option=1' '--test-options="2 3"' '--test-option=4' '--test-options="5 6"' '--verbose=3' --ghcjs --dry-run failed.
Output:
File monitor 'config' changed: first run
Project settings changed, reconfiguring...
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist
creating
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.dist/work/dist/cache
this build was affected by the following (project) config files:
-
/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.project
File monitor 'improved-plan' changed: first run
File monitor 'elaborated-plan' changed: first run
File monitor 'compiler' changed: first run
Compiler settings changed, reconfiguring...
/Users/rune/.ghcup/bin/ghc --numeric-ghcjs-version
/Users/rune/.ghcup/bin/ghc returned ExitFailure 1 with error message:
ghc: unrecognised flag: --numeric-ghcjs-version

Usage: For basic information, try the `--help' option.
Warning: cannot determine version of /Users/rune/.ghcup/bin/ghc :
""

cabal: The program 'ghcjs' version >=0.1 is required but the version of
/Users/rune/.ghcup/bin/ghc could not be determined.



cabal-tests: callProcess: /Users/rune/.ghcup/ghc/8.10.4/bin/runghc-8.10.4 "--" "--ghc-arg=-i" "--ghc-arg=-no-user-package-db" "--ghc-arg=-package-db" "--ghc-arg=/Users/rune/.cabal/store/ghc-8.10.4/package.db" "--ghc-arg=-package-db" "--ghc-arg=/Users/rune/Obsidian/code/cabal/dist-newstyle/packagedb/ghc-8.10.4" "--ghc-arg=-package-id" "--ghc-arg=Cabal-3.6.0.0-inplace" "--ghc-arg=-package-id" "--ghc-arg=sync-2.2.3-dcaa59d1" "--ghc-arg=-package-id" "--ghc-arg=base-4.14.1.0" "--ghc-arg=-package-id" "--ghc-arg=cabal-testsuite-3-inplace" "--ghc-arg=-package-id" "--ghc-arg=clck-0.8.2-2fe2d422" "--ghc-arg=-package-id" "--ghc-arg=exceptions-0.10.4" "--ghc-arg=-package-id" "--ghc-arg=filepath-1.4.2.1" "--ghc-arg=-package-id" "--ghc-arg=ptprs-pplctv-0.16.1.0-afac325a" "--ghc-arg=-package-id" "--ghc-arg=process-1.6.9.0" "--ghc-arg=-package-id" "--ghc-arg=transformers-0.5.6.2" "cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs" "--builddir" "/Users/rune/Obsidian/code/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-testsuite-3" "cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs" "--with-cabal" "./dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.6.0.0/x/cabal/build/cabal/cabal" (exit 1): failed
```

**Comment by Mikolaj** [comment]
We can tell we expect the test to fail and it'd be fine, but I see the problem is that it fails too early, right? Before `-build-runner` appears in the log?

Perhaps hack by specifying a compiler that is really a dummy shell script that ignores all flags? That would get us past the error in the log, but no idea how far along.

**Comment by runeksvendsen** [comment]
> We can tell we expect the test to fail and it'd be fine, but I see the problem is that it fails too early, right? Before `-build-runner` appears in the log?

Exactly.

> Perhaps hack by specifying a compiler that is really a dummy shell script that ignores all flags? That would get us past the error in the log, but no idea how far along.

I tried this initially by placing the following in `fake-ghcjs.sh`

```bash
#!/usr/bin/env bash

if [ "$1" == "--numeric-ghcjs-version" ]; then
   ghc --numeric-version
else
   ghc "$@"
fi
```

so that it responds to both `--numeric-ghcjs-version` and `--numeric-version`:

```
$ ./fake-ghcjs.sh --numeric-ghcjs-version
8.10.4
$ ./fake-ghcjs.sh --numeric-version
8.10.4
```

and running the test like so:

```
cabal-tests cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --with-cabal=cabal-install-3.6.0.0 --with-ghc fake-ghcjs.sh
```

but this fails with the error:

```
/Users/rune/.ghcup/ghc/8.10.4/bin/runghc-8.10.4 -- '--ghc-arg=-i' '--ghc-arg=-no-user-package-db' '--ghc-arg=-package-db' '--ghc-arg=/Users/rune/.cabal/store/ghc-8.10.4/package.db' '--ghc-arg=-package-db' '--ghc-arg=/Users/rune/Obsidian/code/cabal/dist-newstyle/packagedb/ghc-8.10.4' '--ghc-arg=-package-id' '--ghc-arg=Cabal-3.6.0.0-inplace' '--ghc-arg=-package-id' '--ghc-arg=sync-2.2.3-dcaa59d1' '--ghc-arg=-package-id' '--ghc-arg=base-4.14.1.0' '--ghc-arg=-package-id' '--ghc-arg=cabal-testsuite-3-inplace' '--ghc-arg=-package-id' '--ghc-arg=clck-0.8.2-2fe2d422' '--ghc-arg=-package-id' '--ghc-arg=exceptions-0.10.4' '--ghc-arg=-package-id' '--ghc-arg=filepath-1.4.2.1' '--ghc-arg=-package-id' '--ghc-arg=ptprs-pplctv-0.16.1.0-afac325a' '--ghc-arg=-package-id' '--ghc-arg=process-1.6.9.0' '--ghc-arg=-package-id' '--ghc-arg=transformers-0.5.6.2' cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --builddir /Users/rune/Obsidian/code/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-testsuite-3 cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs --with-cabal cabal-install-3.6.0.0 --with-ghc fake-ghcjs.sh
Warning: cannot determine version of fake-ghcjs.sh :
""
cabal.test.hs: dieVerbatim: user error (cabal.test.hs: The program 'ghc' version >=7.0.1 is required but the version
of fake-ghcjs.sh could not be determined.
)
cabal-tests: callProcess: /Users/rune/.ghcup/ghc/8.10.4/bin/runghc-8.10.4 "--" "--ghc-arg=-i" "--ghc-arg=-no-user-package-db" "--ghc-arg=-package-db" "--ghc-arg=/Users/rune/.cabal/store/ghc-8.10.4/package.db" "--ghc-arg=-package-db" "--ghc-arg=/Users/rune/Obsidian/code/cabal/dist-newstyle/packagedb/ghc-8.10.4" "--ghc-arg=-package-id" "--ghc-arg=Cabal-3.6.0.0-inplace" "--ghc-arg=-package-id" "--ghc-arg=sync-2.2.3-dcaa59d1" "--ghc-arg=-package-id" "--ghc-arg=base-4.14.1.0" "--ghc-arg=-package-id" "--ghc-arg=cabal-testsuite-3-inplace" "--ghc-arg=-package-id" "--ghc-arg=clck-0.8.2-2fe2d422" "--ghc-arg=-package-id" "--ghc-arg=exceptions-0.10.4" "--ghc-arg=-package-id" "--ghc-arg=filepath-1.4.2.1" "--ghc-arg=-package-id" "--ghc-arg=ptprs-pplctv-0.16.1.0-afac325a" "--ghc-arg=-package-id" "--ghc-arg=process-1.6.9.0" "--ghc-arg=-package-id" "--ghc-arg=transformers-0.5.6.2" "cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs" "--builddir" "/Users/rune/Obsidian/code/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-testsuite-3" "cabal-testsuite/PackageTests/NewBuild/CmdTest/GHCJSTmp/cabal.test.hs" "--with-cabal" "cabal-install-3.6.0.0" "--with-ghc" "fake-ghcjs.sh" (exit 1): failed
```

**Comment by runeksvendsen** [comment]
@Mikolaj I've added a test. The biggest downside is that the failing case doesn't print any helpful output. Specifically, I _don't_ see the following type of output in case the test fails, and I'm not sure why:

```
cabal.test.hs:  expected: [...]
CallStack (from HasCallStack):
  assertOutputContains, called at cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.test.hs:17:5 in main:Main
```

**Comment by Mikolaj** [comment]
That's strange. Does removing `DoNotRecord` help?

**Comment by runeksvendsen** [comment]
Ah! I see what happens. Although I'm not sure why it happens, exactly.

When patched/fixed cabal-install is used, the `test`/`run`/`bench` commands fail, with this error:

```
cabal: Error: Could not find test program "/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/t/ghcjs-test/build/ghcjs-test/ghcjs-test". Did you build the package first?
```

as expected and required by the test (because I'm wrapping `cabal'` in `fails`).

However, when non-patched/broken cabal-install is used, the `test`/`run`/`bench` commands _succeed_:

```
Test suite ghcjs-test: PASS
Test suite logged to: /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/t/ghcjs-test/test/BuildRunner-1.0-ghcjs-test.log
```

which makes the test fail.

So I guess the problem is that `fails` isn't very good at communicating that a test failed because a step succeeded when it shouldn't.

**Comment by Mikolaj** [comment]
Why this: "when patched/fixed cabal-install is used, the test/run/bench commands fail"?

**Comment by runeksvendsen** [comment]
> Why this: "when patched/fixed cabal-install is used, the test/run/bench commands fail"?

It fails because if we run regular GHC with the `-build-runner` argument it fails with `ghc: unrecognised flag: -build-runner`. I have tried to remove the `-build-runner` argument from the arguments passed to GHC by `fake-ghcjs.sh` without success. Running GHC from within `fake-ghcjs.sh` using `ghc "${@//-build-runner/}"` _does_ seem to remove the `-build-runner` argument, but it results in this failure:

```
ld: can't map file, errno=22 file '.' for architecture x86_64
```

NB: these are the arguments passed to GHC that results in the above error:

```
--make -fbuilding-cabal-package -O -static -outputdir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -odir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -hidir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -stubdir /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -i -i/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -i. -i/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/autogen -i/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/global-autogen -I/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/autogen -I/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/global-autogen -I/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench-tmp -optP-include -optP/Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/autogen/cabal_macros.h -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/home/.cabal/store/ghcjs-8.6.5/package.db -package-db /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/packagedb/ghcjs-8.6.5 -package-db /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/package.conf.inplace -package-id base-4.12.0.0 -XHaskell2010 ./BuildRunner.hs -o /Users/rune/Obsidian/code/cabal/cabal-testsuite/PackageTests/GHCJS/BuildRunner/cabal.dist/work/./dist/build/x86_64-osx/ghcjs-8.6.5/BuildRunner-1.0/b/ghcjs-bench/build/ghcjs-bench/ghcjs-bench
```

This is how the modified `fake-ghcjs.sh` looks like:

```bash
BUILD_RUNNER="-build-runner"
MAGIC_STRING="SUCCESS! GHCJS was invoked with '$BUILD_RUNNER' option"

if [ "$1" == "--numeric-ghcjs-version" ]; then
   ghc --numeric-version
elif [ "$1" == "--numeric-ghc-version" ]; then
   ghc --numeric-version
elif [[ "$*" == *$BUILD_RUNNER* ]]; then
   echo "$MAGIC_STRING"
   ghc "${@//$BUILD_RUNNER/}"
else
   ghc "$@"
fi
```

**Comment by runeksvendsen** [comment]
Looks like the above error is a known issue on OSX: https://bz.apache.org/netbeans/show_bug.cgi?id=267371

**Comment by Mikolaj** [comment]
OK, great, I think the test is good enough and CI is now green.

**Review by Mikolaj — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Even if it is possible the latest GHCJS doesn't need `-build-runner`, that should be addressed with some version-specific logic. For now, reverting to the way it was before for GHCJS 8.10 (not ancient) is fine.

**Pull request merged**
