### PR TITLE
Put hie files in subdirectory of extra-compilation-artifacts

### PR DESCRIPTION
**Pull request by nlander**
@bgamari Does this solve the issue you see about a cluttered extra-compilation-artifacts directory?

**This PR modifies `cabal` behaviour**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

Bonus points for added automated tests!

### CODE REVIEW

**Comment by nlander** [comment]
I'm not sure why Validate is failing. I have tried replicating the failure on my machine and I was unsuccessful.

**Comment by geekosaur** [comment]
See https://github.com/haskell/cabal/pull/9241#issuecomment-1712977557

**Comment by bgamari** [comment]
Yes, thanks @nlander !

**Review by bgamari — APPROVED** [review]

**Comment by Mikolaj** [comment]
I'm re-running the failed CI jobs, since the failure is probably due to the unix package breakage.

**Comment by nlander** [comment]
I'm not sure why the docs are failing to build. Any suggestions?

**Review by andreabedini — APPROVED** [review]

**Comment by ulysses4ever** [comment]
This PR currently has 7 commits. It needs either a cleanup or, at least, the squash+merge label instead of merge-me.

**Comment by andreabedini** [comment]
I rebased the PR on top of master.

**Comment by andreabedini** [comment]
Uhm, now something is failing and I am not sure what :-/

**Comment by Mikolaj** [comment]
And now "[Validate macos-latest ghc-8.6.5](https://github.com/haskell/cabal/actions/runs/6242381181/job/16956276623?pr=9244#logs)" seems to be stuck (50m at Validate build). Let me cancel it and rerun.

**Pull request merged**
