### PR TITLE
Allow hashable-1.5

### LINKED ISSUE #10177: Allow hashable-1.5
Currently restricted by 
https://github.com/haskell/cabal/blob/1837262b1dd533eaf0b4ddbc6c373b9c39351e5d/cabal-install/cabal-install.cabal#L234

### PR DESCRIPTION
**Pull request by geekosaur**
Fixes #10177

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions). —N/A

### CODE REVIEW

**Comment by ulysses4ever** [comment]
CI still picks up 1.4.7: 
https://github.com/haskell/cabal/actions/runs/9802518842/job/27067339750?pr=10178#step:13:117 

In theory, someone should build under the constraint ==1.5 + allow-newer. Was there a problem with the approach described at the bottom of https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#hackage-revisions ? Would be good to figure it out...

**Comment by geekosaur** [comment]
Well. This is going to be fun: we validate with ghc 9.4.8, but the new `hashable` requires the `base` from 9.6.

**Comment by ulysses4ever** [comment]
Right, this was the problem last time we tried the manual run. Back then the static build succeeded (it's Independent of others so it may succeed even if others fail) so that was an evidence that this is a viable version bump. But in this case it will also fail because its GHC is older than 9.6 I think?

**Comment by geekosaur** [comment]
It did fail, yes, and the build log confirmed it was using ghc 9.4.8.

**Comment by geekosaur** [comment]
Local validate fails:
```
Integration tests (internal)
  Regression tests
    program options scope all:                 FAIL (1.30s)
      tests/IntegrationTests2.hs:1560:
      q
      expected: Just ["-fno-full-laziness"]
       but got: Just ["-haddock"]
      Use -p '/program options scope all/' to rerun this test only.
    program options scope local:               FAIL (1.25s)
      tests/IntegrationTests2.hs:1585:
      q
      expected: Just ["-fno-full-laziness"]
       but got: Just ["-haddock"]
      Use -p '/program options scope local/' to rerun this test only.
    program options scope specific:            FAIL (1.27s)
      tests/IntegrationTests2.hs:1610:
      q
      expected: Nothing
       but got: Just ["-haddock"]
      Use -p '/program options scope specific/' to rerun this test only.
```
I don't know how much of this is because I have `documentation: True` in my `~/.config/cabal/config`, but that's never caused problems before. Or if maybe it's related to https://github.com/haskell/cabal/pull/10163 somehow, or some other PR affecting `haddock`.

**Comment by ulysses4ever** [comment]
> I don't know how much of this is because I have documentation: True in my ~/.config/cabal/config, but that's never caused problems before.

Well, it's cheap to check this guess, isn't it? I'd do that. It's not clear what to do if it's true, but that would fill in one bit of information for the fitire investigation.

**Comment by geekosaur** [comment]
Indeed, disabling `documentation: True` made the test pass. I presume it needs to specify its own cabal configuration, as several other tests do.

**Comment by ulysses4ever** [comment]
Mm, does it only fail with this patch about `hashable-1.5`? It's pretty confusing...

**Comment by geekosaur** [comment]
I doubt it, I just don't run local validates that often and last time I did I'd disabled documentation because it was crashing cabal-install HEAD with an internal assert.

**Comment by ulysses4ever** [comment]
ah, good

**Comment by geekosaur** [comment]
And confirmed, it also fails on `master` with `documentation: True`. I'll look into making `IntegrationTests2` use its own cabal config so it's not affected by the local environment.

**Comment by geekosaur** [comment]
Mrf. It already plays games with the cabal config.

**Comment by ulysses4ever** [comment]
@geekosaur any particular reason this one was closed?

**Comment by ulysses4ever** [comment]
The battle goes on in https://github.com/haskell/cabal/pull/10244

**Pull request closed without merging**
