### PR TITLE
[WIP] Always reconfigure automatically

### PR DESCRIPTION
**Pull request by ttuegel**
This is a work-in-progress preview of my solution to #2214. 

Already implemented:
- Cabal saves the arguments to `configure` in `dist/setup-config-args` in a version-independent way.
- A new command, `setup reconfigure`, that calls configure with the last arguments used. It can also take additional arguments and `mappend` them to the command line.
- Whenever `dist/setup-config` is outdated, `reconfigure` is automatically called.
- As a side effect, `setup test` and `setup bench` reconfigure and rebuild as necessary.

Not yet implemented:
- Additional tests
- Replacing cabal-install's own reconfigure logic with this one.
- Better interoperability for cabal-install with external Setup programs

Again, this is a work-in-progess, please do not merge yet.

### CODE REVIEW

**Comment by BardurArantsson** [comment]
I may have missed something *and* I haven't looked through much of the code, but I must say that I think that we should really be aiming for a more *stateless* approach (over all) such as #2631 instead of trying to fix these state-induced bugs. I'm well aware that this may be controversial.

It looks like some these commits could be useful on their own in terms of advancing the state of the code base independently of this partiular PR/Issue. Is that right?

(Obviously, I don't have any authority on the project, I just wanted to offer my opinion.)

**Comment by ttuegel** [comment]
> I may have missed something and I haven't looked through much of the code, but I must say that I think that we should really be aiming for a more stateless approach (over all) such as #2631 instead of trying to fix these state-induced bugs. I'm well aware that this may be controversial.

Yes, I agree we should aim for statelessness to the degree possible, and that's what I'm really doing here. Let me elaborate on my philosophy of state. There are two sources of state, Cabal and the surrounding system (OS, GHC, foreign libraries, ...). The former should introduce as little state as possible. The latter is inherently stateful and we need to query that state from time to time. These queries are expensive, and the environment only changes slowly, so it is appropriate to cache these queries. Furthermore, it makes sense to build the cache of environment data up-front rather than on-the-fly: you may do work that is not required, but that's preferable to getting half-way through compilation to find that `ar` doesn't work (for example). That's the approach I'm taking: make Cabal as stateless as possible, while still dealing with the state of the environment.

> It looks like some these commits could be useful on their own in terms of advancing the state of the code base independently of this partiular PR/Issue. Is that right?

Yes, I'm cleaning things up as I go along.

**Comment by BardurArantsson** [comment]
Kewl! :)

**Comment by 23Skidoo** [comment]
@ttuegel What's the status of this? I'm going to create the 1.24 branch soon, do you want this to go in?

**Comment by ttuegel** [comment]
Yes, I think I can finish this over the weekend.

**Comment by 23Skidoo** [comment]
Nice!

**Comment by ttuegel** [comment]
I can't have this finished in time for the next release; it requires more extensive changes to cabal-install than I previously believed.

**Comment by 23Skidoo** [comment]
OK, noted.

**Comment by dcoutts** [comment]
@ttuegel perhaps we should confer here on how to include these things in the nix-local-build branch. In that branch I do all the state tracking at the cabal-install level, so at the package level, nothing within Cabal at the component level.

**Comment by ttuegel** [comment]
> In that branch I do all the state tracking at the cabal-install level, so at the package level, nothing within Cabal at the component level.

Which state tracking are we talking about? All this does is remember what arguments `configure` was called with. (I think it should also remember environment variables, but I haven't done that yet.) Since `cabal configure` and `Setup configure` take different arguments, I plan to save those states separately, but I haven't touched cabal-install yet.

There is one thing holding me back from finishing this: I need to change `SetupWrapper` in cabal-install. I need control to be inverted with respect to its current arrangement; I need the version of Cabal being used in the wrapper before I determine which commands to run. In its current incarnation, it will only let me use the version to determine the flags passed to the command, not the actual command itself.

**Comment by 23Skidoo** [comment]
@ttuegel 
BTW, I'm actually considering implementing something similar for #3138. Basically, I want to make `cabal configure` save the arguments it was called with (probably in `~/.cabal/config` format) under `dist`, so that in the `onNoBuildConfig` branch of `reconfigure` we'd know how to invoke the setup script and whether `-w` was used.

**Comment by ezyang** [comment]
Since this is self-marked as WIP, I'm going to close the PR for now. Please open a new one if you make more progress / need to RFC more stuff!

**Pull request closed without merging**
