### PR TITLE
Revert #3639 (Don't pass -package-db and -package flags to --abi-hash)

### PR DESCRIPTION
**Pull request by andreabedini**
With ghc>=9.6 `ghc --abi-hash` initialises the plugins so it will fail
if a cabal file specifies `ghc-options: -fplugin=Foo`.

### CODE REVIEW

**Comment by Mikolaj** [comment]
This (partially or fully?) fixes #9375.

**Comment by hamishmack** [comment]
It looks like this reverts it in `GHCJS.hs` instead of `GHC.hs`.  Probably can't hurt to revert it in both.

**Review by mpickering — APPROVED** [review]
Approve, but please squash.

**Review by geekosaur — APPROVED** [review]

**Comment by Mikolaj** [comment]
I agree this is a non-intrusive bugfix and it could go into cabal 3.10.3. Let me start backporting so that the release manager can decide.

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Comment by Mikolaj** [comment]
Uh-oh, conflicts, as usual.

**Pull request merged**
