### PR TITLE
Remove code duplication and unify definition of 'trim' function.

### LINKED ISSUE #7744: The seven definitions of `trim`
The sources of `cabal-install` have three equivalent definitions of `trim`:

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/cabal-install/src/Distribution/Client/Init/Utils.hs#L206-L209

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/cabal-install/src/Distribution/Client/Upload.hs#L231-L234

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/cabal-install/src/Distribution/Client/HttpUtils.hs#L892-L895

More are in the `Cabal` library:

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/Cabal/src/Distribution/FieldGrammar/Parsec.hs#L274-L275

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/Cabal/src/Distribution/FieldGrammar/Parsec.hs#L394-L395

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/Cabal/src/Distribution/FieldGrammar/FieldDescrs.hs#L117-L118

https://github.com/haskell/cabal/blob/69dbf5415e341616999fcd1ddb97234ab6793aa9/Cabal/src/Distribution/Simple/Configure.hs#L1594

### PR DESCRIPTION
**Pull request by kczulko**
Attempt to fix #7744 .

That's my first ever cabal PR so I somehow don't know what I'm doing. Just picked up first `good-first-issue` because I've found this https://twitter.com/bkmlep/status/1432474203245015040

`Distribution.Utils.String` sounds like a good place for `trim` but I had to expose this module unfortunately. 

This the situation after my change:
image

Any advice or criticism fully welcomed!

Karol

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by Mikolaj** [comment]
The CI failures seems to be caused by github upgrading to GHC 9.2.1. We'll have to fix our CI.

**Comment by Mikolaj** [comment]
Please kindly rebase and the two CI failures should be gone.

**Review by jneira — APPROVED** [review]
LGTM, nice clean up, Thanks!

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by fgaz** [comment]
Do we add @since annotations now or on release?

**Comment by Mikolaj** [comment]
It seems we do:

    Cabal/src/Distribution/Version.hs:-- @since 3.6.0.0

Not sure about this particular case, because the function was available long before (though from different places).

Anyway, it makes sense to add them ASAP, because we are on fire and the world is falling when we release.

**Comment by kczulko** [comment]
@Mikolaj 
How can I obtain the next release version in order to add `@since` label?

**Comment by Mikolaj** [comment]
Oh, I forgot not all people are relaxed regarding time travel. It will be 3.8.

**Pull request merged**
