### PR TITLE
allow glob matches of the form dir/**/FileNoExtension

### PR DESCRIPTION
**Pull request by gbaz**
Resolves https://github.com/haskell/cabal/issues/5883

* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] Tests

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by jneira** [comment]
@MergifyIO rebase master

**Comment by jneira** [comment]
@Mergifyio rebase master

**Comment by gbaz** [comment]
Tests, changelog, docs done. ready for review and merge.

**Review by emilypi — APPROVED** [review]

**Pull request merged**
