### PR TITLE
solver: Prevent ghc-internal from being reinstalled (see #10087)

### PR DESCRIPTION
**Pull request by adamgundry**
GHC 9.10 ships with a new wired-in package, `ghc-internal`, which cannot be reinstalled. This commit prevents `cabal-install` from attempting it. See #10087.

It would be good to include this alongside GHC 9.10 support, if possible.

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

## QA Notes

Attempting to build a package called `ghc-internal` that has no dependencies should result in a dependency solving error "constraint from non-reinstallable package requires installed instance".

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]

**Review by grayjay — APPROVED** [review]

**Comment by Mikolaj** [comment]
CI has been broken and is now fixed, so let me rebase to restart it with the fixes included.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Comment by ulysses4ever** [comment]
We missed a changelog entry on this PR, and this is a user-visible change. We should strive to do better next time.

**Pull request merged**
