### PR TITLE
Disregard occurrences of "." while backing up

### LINKED ISSUE #7806: cabal init crashes with `--source-dir=.`
```
$ cabal init --lib --source-dir=.
```
After answering a long list of questions (like when you just want a Burger in an American restaurant), `cabal init` crashes when apparently trying to create the current directory:
```
Creating LICENSE...
Creating file LICENSE...
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: invalid argument (Invalid argument)
```

Related question: Does `cabal init` allow you to cabalize an existing code base?  (Does not seem so, from the error message.)

UPDATE: This seems to be a regression in 3.6.  `cabal-3.4 init` does not crash, but gives me a `.cabal` file.
CORRECTION: No, this is only a regression on `master`.  Version 3.6.2 still is correct.

### PR DESCRIPTION
**Pull request by ptkato**
Fixes #7806.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Is it easy to add the offending example as a test? I guess we don't need a changelog, because in 3.8 we both introduce the bug and fix it?

**Review by Mikolaj — APPROVED** [review]

**Comment by ptkato** [comment]
It is, I'll add it as a test; also that's how I've been dealing with changelogs, since the feature + the bugfix will be in the same bag.

**Review by andreasabel — DISMISSED** [review]
Please can we make it a habit that fixes come with a regression test?

**Comment by Mikolaj** [comment]
A compromise we might have is to create a new PR that extend the testing framework and adds the test (marked as failing) and afterwards we could rebase this PR and see that the test passes (and unmark it). Any volunteers?

**Comment by ptkato** [comment]
@Mikolaj, uh, I volunteer, though I intended to proceed like that anyway.

**Comment by Mikolaj** [comment]
> @Mikolaj, uh, I volunteer, though I intended to proceed like that anyway.

Great minds think alike. :)

But I'm just confirming here, in particular for Andreas, who is not on Matrix/IRC, so didn't hear our conversation about this.

**Comment by ptkato** [comment]
Okay, the test is now in place.

**Comment by Mikolaj** [comment]
@andreasabel: I know you are busy right now and I think your feedback has been addressed, so if you don't object (in time), I will take the liberty of dismissing your review block. But we would love to hear any fresh feedback, of course. :)

**Comment by ptkato** [comment]
@Mikolaj, @andreasabel, I believe this is good to go, yes?

**Comment by Mikolaj** [comment]
Yes, it is, but we need one more review.

**Review by tchoutri — APPROVED** [review]

**Review by Kleidukos — APPROVED** [review]

**Comment by Mikolaj** [comment]
@tchoutri, @Kleidukos: thank you! Let's get this beast merged.

**Pull request merged**
