### PR TITLE
Build release archives (and validate) with GHC 9.2.3

### LINKED ISSUE #8271: Build cabal releases with GHC 9.2
See https://github.com/haskell/cabal/issues/8208#issuecomment-1175869060.

I suppose changing GHC_VERSION in .gitlab-ci.yml would be enough to effect the change.

### PR DESCRIPTION
**Pull request by Mikolaj**
Fixes #8271.

Do we need this in a changelog? I guess not, just as we don't file CI changes? Though this one is user-visible, namely for the users of our binary archives.

### CODE REVIEW

**Review by ffaf1 — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]
As it is user-visible (or, at least, user-sensible), I’d think changelog may make sense. But I defer to your judgement. I am also wondering how possible that this switch breaks something. If it will, though, it will probably be subtle, and a changelog will hardly help.

**Comment by Mikolaj** [comment]
@hasufell: do I read it right that GHC 9.2.3 is not available in ghcup for [build-armv7-linux-deb10](https://gitlab.haskell.org/haskell/cabal/-/jobs/1105390) and [build-i386-linux-alpine](https://gitlab.haskell.org/haskell/cabal/-/jobs/1105384) at

https://gitlab.haskell.org/haskell/cabal/-/pipelines/54257

but GHC 8.10.7 is at

https://gitlab.haskell.org/haskell/cabal/-/pipelines/52918

? Why so? What do I need to tweak?

**Comment by hasufell** [comment]
> @hasufell: do I read it right that GHC 9.2.3 is not available in ghcup for [build-armv7-linux-deb10](https://gitlab.haskell.org/haskell/cabal/-/jobs/1105390) and [build-i386-linux-alpine](https://gitlab.haskell.org/haskell/cabal/-/jobs/1105384) at
> 
> https://gitlab.haskell.org/haskell/cabal/-/pipelines/54257
> 
> but GHC 8.10.7 is at
> 
> https://gitlab.haskell.org/haskell/cabal/-/pipelines/52918
> 
> ? Why so? What do I need to tweak?

For armv7, there are simply no official bindists: https://downloads.haskell.org/~ghc/9.2.3/

For i386 alpine, I've been trying to get official bindists since over a year: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5213

Before, I built them manually. I won't do that anymore. 

So both is up to GHC developers.

**Comment by Mikolaj** [comment]
@hasufell: thank you. In that case, I'm merging and backporting.

@bgamari: is there a chance for GHC 9.2.3 on armv7 and i386 alpine? If not, GHC 9.2.4?

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.8

**Comment by bgamari** [comment]
> @hasufell: thank you. In that case, I'm merging and backporting.
> 
> @bgamari: is there a chance for GHC 9.2.3 on armv7 and i386 alpine? If not, GHC 9.2.4?

Indeed we can try for 9.2.4. However, I do recall running into toolchain trouble last time I attempted to build an ARMv7 release binary distribution.

I'm trying again to introduce i386/Alpine support in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6983.

**Comment by bgamari** [comment]
A quick update here:

 * I am working on fixing ARMv7. Unfortunately, it is a bit tricky since it is remarkably hard to find a linker implementation for ARMv7 that isn't broken in one way or another. See https://gitlab.haskell.org/ghc/ghc/-/issues/21875
 * I am not optimistic about i386/Alpine; I have fixed the first issue I ran into (our inability to resolve the `_GLOBAL_OFFSET_TABLE_` symbol in the RTS linker). However, I quickly ran into a second issue: it appears that `gcc` produces relocations that the linker doesn't approve of when building a fully-static executable. I suspect this is because we are forced to compile with `-fPIC` to ensure that the produced objects are loadable at runtime. Sadly, it's not totally clear what to do about this.

**Pull request merged**
