### PR TITLE
Handle SPDX licences starting with a digit

### PR DESCRIPTION
**Pull request by ffaf1**
cabal has a devscript that parses a json file (containing SPDX licences) and returns a number of of Haskell data constructors.

There have been problems when the SPDX short identifier starts with a digit (e.g. “0BSD”), as that would generate an data constructor starting with a digit, which is not valid Haskell. The way to handle such occourrences was in an ad-hoc basis.

This patch prepends `N_` to the beginning of every SPDX licence starting with a digit, future-proofing the script.

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] n/a ~[Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.~
* [x] I don't think this can have meaningful tests ~~Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)~~

---

This has not been done in #10341 not to incour in bugs or problems during release.

The patch is very simple but not trivial (we are retroactively changing some data constructors). Voice any concerns!

This should not be merged before 3.14 is released.

~This should not need backbort.~ ~It needs a backport (specificaly: the changelog files) since it *will* case breaking changes to a datatype.~ No need for backport, the changelog files will just be picked normally during next release.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]
Does `NN` have any precedent? I'm surprised it's not just `N`, for example...

**Comment by ffaf1** [comment]
> Does NN have any precedent? I'm surprised it's not just N, for example...

Any string that is short/recognizeable enough and does not clash is ok. I will change it to `N_`.

**Comment by ffaf1** [comment]
@Kleidukos we decided to postpone this after the release.

What is your opinion now? I remember you had some doubts about this having to involve the parser, but I forgot the specifics.

**Comment by Kleidukos** [comment]
My opinion was "let's not rush the modification of the SPDX generator, because it will fail us when we need to use it for lib:Cabal 3.14". Now the modification window is open and will close before 3.16 when we will have more urgent problems.

**Pull request merged**
