### PR TITLE
sync `validate.yml` with `master`

### PR DESCRIPTION
**Pull request by geekosaur**
Too many backports in the wrong order = mayhem

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by geekosaur** [comment]
I think I need to patch this up a bit

**Comment by geekosaur** [comment]
Fun. Windows had an unexpected pass due apparently to autotools (or possibly `%TMP%` being set). Reverted those until the relevant PR is backported (if ever).

**Comment by geekosaur** [comment]
Does anyone familiar with Macs know why ~all the Mac tests are dying with
```
*** Exception: /Users/runner/work/cabal/cabal/dist-newstyle-validate-ghc-9.10.1/build/x86_64-osx/ghc-9.10.1/cabal-testsuite-3/build/setup/setup: createProcess: execve: does not exist (No such file or directory)
```
?

**Comment by geekosaur** [comment]
`cabal-tests` hates AArch64 for some reason. Presumably one of @jasagredo's PRs fixes it, since it works on `master`, but I'm not going to fight with it right now.

**Review by Mikolaj — APPROVED** [review]

**Review by Kleidukos — APPROVED** [review]

**Pull request merged**
