### PR TITLE
Change travis dist: trusty -> xenial

### PR DESCRIPTION
**Pull request by phadej**
Fingers crossed

### CODE REVIEW

**Comment by dwijnand** [comment]
Btw, you could add https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing to be notified that, for example, this PR is green in Travis CI, but hasn't finished running the remaining `allow_failures` jobs.

**Comment by phadej** [comment]
@dwijnand yeah, let's add that to `.travis.yml`, do you mind making a PR?

**Comment by dwijnand** [comment]
https://github.com/haskell/cabal/pull/6352

**Comment by phadej** [comment]
backported to 3.0 branch

**Pull request merged**
