### PR TITLE
Ensure that OS X framework headers are in include path

### LINKED ISSUE #2689: Include headers directory of Mac framework
In https://github.com/phaazon/al/pull/6 I noticed that including a framework on OS X like

```
frameworks: OpenAL
```

does not include the framework's headers (so that either `c2hs` or a C file listed in `c-sources` can see them). I also needed to add

```
include-dirs: "/System/Library/Frameworks/OpenAL.framework/Headers/"
```

Seems like this could be done automatically.

### PR DESCRIPTION
**Pull request by bgamari**
This fixes #2689.

### CODE REVIEW

**Comment by bgamari** [comment]
I'm pretty sure this CI failure isn't due to me.

That being said, it's not entirely clear that cabal is the right place to handle this. Perhaps GHC should add these header paths itself?

**Comment by 23Skidoo** [comment]
LGTM. The Travis failure seems to have been spurious.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by mtolly** [comment]
This does not appear to work for me (at least for my original use case); here's my steps:

1. Clone https://github.com/phaazon/al/commit/2f26970ff3ead86252a61e966f1a9580479c928b

2. Edit `al.cabal`, remove the line:

  ```
include-dirs: "/System/Library/Frameworks/OpenAL.framework/Headers/"
  ```

3. `cabal build`, output:

  ```
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring al-0.1.4...
Building al-0.1.4...
Preprocessing library al-0.1.4...
dist/build/Sound/AL/Buffer.chs.h:2:10: fatal error: 'al.h' file not found
#include <al.h>
         ^
1 error generated.
c2hs: Error during preprocessing custom header file
  ```

I notice that `.framework` isn't added to the directory. That is, the framework `OpenAL`'s headers are at `/System/Library/Frameworks/OpenAL.framework/Headers` and I think this change is adding the incorrect `/System/Library/Frameworks/OpenAL/Headers`.

Also, the directory is not actually getting passed to `c2hs`. Here's the command from `cabal build -v`:

```
/Users/mtolly/.local/bin/c2hs '--cpp=/usr/bin/gcc' '--cppopts=-E' '--cppopts=-D__GLASGOW_HASKELL__=710' '--cppopts=-Ddarwin_BUILD_OS=1' '--cppopts=-Dx86_64_BUILD_ARCH=1' '--cppopts=-Ddarwin_HOST_OS=1' '--cppopts=-Dx86_64_HOST_ARCH=1' '--cppopts=-DCALLCV=ccall' '--cppopts=-includedist/build/autogen/cabal_macros.h' '--include=dist/build' '--cppopts=-I/Applications/ghc-7.10.1.app/Contents/lib/ghc-7.10.1/base_I5BErHzyOm07EBNpKBEeUv/include' '--cppopts=-I/Applications/ghc-7.10.1.app/Contents/lib/ghc-7.10.1/integ_2aU3IZNMF9a7mQ0OzsZ0dS/include' '--cppopts=-I/Applications/ghc-7.10.1.app/Contents/lib/ghc-7.10.1/include' '--output-dir=dist/build' '--output=Sound/AL/Defines.hs' src/Sound/AL/Defines.chs
```

**Comment by 23Skidoo** [comment]
@bgamari, can you look into this?

**Comment by bgamari** [comment]
Arg, this is the trouble with not having a test environment.

@mtolly, thanks for your testing! Let me see what I can do on this.

@23Skidoo, sorry, I should have been more clear that the patch still needed testing. Moreover, I'm still not sure whether this logic belong in Cabal or GHC itself.

**Comment by 23Skidoo** [comment]
@bgamari Do you want me to revert it?

**Comment by bgamari** [comment]
@23Skidoo it might be best to do so for now.

**Comment by 23Skidoo** [comment]
@bgamari Reverted.

**Comment by mtolly** [comment]
As noted in #2689 this is not necessary anymore.

**Pull request merged**
