### PR TITLE
Fix wording of haddock-project help and curate list of commands

### PR DESCRIPTION
**Pull request by jasagredo**
The diff:
```diff
➜ cabal haddock-project --help
Generate Haddocks HTML documentation for the cabal project.

-Usage: cabal-3.11.0.0.exe haddocks [FLAGS]
-   or: cabal-3.11.0.0.exe haddocks COMPONENTS [FLAGS]
+Usage: cabal-3.11.0.0.exe haddock-project [FLAGS]
+   or: cabal-3.11.0.0.exe haddock-project COMPONENTS [FLAGS]

-Require the programm haddock, version 2.26.
+Requires the program haddock, version 2.26.
...

➜ cabal --help
Command line interface to the Haskell Cabal infrastructure.

See http://www.haskell.org/cabal/ for more information.

Usage: cabal.exe [GLOBAL FLAGS] [COMMAND [FLAGS]]

Commands:
 [global]
...
  path                   Display paths used by cabal
...

 [project building and installing]
...
  haddock-project        Generate Haddocks HTML documentation for the cabal project.
...

- [other]
-  path                   Display paths used by cabal
-  haddock-project        Generate Haddocks HTML documentation for the cabal project.
-  new-haddock-project    Generate Haddocks HTML documentation for the cabal project.
-  v2-haddock-project     Generate Haddocks HTML documentation for the cabal project.
```

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
It's a little sad that `globalCommand` was not updated at the time when `haddock-project` was added. Maybe we need some sort of checklist for adding a new command. Better yet would be to test somehow that only the explicitly listed commands are understood. (Of course, this may be tricky, especially after the external command proposal.)

**Review by ffaf1 — APPROVED** [review]

**Comment by jasagredo** [comment]
I guess this just needs a rebase on top of `master`. Will do later today hopefully.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@jasagredo: hah, I keep wondering why the CI fix doesn't work for your PR, but you simply did not revert the CI-diagnosing commits you added here.

**Comment by jasagredo** [comment]
Indeed, sorry for that. I think I will have time to work on this and the other PRs next week.

**Pull request merged**
