### PR TITLE
allow building with recent (master) HTTP

### PR DESCRIPTION
**Pull request by Heather**
I need it for GHC 8 support

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by Heather** [comment]
@23Skidoo but so far changes for GHC 8 is not accepted in HTTP library

**Comment by 23Skidoo** [comment]
Well, we can't force Ganesh to accept that patch.

**Comment by Heather** [comment]
@23Skidoo I don't want to just provided tracking information

**Pull request merged**
