### PR TITLE
Open repl even if there are no exposed modules

### PR DESCRIPTION
**Pull request by cocreature**
I see no reason to not open the repl if there are no exposed modules, so opening it always seems like a good idea. As you might sometimes wonder why your modules are not important I added the verbose info.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
On a second thought, I think this should be

```
ifReplLib (runGhcProg replOpts) $ do
    when (null (libModules lib)) $ info verbosity "No exposed modules"
    ifReplLib (runGhcProg replOpts)
```

And maybe `warn` instead of `info`.

**Comment by lspitzner** [comment]
you mean

~~~~
ifReplLib $ do
  when (null (libModules lib)) $ warn verbosity "No exposed modules"
  runGhcProg replOpts
~~~~

**Comment by 23Skidoo** [comment]
@lspitzner Thanks, corrected.

**Pull request merged**
