### PR TITLE
Relax `containers` upper bound in `Cabal-syntax`

### LINKED ISSUE #9603: Allow containers-0.7
https://hackage.haskell.org/package/containers-0.7 has been release last September, but in order to bump it in GHC submodule we need `Cabal` / `Cabal-syntax` HEAD to allow it. Should be a matter of a pure version bump to land into `master`, I do not foresee any incompatibilities.

### PR DESCRIPTION
**Pull request by ffaf1**
Closes #9603 

---

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Review by mpickering — APPROVED** [review]

**Comment by mpickering** [comment]
Thanks @ffaf1

**Comment by Bodigrim** [comment]
I would expect other packages need a relaxation as well, at least `Cabal`, `cabal-install-solver` and `cabal-install`.

**Comment by ffaf1** [comment]
They were already bumped in 12eeb79bac

**Review by Bodigrim — APPROVED** [review]

**Comment by Mikolaj** [comment]
@Bodigrim, @bgamari: do you need a backport of this to the soon to be released cabal-install 3.10.3 (note that GHC 9.10 will likely be accompanied by the current master, which will be 3.12.1)?

**Comment by ffaf1** [comment]
(note that of course that two patches would have to be picked, if this is going to be backported)

**Comment by Bodigrim** [comment]
> do you need a backport of this to the soon to be released cabal-install 3.10.3?

It would not hurt and I imagine someone could benefit from it, but not a strong requirement. Might be easier to do it upfront than (potentially) revise later though.

**Comment by Mikolaj** [comment]
BTW, we need to ask mergify to backport them in proper order or it'd create conflicts...

**Comment by geekosaur** [comment]
@mergify backport 3.10

**Pull request merged**
