### PR TITLE
Make the deps' test for `cabal init` ignore unspecified versions

### LINKED ISSUE #7785: Test 'Check dependenciesHeuristics output` fails locally
**Describe the bug**

When running `cabal test cabal-install:unit-tests` locally, I'm getting a single failure:

            Check dependenciesHeuristics output
              base version bounds is correct:                                                    FAIL
                tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:1221:
                expected: OrLaterVersion (mkVersion [0])
                 but got: MajorBoundVersion (mkVersion [4,14,3,0])
                Use -p '/base version bounds is correct/' to rerun this test only.

I'm worried that it fails and also that CI does not fail similarly (is this test run on CI?).

**To Reproduce**

`cabal test cabal-install:unit-tests` on fresh repo.

**Expected behavior**

All tests pass.

**System information**

Ubuntu, GHC 8.10.7, cabal from master branch.

**Additional context**

Initially reported by @tomjaguarpaw at #7080.

### PR DESCRIPTION
**Pull request by ptkato**
Fixes #7785. The test will now consider passing anything outside of what's manually defined in `baseVersion'`. I also reduced the amount of versions in there to match only the ones in our CI.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
The test now passes for me locally. Thank you.

**Review by Kleidukos — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
@mergifyio rebase

**Comment by Mikolaj** [comment]
I think the MacOS CI run has stalled, so I'm merging.

**Pull request merged**
