### PR TITLE
Cabal: Disable GHCi libraries on Windows with GHC >=9.4

### PR DESCRIPTION
**Pull request by bgamari**
As noted in [GHC #21068](https://gitlab.haskell.org/ghc/ghc/-/issues/21068), the lld linker used on Windows by GHC 9.4 and later does not support object merging. Consequently, `--enable-library-for-ghci` can no longer be supported on this platform.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by Mikolaj** [comment]
This flag is needed for efficiency, but everything should still work, somehow. There seems to be no replacement for this speedup on Windows.

**Comment by bgamari** [comment]
We have concluded that we should disable this flag by default on Windows.

**Comment by bgamari** [comment]
By the way, this is the breakage that we previously encountered last time we tried to disable GHCi libraries: https://github.com/haskell/cabal/issues/1968

**Comment by jneira** [comment]
> Let's remember to close #1968 before we merge this, rather than after.

well maybe we could let it open, as disabling libraries for ghci in other os's would trigger the bug, but given the package is barely buildable with windows nowadays, i would merge it anyways

**Review by jneira — CHANGES_REQUESTED** [review]
Looks good to me, it would need a changelog entry mentioning the windows change but also the `arDashLSupported` addition which does not seem rdirectly related with and affects all os's
No additional test needed for the windows change imo, no sure about the other one

**Comment by bgamari** [comment]
Whoops, it looks like GitHub closed the MR as a result of my renaming the branch. I'll open a new MR addressing @jneira's comments shortly.

**Pull request closed without merging**
