### PR TITLE
Document the `remote-repo-cache` option as is implemented (it is).

### LINKED ISSUE #8737: The `remote-repo-cache` option is implemented but documented as not implemented
**Describe the bug**

[The documentation for the `remote-repo-cache` configuration option](https://cabal.readthedocs.io/en/3.8/cabal-project.html#cfg-field-remote-repo-cache) says:

> [STRIKEOUT:The location where packages downloaded from remote repositories will be cached.] Not implemented yet.

However, the option does appear to be implemented.  Observe a project configured to use an alternate package repo cache directory:

```sh
❯ pwd
/home/cleanroom/chk.hs
❯ cat cabal.project
packages: ./
❯ cat cabal.project.local 
store-dir: /home/cleanroom/chk.hs/.cabal
remote-repo-cache: /home/cleanroom/chk.hs/.cabal/packages
```

And where no cache currently exists, either in the default or configured location:

```sh
❯ stat ~/.cabal/packages
stat: cannot statx '/home/cleanroom/.cabal/packages': No such file or directory
❯ stat .cabal/packages
stat: cannot statx '.cabal/packages': No such file or directory
```

A package update will populate the configured cache location:

```sh
❯ cabal update hackage.haskell.org
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2023-02-07T12:42:11Z.
❯ find .cabal/packages                                                                    
.cabal/packages
.cabal/packages/hackage.haskell.org
.cabal/packages/hackage.haskell.org/hackage-security-lock
.cabal/packages/hackage.haskell.org/root.json
.cabal/packages/hackage.haskell.org/01-index.timestamp
.cabal/packages/hackage.haskell.org/timestamp.json
.cabal/packages/hackage.haskell.org/snapshot.json
.cabal/packages/hackage.haskell.org/mirrors.json
.cabal/packages/hackage.haskell.org/01-index.tar.gz
.cabal/packages/hackage.haskell.org/01-index.tar
.cabal/packages/hackage.haskell.org/01-index.tar.idx
.cabal/packages/hackage.haskell.org/01-index.cache
```

**Expected behavior**

The implemented behavior is what I would expect from the documentation that is currently struck out.

**System information**
 - NixOS 22.11
 - cabal 3.8.1.0
 - ghc 8.10.7

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #8737 

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

I tested that the feature really is implemented and left a transcript on the issue.  I tested that the docs build and render using Python 3.8 on NixOS 22.11 in a virtualenv using the `requirements.txt` in the repo and visual inspection.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Thank you!

**Review by Mikolaj — COMMENTED** [review]
However, are we sure this works in general and not in one easy corner case?

**Comment by exarkun** [comment]
> However, are we sure this works in general and not in one easy corner case?

I could test in some other cases if that would help.  Can you give me an idea of what the general problem space is?  I just learned about this option today and as far as I can tell "specify a different directory" like in the example is the only thing you can do with it.

**Review by Mikolaj — APPROVED** [review]
Hah, I've never used this option, so I don't have an idea. Could anybody toss any other use case for this feature so that we could try?

@exarkun: feel free to set the merge_me label and this will still leave 2 days for people to come up with evil examples to try.

**Comment by ulysses4ever** [comment]
I can't think of trickier examples, but I think if anyone wanted to get to the bottom of it, one could investigate what patch changed the state of things and what that patch had to say about all of that. But that maybe too much effort for such a small thing. It's more efficient to apply the current change and wait for bug reports! In the meantime we have many more "pr-welcome" issues that @exarkun or anyone else could spend their energy for.

**Comment by Mikolaj** [comment]
Let me rebase to apply one more CI fix.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@exarkun: could you let admins write to your branch or, alternatively, rebase youself? Thank you.

**Comment by exarkun** [comment]
@Mikolaj rebased (I would grant permission too but I can't find that github button today...)

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
Apparently that blocks auto-merging, too. so let me merge manually.

**Comment by Mikolaj** [comment]
@exarkun: thank you again!

**Pull request merged**
