### PR TITLE
Try update-alternatives ld

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Anyone have idea what's happening
```
/usr/bin/ld: --hash-size=31: unknown option
```
?

**Comment by alexbiehl** [comment]
GHC checks `ld` and passes `--hash-size=32` to it if it has `GNU ld` in its version info. 
(Cf. https://github.com/ghc/ghc/commit/71a194d8ca2efd075a5c000be0b378c8706ca0b3#diff-183a20ee6313d2c3600ef96e732176a3R660). `gold` is not passed any additional options.

**Comment by phadej** [comment]
@alexbiehl, ok so it's expected that `gold` doesn't work with GHC pre 7.8.x. Thanks

**Comment by phadej** [comment]
It seems that the test isn't that much faster with gold, @nh2 do you have any ideas why so? Is it related to #4439 ?

**Comment by ezyang** [comment]
We should verify that gold is actually being used for the tests. But perhaps the issue is that gold shines when linking large projects, and the test suite is basically always doing very small things.

**Comment by 23Skidoo** [comment]
`-pgml` shouldn't play a role here, since we don't use it.

**Comment by 23Skidoo** [comment]
I think I'll merge this, because it's a small change, but feel free to revert if you disagree.

**Pull request merged**
