### PR TITLE
Test ghc-9.4.0.20220623

### PR DESCRIPTION
**Pull request by jneira**
* Minimal changes to test Cabal with ghc prerelase versions

### CODE REVIEW

**Comment by jneira** [comment]
9.4 support has been added by #8420

**Comment by ulysses4ever** [comment]
We still need a plan for using GHC pre-releases (or even HEAD?)? Is it basically #7798? Or is it better to have a separate ticket?

**Comment by jneira** [comment]
I would open a new one to evaluate costs and what would give us

**Comment by Mikolaj** [comment]
Please do and edit to your liking. #7798 is old and meandering.

**Pull request closed without merging**
