### PR TITLE
#8975, #8981, #8983 rebased

### PR DESCRIPTION
**Pull request by ffaf1**
#8975, #8981 and #8983, cherry picked. 

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Thanks a lot. That preserve commit history, so it's better than just squashing.

**Comment by ulysses4ever** [comment]
We should not forget to close the base PRs when this one is merged...

**Comment by ulysses4ever** [comment]
While we're on it... @ffaf1 how do you feel about including #8983 here (whatever is left from it after you handled the other two)?

**Comment by ulysses4ever** [comment]
I'm putting the delay-passed passed label because the actual changes have been reviewed in the past and this PR is only a tool to make sure those change land on `master` safely and sanely. The only remaining issue here is the flaky test. Will see if the change in https://github.com/haskell/cabal/pull/9055 helps it, as Gershom proposes.

**Comment by Mikolaj** [comment]
Well done. Thank you again.

**Pull request merged**
