### PR TITLE
RFC: Potential fix for #4808

### PR DESCRIPTION
**Pull request by hvr**
See https://github.com/haskell/cabal/issues/4808#issuecomment-337048211

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Test would be great.

I can only shake my head around this. If only we could have versioned APIs to call older `Setup.hs`.

**Comment by hvr** [comment]
@23Skidoo I'm not sure yet how such a test would look like; we can probably do easy roundtrip tests (and it would help if FlagAssignment was a newtype, so we could attach parse/display instances to it). 

(relatedly, @ezyang mentioned in https://github.com/haskell/cabal/pull/4710#issuecomment-323524170 we don't have many communication tests with different lib:Cabal versions)

So which kind of tests did you (& @phadej) have in mind specifically?

**Comment by bgamari** [comment]
What is the status of this? For the record, this is something that 8.2.2 is blocking on.

**Comment by phadej** [comment]
@hvr, I'm ok for this going to 2.0 as is, but for `master` could we change `FlagAssignment` to the newtype and do roundtrip stuff?

**Comment by phadej** [comment]
cherry-picked on 2.0. @bgamari could you verify it unblocks GHC-8.2.2?

**Comment by hvr** [comment]
> but for master could we change FlagAssignment to the newtype and do roundtrip stuff?

oh yes; in fact I have already started on refactoring it into a newtype to see how much places I'd have to touch; it's not bad at all :-)

**Comment by bgamari** [comment]
Thanks @phadej. That should do it.

**Pull request merged**
