### PR TITLE
Temp travis fix

### LINKED ISSUE #5120: Strange Travis failures
Travis seems to fail with:
```
cabal/dist-newstyle/src/pretty-show-1.6.16/dist: renamePath:rename: unsatisfied constraints (Directory not empty)Configuring library for pretty-show-1.6.16..
```
lately a lot.

So I've basically run `git bisect` with `git clean -xfd && cabal new-build cabal-install` on the tree.

That ended up with:

```
84ab693b0162c372c5127e0a27a52bf902beea55 is the first bad commit
commit 84ab693b0162c372c5127e0a27a52bf902beea55
Author: Mikhail Glushenkov <mikhail.glushenkov@gmail.com>
Date:   Thu Jan 4 10:35:30 2018 +0000

    Unbreak Haddock doc generation.
    
    + a whitespace fix.

:040000 040000 375f64d216a741dba303b827e5da2513bd47f490 93da2a12bae5c288aecccff300d636296751937f M	cabal-install
bisect run success
```

log is

```
git bisect start
# good: [abc18aa7a2677a549f2ff57729a0dee026a7f69c] Capitalisation.
git bisect good abc18aa7a2677a549f2ff57729a0dee026a7f69c
# bad: [18317ce96afbdc08e317b41d10802132266b2ec3] Add buildDir includes as needed.
git bisect bad 18317ce96afbdc08e317b41d10802132266b2ec3
# good: [ab585e864929a8d19ed844d82ff2e9d002ae6313] Merge remote-tracking branch 'upstream/dcoutts/project-config-explicit-includes'
git bisect good ab585e864929a8d19ed844d82ff2e9d002ae6313
# bad: [67276f870a55e6a913b98ef7b2ca22a8def21a6e] Merge pull request #4861 from fgaz/new-run/allow-running-tests-benchs
git bisect bad 67276f870a55e6a913b98ef7b2ca22a8def21a6e
# bad: [ce775dbbfe7d04fb9376e2562002a3bbcb0337ed] Add duplicate field negative tests.
git bisect bad ce775dbbfe7d04fb9376e2562002a3bbcb0337ed
# bad: [ec9ce1c82dcff66608a7b1875e11c220828ec2ee] cabal-testsuite: test cabal new-test with coverage
git bisect bad ec9ce1c82dcff66608a7b1875e11c220828ec2ee
# bad: [552ae22bdc7a265bd57b131f3749e239476bd7ca] Rename rewriteFileV to rewriteFileEx.
git bisect bad 552ae22bdc7a265bd57b131f3749e239476bd7ca
# good: [6e42aa2502ff8e318607d8614693c712f5aac709] Merge pull request #4991 from ezyang/pr/T4986
git bisect good 6e42aa2502ff8e318607d8614693c712f5aac709
# good: [a3e1833890afe970da5eeae3b9d5cac8473734f1] Restore BC compatibility for rewriteFile, fixes #4981
git bisect good a3e1833890afe970da5eeae3b9d5cac8473734f1
# bad: [587bc30577759a93615f391ec42afeaecef2f964] Merge pull request #4996 from ezyang/pr/rewrite-file-bc
git bisect bad 587bc30577759a93615f391ec42afeaecef2f964
# bad: [84ab693b0162c372c5127e0a27a52bf902beea55] Unbreak Haddock doc generation.
git bisect bad 84ab693b0162c372c5127e0a27a52bf902beea55
# first bad commit: [84ab693b0162c372c5127e0a27a52bf902beea55] Unbreak Haddock doc generation.
```

hope that's of any use...

### PR DESCRIPTION
**Pull request by angerman**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

alternative fix for #5123, #5126.

Fixes #5120.

### CODE REVIEW

**Comment by angerman** [comment]
Let's see if this really ugly hack, does the trick.

**Comment by angerman** [comment]
Lovely:
```
Linking /Users/travis/build/haskell/cabal/dist-newstyle/build/x86_64-osx/ghc-7.10.3/happy-1.19.9/build/happy/happy ...
Configuring library for pretty-show-1.6.16..
Preprocessing library for pretty-show-1.6.16..
happy: /Users/travis/.cabal/share/x86_64-osx-ghc-7.10.3/happy-1.19.9/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
cabal: Failed to build pretty-show-1.6.16 (which is required by
cabal-install-2.1.0.0).
```
For the (macOS, 7.10.3, script) config.

**Comment by angerman** [comment]
So the reason for the above issue is #5104. 

We build and link happy-1.19.9; and expect the `happy` on path to be 1.19.9 as well, which
of course is not a given.

**Comment by angerman** [comment]
@23Skidoo, all green! Unborked!

**Comment by 23Skidoo** [comment]
Thanks a lot! Merged manually in 22330fc0743f490d3acda27c6c9ca50362a88763.

**Pull request closed without merging**
