### PR TITLE
Update licence list

### PR DESCRIPTION
**Pull request by ffaf1**
Per https://github.com/haskell/cabal/wiki/Updating-the-license-list to version 3.23 (2024-02-08) of SPDX License List.

---

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] not necessary ~~[Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] not needed ~~Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)~~

### CODE REVIEW

**Comment by ffaf1** [comment]
After yesterday’s call with Mikolaj, I think this step has to be done *before* the “bumping version numbers” one.
Let us see what CI says.

**Review by geekosaur — APPROVED** [review]

**Comment by ffaf1** [comment]
I forgot about this. I will add `merge delay passed`, since three days have gone by.

**Review by Mikolaj — APPROVED** [review]
Thank you.

**Comment by Mikolaj** [comment]
I'm guessing this should have been done on master and backported. The old wiki page had "note: most of the changes should be done on branch master and backported to the release branch." I guess we should add this to each and every point except the one or two that are best done on release branch. 

BTW, mergify seems stuck, so let me merge manually.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify queue

**Comment by Mikolaj** [comment]
Hah, `queue` worked.

**Comment by ffaf1** [comment]
@mergify backport master

**Comment by ulysses4ever** [comment]
@ffaf1 two points on interest.

First,

> I will add merge delay passed, since three days have gone by.

The delay is not required for PRs against branches other than `master`. This is just FYI.

Second, this manual backport has a subtle difference from the original (#9837): the json files in `license-list-data` don't have newlines at the end. Compare:

- [`master` version](https://github.com/haskell/cabal/pull/9837/files#diff-86658b7ae322775b93cf74a0529fb9c7a9d71767c84f388955a80039851c0d17)
- [`3.12` version](https://github.com/haskell/cabal/pull/9818/files#diff-86658b7ae322775b93cf74a0529fb9c7a9d71767c84f388955a80039851c0d17)

Just wanted to share my pain: I spent half a day banging my head against the `whitespace` GH workflow that fails on 3.12 and works on master because of this subtlety...

**Comment by geekosaur** [comment]
> The delay is not required for PRs against branches other than `master`. This is just FYI.

IIRC it's only waived for PRs that are identified as backports.

**Comment by ulysses4ever** [comment]
@geekosaur good point. By reading https://github.com/haskell/cabal/blob/master/.github/mergify.yml it appears that if you manually put the backport label, it will do the trick. In this case, it is a manual backport, so the label is justified. But perhaps we should simplify it, since with the current setup, a vanilla (non-backport) PR against a non-master branch will not be served by the bot at all, it looks like.

**Pull request merged**
