### PR TITLE
Add a warning when an env file is created

### PR DESCRIPTION
**Pull request by tomsmeding**
Inspired by https://github.com/haskell/cabal/issues/6481#issuecomment-1934909998

I get that there are many colourable panels on the bikeshed that is `cabal env`, and even many real engineering choices and challenges, but it would be very nice if at least the user gets some warning if they `cabal install --lib` and that creates an environment file. After all, statistically, this is _not_ what they intended, or if it was they probably didn't know the consequences. Had they known the consequences, they would have realised that this is not what they wanted.

This patch only shows a warning if an environment file does not yet exist, to acknowledge the set of people who are actually _using_ this functionality.

This is blocked on the bug mentioned here: https://github.com/haskell/cabal/pull/9697#issuecomment-1938036790

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by fgaz** [comment]
I'd also omit the warning if --package-env is used

**Comment by tomsmeding** [comment]
Thanks @Mikolaj and @fgaz! Very good suggestions, my PR was a bit premature perhaps.

I rebased the branch on the latest master, improved the warning message text, and added a check to only show the message if `--package-env` is not passed.

There is still [this issue](https://github.com/haskell/cabal/pull/9706#issuecomment-1951099399) I found when testing this, but it feels unrelated.

How do you suggest I test this? A test should be self-contained so it cannot try to put a GHC environment file in the global environment, but making it local with `--package-env` disables the warning.

**Comment by tomsmeding** [comment]
@Mikolaj The point is that I'd like to test that cabal gives the warning at the appropriate time, i.e. when creating a new environment file without `--package-env` in effect. But in that situation, the environment file gets created globally (in `~/.ghc`), which a test shouldn't do! Both because running tests shouldn't interfere with the machine it's running on, and because the tests shouldn't be impacted by whatever the contents of `~/.ghc` happen to be on the testing machine. So I'm at a loss for how to test this PR :)

**Comment by fgaz** [comment]
Tbh I'd probably skip the test. It doesn't seem worth it

**Comment by tomsmeding** [comment]
I think the PR is ready, albeit without test. Good suggestions for a testing approach are welcome; merging as-is is also fine.

**Comment by ulysses4ever** [comment]
@mergify rebase

**Review by geekosaur — APPROVED** [review]

**Comment by tomsmeding** [comment]
I have tested this PR again when rebased to current `master` and it still works, so I guess it is ready for merging! :)

**Comment by Mikolaj** [comment]
Great, it's going to merge in 2 days: https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions.

**Comment by Mikolaj** [comment]
@mergify queue

**Comment by Mikolaj** [comment]
Somehow the branch is not modifiable to mergify. I'm going to merge manually, since the delay has passed.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
Huh, mergify merged automatically in the end after the CI finished after a `mergify rebase`. *shrug*

**Comment by Mikolaj** [comment]
@mergify backport 3.12

**Pull request merged**
