### PR TITLE
Swap `cryptohash`/`byteable` dep with `cryptohash-sha256`/`base16-bytestring`

### PR DESCRIPTION
**Pull request by hvr**
See well-typed/hackage-security#152 for rationale

next `hackage-security` release will depend on `cryptohash-sha256`/`base16-bytestring` instead as well

### CODE REVIEW

**Comment by hvr** [comment]
@23Skidoo TODO: update the bootstrap script

**Comment by dcoutts** [comment]
LGTM. We already did this for hackage-security, so just need to do it for cabal-install too (ie this patch). We'll do a release of hackage-security with the change soon. Once the bootstrap script is updated we're good to merge.

**Comment by 23Skidoo** [comment]
@dcoutts Can we get a new `hackage-security` release with this change?

**Comment by dcoutts** [comment]
@23Skidoo is it better to do it right now, or should we wait 24 hours and see if there's anything else we need?

**Comment by hvr** [comment]
@23Skidoo @dcoutts I vote for waiting 24h as this just reminded me there was a different issue related to hackage-security which may or may not require minor fixes somewhere :-)

**Comment by 23Skidoo** [comment]
OK, let's wait then.

**Comment by 23Skidoo** [comment]
So I'll merge this now and update the bootstrap script once the new version of `hackage-security` is released.

**Comment by 23Skidoo** [comment]
Also cherry-picked into `master`.

**Pull request merged**
