### PR TITLE
`cabal init` improvements: application-dir and creating library hs file

### PR DESCRIPTION
**Pull request by m-renaud**
# Overview

This adds support for specifying an "application directory" for the `Main.hs` executable entrypoint to be located in (`"app"` is a very common one).

This also generates a `MyLib.hs` file when initializing a new project that is `Library` or `LibraryAndExecutable`. For the latter, the `Main` module also imports this library and uses it.

This can be provided via the `--application-dir` command line flag, and can also be set in the `init` section of `~/.cabal/config` (and will always use that directory unless overridden by the command line flag).

## Config File

```
init
  ...
  -- application-dir:
  -- source-dir:
```

This partially addresses #5696.

## Examples

**Interactive options:**

```
Application (Main.hs) directory:
 * 1) (none)
   2) src-exe
   3) app
   4) Other (specify)
Your choice? [default: (none)] 2
Library source directory:
 * 1) (none)
   2) src
   3) lib
   4) src-lib
   5) Other (specify)
Your choice? [default: (none)] 4
```

**`--is-library`, no application directory**

```
$ cabal-dev init --is-library -n
Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating MyLib.hs...
Generating inittest.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

$ ls
CHANGELOG.md  inittest.cabal  MyLib.hs  Setup.hs

$ cat inittest.cabal
cabal-version:       >=1.10
-- Initial package description 'inittest.cabal' generated by 'cabal init'.
--   For further documentation, see http://haskell.org/cabal/users-guide/

name:                inittest
version:             0.1.0.0
-- synopsis:
-- description:
-- bug-reports:
-- license:
license-file:        LICENSE
author:              Matt Renaud
maintainer:          matt@m-renaud.com
-- copyright:
-- category:
build-type:          Simple
extra-source-files:  CHANGELOG.md

library
  exposed-modules:     MyLib
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.12 && <4.13
  -- hs-source-dirs:
  default-language:    Haskell2010

```

**`--is-libandexe`, source-dir, no application dir**

```
$ cabal-dev init --is-libandexe --source-dir=src -n
Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating src/MyLib.hs...
Generating Main.hs...
Generating inittest.cabal...

$ cabal-dev v2-run
Resolving dependencies...
<snip>
[1 of 1] Compiling MyLib            ( ... )
<snip>
[1 of 1] Compiling Main             ( ... )
<snip>
Hello, Haskell!
someFunc
```

**`--application-dir`**

```
$ cabal-dev init --is-libandexe --application-dir=app --source-dir=src -n

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating src/MyLib.hs...
Generating app/Main.hs...
Generating inittest.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

$ cabal-dev v2-run
Resolving dependencies...
<snip>
[1 of 1] Compiling MyLib            ( ... )
<snip>
[1 of 1] Compiling Main             ( ... )
<snip>
Hello, Haskell!
someFunc
```

## Code Hackiness

Due to the way that other-modules needs to be handled when MyLib.hs and Main.hs are in the same directory complicates the code a little bit. There's also some explicit checks for `exposedModules flags == Just [ModuleName.fromString "MyLib"]`, I could instead add a new flag which is set to `True` when we're creating a `MyLib.hs` file, will probably be a bit cleaner than checking the `exposedModules` list.

## Testing

Manual testing, see examples above.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by m-renaud** [comment]
This is ready for review as well @23Skidoo :)

**Comment by m-renaud** [comment]
Merge conflicts resolved, should be good to go now :)

**Comment by hvr** [comment]
@m-renaud you say

> "app" is a very common one

which is a bit news to me... I myself have never used such a folder name nor do I remember having seen that one used on Hackage.

Personally, I go for `hs-source-dirs` named `src` or `src-...`, such as

```
src/
src-lib/
src-exe/
src-test/
src-bench/
```

**Comment by m-renaud** [comment]
@hvr thanks for the input! I selected `app` because it is the default directory where `Main.hs` is placed by [Summoner](https://github.com/kowainik/summoner), `stack new`, and over half of available Stack templates that produce an executable (12/20 at time of writing). The thing I was going for is consistency.

> I myself have never used such a folder name nor do I remember having seen that one used on Hackage

I'm guessing that's because you don't often use Summoner or Stack to start packages or projects :)

It's likely that this isn't seen on Hackage because:

a) Most Hackage packages are libraries only, not binaries
b) The packages that are binaries were possible/likely created with `cabal init` which did not create `app` directory, so the creators probably didn't change the default (`/src`).

If desired I can also create a global configuration option for this so that users can set it to be what they want once and not have to think about it again (`application-dir: src-exe/` in your case). If we do this I'd like to do that in a follow-up PR though to keep the scope of this change smaller.

**Comment by gbaz** [comment]
fwiw i've seen "src" for the lib and "app" for the executable used a bit at work. it seems to correspond with using "tests" for the test dir instead of e.g. "src-test". But I don't think it matters much any particular way :-)

**Comment by hvr** [comment]
> I'm guessing that's because you don't often use Summoner or Stack to start packages or projects :)

I'll blame Stack then for this weird naming then, which Summoner simply cargo-culted then... ;-)

**Comment by m-renaud** [comment]
I don't think we'll ever be able to please everyone unfortunately :stuck_out_tongue_winking_eye:  For better or worse, `app/` is the most commonly used directory name, and I think at this point consistency-by-default is more important than the specific name. I'd be happy to implement a global config option so that folks that don't like it can pick one they do like.

**Comment by m-renaud** [comment]
A few more thoughts:

Another possible name for this flag would be `executable-dir`. This is a bit more general/common term than "application".

RE: global configuration: it would be cleaner/easier to understand if init had its own section in the global cabal config, then instead of having a top level `interactive-init` and `application-dir` (or `executable-dir`) options we would have:

```
init
  interactive-init: False
  source-dir: src
  executable-dir: app (or src/exe/ or src/bin/ or exe/ or whathaveyou
  cabal-version: 2.4
  ...etc
```

WDYT? I don't want to hold up merging this PR, just want to put the idea out there :)

**Comment by 23Skidoo** [comment]
I'm +1 on putting `init` settings into its own section.

**Comment by m-renaud** [comment]
> I'm +1 on putting init settings into its own section.

SG, I'll start putting together a PR for that this week.

Anything else blocking this PR?

**Comment by m-renaud** [comment]
@23Skidoo See #5852, that took less time than expected :stuck_out_tongue_winking_eye:

**Comment by hvr** [comment]
@m-renaud at the very least I'd expect the naming convention to be consistent in itself; and if you want to stick to `app`/`test` instead of `src-*`, then for consistency you should also use `lib` instead of `src` for the library component! And just because somebody else picked an inconsistent naming scheme we don't need to promote it even further by blindly adopting it ;-)

**Comment by m-renaud** [comment]
@hvr another option is to not pick a default at all in this PR, just leave it empty (`(none)`) like is done for `source-dir`.

Also, even with the current implementation this does not "default to `app/`" it only suggests it as one of the options. I'd be perfectly happy to remove that suggestion and instead have `src/` as a suggestion for both library source directory and binary/application directory.

So, to summarize you get the following prompts if you select:

`Executable`:
```
Executable (Main.hs) directory:
1) (none)
2) src
3) app
4) Other (specify)
```

`Library`:
```
Library source directory:
1) (none)
2) src
3) Other (specify)
```

`LibraryAndExecutable`:

Both of the above prompts.

Another alternative is to drop option 3 (app) from the "Executable (Main.hs) directory" prompt all together. The goal of this PR is to allow the libraries and executables to be placed in separate directories if desired. I'd also be open to renaming the flag `--executable-dir` instead of `--application-dir` but that could be confused with "the directory that built executables will be placed in.

WDYT?

**Comment by gbaz** [comment]
We should very much steer people away from having the exe-dir and the src-dir the same. It leads to all sorts of issues and confusions. Herbert's proposal was to have `src-lib` (or just `src`) and `src-exe`. I.e. I don't think that the options for the lib and exe dirs should have overlap.

**Comment by m-renaud** [comment]
> We should very much steer people away from having the exe-dir and the src-dir the same

I completely agree. All that I'm saying is this is the status quo (to use `src/` for both), and the discussion on what to name that directory is holding up this PR (which even permits that distinction). The next cabal-install release isn't for another month or two which is more than enough time to paint the bikeshed and then repaint it again if desired ;)

If desired, I could remove `src/` from the application directory list so its just:

```
Executable (Main.hs) directory:
1) (none)
2) Other (specify)
```

This avoids suggesting that the "library" code and Main.hs live in the same directory. Adding other options can easily be done in a follow-up PR.

**Comment by gbaz** [comment]
Why not add both `app` and `src-exe` to the list? And have all of `lib`, `src` and `src-lib` in the lib-dir list?

**Comment by m-renaud** [comment]
@gbaz 

That SGTM, I'll resolve the merge conflicts, make those changes and update the PR description with updated example output.

**Comment by m-renaud** [comment]
Resolved merge conflicts and updated sets of recommendations in interactive prompt (see Examples section in PR description). Also made this available for configuration in `~/.cabal/config > init > application-dir`.

**Comment by m-renaud** [comment]
Friendly ping :) Any other concerns or can this be merged? @23Skidoo @gbaz

**Comment by 23Skidoo** [comment]
Merged, thanks! Sorry for being slow.

**Comment by m-renaud** [comment]
No worries, we've all got stuff going on :)

**Pull request merged**
