### PR TITLE
cabal-install uses internal libraries.

### PR DESCRIPTION
**Pull request by ezyang**
There are lots of benefits:

    * We only build solver code once, instead of repeatedly
      rebuilding it for each test suite.

    * Duplication in the cabal-install file is greatly
      reduced.

There is one downside, which is that we don't rebuild
cabal-install with asserts turned on.  I think we should
look into making this a runtime toggleable chunk of code.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM, but build bot failures will need to be fixed.

>  +36 −122

Nice!

**Comment by BardurArantsson** [comment]
So I'm guessing that this means (assuming it's merged) that we could also do so for the solver-only bits? (That is, the `Distribution.Solver.*` modules.)

(I'd be happy to do a PR for that, time permitting.)

**Comment by 23Skidoo** [comment]
> So I'm guessing that this means (assuming it's merged) that we could also do so for the solver-only bits? (That is, the Distribution.Solver.* modules.)

Yes.

> (I'd be happy to do a PR for that, time permitting.)

Please do!

**Comment by ezyang** [comment]
I guess even when I get this green, we can't do this for 1.26, because the need for internal library support means that you can't "cabal install cabal-install" from 1.24 (which doesn't understand internal libraries.) So we need one intervening release before we can put this in.

**Comment by BardurArantsson** [comment]
Ah, true. Guess it'll have to wait for post-1.26.

**Comment by 23Skidoo** [comment]
Well, in principle we can release cabal-install 1.26 faster than originally planned (e.g. in September).

**Comment by phadej** [comment]
Won't this need a `Cabal-1.26` too?

**Comment by 23Skidoo** [comment]
Yes, but I don't see this as a problem.

**Comment by ezyang** [comment]
Well, I'm going to close this for now, no way to merge.

**Comment by 23Skidoo** [comment]
We should revive this after the next release.

**Pull request closed without merging**
