### PR TITLE
PackageTests/Configure: Use zlib instead of X11.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes (part of) #3623.

### CODE REVIEW

**Comment by phadej** [comment]
Thanks, LGTM :+1:

**Comment by ezyang** [comment]
Yep, let's put it in.

**Comment by phadej** [comment]
duh. Now I can verify that osx test would actually fail when there is something failing...

**Comment by 23Skidoo** [comment]
@phadej You revert this patch in your branch.

**Comment by phadej** [comment]
have to do that

**Pull request merged**
