### PR TITLE
Some cleanups

### PR DESCRIPTION
**Pull request by ezyang**
These commits are unrelated but I didn't feel like making a separate PR for each one. One refactors configure, the other removes some functionality from build-depends (yes I checked, there is no package on Hackage which uses that functionality.)

### CODE REVIEW

**Comment by ezyang** [comment]
I wonder why Travis didn't run on this.

**Comment by 23Skidoo** [comment]
Try changing something trivial and force-pushing.

**Comment by ezyang** [comment]
Yeah, I'm going to get Travis green and then clean it up.

**Comment by 23Skidoo** [comment]
OK, feel free to merge when Travis is green.

**Pull request merged**
