### PR TITLE
cabal-install.cabal: bump hashable, HTTP, time upper bounds

### PR DESCRIPTION
**Pull request by juhp**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

Tested against 3.6.2.0 so far

### CODE REVIEW

**Comment by andreasabel** [comment]
There is a CI failure for Validate Windows GHC 8.10.7:
```
PackageTests\Configure\cabal.test.hs                                                                              FAIL (0.02s)
$ "C:\tools\ghc-8.10.7\bin\runghc.exe" "--" 
"--ghc-arg=-i" "--ghc-arg=-no-user-package-db" 
"--ghc-arg=-package-db" "--ghc-arg=C:\sr\ghc-8.10.7\package.db" 
"--ghc-arg=-package-db" "--ghc-arg=D:\a\cabal\cabal\dist-newstyle-validate-ghc-8.10.7\packagedb\ghc-8.10.7" 
"--ghc-arg=-package-id" "--ghc-arg=Cabal-3.7.0.0-inplace" 
"--ghc-arg=-package-id" "--ghc-arg=Cabal-syntax-3.7.0.0-inplace" 
"--ghc-arg=-package-id" "--ghc-arg=async-2.2.4-868bcb0b8bfbd5dabae6059e02c90868c75826f5" 
"--ghc-arg=-package-id" "--ghc-arg=base-4.14.3.0" 
"--ghc-arg=-package-id" "--ghc-arg=cabal-testsuite-3-inplace" 
"--ghc-arg=-package-id" "--ghc-arg=clock-0.8.3-8d6f0308588d4c62899853cf2a200407866d2820" 
"--ghc-arg=-package-id" "--ghc-arg=exceptions-0.10.4" 
"--ghc-arg=-package-id" "--ghc-arg=filepath-1.4.2.1" 
"--ghc-arg=-package-id" "--ghc-arg=optparse-appl_-0.16.1.0-06e1a7c9966dfac15712d8a0c66d2bc0900408e0" 
"--ghc-arg=-package-id" "--ghc-arg=process-1.6.14.0-e20921632eca8df7ccd15140aea02df6df51aa92" 
"--ghc-arg=-package-id" "--ghc-arg=transformers-0.5.6.2" "PackageTests\Configure\cabal.test.hs" 
"--builddir" "D:/a/cabal/cabal/dist-newstyle-validate-ghc-8.10.7/build/x86_64-windows/ghc-8.10.7/cabal-testsuite-3" "PackageTests\Configure\cabal.test.hs" 
"--with-ghc" "ghc"
stdout:

stderr:

PackageTests\Configure\cabal.test.hs:4:1: error:
Error:     Ambiguous module name ‘System.Directory’:
      it was found in multiple packages:
      directory-1.3.7.0 directory-1.3.7.0
  |
4 | import System.Directory
  | ^^^^^^^^^^^^^^^^^^^^^^^
```

Doesn't look related.  I try and restart.

**Review by andreasabel — APPROVED** [review]
Approved modulo CI passing.

**Comment by Mikolaj** [comment]
> Like #8118 these should also be done as revisions to 3.6.2.0.

I will revise on hackage if tests pass on master, given these are not as fundamental as package base, so testing 3.6 branch specifically is not that crucial IMHO.

**Review by Mikolaj — APPROVED** [review]

**Comment by juhp** [comment]
Thanks!

**Comment by jneira** [comment]
Hmm, the ci was failed when mergify merged the pr, *again* 🤔 
The error is weird:

```
PackageTests\PreProcess\Hsc2HsOptionsCC\setup.test.hs:4:1: error:
Error:     Ambiguous module name ‘System.Directory’:
      it was found in multiple packages:
      directory-1.3.7.0 directory-1.3.7.0
  |
4 | import System.Directory (findExecutable)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

maybe another cache issue?

**Pull request merged**
