### PR TITLE
Remove --cabal-file option

### PR DESCRIPTION
**Pull request by andreabedini**
Closes:  #8395

---

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies `cabal` behaviour**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

Bonus points for added automated tests!

---

**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Comment by andreabedini** [comment]
```
-Documentation created: ../setup-external.dist/work/mylib/dist/doc/html/mylib/index.html
+Documentation created: ../setup-external.dist/work/mylib/dist/doc/html/mylib/
```

I am running into this annoying problem :thinking: :unamused:

**Comment by ulysses4ever** [comment]
> I am running into this annoying problem thinking unamused

It was recently changed in #8919 (see how it updated the tests). Not sure what to do about it though.

**Comment by ulysses4ever** [comment]
We could tag the author of that PR maybe.

**Comment by andreabedini** [comment]
What's puzzling is that it seems to depend on the GHC version :thinking: Let me reset those changes first.

**Comment by andreabedini** [comment]
Maybe I was just mixing up two different failures.

**Comment by andreabedini** [comment]
Can any Windows expert help me understand what's going on here https://github.com/haskell/cabal/actions/runs/5584068207/jobs/10205063977#step:18:1658?

**Comment by Mikolaj** [comment]
Let me try to rerun once again. :)

**Comment by andreabedini** [comment]
Thanks. I am at loss with what is happening on Windows :-/ I don't think I can do much.

**Comment by jasagredo** [comment]
I'm able to reproduce the error in 9.4.4:

```
Running: "C:\ghcup\ghc\9.4.4\lib\../mingw/bin\llvm-ar.exe" "-qL" "..\setup-internal.dist\work\Includes2\dist\build\Includes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI\objs-7580\libHSIncludes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI.a" "@..\setup-internal.dist\work\Includes2\dist\build\Includes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI\objs-7580\ar58B.rsp"
C:\ghcup\ghc\9.4.4\lib\../mingw/bin/llvm-ar.exe: warning: creating ..\setup-internal.dist\work\Includes2\dist\build\Includes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI\objs-7580\libHSIncludes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI.a
C:\ghcup\ghc\9.4.4\lib\../mingw/bin/llvm-ar.exe: error: ..\setup-internal.dist\work\Includes2\dist\build\Includes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI\objs-7580\libHSIncludes2-0.1.0.0-mylib+JA8sqakdQMC7oNcBYWFaHI.a: No such file or directory
```

It seems the folder doesn't exist. I can confirm that `llvm-ar.exe` cannot create directories:
```
Javier@DESKTOP-JDT20GG MINGW64 ~/code/cabal
$ /c/ghcup/ghc/9.4.4/mingw/bin/llvm-ar qL xx/a.a
C:\ghcup\ghc\9.4.4\mingw\bin/llvm-ar.exe: warning: creating xx/a.a
C:\ghcup\ghc\9.4.4\mingw\bin/llvm-ar.exe: error: xx/a.a: No such file or directory

Javier@DESKTOP-JDT20GG MINGW64 ~/code/cabal
$ mkdir xx

Javier@DESKTOP-JDT20GG MINGW64 ~/code/cabal
$ /c/ghcup/ghc/9.4.4/mingw/bin/llvm-ar qL xx/a.a
C:\ghcup\ghc\9.4.4\mingw\bin/llvm-ar.exe: warning: creating xx/a.a

Javier@DESKTOP-JDT20GG MINGW64 ~/code/cabal
$ ls xx
a.a
```

However, the test passes with GHC 9.6.3, and the behavior of `llvm-ar.exe` is the same:
```
Javier@DESKTOP-JDT20GG MINGW64 ~/code/cabal
$ /c/ghcup/ghc/9.6.3/mingw/bin/llvm-ar qL yy/a.a
C:/ghcup/ghc/9.6.3/mingw/bin/llvm-ar.exe: warning: creating yy/a.a
C:/ghcup/ghc/9.6.3/mingw/bin/llvm-ar.exe: error: yy/a.a: No such file or directory
```

Which makes me think that GHC changed something in the steps it followed for creating the paths.

**Comment by jasagredo** [comment]
Note that MinGW does not understand symlinks, so the test would need to be reworked around this fact (or skipped in windows)

**Comment by jasagredo** [comment]
So in fact it has nothing to do with directories but rather with long paths, and it was fixed in 9.4.5: 
- https://gitlab.haskell.org/ghc/ghc/-/issues/21293
- https://github.com/llvm/llvm-project/issues/54559 (in particular this comment by Ryan https://github.com/llvm/llvm-project/issues/54559#issuecomment-1222261353)
- https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9683

```
$ /c/ghcup/ghc/9.4.5/mingw/bin/llvm-ar --version
LLVM (http://llvm.org/):
  LLVM version 14.0.6
  Optimized build.
  Default target: x86_64-w64-windows-gnu
  Host CPU: znver3
```

Rebasing on top of `master` should fix this

**Comment by andreabedini** [comment]
And indeed it works! Thank you again ❤️

**Comment by andreabedini** [comment]
@ulysses4ever @Mikolaj gentle ping for a review :relaxed:

**Comment by Mikolaj** [comment]
Thanks a lot for the tests! How about a changelog?

**Review by ulysses4ever — APPROVED** [review]
LGTM, thank you. And sorry for long delay.

The flag is still available in the library and perhaps v1-commands? There're setup-tests that you updated to not use the flag, but is it really unavailable in setup-tests or is it out of a desire to avoid the legacy flag?

**Comment by ulysses4ever** [comment]
And not only that but just improve its docs.

**Comment by andreabedini** [comment]
> That is fair and I agree. Is there no place in the docs to expand a little bit on the "internal" nature of this flag? I remember users trying to use the flag in all sorts of wrong ways...

There is space but I am afraid someone else will have to do this. I don't know much about that flag; only from reading #8395 I thought it was a low-hanging fruit :relaxed: and here we are half a year later :joy:

**Comment by Mikolaj** [comment]
> > That is fair and I agree. Is there no place in the docs to expand a little bit on the "internal" nature of this flag? I remember users trying to use the flag in all sorts of wrong ways...
> 
> There is space but I am afraid someone else will have to do this. I don't know much about that flag; only from reading #8395 I thought it was a low-hanging fruit :relaxed: and here we are half a year later :joy:

Could you open a short ticket about it and mark it `documentation`? Thank you.

I still don't see a changelog file. Am I missing it?

**Comment by Mikolaj** [comment]
Alternatively, perhaps let's not close https://github.com/haskell/cabal/issues/8395 and let's add the note about the docs there.

**Comment by andreabedini** [comment]
@Mikolaj I have added the changelog ;-)

**Review by Mikolaj — APPROVED** [review]
This looks fine. Thank you.

**Pull request merged**
