### PR TITLE
Partially linted

### PR DESCRIPTION
**Pull request by fgaz**
There are still lots of lint warnings, but I removed a good half of the worse ones ...if you don't count the redundant brackets, that is.

I rewrote the history while the old pr was closed, so apparently I can't reopen it

### CODE REVIEW

**Comment by ezyang** [comment]
I always get worried when I see lint commits but this one looks pretty good. CI is broken right now so I don't want to merge it yet but once we unbreak CI feel free to merge.

**Comment by fgaz** [comment]
Yeah, i checked each suggestion individually for correctness and consistency, so it should be safe.

I would merge it, but I can't seem to be able to do it, despite #3567

**Comment by 23Skidoo** [comment]
Some previous discussion on applying HLint hints: https://github.com/haskell/cabal/pull/1096 https://github.com/haskell/cabal/pull/1094

**Comment by 23Skidoo** [comment]
Yep, all these changes are pretty good.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
@fgaz 

> I would merge it, but I can't seem to be able to do it, despite #3567

On the settings page, it says that it's awaiting your response. Check your spam folder, there should be an invite link from GitHub.

**Comment by fgaz** [comment]
Oh ok, thanks, I thought it was automatic. They must have changed it after [this](https://www.reddit.com/r/programming/comments/4ur3n9/a_github_user_just_forked_the_unrealengine_repo/).

**Comment by 23Skidoo** [comment]
I can copy and send the invite link to you directly if you don't have it.

**Pull request merged**
