### PR TITLE
travis: use containers infrastructure

### PR DESCRIPTION
**Pull request by ttuegel**
Don't merge this yet, I'm just seeing what it would take to make this work.

### CODE REVIEW

**Comment by phadej** [comment]
@ttuegel check
- https://github.com/commercialhaskell/stack/wiki/Travis
- https://github.com/purescript/purescript/pull/1342

**Comment by ttuegel** [comment]
Thanks! I was afraid I would have to do something like that.

**Comment by phadej** [comment]
@ttuegel unfortunately `addons` section isn't mergeable, you have to copy&paste happy and alex everywhere :(

**Comment by ttuegel** [comment]
Any idea why it won't install `cabal-install-1.22` now?

**Comment by phadej** [comment]
@ttuegel there's another `matrix:` entry at the end of `.travis.yml`. Probably that.

**Pull request closed without merging**
