### PR TITLE
Add differenceVersionRanges

### PR DESCRIPTION
**Pull request by sjakobi**
Supersedes https://github.com/haskell/cabal/pull/3518.

### CODE REVIEW

**Comment by sjakobi** [comment]
Not sure what to do about the [Travis](https://travis-ci.org/haskell/cabal/jobs/142298406) [failures](https://travis-ci.org/haskell/cabal/jobs/142298408).

Maybe someone can just restart those jobs?

**Comment by phadej** [comment]
LGTM, ping @23Skidoo

**Comment by sjakobi** [comment]
Cheers!

**Comment by 23Skidoo** [comment]
Merged, thanks!

@sjakobi BTW, you don't have to close and reopen a PR every time you change something, you can just use `push --force` to update it in-place.

**Comment by 23Skidoo** [comment]
Also cherry-picked into `master`.

**Comment by sjakobi** [comment]
> @sjakobi BTW, you don't have to close and reopen a PR every time you change something, you can just use push --force to update it in-place.

I opened the new PR in order to target the `1.24` branch instead of `master`. I believe Github doesn't let you edit the target branch in an open PR.

**Comment by 23Skidoo** [comment]
@sjakobi Ah OK. Yes, I don't think it's possible.

**Pull request merged**
