### PR TITLE
[2.2, DO NOT MERGE] Revert "Merge pull request #4874 from zw3rk/feature/basedir"

### PR DESCRIPTION
**Pull request by 23Skidoo**
This reverts commit 783cbe6b86e7dbdcc5eaa8f7962caa574ef04fae, reversing changes made to c094940abc4266c8d013853b66271540cb2dc7f0.

The basedir patch breaks GHC (see https://github.com/haskell/cabal/issues/5075#issuecomment-369984102), so unless that issue gets fixed soon (@alpmestan, @angerman and @hvr are looking into it) we'll have to revert it on the 2.2 branch to unblock the 8.4.1 release.

---

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
To make it clear: this is plan B in case plan A (merging https://phabricator.haskell.org/D4453) doesn't work.

**Comment by angerman** [comment]
Current phabricator CI status:
- Windows: OK
- Linux: Waiting to build.
- macOS: some ext-int failures (which I can not locally reproduce on my mac...)

**Comment by hvr** [comment]
> macOS: some ext-int failures (which I can not locally reproduce on my mac...)

those seem completely orthogonal to the basedir patch; what I've figured out so far is that `-fexternal-interpreter` indeterministically segfaults... for no apparent reason; I had to invoke `ghc-stage2` in a loop for couple dozen times before it would segfault.

**Comment by 23Skidoo** [comment]
I see that D4453 has been merged, so looks like we won't need this. Closing.

**Pull request closed without merging**
