### PR TITLE
Support new section syntax for remote-repo.

### PR DESCRIPTION
**Pull request by mf59816**
Joint work with several people on zurihac.

Almost self-contained, and should be backwards-compatible.  The purpose of the change is that we want to add more fields to the remote-repo sections for hackage-security data types.

Hopefully there will be more progress tomorrow.

### CODE REVIEW

**Comment by mf59816** [comment]
futher things to do:

- root keys still have type `()`.
- special case: if there is a field-based remote-repo called hackage.haskell.org with the excpected url, replace it with the default, since that knows has the built-in root keys.
- cabal should warn thusly: `you are not secure.  to disable this warning, add 'no-tuf' field to the remote-repo `some.or.other`.`
- what about remote-repos in if-blocks in .cabal/config?

(anybody working on this: you are welcome to steal this branch, just notify me so we won't duplicate work.)

**Comment by edsko** [comment]
I will start building on this to actually support keys now, but PR LGTM at review.

**Comment by edsko** [comment]
Do we care that old cabal-install will choke on the new config file syntax with an "Unrecognized stanza" error? (@dcoutts will have an opinion on this.)

**Comment by mf59816** [comment]
I don't see how this can be avoided, and don't see a problem with that.  This must have happened to cabal during previous extensions of the package description language.

Btw, does hackage-security still depend on #2620?

**Comment by edsko** [comment]
No, it doesn't.

**Comment by edsko** [comment]
Incidentally, as part of actually adding for keys as part of a remote repo I changed the definition of `remoteRepoKeys` slightly to bring it more inline with the other sections (and make extension easier). See https://github.com/edsko/cabal/blob/using-hackage-security/cabal-install/Distribution/Client/Config.hs#L917-930 . This PR can stay as is though.

**Comment by edsko** [comment]
Ok, this all looks good. I've extended the section with two fields (the actual keys, and thekey threshold), and it all works fine. I suggest however we don't merge this until we merge Hackage security support proper.

**Comment by dcoutts** [comment]
I've merged it early because I want it for something else too.

**Pull request merged**
