### PR TITLE
Allow bytestring-0.11 + tree-diff-0.2

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Review by emilypi — APPROVED** [review]
Thanks for the bump @Bodigrim

**Comment by fgaz** [comment]
This only changes one of the generated files, and CI didn't catch it... again

**Comment by emilypi** [comment]
@fgaz sigh. Well, unreliable CI problems are yet another reason to rip it out, among the many there already are. After 3.6 i'll make sure that PR is split out early on from #7344

**Comment by fgaz** [comment]
@Bodigrim could you update the other files (`cabal-install.*`) in another pr?

**Comment by Bodigrim** [comment]
@fgaz which files? The ones I'm looking at (`cabal-install.cabal.{dev,prod,zinza}`) say `DO NOT EDIT MANUALLY`.

**Comment by emilypi** [comment]
@Bodigrim those turn out to be wrong. Edit the `zinza` and it should be fine.

**Pull request merged**
