### PR TITLE
Use enabledBuildInfos rather than allBuildInfo

### PR DESCRIPTION
**Pull request by ezyang**
In the previous documentation for 'ComponentEnabledSpec', I claimed
that enabled components were buildable, as well as requested
by the user.  In the course of working on #3847, however,
I realized that I hadn't actually *checked* that the component
was buildable anywhere.  In particular, the 'ComponentDisabled'
reason was *never used*.  This mostly didn't cause problems,
however, because when we 'flattenPD' all non-buildable components
get deleted, so you basically never actually have a non-buildable
'Component'.

But it still seemed a bit silly, so I fixed it by doing this:

1) I introduce a new concept of a component being requested,
which captures the use of --enable-tests and friends.  This
does NOT imply buildability.  Renamed ComponentEnabledSpec
to ComponentRequestedSpec

2) A component is enabled if it is requested and buildable.
If you give me a Component and a ComponentRequestedSpec I
can tell you if it's enabled.  However, if you give me a
ComponentName I can't, because I have no idea if it's buildable.

3) Stopped reexporting ComponentRequestedSpec from
Distribution.Simple.LocalBuildInfo

4) Added a test for attempting to specify a non-buildable
component as a target.  The test is accepting suboptimal
output at the moment, see #3858.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
Milestone note: this changes APIs of unreleased functions, so would be good to merge before 2.0.

**Comment by ezyang** [comment]
And the second part:

In many places, we incorrectly used allBuildInfo, which
returns all BuildInfos that are buildable, and not
necessarily the ones we are actually going to *build*.
This used to "mostly do the right thing" because we
literally edited the PackageDescription to nub out things,
so you wouldn't see non-enabled components anyway.  However
when I added support for per-component configure, I stopped
editing the PackageDescription, which meant all of these
uses were wrong.

So, I updated them to do the right thing. Note that there
are still uses of allBuildInfo in Check, but that probably
requires a closer look.

Fixes #3847.

**Comment by ezyang** [comment]
CC @hvr

**Comment by hvr** [comment]
Initial tests on IBM AIX (where I ran into the original issue because GHC 8.0 doesn't advertise `TemplateHaskell` support) look very promising

**Comment by dcoutts** [comment]
Ok, looks fine to me.

**Pull request merged**
