### PR TITLE
[cabal-3.8] bump bounds for ghc-9.4

### PR DESCRIPTION
**Pull request by juhp**
Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Comment by juhp** [comment]
Rather than moaning too much, I do wish at least Hackage revision were reflected in git.

**Comment by ulysses4ever** [comment]
@juhp they do (if you find a violation of that, please open a ticket).

As per the recently created revision policy, we only revise the latest major releases normally: https://github.com/haskell/cabal/issues/9531#issuecomment-1866930240 But this doesn't preclude occasional revisions to other releases. You just need to find someone with enough access rights to do the revision. It's harder than update the repository: we have way more approvers than Hackage maintainers.

**Comment by juhp** [comment]
@ulysses4ever 3.8 builds from Hackage but not from git.

I would suggest to revert that new policy.

**Comment by Mikolaj** [comment]
> @ulysses4ever 3.8 builds from Hackage but not from git.
> 
> I think that is too bad, and enough to make an exception.

Indeed. I wonder if we should even permit this adjustment without a successful CI run, exceptionally. Does it completely reflect the bounds on Hackage? Does CI build and fails only in tests? Are there any companion commits on master related to the bounds change?

> It's the first I hear of this new policy - I think it should be discussed more broadly if it wasn't.

It was mentioned in the Matrix channel, discussed in the ticket and decided in the fortnightly devs video chat. @juhp: would you like to attend the latter from time to time, e.g., if only to share the perspective of a distro packaging maintainer?

**Comment by Mikolaj** [comment]
@juhp: thank you for starting the discussion. I've now adjusted the policy as described at https://github.com/haskell/cabal/issues/9616#issuecomment-1902245983. If nobody objects, I will try to revise cabal 3.8 on Hackage according to the new policy and basing the process on this PR. If there are additional changes to the PR you'd like to make (any extra bound bumps?), please go ahead.

**Comment by juhp** [comment]
I am not aware of any more needed changes, so I think this is good to go.
The upperbounds are already in Hackage revisions.

**Review by Mikolaj — APPROVED** [review]
Oh, I see. I double-checked and you are right that Hackage doesn't need any action. Thank you for the PR.

**Review by Kleidukos — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify rebase 3.8

**Pull request merged**
