### PR TITLE
Fix typos in changelog entries

### PR DESCRIPTION
**Pull request by fgaz**
The changelog-d tool was rejecting those entries.

Maybe we should add a changelog-d call in ci...

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
Let's remember to add this to branch protection rules. As a separate entry or a part of something bigger?

**Comment by fgaz** [comment]
I made it run conditionally on the presence of changelog.d changes though, so I'm not sure if that's possible

**Comment by Mikolaj** [comment]
Doh, I just had to do all these changes by hand when releasing, because I forgot this PR existed. Marking it as requiring review.

**Comment by Mikolaj** [comment]
(All these changes except the CI part, which is what I hoped somebody would do seeing that I needed to make the changes. Or at least that somebody would open a ticket, me being too embattled with countless fixes needed to get the release off the ground. Thank you for the CI part, this is much needed.)

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
The PR in question is #8156, for the record.

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Comment by Mikolaj** [comment]
Merging so that it doesn't get lost and forgotten a second time.

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.8

**Pull request merged**
