### PR TITLE
Handle file:// urls in cabal.project files

### PR DESCRIPTION
**Pull request by dcoutts**
Just translate it to the local file case.

FYI: this is a trivial first step in a WIP branch on support for tarball packages, local and remote, which should make it easier to see how to integrate repo packages (ie git, darcs, etc)

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Should there be a test?

**Comment by dcoutts** [comment]
> Should there be a test?

Probably, but honestly this is such a silly corner case it's hardly worth bothering.

**Comment by 23Skidoo** [comment]
OK.

**Comment by ezyang** [comment]
Being a corner case is exactly why there should be a test. Otherwise, how do you know when it breaks?

**Comment by hvr** [comment]
...soo... what are we waiting for here btw? :-)

**Pull request merged**
