### PR TITLE
Add HLint configuraton.

### PR DESCRIPTION
**Pull request by philderbeast**
HLS often alerts me to one HLint suggestion or another in this project. This adds a default configuration that silences these and shows how many of each suggestion we have so that when we want to tackle these we can.

### CODE REVIEW

**Comment by ulysses4ever** [comment]
After @Kleidukos added the auto-formatting (via Fourmolu) I was thinking that HLint should be the next step. But simply adding the file with exceptions doesn't seem very useful. Imagine someone adds a patch that regresses some of these metrics (so the numbers will loose any meaning over time) or adds code that would need another HLint flag to silence it (so, you're back to square one seeing warnings locally).

The way to go I think is to add a CI job alongside the HLint config.

**Comment by ffaf1** [comment]
> The way to go I think is to add a CI job alongside the HLint config.

Some Hlint suggestions canbe really annoying (e.g. all those `redundant $`, I bet half of those are in tests which follow a specific template — yes you can remove the `$` but the day someone copies your code they will maybe get an annoying compilation error).

Sorting which ones are useful (always) and which not could be a good first step.

I wonder what other large codebases do.

**Comment by ulysses4ever** [comment]
I don't suggest to sort anything out. Just add a CI job along with the config file. Hopefully, the job could check that we don't regress beyond the current values in the file.

**Comment by philderbeast** [comment]
The approach we took with [liquid-fixpoint##552](https://github.com/ucsd-progsys/liquid-fixpoint/issues/552) was to tackle one hint at a time, each with its own pull request. For those hints we didn't want to adopt, we kept the ignores. The counts are useful for gauging which of the hints to tackle next.

```yaml
# The following are kept for usability and style sake
- ignore: {name: "Avoid lambda"} # 4 hints
- ignore: {name: "Eta reduce"} # 30 hints
- ignore: {name: "Use $>"} # 7 hints
- ignore: {name: "Use <$"} # 1 hint
- ignore: {name: "Use infix"} # 4 hints
```

**Comment by philderbeast** [comment]
> The way to go I think is to add a CI job alongside the HLint config.

I actually started doing this as well but then saw that the gh-action wasn't running in my fork (after altering the `on` condition too) but I would be happy to add this too (in another pull request preferably).

**Comment by ulysses4ever** [comment]
@philderbeast did you allow actions on the fork? By default they are disabled, see the screenshot
Screenshot_20230618-134339

My opinion is that the action should go in the same PR as the config file for the reasons described above. But others may feel differently.

**Review by ulysses4ever — APPROVED** [review]
Oh, you should have pinged me. Thanks a lot for doing this! Let's hope someone else adds the second approval.

**Review by geekosaur — APPROVED** [review]
LGTM

**Comment by ulysses4ever** [comment]
Now, after 2 approvals, feel free to apply one of the merge labels. I'd expect squashing (via label or manually).

**Comment by andreabedini** [comment]
Yes please!

**Comment by ulysses4ever** [comment]
@Mergify rebase

**Comment by ulysses4ever** [comment]
@philderbeast could you please allow maintainers' updates of your patch? Otherwise it's very tricky to make our merge bot happy.

**Comment by ulysses4ever** [comment]
@philderbeast same here: our merge policy (rebased) requires permissions to update your branch

**Comment by philderbeast** [comment]
> @philderbeast same here: our merge policy (rebased) requires permissions to update your branch

I haven't been able to find where to do that for an organisation-owned fork. The advice for this setting is for user-owned forks.

> On user-owned forks, if you want to allow anyone with push access to the upstream repository to make changes to your pull request, select Allow edits from maintainers.
> [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
> [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by philderbeast** [comment]
@ulysses4ever I did the squashing myself.

**Comment by ulysses4ever** [comment]
@philderbeast thank you and sorry for the inconvenience. It's not only squashing it's also rebasing that bites us. I have a to-do to look into supporting people who can't / won't allow updating their branches: this does come up once in a while. We could have a separate, merge-based workflow besides the current rebase-based one.

So far let's hope that by the time CI finishes master won't update.

**Comment by philderbeast** [comment]
@ulysses4ever I rebased at the same time as squashing, if that helps.

**Comment by ulysses4ever** [comment]
@philderbeast yes, thank you, this helps a bit. The issue is that every update starts CI which will take time to pass, and during that time master can get updates. Currently, any master update, even non-conflicting one, will make the whole thing fail because the merge bot is set up to rebase in such case, and it can't rebase without the permission. We need to create a bot setting that would simply merge instead of rebase for cases when the bot is not allowed to rebase.

**Comment by ulysses4ever** [comment]
@philderbeast thanks and sorry it took so long! I noticed you have a couple older PRs open. Do you want to do anything about them?

**Pull request merged**
