### PR TITLE
Add `Distribution.Simple.Utils.ShortText` type

### PR DESCRIPTION
**Pull request by hvr**
This implements a compact representation of `[Char]`.

The data is stored internally as UTF8 in an `ShortByteString`
when compiled against `bytestring >= 0.10.4`, and otherwise in a
(strict) `ByteString`.

### CODE REVIEW

**Comment by ezyang** [comment]
Did you look at any perf numbers? ;)

**Comment by hvr** [comment]
@ezyang the idea is to e.g. use it e.g. a `newtype PackageName = PN ShortText`, which would then look like https://github.com/haskell/cabal/pull/3896#issuecomment-249428236

**Comment by ezyang** [comment]
Looks good.

**Comment by dcoutts** [comment]
@hvr no need to change this now, but if we start using this internally for more opaque types in Cabal then we will likely need to promote it to it's own module in `Distribution.*` to avoid cycles, or just to maintain the sanity of the `Distribution.*` vs `Distribution.Simple.*` distinction.

And we should agree not to expose this type in the API. Whenever we want to expose it we should convert to String or Text. This becomes slightly less bad if/when the text package gains a ShortText, but still applies then. Same with ShortByteString, we should not expose them in APIs.

**Comment by hvr** [comment]
for the record, @dcoutt's last comment was implemented via e204a3469e1c640f08abd04d38647d043977f9c2 as it became necessary anyway

**Pull request merged**
