### PR TITLE
Print out which project file we're using by default (fix #8519)

### LINKED ISSUE #8519: Display within which cabal.project we build
**Describe the bug**

The `cabal` behaves differently depending whether any of the ancestor directories has `cabal.project` or not.
Since we should not demand the user to only ever test builds within a fresh `/tmp` directory, and large builds
may easily have multiple `cabal.project`s, it would be nice to warn the user which `cabal.project` we use, or that there is none used in this case.

**To Reproduce**

```
$ git clone https://gitlab.com/migamake/homplexity
$ cabal new-build
$ cabal sdist
$ cd dist-newstyle/sdist
$ tar xzf homplexity-*.tar.gz
$ echo "Let's test the build...."
$ cd homplexity-*
$ cabal new-build
```
This build breaks.

If we do:
```
$ mkdir /tmp/homplexity-test
$ tar xzf $MYPATH/homplexity*.tar.gz
$ cabal new-build
```
We get a correct build.

The only difference is absence of the `cabal.project` file in the second case.

**Expected behavior**

`cabal new-build` should tell why its behaviour differs by indicating which `cabal.project` is used,
or printing `no cabal project`.

**System information**
 - any
- `cabal` 3.4.1,0
- `ghc` version -- does not matter

### PR DESCRIPTION
**Pull request by ulysses4ever**
Attempting to resurrect #8617

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Converting to a draft because of spurious changes like https://github.com/haskell/cabal/pull/10507/files#diff-d6f32a6a398cc85df21df74b2a260427387c0ea52d96987e49551137d466d92fL7 Will see what CI has to say.

**Comment by ulysses4ever** [comment]
I bet it's because the `--intree-cabal-lib` business...

**Comment by geekosaur** [comment]
I gave up on making that work when I was bisecting an issue and wanted to streamline validate a bit.

**Comment by ulysses4ever** [comment]
Okay, fixed by running with the in-tree Cabal:

```
❯ cabal run cabal-testsuite:cabal-tests -- --with-cabal=(cabal list-bin cabal) --accept --intree-cabal-lib $PWD --test-tmp $PWD/testdb
```

**Comment by ulysses4ever** [comment]
I'll put the label requesting reviews after CI is happy.

**Review by Mikolaj — APPROVED** [review]
A good decision. And well tested. :)

**Comment by ulysses4ever** [comment]
Thanks! Since it's been up for 5 days, I consider the chill out period passed and apply the label manually in the interest of getting this merged in time for 3.14.1 (the final decision about addition to 3.14.1 is up to Hécate of course).

**Comment by ulysses4ever** [comment]
@mergify backport 3.14

**Pull request merged**
