### PR TITLE
Version range refactor

### LINKED ISSUE #4780: QuickCheck failure in the parsec . display test
See https://travis-ci.org/haskell-pushbot/cabal-binaries/builds/278106292#L692:

```
parsec . display involutive:                           FAIL
      *** Failed! Falsifiable (after 2 tests): 
      UnionVersionRanges (VersionRangeParens (LaterVersion (mkVersion [1]))) (ThisVersion (mkVersion [1]))
      Just (UnionVersionRanges (LaterVersion (mkVersion [1])) (ThisVersion (mkVersion [1]))) /= Just (UnionVersionRanges (ThisVersion (mkVersion [1])) (LaterVersion (mkVersion [1])))
      Use --quickcheck-replay=729075 to reproduce.
```

@phadej, is this related to the recent Parsec changes?

### PR DESCRIPTION
**Pull request by phadej**
Fixes #4780. `VersionRange` now faithfully represents the input grammar.

TODO:
- [x] split `Version` module into `Version`, `VersionRange` and `VersionIntervals`.
- [x] add `since` annotations.
- [x] deprecate `mkVersionIntervals`, create proper inverse of `asVersionIntervals`.

I'll complete the PR if the approach is ok.

---

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
The general direction looks good, I'll do a more detailed review later today or tomorrow.

**Comment by phadej** [comment]
@23Skidoo this is ready for review.

**Comment by phadej** [comment]
ping @23Skidoo. 

I'd like this to get merged, as my further changes towards SPDX depend on it. We have to split modules, to avoid cycles :)

**Comment by 23Skidoo** [comment]
I'm merging this, but see the comment above.

**Comment by 23Skidoo** [comment]
Merged, thanks! Sorry for the delay.

**Pull request merged**
