### PR TITLE
Experiment with Travis's build stages.

### PR DESCRIPTION
**Pull request by 23Skidoo**
See #4556.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Doesn't seem to work, so I'm putting this on the back burner.

**Comment by 23Skidoo** [comment]
Great success! Finally managed to enable multiple build stages: https://travis-ci.org/haskell/cabal/builds/241458856.

**Comment by 23Skidoo** [comment]
Closing this, since I don't think that enabling build stages is currently worth it.

**Comment by 23Skidoo** [comment]
I'm not deleting the branch, so if anyone wants to pick this up, she is welcome to do so.

**Comment by hvr** [comment]
at least we tried...

**Pull request closed without merging**
