### PR TITLE
Haddockumentation fixes in Distribution.Types.VersionRange.Internal

### PR DESCRIPTION
**Pull request by andreasabel**
Haddockumentation fixes in `Distribution.Types.VersionRange.Internal`

- 2 typos
- meaningful doc for `wildcardUpperBound`
- cosmetics

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Thank you very much. BTW, CI is currently broken in two different (visible) ways, we are working on it.

**Comment by Mikolaj** [comment]
Rebasing after CI fixed.

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Comment by Mikolaj** [comment]
Rebasing after CI really fixed.

**Comment by Mikolaj** [comment]
@Mergifyio rebase

**Review by Kleidukos — APPROVED** [review]

**Pull request merged**
