### PR TITLE
Fix bug in dependency solver stanza preferences

### PR DESCRIPTION
**Pull request by grayjay**
The first commit creates a newtype for the weak/trivial attribute of package flags and stanzas.

The second commit fixes a bug in dependency solver stanza preferences. Previously, stanza choices were set to "weak" even when the stanza preference did not apply. See https://github.com/haskell/cabal/issues/3453#issuecomment-222580111.

@kosmikus Does it make sense to call the newtype `WeakOrTrivial`?  I'm still not completely sure I understand the meaning of the weak/trivial fields in the solver's `FChoice` and `SChoice` nodes.

### CODE REVIEW

**Comment by kosmikus** [comment]
LGTM.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by grayjay** [comment]
Thanks!

**Pull request merged**
