### PR TITLE
WIP: Create package indexes implicitly by traversing the file system

### PR DESCRIPTION
**Pull request by tibbe**
This is a work in progress pull request created to solicit early feedback.

This is part of #2631.

/cc @dcoutts

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Fails on GHC < 7.10.1 due to `Version.makeVersion` not being available.

**Comment by 23Skidoo** [comment]
Otherwise looks good to me.

**Comment by tibbe** [comment]
Removed the use of `Version.makeVersion`.

**Comment by dcoutts** [comment]
Note that the nix-local-build branch does something like this. The default if you don't create a cabal.project file is to look in the current dir and all immediate subdirs for packages. It's equivalent to an explicit cabal.project file of:

    packages: ./*.cabal, ./*/*.cabal

The good thing about this is it's convention over configuration, and lets you do `cabal unpack blah` and it'll use that local version automatically. The potential downside is that it's perhaps not always clear what packages it's using, though this can perhaps be solved by emitting appropriate status messages.

**Comment by BardurArantsson** [comment]
Given that nix-local-build seems to be the chosen approach, perhaps we should just close this? (And #2631 along with it?)

**Pull request closed without merging**
