### PR TITLE
Update pretty printing to use 2 space indent.

### PR DESCRIPTION
**Pull request by m-renaud**
This is inline with all the documentation and examples I've seen throughout the cabal docs, as well as all cabal file templates I've seen in the wild and those constructed with stack and summoner (the two other leading ways to initialize a project). It appears that `cabal format` hasn't been released yet so this is unlikely to cause a large number of diffs.

/cc @phadej who made the original change.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by m-renaud** [comment]
Will update tests if this LG.

**Comment by m-renaud** [comment]
> Obviously, I like 4 space more myself.

;P

/cc @hvr @23Skidoo @gbaz (?) Not sure how to get a go/no-go on this, maybe :+1: :-1: 's on the PR?

**Comment by phadej** [comment]
FWIW, I have a PR in preparation (blocked by #5723) to refactor pretty printing a little (it reformats everything too, makes output prettier).

**Comment by 23Skidoo** [comment]
idk
Can we get a before/after comparison?

**Comment by 23Skidoo** [comment]
I'm neither for nor against. `Cabal.cabal` uses 2 spaces, `cabal-install.cabal` uses a mix (which is a bit ungood).

**Comment by phadej** [comment]
This PR is obsoleted technically after https://github.com/haskell/cabal/pull/5799 is merged.

Changing `4` to `2` would be easier, if needed.

**Comment by m-renaud** [comment]
Closing this due to @phadej's reply above.

**Pull request closed without merging**
