### PR TITLE
bootstrap: prepare for ghc 8.4.1

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
Only item left is hackage-security which should be released any day now (https://github.com/haskell/hackage-security/issues/211).

**Comment by hvr** [comment]
@tuncer we also need #5209 merged & backported, as otherwise the resulting `cabal` executable will be unusable

**Comment by tuncer** [comment]
Right, but the bootstrap changes alone are safe with 8.2.2. Thus, we could merge this now and later bump only hackage-security.

**Comment by tuncer** [comment]
ping?

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
