### PR TITLE
Document that Cabal passes -O2 to C compilers

### PR DESCRIPTION
**Pull request by cocreature**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

The relevant code for this can be found in https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/GHC/Internal.hs#L280. Thanks to @hvr for pointing me to it.

### CODE REVIEW

**Comment by cocreature** [comment]
> LGTM, feel free to merge.

I don’t have commit access so I would appreciate if someone else could merge this :)

**Comment by 23Skidoo** [comment]
Hmm, for some reason I thought you've already had several PRs accepted. You have commit access now.

**Comment by cocreature** [comment]
> Hmm, for some reason I thought you've already had several PRs accepted. You have commit access now.

I’ve had a few accepted but most of those were quite some time ago, see https://github.com/haskell/cabal/pulls?q=is%3Apr+author%3Acocreature+is%3Aclosed if you want a list. Thanks for the commit bits :)

**Comment by 23Skidoo** [comment]
So most of them except #4549 were in 2015, before we started giving out commit bits more liberally. I guess I assumed that you had them already when I reviewed #4549.

**Pull request merged**
