### PR TITLE
Fix issues with OSX builds after nubbing hsc2hs arguments

### PR DESCRIPTION
**Pull request by anton-dessiatov**
This is a fix I came up for @christiaanb issues (see #2516 for additional details). I've just splitted hsc2hs arguments in two parts. One part is nub'ed, another isn't. ```-framework``` flags are in the latter part.

@christiaanb could you please check if this PR fixes build failures on OS X?

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@anton-dessiatov Are you sure that this bug exists only in OSX code and won't bite us in other contexts?

**Comment by anton-dessiatov** [comment]
Not really. The issue is that if there are cflags that work in groups then these groups have to be treated  as a whole (like ```-framework CoreVideo```, which are essentially two flags, but they cannot be splitted). If some other code decides to bring agrument groups like that, the thing will break again.

**Comment by 23Skidoo** [comment]
Then we probably should revert that change altogether.

**Comment by anton-dessiatov** [comment]
Probably yes, because it was just a workaround for limited length of Windows command line argument string.

The ultimate solution would be to patch ```hsc2hs``` to accept command line arguments from a file (like Visual Studio tools do with ```.rsp``` files) and pass them in a temporary file instead of a command line. Maybe I'll come with that later.

**Comment by 23Skidoo** [comment]
We already do it for Haddock.

**Comment by 23Skidoo** [comment]
Reverted #2516 in fe7b8784ac0a5848974066bdab76ce376ba67277, so closing.

**Comment by 23Skidoo** [comment]
@anton-dessiatov BTW, if you decide to write a patch for `hsc2hs`, one thing to think about is how to handle arguments with spaces in them. With Haddock we went for a simple solution: each argument on its own line. However, the standard solution (used by `gcc` for example) is to use quotation marks (both single and double quotation marks are supported).

**Pull request closed without merging**
