### PR TITLE
[RFC] Add option to find best install plan before backjump limit

### PR DESCRIPTION
**Pull request by grayjay**
I've started implementing install plan scoring, as described in #2860.  `cabal install` now prints the score of each install plan and allows the user to find better plans with the option `--max-score`, where zero is perfect.  `cabal` should find the same install plans as before when no maximum is specified.  This pull request isn't ready to be merged yet.  It needs documentation and tests, and I have a few questions in TODO comments.  Also, this is the most basic way to expose install plan scoring, and it might be better to automate determining when to continue searching before this is merged.

I rebased onto #2916 because this change made the existing space leak worse.  Then I compared performance between #2916 and the latest commit.  Memory usage is similar, but the latest commit is noticeably slower when the solver runs for longer.  I compiled cabal with GHC 7.10.2 and ran `cabal --ignore-sandbox install --dry-run --max-backjumps -1` with the following packages and compilers:

| Package | Compiler | Measurement | https://github.com/haskell/cabal/commit/c1189c3d61585207e99818531e3cd990d4babf3a (#2916) | https://github.com/haskell/cabal/commit/868909732813b584aa15c3ccd62e8469063f9122 (#2917) |
| --- | --- | --- | --- | --- |
| aeson | GHC 7.10.2 | time | 0.884 s | 0.876 s |
| hackage-server-0.4 | GHC 7.10.2 | time | 6.01 s | 6.66 s |
| hackage-server-0.4 | GHC 7.6.3 | time | 122.6 s | 140.5 s |
| hackage-server-0.4 | GHC 7.6.3 | total memory (`+RTS -s`) | 256MB | 258MB |

These comments that I made on the issue are still relevant:
https://github.com/haskell/cabal/issues/2860#issuecomment-149114193
https://github.com/haskell/cabal/issues/2860#issuecomment-151069126

### CODE REVIEW

**Comment by grayjay** [comment]
I rebased this to deal with conflicts and made a few minor changes that shouldn't affect the behavior.

**Comment by 23Skidoo** [comment]
@kosmikus, would be nice if you could provide @grayjay with some feedback on this.

**Comment by BardurArantsson** [comment]
@grayjay Note that there are now new conflicts, probably because my dead code removal patch was merged.

**Comment by grayjay** [comment]
I resolved the conflicts.  The dead code removal actually shortened the diff by about 80 lines.

**Comment by grayjay** [comment]
I tried exposing install plan scoring in a more user-friendly way.  The latest commit adds a new option, `--find-best-solution`.  The solver searches until the backjump limit and then uses the best-scoring install plan found.  If there is no backjump limit, the search is exhaustive.  The only benefit of `--max-score` now is that it can allow the solver to run faster by pruning low-scoring nodes during the whole run.  `--find-best-solution` works by decreasing the maximum allowed score as the solver finds better and better solutions.

There are a few things I'd like to improve if this feature is added to cabal:
* The solver is much slower than on master.  This branch ran for 43% longer in one long-running test.
* On master, `explore` creates a log from the search tree, and then `logToProgress` processes the log and applies the backjump limit.  I think it would be easier to implement the interaction between `--max-backjumps` and `--find-best-solution` if I first moved application of the backjump limit into `explore`.  That would take significant refactoring, though.  This branch currently just stores the best install plans in the log entries, which is awkward.
* I think `--max-score` is unnecessary if we have `--find-best-solution`, but I left it in for testing.

**Comment by kosmikus** [comment]
@grayjay Thanks for rebasing this. I'm hoping that I can finally take a look at this soon.

**Comment by grayjay** [comment]
@kosmikus Thanks.  I just rebased on top of the module reorganization and added some comments and quickcheck tests.  I also added a commit that does dynamic goal reordering based on conflict sets.  It sometimes finds the best solution faster, especially when combined with `--reorder-goals`.

**Comment by kosmikus** [comment]
@grayjay Thanks! I had just been experimenting with the same/a similar thing. My "dynamic-goal-reordering" branch is at https://github.com/kosmikus/cabal/tree/count-conflicts

My initial experiments with this have been very promising. There are only very few cases where it seems to be slower, and many where it seems to perform vastly better. So I'd actually be optimistic that something like this can become the new default.

I will have a look at how our approaches differ, if at all.

**Comment by grayjay** [comment]
@kosmikus Cool!  I'm interested in looking at your branch when I have time.

I added `--dynamic-goal-reordering` a while ago without pushing it, and I just realized that I never finished it.  I wanted the solver to try choosing goals that were in the last conflict set, because they are likely to also fail in the next subtree.  My code is using the wrong conflict set, though.  Sorry about the mix-up.  The first two commits should be ready for review.

**Comment by kosmikus** [comment]
@grayjay Right, this corresponds to what I'm doing, only that I'm actually not just considering the "last" conflict set, but counting how often each goal was involved in conflicts and use that for sorting.

**Comment by grayjay** [comment]
@kosmikus I fixed the bug in `--dynamic-goal-reordering`.  Now it actually seems like an improvement!  I haven't tested it thoroughly, though.

I wanted to do something more complex, but I haven't implemented it.  The solver would prefer goals whose variables are contained in conflict sets at any level, but prefer variables at lower levels over variables at higher levels.  For example, when the solver is at node 4, it would first look for goals in the conflict set at node 3, then node 2, and finally node 1. (I left out the goal nodes and other children.)  This PR only uses the conflict set at node 3.

tree-2

The reason that I used conflict sets from non-`Fail` nodes is that I thought it might deal with the case where the solver spends a long time solving for a few goals, only to hit an unrelated, unresolvable conflict farther down in the tree. If that pattern repeats in siblings' subtrees, the solver could try the goals involved in the unresolvable conflict first and give up faster on those subtrees.

I tried your branch on a few packages that my PR couldn't handle, at least without `--reorder-goals`, and it was fast!  It seems like a good default, so far.  I'm curious to see how it interacts with `--find-best-solution`.

**Comment by kosmikus** [comment]
@grayjay FYI: I have pushed https://github.com/kosmikus/cabal/tree/count-conflicts-2 that is a version of `count-conflicts` on top of current master.

**Comment by grayjay** [comment]
@kosmikus I'm getting a compiler error on the new branch:

```
Distribution/Solver/Modular/Explore.hs:122:35:
    Couldn't match type ‘Goal QPN’ with ‘OpenGoal ()’
    Expected type: P.PSQ
                     (OpenGoal ())
                     (Assignment
                      -> ConflictMap
                      -> (ConflictSetLog (Assignment, RevDepMap), ConflictMap))
      Actual type: P.PSQ
                     (Goal QPN)
                     (Assignment
                      -> ConflictMap
                      -> (ConflictSetLog (Assignment, RevDepMap), ConflictMap))
    In the second argument of ‘getBestGoal’, namely ‘ts’
    In the expression: getBestGoal cm ts
```

**Comment by kosmikus** [comment]
@grayjay Sorry, I made a mistake when pushing. I force-updated the branch.

**Comment by grayjay** [comment]
@kosmikus Thanks.  I tried it on a few more packages, and it seems to work really well.  I'll look at the code when I have more time.

**Comment by grayjay** [comment]
@kosmikus I started rebasing this onto master, because I think it will be easier to split it apart when it is up to date.

**Comment by grayjay** [comment]
I'm done rebasing.

**Comment by grayjay** [comment]
I rebased onto #3594.

**Comment by grayjay** [comment]
This PR needs more work.

**Pull request closed without merging**
