### PR TITLE
Forwardport 3.8.0

### PR DESCRIPTION
**Pull request by Mikolaj**
This forward-ports parts of  #8157 from branch 3.8 to master. Next time we should be smarter and do more of the work on master beforehand instead of manually forward-porting. Still, a portion of this is different on both branches (notably, new version numbers) so has to be done separately on both branches.

### CODE REVIEW

**Comment by Mikolaj** [comment]
I needed to revise hackage-security to permit Cabal 3.9.

**Comment by Mikolaj** [comment]
Doh, Hackage did not propagate the revision yet. Trying again soon.

**Comment by Mikolaj** [comment]
Now it contains some more fixes for problems spotted in candidate packages.

**Comment by Mikolaj** [comment]
And I also added a refreshed bootstrap. I guess that's all for this PR.

**Comment by Mikolaj** [comment]
Edit: I force-reverted the boostrap refresh, because then CI fails. See https://github.com/haskell/cabal/issues/8166. Instead I manually tweaked the boostrap jsons to compile with new Cabal version.

**Comment by Mikolaj** [comment]
Now that's really all for this PR, promise.

**Comment by jneira** [comment]
> Still, a portion of this is different on both branches (notably, new version numbers) so has to be done separately on both branches.

or split an only version changes, if possible
wonderful work, thanks for take care of the new release epic work

**Review by Kleidukos — APPROVED** [review]

**Review by jneira — APPROVED** [review]
lgtm with a very quick review

**Pull request merged**
