### PR TITLE
Prepare 3.8.1.0 release on master

### PR DESCRIPTION
**Pull request by Mikolaj**
This is done according to the (constantly updated) https://github.com/haskell/cabal/wiki/Making-a-release.

### CODE REVIEW

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Review by Kleidukos — APPROVED** [review]
:rocket:

**Review by jneira — APPROVED** [review]
amazing work, many, many thanks for driving the release

**Comment by Mikolaj** [comment]
Thank you for reviews. Force-merging skipping delay.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
