### PR TITLE
Tests for solver support language extensions and language flavours

### PR DESCRIPTION
**Pull request by jdnavarro**
These are the tests and the corresponding DSL modifications required for merging PR #2732. I don't think GitHub lets you reuse PR issue number so that's why I'm submitting a new PR.

Aside of general mistakes, please check I'm not missing any important test case.

I acknowledge the commit history is not very clean, let me know if you want me to clean it up.

/cc @kosmikus @luigibozzo

### CODE REVIEW

**Comment by kosmikus** [comment]
Thanks a lot. I'll try to take a look.

**Comment by 23Skidoo** [comment]
Nice!

**Comment by BardurArantsson** [comment]
Ooooh! Interesting, I'll try to have good gander at this tomorrow. (Not that I decide anything, obviously.)

**Comment by kosmikus** [comment]
@jdnavarro Sorry for the long delay. Yes, this all looks good as far as I can see. Thanks! I think it would indeed be nice if you could rebase and squash all of the test-related commits (so that in principle there are only two changes in this PR: my solver change and your tests change).

**Comment by jdnavarro** [comment]
@kosmikus, I had to redo the merge conflicts we resolved at the hackathon in order to include them in your commit, so please have a look at your your commit too.

**Comment by BardurArantsson** [comment]
@ "the management" :) :

Any reason we shouldn't just push the "merge" button on this?

We're piling up quite a bit of solver changes in the PR queue and unfortunately many of them seem to be conflicting :(.

See also discussion in: #2928#issuecomment-157479392

**Comment by 23Skidoo** [comment]
The reason is that @kosmikus seems to be busy with other things.

**Comment by BardurArantsson** [comment]
AFAICT this is "new functionality" + "tests of said functionality". I don't understand the solver code, but the tests look pretty reasonable and seem like they cover at least the basic functionality...?

Of course, if @kosmikus  thinks the tests *aren't* comprehensive enough, then that's perhaps worth blocking this on.

**Comment by BardurArantsson** [comment]
I mean, if we're getting nervous about merging PRs *with tests* (with some semblance of coverage), then I'm going to get really worried :).

(Unless of course we're talking about things that are clearly out-of-scope for the project, but that's another matter.)

**Comment by 23Skidoo** [comment]
@kosmikus has the final word on everything related to the solver, and since he assigned this PR to himself, it's up to him to review and merge it.

**Comment by BardurArantsson** [comment]
Fair enough, I guess.

I wonder if it would be a good idea to make "ownership" explicit, per http://meowni.ca/posts/chromium-owners/ ?

(I certainly know that *I* have no idea about who "owns" what bit of Cabal/cabal-install. Maybe it would be a good idea to make it explicit via OWNER/MAINTAINER files or something similar? It would certainly help to be able to ping the right people when making "drive-by" contributions.)

**Comment by BardurArantsson** [comment]
@kosmikus Any idea when you'll be able to look at this?

(Btw, I realize that I can be a little bit of a "bull in a china shop", but it's getting quite frustrating to have to put everything solver-related on hold. I'm also worried about the bus factor of 1 on the solver :/ .)

**Comment by kosmikus** [comment]
@BardurArantsson I can understand your frustration, and share it: I'm frustrated myself that I haven't managed to look at anything related to Cabal in the past few weeks ... I'm also sorry, because I really appreciate these contributions. For this one, I'm relatively sure this is all fine, because I've already looked at a previous version, so I guess you can go ahead and merge it without another review by me.

**Comment by jdnavarro** [comment]
Actually the trickiest part of my commit was extending the testing DSL. I'd have more peace of mind if I explicitly knew I didn't butcher @edsko code.

**Comment by edsko** [comment]
What wait? Who butchered my code?? 😡 :-)

**Comment by jdnavarro** [comment]
@edsko, what do you think of this function? https://github.com/jdnavarro/cabal/commit/594335b1af7a2dc54659b5c81266dda12d3dfcb8#diff-b49d34e968c603ec0c673e0c5c33a9cdL134

**Comment by edsko** [comment]
Ah, this is what we briefly discussed at the hackathon? Without studying it in great detail your changes look reasonable.

**Comment by jdnavarro** [comment]
@edsko, yes, this is what we discussed at the Hackathon but we didn't have time to wrap it up.

**Comment by BardurArantsson** [comment]
@kosmikus : Don't feel too bad -- nobody has infinite amounts of time and we all have to prioritize. I wonder if there's anybody who might be suitable to be a "co-owner" of the solver subsystem just so that we can increase the bus factor and avoid pipeline stalls...?

Given that the concensus here seems to be that this looks good, I'd be happy to press the "Merge" button. @dnavarro : Any chance you could rebase on top of current master? (Just to make the commit graph look a little nicer :).)

**Comment by dnavarro** [comment]
Hi! @BardurArantsson I think you meant to tag @jdnavarro in the above comment :)

**Comment by BardurArantsson** [comment]
Doh! Yes, sorry about that :)

**Comment by jdnavarro** [comment]
@BardurArantsson There you go

**Comment by BardurArantsson** [comment]
Merged, thanks!

**Comment by phadej** [comment]
:+1:

**Pull request merged**
