### PR TITLE
Revert "Drop sub-component targets (#8966)"

### LINKED ISSUE #9688: Removal of sub-component targets breaks HLS/hie-bios
**Describe the bug**

https://github.com/haskell/cabal/pull/8966 removes cabal-install's support for sub-module targets.

But this (mis-)feature is used by HLS via hie-bios to determine the flags for a component.

In particular it makes a call to `cabal v2-repl <path to a .hs in the component>`

**To Reproduce**

Have a prerelease of cabal-install on your PATH
```
$ cabal repl <path to a .hs file>
Warning: this is a debug build of cabal-install with assertions enabled.
Error: [Cabal-7121]
Failed extracting script block: `{- cabal:` start marker not found
```
or
```
$ haskell-language-server <path to .hs file or a component target>
...
Loading the module 'so-and-so.hs' failed.

  It may not be listed in your .cabal file!
  Perhaps you need to add `so-and-so` to other-modules or exposed-modules.
```

**Expected behavior**
HLS should at least work.
Perhaps some work needs to be done to migrate HLS/hie-bios off this feature.
Alternatively the MR could be reverted.

**System information**
tested using cabal-head

### PR DESCRIPTION
**Pull request by fendor**
This reverts commit 3f4c81fd7936fa6dcdcac833ae42cc4158b1823a.

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

Closes #9688

### CODE REVIEW

**Comment by fendor** [comment]
This does not need to be merged as is but serves as somewhat of a reminder :)

**Comment by andreabedini** [comment]
<rant>It's clear the ecosystem is put togheter with sticky tape</rant>

If this is the only option, I reckon it's a fair call to revert.

**Review by mpickering — APPROVED** [review]

**Comment by Mikolaj** [comment]
A random CI infra failure: "Mikolaj token is invalid, make sure Mikolaj can still log in on the [Mergify dashboard](https://dashboard.mergify.com/)."

I will keep insisting.

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify queue

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
I'm able to rebase just fine in https://github.com/haskell/cabal/pull/9698, so may this be something wrong with the PR? I can see "Maintainers are allowed to edit this pull request" and I don't know what else can be broken. @ulysses4ever, any ideas?

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
> @ulysses4ever, any ideas?

not really. Let's rebase via the github UI, perhaps? It worked fine and helped some times in the past. After that, the bot may be able to proceed..

**Comment by Mikolaj** [comment]
Thanks, I rebased via the UI button.

**Comment by Mikolaj** [comment]
@ulysses4ever, you are a wizard!

**Pull request merged**
