### PR TITLE
Deduplicate `LD_LIBRARY_PATH` when running tests

### PR DESCRIPTION
**Pull request by 9999years**
When Cabal runs a test suite, it adds all the dependent libraries to `LD_LIBRARY_PATH`. In some cases, this can exceed the operating system's `ARG_MAX` limit:

    dist/build/test/test: createProcess: posix_spawnp: resource exhausted (Argument list too long)

However, many of the entries (observed as high as 75%!) in `LD_LIBRARY_PATH` are duplicates. Deduplicating the list with `ordNub` fixes this error.

This error was originally observed when testing a large commercial Haskell project (the mercury.com backend). Ideally, `depLibraryPaths` would be fixed to not return duplicate entries, but this fixup is low-cost and effective.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

Prior art:
- #4105

### CODE REVIEW

**Comment by lf-** [comment]
For what it's worth, this is *likely* a reasonable idea to fix the code that's there, but the use of LD_LIBRARY_PATH at all for this purpose is probably wrong to begin with and the code should be changed. Cabal should be emitting executables that have been linked with the correct `-rpath` to pull in their dependencies, rather than bodging with LD_LIBRARY_PATH.

One major hazard of the use of this environment variable is that it is used *preferentially* to the `rpath` values specified while building the executable. This means that system libraries may inadvertently be overridden (especially on Nix systems where rpath is relied upon to allow coexistence of multiple versions of anything). This becomes even more perilous when considering the inheritance of environment variables by child processes: cabal sets LD_LIBRARY_PATH for the Haskell program, which then execs something else that uses system libraries or specifies an `rpath`, etc, and that process explodes.

See: https://gms.tf/ld_library_path-considered-harmful.html

However, one interesting (although it should be considered thoughtfully before doing it instead of using rpath) suggestion is in there: call `ld-linux.so` manually with `--library-path`. This would eliminate the unfortunate inheritance behaviour, but I think this hack should be removed in favour of rpath.

**Comment by ulysses4ever** [comment]
@9999years thank you for the contribution! Is there a ticket describing the problem I'm more detail? Is there a reproducer? Could you add a test to this PR?

**Comment by ulysses4ever** [comment]
You'd also need to a changelog file (see the PR template).

**Comment by 9999years** [comment]
> Is there a ticket describing the problem in more detail?

The PR description lays out the exact cause of the problem and how it manifests. Not sure how much more detail you want.

> Is there a reproducer?

As I said in the PR description:

> This error was originally observed when testing a large commercial Haskell project (the mercury.com backend).

Our code is unfortunately closed source. Building a sufficiently large project under Nix should reproduce. The long `/nix/store` paths magnify the length of `LD_LIBRARY_PATH`. It's also been a few months since I've touched this code.

It's easy enough for us to cherry-pick this patch on our end so if you don't think it's worth fixing with a 2-line diff let us know.

**Comment by ulysses4ever** [comment]
@9999years thank you for the explanation. I absolutely think this should be merged. I'd prefer to have a test case to make sure we will not the in the future. Do you think you could create one? If not, that's all right: we'll see if there's a volunteer to add it.

**Comment by jneira** [comment]
Hi, maybe i am too cautious but i think deduplication colud have some effect in cabal behaviour, if a remember correctly order of libraries matter if there exist duplicate defintions and `lib1,lib2,lib1` could not have the same behaviour as `lib1,lib2`  or `lib2,lib1`.
So depending the order chosen by the linker (probably left to right but who knows) and the logic used to deduplicate current cabal nehaviour could change.

**Comment by 9999years** [comment]
When would there be duplicate definitions? Anyways, I think only the first one is chosen, which is why `nub` is used here.

**Comment by ulysses4ever** [comment]
If we imagine a linker that reads the list of libraries right-to-left, then nubbing indeed could change the order as visible by that linker (e.g. `lib1,lib2,lib1` would be turned into `lib1,lib2`, and now `lib2` is in the front for such linker). But I think it's too hard to imagine a linker like that. That's why I think this is probably not the reason to reject the patch. As to whether there may be other reasons to be cautious, I am not certain.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Kleidukos** [comment]
@9999years We'd like to offer our help for rebasing your PR. Would you accept it?

**Comment by 9999years** [comment]
Rebased against latest `master`, PTAL

**Review by Kleidukos — APPROVED** [review]

**Comment by Kleidukos** [comment]
@9999years Thank you for this contribution!! :)

**Comment by mouse07410** [comment]
Does this apply to Mac as well? If so, Mac uses `DYLD_LIBRARY_PATH`, and `LD_LIBRARY_PATH` is simply ignored theyre.

**Comment by 9999years** [comment]
@mouse07410 Yes, this applies to macOS. (I created and tested this patch on an M1 Mac.)

**Pull request merged**
