### PR TITLE
Fail parsing -none or ^>= if old cabal-version

### PR DESCRIPTION
**Pull request by phadej**
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
`check-tests` are "broken". Now already parser fails, we don't wait until `cabal check`. Out of two options

- Downgrade error to warning
- Make error text similar to what's check now, and update check tests

I prefer the latter.

**Comment by hvr** [comment]
I prefer

> Make error text similar to what's check now, and update check tests

as well.

IMO, `cabal check` should be only used for things we can't easily catch as errors early during parsing or which make little sense to catch during parsing.

**Comment by phadej** [comment]
@hvr, @23Skidoo is this good to merge?

**Comment by hvr** [comment]
@phadej looks good to me

I've got one question though: is it *easily* possible to detect the use of `-none` at `cabal check` time?

**Comment by phadej** [comment]
@hvr currently no. I'll make it for *next-after-2.2* to represent `-any` and -none` in the AST too. (as we do with wildcard and major bounds and even parens).

**Pull request merged**
