### PR TITLE
Accumulate environment (perhaps in a dodgy way.)

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by dcoutts** [comment]
Any explanation / context?

**Comment by ezyang** [comment]
Well, previously you couldn't use `withEnv` in a nested fashion in the test suite. In some new test cases I wrote, I needed this functionality. This patch relaxes that by simply appending the new environment variables. But I'm not sure it's right / has the intended semantics.

**Comment by 23Skidoo** [comment]
@ezyang Looks OK to me. In which way the semantics could be wrong?

**Comment by ezyang** [comment]
Well, it's possible that you need to *replace* the old entry, rather than just tack entries on.

**Comment by 23Skidoo** [comment]
I see, so the alternative is to do something like `toList $ (fromList b `union` fromList a)`. I guess that'd be the safer choice.

**Comment by ezyang** [comment]
Well, I'd rather we not guess what the correct thing to do is :)

**Comment by 23Skidoo** [comment]
It depends on the semantics of `createProcess`, right? I can see how the first alternative can go wrong (old entry used instead of the one we appended), but the second one should always work.

**Pull request closed without merging**
