### PR TITLE
Fix #4456.

### LINKED ISSUE #4456: Appveyor is broken: Cannot select only the dependencies
```
echo "" | ..\appveyor-retry ..\cabal install --only-dependencies --enable-tests
Resolving dependencies...
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the packages are required by a dependency of one
of the other targets.
```

Failing log: https://ci.appveyor.com/project/23Skidoo/cabal/build/%233393%20(master)

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by hvr** [comment]
This is not really a fix, but rather a workaround, isn't it? :-)

**Comment by 23Skidoo** [comment]
I guess it's OK for now.

**Comment by ezyang** [comment]
Yeah it's a horrible workaround.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
