### PR TITLE
Add explicit osx image to GHC 7.8.4 job

### LINKED ISSUE #3991: Mac OS X GHC 7.8 CI failure: Cannot cabal install happy
All of our Mac OS X GHC 7.8 CI builds are failing because the cache was recently cleared out, and we are now tickling a latent bug: "cabal install happy" no longer works because happy is built with a Custom setup which is built with the system Cabal which is built against the old version of unix which has the "ar: permission denied" error.

I'm not sure what the easiest/most robust way of fixing this. There isn't an easily accessible non-buggy copy of the Cabal library on our OS X image which the Custom setup could link against. There isn't an obvious pre-built happy binary we can use. I suppose we could patch and install a custom copy of happy with the problem fixed?

Maybe we should just drop Mac OS X 7.8 support?

### PR DESCRIPTION
**Pull request by phadej**
Hopefully resolves #3991

### CODE REVIEW

**Comment by phadej** [comment]
It works, just runs out of time :P

**Comment by ezyang** [comment]
:-1: XCode 7.1 support is going away on October 31st: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

**Comment by phadej** [comment]
We can use `osx_image: xcode6.4`, as the xcode version is irrelevant. Their documentation haven't pointed that fact.

**Comment by ezyang** [comment]
OK let's do that.

**Pull request merged**
