### PR TITLE
Add a test case for #5541

### PR DESCRIPTION
**Pull request by nomeata**

### CODE REVIEW

**Comment by quasicomputational** [comment]
I think this also needs a `cabal.project` in the test directory, or else the outer one (i.e., Cabal's) will be picked up.

**Comment by nomeata** [comment]
Added.

**Comment by phadej** [comment]
I wonder if the input files could be generated. Doesn't feel very nice to have arbitrary amount of files for a test checked-in. Someone might have a bigger ulimit, so test will pass trivially.

**Comment by 23Skidoo** [comment]
+1 on autogenerating test data.

**Pull request closed without merging**
