### PR TITLE
Small refactor of component pre-build

### PR DESCRIPTION
**Pull request by sheaf**
This commit very slightly refactors the per-component pre-build steps (renaming from `componentInitialBuildSteps` to `preBuildComponent`). It gets rid of some unnecessary arguments and gets rid of the unused `initialBuildSteps` function.

### CODE REVIEW

**Review by andreabedini — APPROVED** [review]
:+1:

**Review by geekosaur — APPROVED** [review]

**Comment by alt-romes** [comment]
The failures seem spurious / related to network failures. I'm going to retry the pipeline.

**Comment by Mikolaj** [comment]
Let me restart CI once more, this time by rebasing.

**Comment by Mikolaj** [comment]
@mergify rebase

**Pull request merged**
