### PR TITLE
A dumber approach to reverting #7995 on 3.8 branch

### PR DESCRIPTION
**Pull request by Mikolaj**
A dumber (commit by commit) approach to reverting #7995 on 3.8 branch. This is made painful by the fact that we got sloppy and didn't rebase a subsequent PR and so the overall merge got complex instead of fast-forward. Also, some other PRs (at least one, but probably more) actually depend on this PR.

Manual hacks notes: 
* I've left the definition of `rawSystemProcAction` and `fromCreatePipe` in the revert of  [Rework subprocess helpers](https://github.com/haskell/cabal/pull/7995/commits/a5986e37f45d3fca329fa2a0bf03d659b2f7354d), because they were causing a conflict and indeed they are used in some subsequent PRs
* I've re-added logCommand (from the same reverted commits as above) that is used in newer PRs

### CODE REVIEW

**Comment by jneira** [comment]
Thnks for trying the revert, ci is failing at `UNEXPECTED FAIL: PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs`, like mine one: i had to revert #8081 with [a796fa9](https://github.com/haskell/cabal/pull/8295/commits/a796fa921362164436a6a255cc4fa5ca57b59d2e)

**Comment by Mikolaj** [comment]
Let's hope your version works. I remember CI was a flaky with that test, but it's better than failing every time. I'm trying another hack, but at this point it's failing outright. :)

**Comment by Mikolaj** [comment]
This really failed hard with "*** Exception: unexpected: done sleeping", so changing the test harness doesn't seem to be sufficient. The cleanup probably fixed the real code that is used in the test. I will try your idea and revert the change of the test https://github.com/haskell/cabal/pull/8081 that adjusts it to the revised code (that we are reverting here).

**Comment by Mikolaj** [comment]
The same failure with https://github.com/haskell/cabal/pull/8081 reverted, so I'm just going to mark the test as known broken. It was flaky before.

**Comment by Mikolaj** [comment]
If CI passes, I'm going to tag this to get gitlab to build binaries so that @jneira can easily test if this works around https://github.com/haskell/cabal/issues/8208.

**Comment by robx** [comment]
Here's the list of commits that you'd want to revert. It's not a good idea to keep #7921 if reverting #7995, that's very likely to break things.

```
4416ea5c1 - Bootstrap generation fix for exe-only dependencies (5 months ago) <Robert Vollmert>
aa4f0ad3c - Add changelog (4 months ago) <Robert Vollmert>
d2172d896 - Add test for terminating "cabal run" on unix (4 months ago) <Robert Vollmert>
a03b4a79e - Handle SIGTERM by throwing an asynchronous exception (4 months ago) <Robert Vollmert>
0284bfbec - Use Process.withCreateProcess to ensure child cleanup (4 months ago) <Robert Vollmert>
67092dab6 - Use maybeExit in more places (4 months ago) <Robert Vollmert>
91fa33bd5 - Add changelog (5 months ago) <Robert Vollmert>
97f2c7b38 - Remove newly deprecated functions (5 months ago) <Robert Vollmert>
d5ae20cf9 - Deprecate obsolete functions (5 months ago) <Robert Vollmert>
9d33338c1 - manpage: use rawSystemProcAction (5 months ago) <Robert Vollmert>
3aa45a2d7 - LibV09: use rawSystemProcAction (5 months ago) <Robert Vollmert>
200478ef9 - SetupWrapper: replace runProcess' by rawSystemProc (5 months ago) <Robert Vollmert>
1969327c8 - Set delegate_ctlc for rawSystemStdInOut, too (5 months ago) <Robert Vollmert>
f972102ef - Default delegate_ctlc to True (5 months ago) <Robert Vollmert>
a5986e37f - Rework subprocess helpers (5 months ago) <Robert Vollmert>
eefe45d9f - Drop unused module Distribution.Client.Compat.Process (5 months ago) <Robert Vollmert>
592a48e33 - Disambiguate qualified imports (5 months ago) <Robert Vollmert>
```

**Comment by Mikolaj** [comment]
OK, let's do that in yet another PR.

**Comment by Mikolaj** [comment]
Tried it, at least not conflicts this time...

**Comment by Mikolaj** [comment]
Done on https://github.com/haskell/cabal/pull/8321.

**Comment by Mikolaj** [comment]
CI passed fine, but closing in favour of #8321.

**Pull request closed without merging**
