### PR TITLE
Make enable/disable nix flag easier to read

### LINKED ISSUE #8036: --help text seems wrong for --dis/enable-nix
```
cabal --help
...
 --enable-nix                   Enable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
 --disable-nix                  Disable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
```
in the second line, threre is a negation missing (don't run commands .. even if ..)?

```
cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library 
```

### PR DESCRIPTION
**Pull request by Colton-Clemmer**
This PR is attempting to close #8036 

The `boolOpt` function will not allow for more than one description so I changed the option type from `option` to `multiOption` so that the "nix" (`--enable-nix` and `--disable-nix`) flags would still be grouped together and allow separate descriptions for disabled and enabled.

As far as the language goes I felt like if the description of "Nix integration" for the `--disable-nix` was taken out it would make it more clear. It is defined in `--enable-nix` and `--disable-nix` is right under it.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — CHANGES_REQUESTED** [review]
Make sense. Would you add a tiny changelog file and test?

**Comment by Mikolaj** [comment]
@jwaldmann: could you review?

**Comment by jwaldmann** [comment]
I'll look into it, but I'm busy this week.

**Comment by Mikolaj** [comment]
Thank you. No rush.

**Comment by Colton-Clemmer** [comment]
@Mikolaj I have tested the `--help` flag. I assume that when you run `cabal foo --enable-nix` you would get some kind of error asking for a "shell.nix" file, but I can't get it to change anything on my pc's version of cabal or on my current source build. 
image

**Comment by jneira** [comment]
hmm, `--enable-nix` is a global flag and they should go before any command, so `cabal --enable-nix build` should work:

```
> cabal help

Command line interface to the Haskell Cabal infrastructure.

See http://www.haskell.org/cabal/ for more information.

Usage: cabal.exe [GLOBAL FLAGS] [COMMAND [FLAGS]]

.....

Global flags:
.....
 --enable-nix                   Enable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
 --disable-nix                  Disable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
....
```

**Comment by Colton-Clemmer** [comment]
@jneira Thanks for the suggestion, I tried that and it doesn't give any more info than it did before (I assume it would throw an error if it didn't find "shell.nix" or "default.nix") but it may be working. I've been trying to go through the command with `cabal repl` to see if the flag is being set correctly in memory but I'm still new to this repo and it's slow going. Give me a day or so to go through it and write a test.

**Comment by jneira** [comment]
well --enable-nix is not applied to v2- commands (and default build is v2-build) so it will be honoured only for `cabal --enable-nix v1-build`
see #6444

**Review by jneira — APPROVED** [review]
lgtm, thanks for adding a test and the changelog

**Review by Mikolaj — APPROVED** [review]
You could probably obtain the test quicker by copy-pasting something that depends on an existing harness. but test variety is a boon (except when maintaining tests) and this one is really good.

**Comment by Colton-Clemmer** [comment]
@Mikolaj Thanks, I wasn't sure where to put the test but it seems like that was good enough. I couldn't find anything that was already in place that tested flags so I just set it up with the functions I could find.

**Pull request merged**
