### PR TITLE
Whitelist branches for travis to build

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
FWIW, I'd rather not have any dev branches in this repository, but this will prevent some builds.

Something like that would be good for appveyor too, but I'm not familiar with its configuration

**Comment by ezyang** [comment]
OK. The classic reason to push branches to the Cabal repo is so that other people can edit them. Things are better with the "allow maintainers to edit PRs" so maybe we can ask people not to push branches, or always qualify them with a prefix.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
@ezyang Usually when we do that, we also create a PR. If there's a long-lived feature branch without a corresponding PR, it can be whitelisted.

**Comment by ezyang** [comment]
Well, you're right, we shouldn't build them anyway :)

**Pull request merged**
