### PR TITLE
Travis: work around #5120 by moving to cabal-install-head.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by angerman** [comment]
```
        tests\UnitTests\Distribution\Client\FileMonitor.hs:688:
        expected: MonitoredFileChanged "C:\\projects\\cabal\\cabal-install\\file-status--2596\\dir/good-a"
         but got: MonitoredFileChanged "C:\\projects\\cabal\\cabal-install\\file-status--2596\\dir\\good-a"
```
windows is just lovely.

**Comment by 23Skidoo** [comment]
FileMonitor tests should've been ignored.

**Comment by 23Skidoo** [comment]
orz, now a test failure:

```
/opt/ghc/8.0.2/bin/ghc --make -odir /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup -hidir /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup -i -i/home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom -package-db /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/sandbox.dist/sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d -package-id Cabal-1.24.2.0 /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup/setup.hs -o /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup/setup -threaded
[1 of 1] Compiling Main             ( /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup/setup.hs, /home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup/Main.o )
/home/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-ad11a557/setup/setup.hs:1:1: error:
    Ambiguous interface for `Distribution.Simple':
      it was found in multiple packages: Cabal-1.24.2.0 Cabal-2.1.0.0
```

No idea how we get Cabal-2.1.0.0 in scope with that command line.

Well, at least AppVeyor works...

**Comment by angerman** [comment]
Not sure if relevant, I just tried to build pretty-show with new-build, resulting in:
```
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - haskell-lexer-1.0.1 (lib:haskell-lexer) (requires download & build)
 - mtl-2.2.1 (lib:mtl) (requires build)
 - text-1.2.3.0 (lib) (requires download & build)
 - parsec-3.1.13.0 (lib) (requires download & build)
 - Cabal-2.1.0.0 (lib) (first run)
 - happy-1.19.9 (exe:happy) (requires build)
 - pretty-show-1.6.16 (lib) (first run)
 - pretty-show-1.6.16 (exe:ppsh) (first run)
Downloading haskell-lexer-1.0.1...
Configuring mtl-2.2.1 (all, legacy fallback)...
Downloading text-1.2.3.0...
Configuring haskell-lexer-1.0.1 (all, legacy fallback)...
Building mtl-2.2.1 (all, legacy fallback)...
Building haskell-lexer-1.0.1 (all, legacy fallback)...
Downloading parsec-3.1.13.0...
Configuring text-1.2.3.0 (lib)...
Building text-1.2.3.0 (lib)...
Configuring parsec-3.1.13.0 (lib)...
Building parsec-3.1.13.0 (lib)...
Configuring library for Cabal-2.1.0.0..
<command line>: cannot satisfy -package-id Cabal-2.1.0.0-inplace
    (use -v for more information)
cabal: Failed to build happy-1.19.9 (which is required by exe:ppsh from
pretty-show-1.6.16). The failure occurred during the configure step.
```

so somewhere we require Cabal-2.1.0.0 in there...

**Comment by 23Skidoo** [comment]
Closing in favour of #5132.

**Pull request closed without merging**
