### PR TITLE
add squash+merge for backports

### PR DESCRIPTION
**Pull request by geekosaur**
Made by copying things from the master squash+merge into a copy of the backport strategy. I'm a neophyte at Mergify, so someone should check this.

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

Testing notes:
* since this affects only CI of backports, there's no way to test on `master`
* I disrecommend testing on actual release branches. I suspect we need to create a test branch to "backport" things to.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Looks plausible.

**Review by ulysses4ever — APPROVED** [review]
LGTM, thanks!

**Comment by Mikolaj** [comment]
I took the liberty of adding the label.

**Comment by geekosaur** [comment]
Hrm, I was expecting some actual testing by making a dummy branch to backport things to.

**Pull request merged**
