### PR TITLE
Update cabal-install-solver synopsis (fix #10183)

### LINKED ISSUE #10183: cabal-install-solver package description synopsis is a copypasto from cabal-install
Let's put something meaningful there?

This is noticed by Henning on Haskell Cafe under the announcement for the 3.12 release.

### PR DESCRIPTION
**Pull request by ulysses4ever**
**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [X] [NO] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
I wonder if we can say more, like why it's separate. I think someone said they were using a different solver locally, and this made it easier to swap solvers out?

**Review by ffaf1 — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@geekosaur good point. That's below my pay grade, sadly. We'd need someone with better understanding of things to phrase it carefully..  @grayjay, would you be interested in putting together a couple of sentences about the mission and potential use cases of cabal-install-solver as a separate package? We could put them in the package description. Currently it's pretty low on content...

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Comment by ulysses4ever** [comment]
Oh, I forgot about it completely! Setting the label...

**Comment by geekosaur** [comment]
I thought you were waiting for @grayjay to comment.

**Comment by ulysses4ever** [comment]
I think it's too simple of a change to bother Kristen. But there is a two-day delay still!

**Comment by grayjay** [comment]
Sorry I missed this. I'm not very familiar with the decision to split the solver into another package. It's possible that the same goal could be met by moving it into a sub-library within cabal-install, though I don't know whether cabal-install can use the sub-libraries feature yet. I do know that cabal-install-solver currently doesn't have a stable interface. I think that it would take some work to turn it into a library that could be easily depended upon. For example, the solver unit tests test the solver through an interface that is still part of cabal-install.

**Review by grayjay — APPROVED** [review]

**Pull request merged**
