### PR TITLE
Bring the command help up to date

### PR DESCRIPTION
**Pull request by philderbeast**
Have the section on `cabal help` match this command's output and link to sections in the command intro.

---
Please include the following checklist in your PR:

* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
LGTM, thanks!

**Comment by ulysses4ever** [comment]
Please put the appropriate label (e.g. merge-me) when you think it's ready. The bot will try to merge it after the mandatory two-days delay.

**Comment by philderbeast** [comment]
@ulysses4ever we'll like hit this same problem https://github.com/haskell/cabal/pull/9041#issuecomment-1627832362, won't we?

**Comment by ulysses4ever** [comment]
After RTFM I think we'd just merge it manually. Still do put the label.

**Comment by philderbeast** [comment]
@ulysses4ever the [merge pull request] button is green. Should I press it myself?

**Comment by ulysses4ever** [comment]
@philderbeast no, we have a role about two-days delay (it's described in the CONTRIBUTING.md). Generally, we very rarely merge directly and it's better be some by admins.

**Pull request merged**
