### PR TITLE
cabal.project: Add a constraint on unix.

### LINKED ISSUE #3938: Strange OS X failures on Travis with GHC 7.8.4
Our CI recently started failing on OS X with GHC 7.8.4. There's a large number of permissions failures, all of them looking like this:

```
    Command /Users/travis/build/haskell/cabal/Cabal/tests/Setup configure -v --distdir dist-test/./dist --global --with-ghc /Users/travis/.ghc-install/7.8.4/bin/ghc --disable-optimization '--prefix=/Users/travis/build/haskell/cabal/Cabal/tests/PackageTests/BenchmarkStanza/dist-test/usr' '--package-db=clear' '--package-db=global' '--package-db=user' '--package-db=/Users/travis/build/haskell/cabal/dist-newstyle/build/Cabal-1.25.0.0/package.conf.inplace' failed.
    Output:
    Warning: my.cabal: A package using section syntax must specify at least
    'cabal-version: >= 1.2'.
    Configuring BenchmarkStanza-0.1...
    Dependency base -any: using base-4.7.0.2
    Setup: /usr/bin/ar: permission denied
```

The problem is probably not on our side, but this is still annoying, since it keeps happening.

/cc @phadej

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #3938.

### CODE REVIEW

**Comment by ezyang** [comment]
OK, but why not also put the constraint in `cabal-install.cabal`?

**Comment by 23Skidoo** [comment]
If I understand #2653 correctly, the constraint should be in `Cabal.cabal`. This will make Cabal non-buildable out of the box on GHC 7.8.

**Comment by 23Skidoo** [comment]
...and now it fails on all GHCs <= 7.8:
```
$ /home/travis/build/haskell/cabal/dist-newstyle/build/Cabal-1.25.0.0/build/package-tests/package-tests
(Re)configuring test suite (ignoring LBI)
Cabal test suite - testing cabal version 1.25.0.0
Cabal build directory: /home/travis/build/haskell/cabal/dist-newstyle/build/Cabal-1.25.0.0
Cabal source directory: /home/travis/build/haskell/cabal/Cabal
File modtime calibration: 20.0 (maximum observed: 4.425)
Environment:
CABAL_PACKAGETESTS_GHC="/opt/ghc/7.8.4/bin/ghc" \
CABAL_PACKAGETESTS_GHC_PKG="/opt/ghc/7.8.4/bin/ghc-pkg" \
CABAL_PACKAGETESTS_WITH_GHC="/opt/ghc/7.8.4/bin/ghc" \
CABAL_PACKAGETESTS_WITH_GHC_PKG="/opt/ghc/7.8.4/bin/ghc-pkg" \
CABAL_PACKAGETESTS_DB_STACK="clear:global:user"
CABAL_PACKAGETESTS_WITH_DB_STACK="clear:global:user"
Building shared ./Setup executable
package-tests: could not build shared Setup executable
  ran: /opt/ghc/7.8.4/bin/ghc-7.8.4 --make -clear-package-db -global-package-db -user-package-db '-package-db=/home/travis/build/haskell/cabal/dist-newstyle/build/Cabal-1.25.0.0/package.conf.inplace' '-hide-package Cabal' '-package Cabal-1.25.0.0' -O0 Setup.hs
  output:
<command line>: cannot satisfy -package Cabal-1.25.0.0
    (use -v for more information)
```
Looks related to this fragment in PackageTester.hs:
```
    r <- rawRun verbosity (Just path) (ghcPath suite) e $
        [ "--make"] ++
        ghcPackageDBParams (ghcVersion suite) (packageDBStack suite) ++
        [ "-hide-package Cabal"
        -- This mostly works, UNLESS you've installed a
        -- version of Cabal with the SAME version number.
        -- Then old GHCs will incorrectly select the installed
        -- version (because it prefers the FIRST package it finds.)
        -- It also semi-works to not specify "-hide-all-packages"
        -- at all, except if there's a later version of Cabal
        -- installed GHC will prefer that.
        , "-package Cabal-" ++ display cabalVersion
        , "-O0"
        , "Setup.hs" ]
```

@ezyang, you wrote that code, any ideas?

**Comment by ezyang** [comment]
Actually, the problem is obvious: for some reason, the Setup build isn't using the Nix-local build store, so the Cabal library is broken because it can't find the newer Unix. Fix coming.

**Comment by ezyang** [comment]
Ah, this is annoying. Some of the cabal-install tests use the built-in Cabal library to test Custom scripts, and those are obviously going to fail. Ugh.

**Comment by ezyang** [comment]
I think the newest version of the patch I've pushed here should green CI. When it finishes testing I'll merge.

**Comment by 23Skidoo** [comment]
@ezyang Awesome, thanks!

**Pull request merged**
