### PR TITLE
README: replace broken travis badge by representative GHA badge

### PR DESCRIPTION
**Pull request by andreasabel**
# README: replace broken travis badge by representative GHA badge

The travis badge shows "build failure" all the time (travis doesn't
run anymore).

To represent the success of GHA builds, I picked the Artifacts
workflow, as this one covers all three OSs (Linux, macOS, Windows).

### CODE REVIEW

**Review by fgaz — COMMENTED** [review]
Looks good but I'd link to https://github.com/haskell/cabal/actions/workflows/artifacts.yml?query=branch%3Amaster instead so people don't download artifacts from random PRs

**Comment by andreasabel** [comment]
@fgaz I implemented your suggestion.

**Comment by fgaz** [comment]
Thanks! I should have mentioned that then the image should be https://github.com/haskell/cabal/actions/workflows/artifacts.yml/badge.svg?branch=master to match. Could you update the url?

**Review by Mikolaj — APPROVED** [review]
LGTM.

**Comment by andreasabel** [comment]
@fgaz wrote:
> https://github.com/haskell/cabal/actions/workflows/artifacts.yml/badge.svg?branch=master

Done!

**Review by fgaz — APPROVED** [review]
Thanks!

**Comment by Mikolaj** [comment]
AppVeyor died again, for no discernible reason, or I don't know how to look: https://ci.appveyor.com/project/emilypi/cabal/builds/40575989?fullLog=true

Let me update the branch and perhaps CI will pass this time...

**Comment by Mikolaj** [comment]
Nope, CI broken again, now some other job disconnected. Merging manually.

**Pull request merged**
