### PR TITLE
Remove unnecessary references to QGoalReason

### PR DESCRIPTION
**Pull request by grayjay**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Looks like I broke CI for PRs with my fix to #3543.

**Comment by phadej** [comment]
@23Skidoo I working on the fix to CI as part of osx branch. Soon done

**Comment by 23Skidoo** [comment]
@phadej Well, I think I fixed it.
@grayjay  Should be fixed now, try rebasing.

**Comment by grayjay** [comment]
Thanks! It worked. I'll merge this because it is a simple refactoring.

**Pull request merged**
