### PR TITLE
Use defaultRenaming for pkgs without renaming info

### PR DESCRIPTION
**Pull request by edsko**

### CODE REVIEW

**Comment by ezyang** [comment]
I put the error in there on purpose, to check for an invariant that all packages have renamings in the map when Cabal processes. Does Cabal ever trigger this error, or is this on account of code you wrote with the Cabal library?

**Comment by edsko** [comment]
The latter -- we use Cabal to call gcc and the C compiler and don't have all the info to populate all these fields.

**Comment by ezyang** [comment]
The fields in ComponentLocalBuildInfo? You should, if you were able to fill in the package deps?

**Comment by edsko** [comment]
No, we didn't fill those in either. If all you are interested in is calling the compiler, there are tons of fields that are not relevant. Ideally of course we'd be able to call the functionality we need with a more fine grained data structure, but that that would be larger change to Cabal.

**Comment by ezyang** [comment]
OK, let's step back a bit: what precisely is the functionality you want to Cabal for? You said calling gcc and the C compiler; what bits is Cabal doing that is useful? (Trying to get a better idea for how big the other change would be.)

**Comment by Mikolaj** [comment]
I think @edsko meant "calling _ghc_ and the C compiler". Note that we don't have a .cabal file for the project we work on, though we have enough information to, e.g., construct such a file. We use Cabal as follows. 

1. To compile C files to .o files, taking into account the current package DB stack that we maintain (so that the C compiler has access to the files from the installed packages). We'd also like to be able to switch between profiling and shared ways and specify all kinds of extra paths and includes.

2. To generate the cabal_macros.h file for a given package DB stack (or for a list of installed packages --- we get it from a package DB stack using Distribution.Simple.Program.HcPkg.list).

3. To obtain the set of licence files or license strings for a list of installed packages. 

4. To create a correct .cabal file from the semantic value of a few of its fields.

5. To call haddock to build documentation for a set of modules, given package DB stack and a few other parameters.
 
6. To build a project (create a binary), given the package DB stack, path to the sources, list of modules to use, the name of the main module, list of packages we depend on.

One of the problems is that the relevant Cabal functions take huge data structures as arguments, even though usually only a tiny bit is relevant. It's not as bad as taking the whole parsed .cabal file as argument each time, but sometimes it almost feels like it. Also, even if the functions take less data, they still assume the data comes from parsing a .cabal file, with all the invariants it entails (even if the invariants are not needed for the function to operate sensibly). Please let me know if I can provide more details (no source code at this time, unfortunately, but I will let you ASAP know when that changes).

**Comment by ezyang** [comment]
I think the most useful information we could get is specific examples of functions which are useful, but take more arguments than they need. But I'm also keenly aware that proposing API changes is pretty difficult, especially with something as big as Cabal.

I guess I should ask (although I'm sure you have a good reason), why don't you have actual Cabal files?

**Comment by Mikolaj** [comment]
We don't have .cabal files, because the end users can't be bothered to (learn to) write them and update them; they prefer if it's done automatically for them (with or without actually creating the text file by using the partial information and guessing the rest based on the changing context).

I can't explain well the case that @edsko's PR is about, but here a few problems I remember. Note that I half-forgot all this and the Cabal code-diving that led to some of the conclusions is 2 years old. I will verify and provide more accurate details on demand. Please note that we are not complaining about verbosity, but about the ease of making mistakes and the difficulty of updating when the Cabal API or even just its internal code changes. We were repeatedly bitten by falsely assuming some of the countless fields are unused or irrelevant in the chosen code path or that their default value from an `emptyFoo` constructor or generated by one of the Cabal functions is OK for us.

1. Probably the worst offender is C files compilation via `runGHC`, which takes parameters prepared by `componentCcGhcOptions` and others and they take both a `BuildInfo` which is almost totally irrelevant and `LocalBuildInfo` which we needed to fill mostly by error values (and it's a couple dozen of fields, including nested ones).

1. Similarly we needed a `LocalBuildInfo` when building a binary (`Distribution.Simple.Build.build`) or generating haddocks with Cabal (`Distribution.Simple.Haddock.haddock`). But in that case we had enough context and our needs were standard enough, so we managed to feed `Distribution.Simple.Configure.configure` with lots of fake and empty data, which generated the mostly dummy and ignored `LocalBuildInfo` for us.

1. When creating `GenericPackageDescription` with a `PackageDescription` in one of the fields, a few `PackageDescription` fields are apparently ignored, e.g., `library`, possibly `buildDepends`.

1. Field `genPackageFlags` of `GenericPackageDescription` seemed totally unused (or was it only for the use-cases we needed?).

1. Function `parsePackageDescription` has a fixed default `AllRightsReserved` and so can't be used if the licence policy for your package DB is different.

**Comment by ezyang** [comment]
OK, I'm fine with merging this pull request to make things better for now.

**Comment by dcoutts** [comment]
Ok, if @ezyang is ok with it I'll merge.

**Pull request merged**
