### PR TITLE
final fixups to sdist check

### PR DESCRIPTION
**Pull request by geekosaur**
validated on 3.12 branch and applied in backport of #10448; this brings the fixes up to `master`

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] ~~Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).~~ actually taken from a backport!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Looks plausible...

**Comment by geekosaur** [comment]
It led to the first actual success of the check on 3.12 branch where it originated (as a fixup to #10477), so I'm fairly confident that it's now working properly.

**Comment by geekosaur** [comment]
Not needed for 3.14 release, but we probably want it in the tree before we make any later 3.14 releases so we can verify that they don't break compatibility with the bundled Cabal in 9.12.1.

**Comment by Kleidukos** [comment]
@geekosaur I believe this can go in for 3.14.0.0 and then I can start the process of producing the binaries

**Comment by geekosaur** [comment]
There's no reason it can't, it just won't do anything until post-release and even then it'll only affect CI, so I don't see much point to it.

**Comment by geekosaur** [comment]
@mergify backport 3.14

**Comment by geekosaur** [comment]
@mergify backport 3.14.1.1

**Comment by geekosaur** [comment]
turns out we need it because I added the branch protection rule… after the release. which wouldn't have been a problem except for this emergency release.

**Pull request merged**
