### PR TITLE
Tiny refactor of how Cabal handles configure scripts

### PR DESCRIPTION
**Pull request by Ericson2314**
See each commit for details. There are no public interface changes, just shuffling around private details.

### CODE REVIEW

**Comment by Mikolaj** [comment]
I've restarted doctests CI and now it passes (previously complained about checksums), so probably a random instability.

**Comment by Mikolaj** [comment]
As far as I can see, this is indeed a guaranteed safe refactoring, so tests are not mandatory. A changelog file would be welcome, though.

**Review by andreasabel — APPROVED** [review]

**Review by Mikolaj — CHANGES_REQUESTED** [review]
Blocking on a changelog file.

**Comment by Ericson2314** [comment]
I sort of would think this sort of internal-only change would be the type of thing that belongs in the git history but not a change log, but I added a change log entry as requested.

**Review by Mikolaj — APPROVED** [review]
Actually, you are probably right and I was overzealous. This is not even a change of API, because the module is not yet visible. Anyway, it doesn't hurt.

**Comment by Mikolaj** [comment]
Please feel free to set a merge label.

**Comment by ulysses4ever** [comment]
@Ericson2314 please, refer to https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions for a description of how a PR is supposed to be merged.

**Comment by andreasabel** [comment]
@Ericson2314 : Ah, yes, me setting the "merge me" label wasn't instructing you to do a merge commit, but this is a command to Mergify to rebase+merge (with a 2 day delay).  No great harm done, but for the sake of a linear history rebase+merge (e.g. in your case with clean commits) or squash+merge are preferred.

**Comment by Ericson2314** [comment]
Ah sorry about that, yes I did indeed misinterpet the label.

**Pull request merged**
