### PR TITLE
fix(Cabal-syntax): Remove left-over file after #8980

### LINKED ISSUE #9196: Cabal-syntax/src/Distribution/Fields/Lexer.x and .hs exist
Since 0ab5571e81be89eb9f2ff0e6f51570f2b93ccd08 there is both a .x file and .hs file for the Distribution.Fields.Lexer module.

I think there should only be one file committed as otherwise they seem likely to get out of sync. 

Now there is a build-tool-depends listed on Alex, I imagine the correct fix is to delete Distribution/Fields/Lexer.hs

cc @andreabedini

### PR DESCRIPTION
**Pull request by andreabedini**
In https://github.com/haskell/cabal/pull/8980 we started generating Lexer.hs with Cabal rather than as a external step. That PR forgets to remove the generatex file though which this PR rectifies.

Closes #9196

PS: now I wonder whether Cabal should complain/fail if an auto-generated file is already present in the source distribution. :thinking:

### CODE REVIEW

**Review by mpickering — APPROVED** [review]
Thanks @andreabedini

**Review by Mikolaj — APPROVED** [review]
LGTM. Please feel free to set the merge_me label.

**Comment by Bodigrim** [comment]
It seems this change breaks GHC bootstrapping process:https://gitlab.haskell.org/ghc/ghc/-/jobs/1665720#L5755

Without `Lexer.x` one cannot boostrap GHC on a new platform, which does not have Alex available (because, well, it does not have GHC available yet).

Relevant part of https://gitlab.haskell.org/ghc/ghc/-/blob/master/.gitlab-ci.yml#L691:
```yml
    # Bootstrapping should not depend on HAPPY or ALEX so set them to false
    # so the build fails if they are invoked.
    - export HAPPY=/bin/false; export ALEX=/bin/false
```

Could `Lexer.x` please be restored back?

**Comment by Bodigrim** [comment]
Just restoring `Lexer.hs` does not help, because now there are both `Lexer.hs` and `Lexer.x` in the same folder. I'm afraid we need to revert key parts of #8980, moving `Lexer.x` back to `boot/` folder and restoring `Makefile` rule.

**Comment by mpickering** [comment]
@Bodigrim I will look into this tomorrow about whether we need to patch hadrian to resolve this.

**Comment by andreabedini** [comment]
I believe @hamishmack had run into this issue with Hadrian already and make a fix in Haskell.nix.
I'll look at this today too.

**Comment by hamishmack** [comment]
I only made a branch of GHC that bumped the Cabal submodule to a version with this PR. https://gitlab.haskell.org/hamishmack/ghc/-/tree/hkm/bump-Cabal

**Comment by andreabedini** [comment]
@Bodigrim @mpickering Is the quoted comment still applicable/relevant?

I admit that I don't have much experience with boostrapping or cross-compiling but I ask because just before that we bootstrap hadrian:
```
    - python3 ./hadrian/bootstrap/bootstrap.py -w $GHC --bootstrap-sources hadrian-bootstrap-sources-$GHC_VERSION.tar.gz
    - export HADRIAN_PATH="$PWD/_build/bin/hadrian"
    - .gitlab/ci.sh setup
    # Bootstrapping should not depend on HAPPY or ALEX so set them to false
    # so the build fails if they are invoked.
```
and, in this repository, we have tests to check we can bootstrap `cabal-install` in the same way (which also builds `Cabal-syntax`).

Cannot `Cabal-syntax` be compiled exactly as we compile hadrian? I am happy to help with figuring out build plans it that's of any help.

**Comment by mpickering** [comment]
@andreabedini I have pushed a commit which will hopefully fix hadrian (https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11274/diffs?commit_id=326719c1d5e43013b660e138536c8042c7e3f197).

**Comment by Mikolaj** [comment]
Any progress here? This sounds mildly alarming, but I have no clue.

**Comment by mpickering** [comment]
This was fixed on the ghc side and we successfully bumped the Cabal submodule.

**Comment by Mikolaj** [comment]
Oh, so I assume there's nothing to do cabal-side. Great, so this PR is closed-closed.

**Pull request merged**
