### PR TITLE
Added empty exposed modules check for library targets

### PR DESCRIPTION
**Pull request by headprogrammingczar**
What it says on the tin.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Apparently this breaks the test suite. Can you please look into that?

**Comment by headprogrammingczar** [comment]
The fails appear to be that `(libModules lib)` is erroneously empty, but I can't immediately see why. Will keep looking.

**Comment by headprogrammingczar** [comment]
It looks like I had the test backwards. I'm still not sure why tests were passing on my machine, but when I ran the sandbox's result manually I finally managed to reproduce it and catch my mistake. We'll see what CI makes of this.

**Comment by 23Skidoo** [comment]
Merged in 0252a0aed79e881d4f6210d9296216aef3c301d0, thanks!

**Comment by hvr** [comment]
I hope this is only an advisory warning not causing `cabal check` to return non-zero? I have a few packages which have empty exposed-modules in their library stanze on purpose

**Pull request closed without merging**
