### PR TITLE
Warn on new-install failure (temp hotfix for #5641)

### PR DESCRIPTION
**Pull request by fgaz**
Temporary hotfix until we have a proper fix for #5641 

/cc @hvr

### CODE REVIEW

**Comment by 23Skidoo** [comment]
AppVeyor seems to be confused.

**Comment by fgaz** [comment]
Oh wait, I'm targeting the 2.4 branch and that failure does not seem new

**Comment by 23Skidoo** [comment]
Maybe it's somehow connected to the fact that AppVeyor caches `dist-newstyle`. That was added 076c966a0567851696c55a3bb5114a80efd0130a.

**Comment by fgaz** [comment]
Merging since there are no new failures

**Pull request merged**
