### PR TITLE
Update repo URL in doc example and Drop outdated Hackage vs CPAN package counts

### PR DESCRIPTION
**Pull request by Mikolaj**
Doc changes by Vilius Panevėžys <vp@mikrovisata.net> sent to cabal-devel@haskell.org.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
A rather strange Windows CI error: "D:\a\cabal\cabal\cabal-testsuite\PackageTests\SDist\T7124\dist-newstyle\cache\com62FE.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\D:\\a\\cabal\\cabal\\cabal-testsuite\\PackageTests\\SDist\\T7124\\dist-newstyle\\cache\\com62FE.tmp" Just "\\\\?\\D:\\a\\cabal\\cabal\\cabal-testsuite\\PackageTests\\SDist\\T7124\\dist-newstyle\\cache\\compiler": permission denied (Access is denied.)".

Rerunning.

**Comment by jneira** [comment]
iirc that error arises sometimes in Windows and it is transient

**Comment by Mikolaj** [comment]
> iirc that error arises sometimes in Windows and it is transient

Thank you. Indeed, it worked this time. Merging myself, because the author is not on github.

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.8

**Pull request merged**
