### PR TITLE
Fix space leak in ./Setup configure

### PR DESCRIPTION
**Pull request by grayjay**
This commit fixes the space leak in #2777 without modifying the logic for choosing flags.  It is a lot simpler than #2925, though I think an improvement to the algorithm like in #2925 is still needed.  I tested the practicality of solving for more flags by running `./Setup configure` on git-annex with 3 of the 21 flags removed.  Most of the dependencies were missing, which meant that Setup had to try all 2^18 flag combinations.  It took 13 minutes.

/cc @joeyh

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Travis failure is unrelated to your change (see #3003).

**Comment by joeyh** [comment]
Incidentally, git-annex HEAD is down to 16 flags;
under 10 minutes worst case for Setup configure is fine by me.

-- 
see shy jo

**Comment by 23Skidoo** [comment]
LGTM, merging. Sorry for taking so long!

**Comment by grayjay** [comment]
@23Skidoo No problem. Thanks for merging it.

**Pull request merged**
