### PR TITLE
Implement `cabal upload --doc`

### PR DESCRIPTION
**Pull request by bennofs**
This is the second part that was still remaining for the implementation of #2080. I still need to test this on powershell though, I'll report back when I've done that.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Thanks for working on this! Can you look into what's causing the Travis failure?

**Comment by bennofs** [comment]
Ok, the upload works on windows, but cabal still reports an error (this is related to the powershell code, which doesn't deal with non-empty response bodies well). There is also some misbehaviour (reporting failure while the upload actually worked) when using curl. I'll look into those two issues, after that the PR should be ready to merge.

About the travis build, it seems that there is no longer any failure? Was it restarted?

**Comment by bennofs** [comment]
Fixed the remaining errors on Windows and the curl issue. Should be good to merge now.

**Comment by bennofs** [comment]
ping @23Skidoo (hope pinging is OK)

**Comment by 23Skidoo** [comment]
Sorry for the delay. Will take a look now.

**Comment by 23Skidoo** [comment]
LGTM except that small security issue. Also would be nice to see a changelog entry. Thanks again for working on this!

**Comment by bennofs** [comment]
@23Skidoo changelog entry added, security issues fixed. I'm not quite sure here about the powershell situation regarding password security: the password is in cleartext in the generated script, so anyone who can read the script also has access to the password. Are the temporary files generated by cabal only readable by the current user?

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
