### PR TITLE
CI: ubuntu 20.04 -> latest

### PR DESCRIPTION
**Pull request by ulysses4ever**
I felt lucky and wanted to check if the problem still exists... Waiting for CI. Draft for now.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Lol, that's not the arch that was supposed to crash. :D

**Comment by Mikolaj** [comment]
It happens in https://github.com/haskell/cabal/pull/8904 as well.

**Comment by ulysses4ever** [comment]
Software engineering (or rather DevOps) never stops amusing me...

**Comment by Mikolaj** [comment]
Yay, https://github.com/haskell/cabal/pull/8904 fixed itself as well!

**Comment by ulysses4ever** [comment]
Ready for prime time!

**Review by Kleidukos — APPROVED** [review]

**Pull request merged**
