### PR TITLE
Skeleton for SPDX module generation [ci skip]

### PR DESCRIPTION
**Pull request by phadej**
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Do you want `cabal-spdx-codegen` to go into `cabal-install`'s `build-tool-depends`? I'm afraid we can't do that, because we want `cabal install cabal-install` to work on older versions of `cabal-install`. Otherwise looks OK.

**Comment by 23Skidoo** [comment]
...so I think we're just going to check in the generated module. So when we do that we should also add a CI check that `cabal-spdx-codegen`'s output is identical to the checked-in module.

**Comment by phadej** [comment]
Is it ok to commit `licenses.json` into Cabal repository.

https://github.com/spdx/license-list-data/issues/6 is related.

**Comment by 23Skidoo** [comment]
I think yes, why not?

**Comment by phadej** [comment]
@23Skidoo ok, I guess there isn't problem, https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf is licensed under *CC-BY-3.0* and has the same data, yet in not so nice format.

**Comment by phadej** [comment]
See #4913

**Pull request closed without merging**
