### PR TITLE
Fix AutogenModulesToggling test

### PR DESCRIPTION
**Pull request by mpickering**
By converting this to a setupTest we use the in-tree Cabal library rather than relying on a proxy of the GHC version to provide the right Cabal library version.

Supersedes #9398

### CODE REVIEW

**Comment by mpickering** [comment]
I tested locally to see that reverting #8690 causes this test to fail.

**Review by sergv — APPROVED** [review]
LGTM! It's much better test now. The previous version was limited by my familiarity with Cabal testing infrastructure.

**Review by ulysses4ever — APPROVED** [review]
Makes sense to me, thank you!

**Comment by mpickering** [comment]
It seems to fail in CI. I will try again locally shortly.

**Review by geekosaur — APPROVED** [review]

**Comment by mpickering** [comment]
I think this might be failing on older GHC versions because of a recompilation bug in older GHC versions. I removed the job cancelling logic in CI so I can see the full matrix of GHC versions.

**Pull request merged**
