### PR TITLE
try Apple AArch64 again

### PR DESCRIPTION
**Pull request by geekosaur**
Let's see if the runner has stabilized yet. Also, fixed the arch issues (validate no longer assumes everything is x86_64).

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by ulysses4ever** [comment]
It'd be great to have this working and add it to the set of pre-release binaries. Many people are using ARM silicon from Apple these days.

Godspeed!

**Comment by geekosaur** [comment]
If you look at it, adding it to the prerelease (and adding support for archs other than x86_64 in the process) is part of what this PR does.

**Comment by geekosaur** [comment]
It's a good sign that it's now the Windows jobs that are slowest. (That one someone like jasagredo will have to figure out.)

**Comment by geekosaur** [comment]
Question: a large part of my objective here was to speed up the Mac builds, but in the process all the Intel builds were lost. Do we want to support those some other way (e.g. overnight builds), or re-add them for the ghcs that only work on Intel, or something else?

**Review by ulysses4ever — APPROVED** [review]
Nice!

**Review by ffaf1 — APPROVED** [review]

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Comment by geekosaur** [comment]
@mergify backport 3.14

**Comment by Mikolaj** [comment]
> Do we want to support those some other way (e.g. overnight builds), or re-add them for the ghcs that only work on Intel, or something else?

I think, given the complexity of our CI and how often it breaks (including due to external reasons), optimizing for CI maintenance should be the priority and compromises are fine (e.g., only running some tests on Intel Macs). It's better to have less exhaustive CI that works and doesn't consume all out maintenance budget than the other way around. So I support your approach.

**Comment by Mikolaj** [comment]
The backport has been closed due to extra work required, so let me remove the label, too.

**Pull request merged**
