### PR TITLE
Only include dynlink opts when building a dynamic executable

### LINKED ISSUE #2766: Executable profiling erroneously turns on dynamic linking options
`muzzlecar` on reddit reported [this](https://www.reddit.com/r/haskell/comments/3gz905/ghcmod_builds_on_ghc_7101/cu33dx2) as a `ghc-mod` install bug on OS X.

```
-> % cabal install ghc-mod
Resolving dependencies...
Configuring cabal-helper-0.5.1.0...
Building cabal-helper-0.5.1.0...

...

[5 of 6] Compiling CabalHelper.Data ( CabalHelper/Data.hs, dist/build/cabal-helper-wrapper/cabal-helper-wrapper-tmp/CabalHelper/Data.p_o )
ld: -rpath can only be used when creating a dynamic final linked image
clang: error: linker command failed with exit code 1 (use -v to see invocation)
cabal: Error: some packages failed to install:
cabal-helper-0.5.1.0 failed during the building phase. The exception was:
ExitFailure 1
ghc-mod-5.3.0.0 depends on cabal-helper-0.5.1.0 which failed to install.
```

Seeing how I wrote the `rpath` handling stuff for Cabal I was immediately triggered to investigate. What I saw was the following:

- Dynamic linker opts when building executables, which include `rpath`s are only included, when `withStaticExe` is set to false: https://github.com/haskell/cabal/blob/a40a3429e806c17bbd2f9dd31617934885007c72/Cabal/Distribution/Simple/GHC.hs#L837
- However, looking line https://github.com/haskell/cabal/blob/a40a3429e806c17bbd2f9dd31617934885007c72/Cabal/Distribution/Simple/GHC.hs#L812:

  ```haskell
  withStaticExe = (not $ withProfExe lbi) && (not $ withDynExe lbi)
  ```

  I see that cabal seems to think when we are no longer building a static executable when profiling is turned on. However, I think that line of code is wrong, I think it should be:

  ```haskell
  withStaticExe = (withProfExe lbi) && (not $ withDynExe lbi)
  ```

According to `git blame`, that line was include by @23Skidoo in https://github.com/haskell/cabal/commit/c92409a4ced44577b11fd66242988392eac95b08, so maybe he can elaborate if `withStaticExe = (not $ withProfExe lbi) && (not $ withDynExe lbi)` is what he really intended.

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #2766

### CODE REVIEW

**Comment by christiaanb** [comment]
The failed test on GHC 7.4.2 of `UnitTest.Distribution.Version Parse Property 1` seems spurious and unrelated to my patch.

**Comment by 23Skidoo** [comment]
Travis failure is now gone.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by isaiah** [comment]
Since `ghc` 8 is still month away, can we make another minor release with this fix? It prevents me from installing `ghc-mod`. Specifically the dependency `cabal-helper`.

**Comment by 23Skidoo** [comment]
@isaiah I wish you posted this sooner, then it'd be released with GHC 7.10.3. Yes, we'll likely do one last release from the 1.22 branch soon, see #2966.

**Pull request merged**
