### PR TITLE
Switch to the tar package, drop builtin code

### PR DESCRIPTION
**Pull request by dcoutts**
The current incarnation of the tar package originated as code inside
cabal-install. That external tar package is now quite mature, with more
features and is much faster. In particular the tar index features will
be very useful for cabal-install, which currently has to maintain its
own custom-format index/cache.

### CODE REVIEW

**Comment by dcoutts** [comment]
The idea is we'll rebase #2983 on top of this.

**Comment by dcoutts** [comment]
Note that this means we effectively require bytestring >= 0.10. Is that going to be a problem?

**Comment by dcoutts** [comment]
So the build on ghc-7.4 is failing because it cannot pick bytestring-0.10. This is not because bytestring-0.10 does not build with ghc-7.4, but because the way the travis test script works it forces the choice of bytestring-0.9 when it builds Cabal, and then when the solver runs for cabal-install it has to pick the same things that were picked for Cabal.

So we have a couple choices: we can declare we don't care about 7.4, we can change the travis script to make sure it builds bytestring-0.10, or we can say that we think building with older ghc with the version of bytestring which they shipped with is actually really important, in which case we'll need a new release of the tar package, since the tar package currently forces the use of bytestring-0.10.

Thoughts?

**Comment by hvr** [comment]
IMHO, allowing the script to pickup bytestring-0.10 would be acceptable. We'd still support building `cabal-install` on GHC 7.4, just not with its "native" bytestring version. After all, with the upcoming GHC 8.0, we're about to support 5 GHC major versions: 8.0, 7.10, 7.8, 7.6, 7.4. Making some minor compromise when using GHC 7.4 doesn't seem so bad to me...  especially since this is about `cabal-install` (and not `Cabal`)

**Comment by phadej** [comment]
I agree with @hvr.

**Comment by 23Skidoo** [comment]
> IMHO, allowing the script to pickup bytestring-0.10 would be acceptable. 

+1.

**Comment by edsko** [comment]
Note that insisting on `bytestring >= 0.10` has additional knock-on effects on 7.4. Here's part of the package DB on 7.4:

screen shot 2016-01-07 at 10 28 11

Thus, insisting on `bytestring >= 0.10` also means we cannot use the installed versions of `unix`, `directory`, `binary`, `process`, `Cabal` and `bin-package-db`.

**Comment by phadej** [comment]
Let's see how https://github.com/haskell/tar/pull/14 goes, the changes to `tar` to support older `bytestring` via `bytestring-builder` were trivial

**Comment by dcoutts** [comment]
Thanks folks.

**Pull request merged**
