### PR TITLE
Temporarily revert #7995 and #7921 due to #8208

### PR DESCRIPTION
**Pull request by Mikolaj**
Yet another approach to (commit by commit) approach reverting https://github.com/haskell/cabal/pull/7995 on 3.8 branch due to #8208 and the 3.8 tag-for-GHC deadline. 

This is made painful by the fact that we got sloppy and didn't rebase a subsequent PR and so the overall merge got complex instead of fast-forward. Also, some other PRs (at least one, but probably more) actually depend on this PR.

Based on https://github.com/haskell/cabal/pull/8319#issuecomment-1194237426 I'm also reverting https://github.com/haskell/cabal/pull/7921 and, so far, this results in *no* revert conflicts. Let's see the CI.

### CODE REVIEW

**Review by jneira — APPROVED** [review]
it is a pity to have to revert two PRS, I hope the can be reapplied after the release, with a test over windows or manually testing it

**Comment by Mikolaj** [comment]
I hoped we can keep it on master and fix it quickly on master, so we only need to revert on 3.8. Do you think that many Windows users are building straight from master branch? Or is treating the branches differently a bad idea for another reason?

**Comment by jneira** [comment]
nah agree on trying to fix it in master, will keep the issue opened to track it, thanks for take care!

**Comment by Mikolaj** [comment]
I think mergify doesn't permit skipping the delay for non-backports, so let me merge manually.

**Comment by jneira** [comment]
I've tested the artifact generated by this prjust incase and ctrl+c works fine, as expected

**Pull request merged**
