### PR TITLE
Release 3.12.1.0 version bumps

### PR DESCRIPTION
**Pull request by geekosaur**
The original branch name collides with a branch protection rule, making it difficult to work with.
This is C.3.1/2 in the wiki.
See #9885.

### CODE REVIEW

**Comment by ulysses4ever** [comment]
As an experiment, I'd try to change:

https://github.com/haskell/cabal/blob/06145ea6574bca8b873b7664ac9a71078ffc10cc/cabal-testsuite/cabal-testsuite.cabal#L149-L150

to say 3.12 instead of 3.10.

**Comment by geekosaur** [comment]
Yeh, I changed it back and it worked locally, so I tried to push it up and discovered that I'd misnamed my local branch and branch protections were applying on github's side. So I killed the branch and started over.

**Comment by geekosaur** [comment]
Does anything remain to be done on the hackage-security side? Its GitHub repo is already updated, but I don't think it's on Hackage yet.

**Comment by geekosaur** [comment]
Unrequested reviews until I finish with bootstrap plans.

**Review by ulysses4ever — APPROVED** [review]
LGTM, thank you!

**Comment by geekosaur** [comment]
I'm not actually sure it's ready though. We don't have a 9.10.1 bootstrap, and I'm still suspicious that `hackage-security` isn't actually using the correct `Cabal`/`Cabal-syntax`.

**Comment by geekosaur** [comment]
Right, I just tried to add a 9.10.1 bootstrap and ran into one of the known upstream issues (TH version) which I think is fixed in git but not yet released.

**Review by Kleidukos — APPROVED** [review]

**Comment by geekosaur** [comment]
Sorry, wrong ticket

**Comment by geekosaur** [comment]
https://github.com/haskell/hackage-security/issues/316

**Comment by geekosaur** [comment]
I'll hold onto the changes for 9.10.1 bootstrap and apply them to `master` when `hackage-security` is ready.

**Comment by geekosaur** [comment]
Manual squash+merge because Mergify on 3.12 has neither `squash+merge me` nor rules for non-backports on non-`master` branches. I'll fix both post-release.

**Pull request merged**
