### PR TITLE
Add 'store-dir' global flag for custom store location

### PR DESCRIPTION
**Pull request by alexbiehl**
This is also a nice workaround for https://github.com/haskell/cabal/issues/4515 since I can easily define `store-dir=C:\cabal-store` in my global configuration.

This also propagates the global `logs-dir` configuration instead of hard-coding the logs dir to `cabalDir </> logs`.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Haven't looked at the code, but the general idea is good.

**Comment by ezyang** [comment]
LGTM. CI failures are because you've forgotten some test/monoid-y code for the config change. Look at an old diff which added a field to figure out exactly what.

**Comment by alexbiehl** [comment]
OK, this is ready for review now! Tests should work pass now!

**Comment by alexbiehl** [comment]
Hmm. I am not sure what is causing some of the tests to fail.

**Comment by ezyang** [comment]
It doesn't look like it's your fault, looks like CI is in trouble right now.

**Comment by ezyang** [comment]
FYI I cancelled your most recent build because it was definitely going to fail

**Comment by ezyang** [comment]
CI is unwedged, I restarted it.

**Comment by ezyang** [comment]
Hi @alexbiehl, can you rebase your PR on master and repush? It doesn't look like Travis is successfully merging with master (which has fixed contbuild.)

**Comment by alexbiehl** [comment]
Almost...

**Comment by alexbiehl** [comment]
Yeah! CI is happy!

**Comment by 23Skidoo** [comment]
@alexbiehl Can you please add some docs and update the changelog? Otherwise the patch seems okay.

**Comment by 23Skidoo** [comment]
@alexbiehl NB: you can use `[ci skip]` anywhere in the commit message body to avoid triggering CI for documentation-only commits.

**Comment by hvr** [comment]
@23Skidoo are the `changelog` conflicts the only thing keeping this from being merged, or was there something else that needs doing?

**Comment by ezyang** [comment]
Yes it's just the changelog conflict.

**Comment by Mistuke** [comment]
I've been trying to use this but it always results in a weird path:

```
$ cabal --store-dir=/e/cabal-store new-test
Build profile: -w ghc-8.0.2 -O1
In order, the following will be built (use -v for more details):
 - base-compat-0.9.3 (lib) (requires build)
....
Configuring library for base-compat-0.9.3..
cabal.exe: ghc-pkg dump failed: dieVerbatim: user error (cabal.exe:
'E:\msys64\mingw64\bin\ghc-pkg.exe' exited with an error:
ghc-pkg.exe: C:cabal-store\ghc-8.0.2\package.db:
getDirectoryContents:findFirstFile: does not exist (The system cannot find the
path specified.)
)
```
No matter what path I give it, the resulting path seems to always be rooted in `C:` even though I gave it `E:` and the path itself is invalid because it's missing the `\` after the colon...

**Comment by 23Skidoo** [comment]
@Mistuke Can you please file a new issue?

**Pull request merged**
