### PR TITLE
Show format for --help flag. Fixes #2460

### LINKED ISSUE #2460: `cabal format` is not listed in --help message
Any ideas why this command is hidden? I recently discovered this and I think it's very useful.

### PR DESCRIPTION
**Pull request by psibi**
Fixes #2460

### CODE REVIEW

**Comment by 23Skidoo** [comment]
It's intentionally hidden because it's somewhat buggy.

**Comment by gbaz** [comment]
Now that #2353 is closed, are there any other blockers on exposing this?

**Comment by bgamari** [comment]
@23Skidoo?

**Comment by 23Skidoo** [comment]
@bgamari Sorry, I'm sick right now, will answer in a few days.

**Comment by bgamari** [comment]
@23Skidoo ping (apologies if you are still ill).

**Comment by dcoutts** [comment]
Patch looks fine, assuming we're now happy with exposing this feature.

**Comment by 23Skidoo** [comment]
Well, the patch itself is trivial, but `format` has been a constant source of bugs, so I'd like to see some more testing done before merging. One suggestion is to go through all `.cabal` files on Hackage and check that `readPackageDescription path` is equivalent to `(readPackageDescription path >>= writeGenericPackageDescription path) >> readPackageDescription path`.  Looking through open tickets I see #2661, maybe there is more. Other enhancements that'd be nice to see: #1966, #1127.

**Comment by phadej** [comment]
Simple check for @23Skidoo `read . write . read = read`, using https://github.com/commercialhaskell/all-cabal-files
```haskell
module Main (main) where

import Control.Monad
import Control.Applicative
import Distribution.Verbosity
import Distribution.PackageDescription.Parse
import Distribution.PackageDescription.PrettyPrint
import Distribution.ParseUtils

hoist :: ParseResult a -> Maybe a
hoist (ParseOk _ x) = Just x
hosit (ParseFailed _) = Nothing

check :: FilePath -> IO ()
check cabal = do
  print cabal
  desc <- readPackageDescription silent cabal
  let desc' = parsePackageDescription (showGenericPackageDescription desc)
  when (Just desc /= hoist desc') $ do
    print $ Just desc
    print $ hoist desc'
    fail cabal

main :: IO ()
main = do
  -- Generate listing with
  -- find . -type f -name '*.cabal' > cabal-files
  cabalFiles <- lines <$> readFile "cabal-files"
  mapM_ check cabalFiles
```

Fails already at `./accelerate-cuda/0.12.0.0/accelerate-cuda.cabal` on my machine (using Cabal in master)

**Comment by 23Skidoo** [comment]
@phadej Thanks! I think we shouldn't expose `format` until this test passes for all `.cabal` files on Hackage.

**Comment by 23Skidoo** [comment]
Current status: blocked by #2661 and #2681.

**Comment by BardurArantsson** [comment]
I'm sure this is nice'n'all, but I'm not sure "round-tripping" is the be-all-and-end-all of package description formats[1]. So, I'd argue to just say WONTFIX... as unpopular as that may be. I'd rather argue that the cmdline arg and all supporting code should be removed.

(I hope I haven't *completely* misunderstood the point of this PR.)

[1] Parsers of said formats, sure, but not the semantics.

**Comment by m-renaud** [comment]
I have recently started taking a closer look at the `cabal format` command and there are quite a few changes that we need to make before this is generally available. I have started tracking the work at https://github.com/haskell/cabal/projects/9, expect some updates there in the coming weeks.

I'm going to close out this PR since it'll be a little while before we want this to be published.

**Pull request closed without merging**
