### PR TITLE
 {test,bench}: Ignore "bad version" error when loading LBI.

### PR DESCRIPTION
**Pull request by 23Skidoo**
See https://github.com/haskell/cabal/pull/1821#commitcomment-16052702.

### CODE REVIEW

**Comment by ezyang** [comment]
This fix seems questionable but I can't think of a better way of working around it. (Maybe having cabal-install just parse the package description itself.) It's a bit counterintuitive that returning an empty list means "build everything".

**Comment by 23Skidoo** [comment]
> It's a bit counterintuitive that returning an empty list means "build everything".

Good point, I'll add a special-purpose ADT to make the code more readable.

**Comment by 23Skidoo** [comment]
> Good point, I'll add a special-purpose ADT to make the code more readable.

Done.

**Comment by ttuegel** [comment]
> I'll add a special-purpose ADT to make the code more readable.
> 
> Done.

Is that commit in there? I don't see it.

**Comment by 23Skidoo** [comment]
> Is that commit in there? I don't see it.
I rebased and force-pushed.

**Pull request merged**
