### PR TITLE
Update cabal-install to allow time 1.14

### PR DESCRIPTION
**Pull request by geekosaur**
Note that #9848 covers `Cabal` and `Cabal-syntax` already.
For sanity's sake, #9848 should probably be committed first.

**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions). (n/a)

### CODE REVIEW

**Comment by geekosaur** [comment]
As noted in #9848, this needs to be validated locally by reviewers because `time` is a bootlib. I found I needed an `allow-newer` as well, because one of our (test?) dependencies didn't have its bounds adjusted yet.

**Comment by Mikolaj** [comment]
I think @ulysses4ever prototyped a tool to permit precisely such a usage of our own CI, but I can't find docs for it.

**Comment by ulysses4ever** [comment]
They're at the bottom of CONTRIBUTING.md, I think

**Comment by Mikolaj** [comment]
Oh, great, thank you. I only searched in READMEs and the Wiki. I've updated the placeholder with the link at the bottom of https://github.com/haskell/cabal/wiki/Cabal-Packages-Hackage-Revision-Policy.

**Review by Mikolaj — APPROVED** [review]
Looks good and Artem reports: 

> started CI run of the Validate workflow with time==1.14: https://github.com/haskell/cabal/actions/runs/8650585264
> will see how it goes
> [Validate · haskell/cabal@8e971f5](https://github.com/haskell/cabal/actions/runs/8650585264) - GitHub
> Official upstream development repository for Cabal and cabal-install - Validate · haskell/cabal@8e971f5
>... it failed for an unfortunate reason: validate uses various ghc and some come with base older than the lower bound on base that time-1.14 has. This is clearly a shortcoming of this approach for testing version bumps :-( I'll think if there's a way around it. But in the meantime you may want to just trust the PR author that they tested it locally on one GHCV at least...
> actually, the static exe job succeeded with time-1.14! https://github.com/haskell/cabal/actions/runs/8650585264/job/23719429299

**Comment by Mikolaj** [comment]
@ffaf1: we have teo compilation tests with the bound forced, so I think it's fine for you to approve and set the merge label without repeating the tests.

**Review by ffaf1 — APPROVED** [review]

**Comment by Mikolaj** [comment]
I've we set the `delay_passed` label by hand. It's been untouched for 4 days and will now take some more time for CI to pass after rebase anyway.

**Pull request merged**
