### PR TITLE
Update Cabal{,-install,-syntax} to 3.10.2.0

### PR DESCRIPTION
**Pull request by Kleidukos**
See https://github.com/haskell/cabal/issues/9008

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
so, cabal-install-solver will lag behind the rest of the crew? (i.e. stay on 3.10.1)

**Review by ffaf1 — APPROVED** [review]
☑

**Comment by Kleidukos** [comment]
@ulysses4ever we are not releasing any patch to it, so I don't see it as lagging, more as "was perfect since the beginning" :)

**Comment by ulysses4ever** [comment]
CI is stuck with some trouble about version number bump...

**Comment by ulysses4ever** [comment]
@Kleidukos I looked into it: if you bump the host version of `cabal-install` to 3.10.1, it works fine.

**Comment by ulysses4ever** [comment]
I went ahead and added a commit doing the bump. Let's see how far it gets...

**Comment by ulysses4ever** [comment]
It passes Linux fully now but fails on Windows probably as in https://github.com/haskell/cabal/pull/8840/commits/420ccd80d99b165ac143726b1cf9a47a3689f7f6 Too bad we didn't got around to nailing 9.6.1 for 3.10

**Comment by ulysses4ever** [comment]
I'm slowly working through tests that are failing on Windows with the GHC and cabal bumps you already made. Those tests were handled (well, blocked) on master in the past. So far so good.

I also tried to add GHC 9.6.2 on CI and so far it worked on Linux.

**Comment by ulysses4ever** [comment]
All right, adding 9.6 was a stretch, perhaps: I'm seeing strange testsuite failures on Windows. I'm striking that commit for the time being.

**Comment by ulysses4ever** [comment]
Anyone knows how to cure stuck bootstrap jobs? I see them regularly but I never mastered this skill...

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
Doh, I give up.

**Comment by ulysses4ever** [comment]
Green now!

**Comment by ulysses4ever** [comment]
We don't have Mergify rules for non-master branches (except backports), so someone has to push the button. @Kleidukos whenever you're ready...

**Comment by Kleidukos** [comment]
Thanks a bunch @ulysses4ever

**Pull request merged**
