### PR TITLE
Use case insensitive match on ETag headers

### LINKED ISSUE #9113: Remote packages always downloaded
**Describe the bug**
When specifying a remote package in the `packages` field of the `cabal.project` file, that package is always downloaded when building. There does not appear to be any way to cache it. 

**To Reproduce**

Create a `cabal.project` file like this:

```
packages:
  .
  https://hackage.haskell.org/package/flow-2.0.0.3/flow-2.0.0.3.tar.gz
```

Then set up a local package just to give Cabal something to build. Then run `cabal build` and you should see this output:

``` sh
$ cabal build 
Downloading
https://hackage.haskell.org/package/flow-2.0.0.3/flow-2.0.0.3.tar.gz
Resolving dependencies...
# ...
```

That's all expected. However if you run `cabal build` _again_, it will download the remote package again even though it hasn't changed:

``` sh
$ cabal build
Downloading
https://hackage.haskell.org/package/flow-2.0.0.3/flow-2.0.0.3.tar.gz
Up to date
```

**Expected behavior**
The remote package should only be downloaded once. Obviously remote resources can change, so perhaps this should be based on some header like `Content-MD5` or `ETag` or `Last-Modified`. 

**System information**
``` sh
$ uname -a
Linux acf2eb0d828d 6.3.12-orbstack-00209-ga2cd8129a099 #1 SMP Mon Jul 10 05:35:25 UTC 2023 aarch64 GNU/Linux
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.2
$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 
```

**Additional context**
I'm using a package tarball from Hackage, but I see the same behavior from other sources such as GitHub.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #9113.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Terrific, thank you!

Hopefully, will be merged over weekend if no issues raised by then.

**Comment by ulysses4ever** [comment]
Also, optimistically marking it for backporting to 3.10.

**Comment by ulysses4ever** [comment]
@mergify backport 3.10

**Comment by andreabedini** [comment]
❤️

**Comment by ulysses4ever** [comment]
@Mergify rebase

**Comment by ulysses4ever** [comment]
Fourmolu is failing for an unrelated reason. A fix is in flight.

**Comment by fgaz** [comment]
This is missing a changelog entry. @tfausak could you add one in a follow-up pr?

**Comment by tfausak** [comment]
Sure: #9152

**Pull request merged**
