### PR TITLE
Revert "Merge pull request #7995 from robx/cleanup-processes"

### PR DESCRIPTION
**Pull request by jneira**
This reverts commit ddf3ba20c48d9f82fe91ef604defd0c813f296b3, reversing
changes made to 001e3cc810b0f735007ef8cbfef002d7bf4756e8.

pr https://github.com/haskell/cabal/pull/7995

I've checked manually a version of branch 3.8 with this reverted and it does not show the problem described here: #8208
This is the fast way to remove the issue for the incoming 3.8 version but ideally the pr should be kept and fixed as the refactor was good.

//cc @robx

### CODE REVIEW

**Comment by hasufell** [comment]
Why are we reverting? Is there time pressure? The correct way is to fix it.

Please explain exactly what this reversal fixes, on which platform etc. Even after reading https://github.com/haskell/cabal/issues/8208 I don't understand it.

**Comment by jneira** [comment]
The bug and the platform is the title of the linked issue: `Interrupting cabal-3.8.0.0.20220526 with ctrl+c makes it hang on windows`. Not sure how could be more precise about that.

The time pressure is mentioned in the last comment of the issue, and also my preference for fixing it.

> i would like to examine the pr and find the cause to not having to revert it but i will not have time to not delay the release excessively, what do you think about?

**Comment by hasufell** [comment]
-1 for reverting, unless @robx agrees that fixing will take a long time. The way is forward. Releases should be good quality.

**Comment by jneira** [comment]
> -1 for reverting, unless @robx agrees that fixing will take a long time. The way is forward. Releases should be good quality.

Agree, i asked @robx for that reason. This one would be the last resort to not include the bug in the release. Will mark as draft to make it clearer.

**Comment by jneira-stratio** [comment]
closing in favour of #8321

**Pull request closed without merging**
