### PR TITLE
Add extraLibDirs to runtime lib search paths of library

### LINKED ISSUE #7339: Cabal should probably add extra-lib-dirs to RPATH
**Describe the bug**
In [GHC #19350](https://gitlab.haskell.org/ghc/ghc/-/issues/19350) it was noted that dynamic libraries findable via `extra-lib-dirs` are not found in GHCi on POSIX platforms. While in principle GHC has the information that it needs to find these libraries from the package database registration, due to limitations of the the POSIX dynamic linking interface, it is not possible for GHC to do better here.

I believe the solution here is to (on POSIX platforms) add Cabal's `extra-lib-dirs` paths to RPATH during the final link of libraries. This isn't a perfect solution (since it may result in spurious RPATH entries) but this seems to be the best we can do.

**To Reproduce**
See this [testcase](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5327).

**Expected behavior**
GHCi is able to load libraries with foreign dependencies findable only via `extra-lib-dirs`.

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

### PR DESCRIPTION
**Pull request by alt-romes**
Runtime search paths are hard. Here's the current picture to understand why this patch exists:

* When linking a shared library, GHC will include in the rpath entries of the shared library all the paths listed in the library dirs section of the installed package info of all packages the shared library depends on. * On darwin, GHC has special logic to inject the library dirs listed in the installed dependent packages info into the rpath section instead of passing the dirs as -rpath flags to the linker. However, only the dirs where used libraries are found are actually injected. The others are ignored. This works around limitations of the darwin loader.

* Cabal, in addition, passes directly to the linker (via -optl-Wl,-rpath,...) the library dirs of packages the shared library for the package being built depends on. * In a vanilla cabal installation, this will typically only be the path to the cabal store and the path to the installed GHC's boot libraries store. * When using nix there will a different library dir per installed package. Since these lib dirs are passed directly to the linker as rpaths, we bypass the darwin loader logic and, for very big packages, on darwin, we could end up reaching the load command limit and fail linking. We don't address this situation in this MR.

When we specify `extra-lib-dirs` in Cabal, these extra-lib-dirs will be added to the library dirs listed in the installed package info of the library they were specified for. Furthermore, when building a shared library, extra-lib-dirs will be passed as `-L` flags to the linker invocation. However, the same extra-lib-dirs will not be passed as `-rpath` to the linker.

The end situation is as follows:

    1. The shared library `libA` built for a package `A` will be linked
       against some libraries `libExtra` found in extra-lib-dirs
       `extraA`.

    2. The RPATH section of `A` will NOT contain `extraA`, because we
       don't pass -rpath extra-lib-dirs when linking the library, but it
       will depend on `libExtra`.

    3. The installed package info of that package `A` will contain, in
       the library dirs section, the extra-lib-dirs `extraA` and the
       path to `libA`.

    4. When a package `B` depends on package `A`, it will include in the
       RPATH section of the shared library `libB` the lib dirs from the
       installed package info of `A`, i.e. `/path/to/libA` and `extraA`,
       and depends on `libA` and, transitively, on `libExtra`.

The conclusion is:

    5. When we load `libB`, we will load `libA`, which is found in
       `/path/to/libA`, and, transitively, load `libExtra` which is
       found in `extraA` -- they are both found because both
       `/path/to/libA` and `extraA` are listed in the RPATH entries.

    6. However, if we load `libA` directly we will /NOT/ find
       `libExtra`, because `extraA` is not included in the RPATH
       entries.

So, ultimately, what this commit fixes, is the failure described in (6), caused by the incorrect behaviour of (2), by specifying `-rpath extra-lib-dirs` when linking the shared library of a package, to include the extra lib dirs in the RPATH entries of that shared library (even though dependents of this library would already get the extra-lib-dirs in their RPATH, the library itself didn't, resulting in cabal#7339 and ghc#19350)

Fixes #7339
Fixes ghc#19350

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by mouse07410** [comment]
Yes!!

**Comment by alt-romes** [comment]
Fixes #7339

**Comment by alt-romes** [comment]
Should this change also be backported @Kleidukos ? Should apply cleanly.

**Comment by Kleidukos** [comment]
@alt-romes ok, can I let you drive the backport? it's `@mergifyIO backport 3.10`

**Comment by alt-romes** [comment]
> @alt-romes ok, can I let you drive the backport? it's `@mergifyIO backport 3.10` in a comment

I'd need some instructions to do so, I haven't worked with `mergifyIO`. Happy to do so in any case.

**Review by geekosaur — APPROVED** [review]

**Comment by Mikolaj** [comment]
@alt-romes: You create a github comment, here, saying "@mergify backport 3.10". That's it. You can do it right now.

**Comment by alt-romes** [comment]
@mergify backport 3.10

**Comment by alt-romes** [comment]
I'd be great if you could review this @andreabedini @gbaz

**Comment by andreabedini** [comment]
I defer to my linking expert @angerman :joy:

**Comment by alt-romes** [comment]
@andreabedini Yes and no. The rpath logic is not left to GHC, and even if an -rpath flag were to be added, it wouldn't be clear whether extra paths added through it should be handled via the macOS length limit workaround.

In fact, I implemented the suggested -rpath flag, but it wasn't finished because it is unclear [what semantics it should have](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11801#note_540491).

I've also posted a comment to @angerman's original MR that attempted something slightly orthogonal to this (https://github.com/haskell/cabal/pull/7094#issuecomment-1880730072).
I think we indeed all agree (me, @bgamari, @angerman), and I have tried to clarify the confusion regarding this in the commit message.

Replying to what you quoted:

> Cabal currently uses GHC's -optl-Wl,-rpath and -L flags to precisely specify the compile-time and runtime library search paths needed for a particular install plan. From the perspective of Darwin (the issue fixed in https://github.com/haskell/cabal/pull/7094) this status quo is unfortunate since we do not benefit from the clever rpath handling introduced in [ghc@4ff93292243888545da452ea4d4c1987f2343591](https://gitlab.haskell.org/ghc/ghc/-/commit/4ff93292243888545da452ea4d4c1987f2343591).

Indeed, Cabal already specifies runtime search paths and compile-time library paths to GHC, with information only cabal is aware of. This path extends the runtime search paths Cabal passes to GHC to include the extra-lib-dirs field which specifies paths where libraries will be found at runtime (the field itself unfortunately conflates compile time and load time paths).

>  However, this is not a fundamental issue: it can be easily avoided by introducing a -rpath flag in GHC's command-line interface, providing a reliable and precise way for the user to influence the runtime library search path. This would allow us to fix the issue pointed out in this ticket (that extra-lib-dirs don't make it into RPATH) while giving us a more robust way to address the Darwin issue addressed in https://github.com/haskell/cabal/pull/7094.

It turns out that the Darwin workaround will only include in the RPATH entries of a dynlib the paths where libraries are found at runtime, in order to not include RPATHs to libraries which are never used by the library. However, sometimes, we really do want to specify the path to a directory where a library can be found at *runtime*, even if no library is found there at compile time. `extra-lib-dirs` should make it into RPATH, because they are extra directories where the user manually specifies they want to search. Arguably, there could be an `extra-runtime-lib-dirs` field to be more precise about the diference between runtime and compile time search paths, but, at present time, `extra-lib-dirs` serves that purpose.

So, even if there were an -rpath flag, it is unclear if such a flag should go through Darwin's special rpath logic, or bypass it completely (again see [!11801](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11801#note_540491)).

**Comment by andreabedini** [comment]
@alt-romes Thank you for your very detailed reply!

**Pull request merged**
