### PR TITLE
Make cabal check warn about BOM

### PR DESCRIPTION
**Pull request by phadej**
Implements first bullet point of #2573

It seems that second point is implemented already, the BOM is ignored.

### CODE REVIEW

**Comment by dcoutts** [comment]
This is ok, but it'd be better if it used the `checkPackageContent` & `CheckPackageContentOps` system so that it can work in other contexts, like on hackage. You'd want to extend the `CheckPackageContentOps` to include something to read the content of a file, and then add your check to the `checkPackageContent` set.

The reason we have this abstracted over file I/O is so that we can perform these checks not just on unpacked local packages, but also packed tarballs (which for example the hackage-server uses, it never unpacks the tarballs).

**Comment by phadej** [comment]
@dcoutts I did it the way I did, cause not sure if I can trust that the `*.cabal` file is always `package.cabal`. If it is so, i.e. there is (or one can create) `PackageDescription -> FilePath` function, then I'll do the change.

**Comment by phadej** [comment]
At least if I name my cabal file `mypackage-foo.cabal`, `cabal check` stills says `No errors or warnings could be found in the package.`.

**Comment by dcoutts** [comment]
Ahh good point. We'd have to duplicate the `findPackageDesc` logic. Ok, well isn't not a big deal. Could do it by adding a getDirectoryContents to `CheckPackageContentOps` but perhaps it's not worth it.

**Comment by dcoutts** [comment]
Pefect.

**Pull request merged**
