### PR TITLE
Updated warning message to output on stderr

### LINKED ISSUE #8393: "Warning: ... assertions enabled"  should go to stderr, not stdout
It it seems that the warning about assertions on goes to `stdout`, which is inconvenient for commands that produce reusable output, e.g. in use case `$(cabal list-bin foo)`:
```
$ cabal list-bin cabal-install
Warning: this is a debug build of cabal-install with assertions enabled.
/Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-9.2.4/cabal-install-3.9.0.0/x/cabal/build/cabal/cabal

$ cabal list-bin cabal-install 2>/dev/null
Warning: this is a debug build of cabal-install with assertions enabled.
/Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-9.2.4/cabal-install-3.9.0.0/x/cabal/build/cabal/cabal

$ cabal list-bin cabal-install > /dev/null
<EMPTY>
```
Request: send the warning to `stderr`.

Correct behavior should be secured by testsuite.

### PR DESCRIPTION
**Pull request by SaadAhmedGit**
This Fixes #8393
The message warning about assertions being enabled was previously being output to the stdout stream rather than stderr.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks for the PR!

If I infer the intentions of previous cabal developers correctly, there shouldn't be any naked `putStr` calls ever, but output should be channeled through one of the service functions given here: https://github.com/haskell/cabal/blob/a97e1f13bdb28a3f761d55845f14a9072bee17ca/Cabal/src/Distribution/Simple/Utils.hs#L34-L37
I suppose `warn` would be what we want here, and `warnIfAssertionsAreEnabled` then needs a `Verbosity` argument.

**Comment by ulysses4ever** [comment]
There's a similar PR right next door: #7838. Maybe you want to pick it up?

**Review by andreasabel — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]
LGTM, thanks! The big stderr switch will have to wait for another day, I guess…

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify refresh

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by andreasabel** [comment]
Weird, I commanded "squash + merge me" 4 days ago, but it still isn't merged.  I thought the waiting period was 2 days.  Is the Mergify way of merging brittle?  Should we go back to hit the button manually?

**Comment by Mikolaj** [comment]
The waiting period probably resets sometimes. I hope not at every manual rebase, but it's possible. As you can see I struggled with broken CI, fixed it, the merge queue was still blocked, so I rebased manually a few times, etc. Last time 2 days ago.

Merging delay is brittle whenever CI is broken.

**Comment by ulysses4ever** [comment]
Last events I see (before your comments today):

> jneira force-pushed the patch-1 branch from 5f395e6 to 0a01a22 2 days ago
> Mikolaj added the squash+merge me label 2 days ago 

When pointing "2 days ago" with the mouse, I see the exact time and it's less than 48 hours, so I don't see a problem.

I was thinking about this whole system, and I think what makes it take longer are concurrent merges during the 48 hours windows. Because Mergify has to rebase in that case, and that probably qualifies for a timer reset. Also, manual merges probably makes the queue of "law-abiding" (2-day rule preserving) merges to starve. 

It'd be nice to say: merge 2 days after last "significant" event, rather than any event, but that doesn't seem to be possible.

**Comment by andreasabel** [comment]
> It'd be nice to say: merge 2 days after last "significant" event, rather than any event, but that doesn't seem to be possible.

Yes, I think the clock should start ticking once the yellow "merge me" label is set.  If one wants to halt the merge process, one would remove that label again.
I suppose the API may not support this; I wonder if/hpw one could report this upstream to Mergify...

**Comment by ulysses4ever** [comment]
@andreasabel 

> Q: Is me commenting here also delaying the merge?

Correct.

**Comment by ulysses4ever** [comment]
I submitted an issue against Mergify tracker about the spurious delays: https://github.com/Mergifyio/mergify/issues/5036 Feel free to pitch in.

**Review by athas — APPROVED** [review]
Based on my understanding of the code base, this is correct.

**Comment by SaadAhmedGit** [comment]
Looks like mergify has cancelled putting this PR on squash+merge queue

**Comment by ulysses4ever** [comment]
It looks fine to me so far. The 2-day timer was reset by the last rebase 9 hours ago (and our comments after that), so we'll have to wait. Unless someone wants to take a liberty and merge it manually.

**Comment by andreasabel** [comment]
> Unless someone wants to take a liberty and merge it manually.

Yes, me.
I am loosing patience with the Mergify procrastinator.

**Comment by andreasabel** [comment]
Having been hit by
- #8654

I regret that I requested changes to @SaadAhmedGit 's original fix.  The problem is that the `warn` machinery does not work at this point where command line options are not passed, so it cannot be silenced with `-v0`.  So vanilla printing to `stderr` would have been better.  I'll open a new PR.

**Pull request merged**
