### PR TITLE
extraBundledLibs (fix typos in comments)

### PR DESCRIPTION
**Pull request by askeblad**
examples also properly sequenced

### CODE REVIEW

**Comment by askeblad** [comment]
@nh2 
@alexbiehl 

can you review

**Review by alexbiehl — APPROVED** [review]

**Review by nh2 — APPROVED** [review]

**Review by angerman — APPROVED** [review]
Thank you!

**Comment by Mikolaj** [comment]
Thank you for the fixes! 

Some CI jobs seems to have failed due to some network issues. Restarted.

**Review by Mikolaj — APPROVED** [review]
Spot on.

**Comment by Mikolaj** [comment]
Now different jobs from the restarted group failed. Restarting again. I won'der if it's GHA or if we are doing something wrong in our tests.

**Comment by Mikolaj** [comment]
Failed again. This seems like github error to me:

    fatal: unable to access 'https://github.com/haskell/cabal.git/': GnuTLS recv error (-54): Error in the pull function.

Let's wait until it fixes itself.

**Comment by Mikolaj** [comment]
Actually, let's merge and worry about CI only when merging other PRs.

**Comment by Mikolaj** [comment]
@mergifyIO rebase

**Pull request merged**
