### PR TITLE
Implement better error handling for "sandbox delete-source".

### PR DESCRIPTION
**Pull request by martinvlk**
This is a continuation of [pull/2939](https://github.com/haskell/cabal/pull/2939) with cleaned-up commits.

### CODE REVIEW

**Comment by martinvlk** [comment]
In response to the question about the newline in the output -

with the newline it might look like this:
```
Warning: Source directory not found for paths: "r" "s"
If you are trying to delete a reference to a removed directory, please provide
the full absolute path (as given by `sandbox list-sources`).

Warning: Sources not registered: "q"

cabal: The sources with the above errors were skipped.
```

While without newline it would be like this:
```
Warning: Source directory not found for paths: "r" "s"
If you are trying to delete a reference to a removed directory, please provide
the full absolute path (as given by `sandbox list-sources`).
Warning: Sources not registered: "q"
cabal: The sources with the above errors were skipped.
```

**Comment by martinvlk** [comment]
I guess I could add `\n\n` into the message string itself and not do it with a separate function, although that's just a matter of style, not principle.

**Comment by grayjay** [comment]
Listing the skipped sources again might make it easier to see where the errors start:

    Warning: Source directory not found for paths: "r" "s"
    If you are trying to delete a reference to a removed directory, please provide
    the full absolute path (as given by `sandbox list-sources`).
    Warning: Sources not registered: "q"
    cabal: The sources with the above errors were skipped ("q", "r", "s").

**Comment by martinvlk** [comment]
Good idea - I'll do that, thanks!

**Comment by martinvlk** [comment]
Ready for merge.

**Comment by BardurArantsson** [comment]
LGTM.

(If there are still quibbles about the exact error message formatting, that can be addressed in a follow-up PR.)

Btw, you actually don't have to do a new PR when rebasing -- you can just force-push to the branch in your own repository -- GitHub will automatically pick those commits up as the "new set of commits".

**Comment by 23Skidoo** [comment]
@martinvlk Thanks for your contribution!

**Pull request merged**
