### PR TITLE
Stabilize use of brew in GitLab CI

### PR DESCRIPTION
**Pull request by chreekat**
Use a specific release instead of HEAD.

Darwin job: https://gitlab.haskell.org/haskell/cabal/-/jobs/1399049

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] (N/A) Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] (N/A) The documentation has been updated, if necessary.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by chreekat** [comment]
Note that the (existing, unchanged) `brew update` line will change the version of brew anyway. This just uses a known-good version as a base on runners that don't have it cached yet.

**Comment by Mikolaj** [comment]
I will fast-merge as soon as CI finishes. but a second review is welcome anyway.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Pull request merged**
