### PR TITLE
Add ALens machinery

### PR DESCRIPTION
**Pull request by phadej**
I might need this for parser work (to provide accumulating grammar evaluation)

---

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
appveyor is really unreliable lately.

```
rogress: Downloading cabal 2.0.0.0... 3%ghc not installed. An error occurred during installation:
 The operation has timed out.
ghc package files install completed. Performing other installation steps.
The install of ghc was NOT successful.
ghc not installed. An error occurred during installation:
 The operation has timed out.
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - ghc (exited 1) - ghc not installed. An error occurred during installation:
 The operation has timed out
```

**Comment by 23Skidoo** [comment]
@hvr Can you add @phadej to the Cabal team on GitHub so that he could restart AppVeyor builds?

**Comment by hvr** [comment]
@23Skidoo done!

**Comment by 23Skidoo** [comment]
I haven't reviewed the diff, but basically I'm okay with adding whatever lens machinery is needed for the new parser as long as it doesn't involve TH.

**Pull request merged**
