### PR TITLE
Update the SPDX License List to version 3.16

### LINKED ISSUE #8126: Update the SPDX License list to v3.16 (2022-02-06)
Update the SPDX License list to v3.16 for Cabal 3.8

### PR DESCRIPTION
**Pull request by Kleidukos**
closes #8126

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by andreabedini — APPROVED** [review]
LGTM

**Review by Mikolaj — COMMENTED** [review]
Impressive. Is this done via a script and then verified? How is this verified/tested?

**Comment by Kleidukos** [comment]
@Mikolaj Absolutely, the `cabal-dev-scripts` has the `gen-spdx` and `gen-spdx-exc` executables to regenerate these lists from the JSON data that is provided. :)

**Comment by Mikolaj** [comment]
@Kleidukos: and how is this modified code verified/tested?

**Comment by Kleidukos** [comment]
@Mikolaj I learned the existence of this script yesterday evening, so I can't answer this. Maybe @gbaz has some insight?

**Comment by Mikolaj** [comment]
@gbaz: any comments? If not, let's merge before it bit-rots. :)

**Review by Mikolaj — APPROVED** [review]
Ready to merge IMHO.

**Comment by fgaz** [comment]
It looks like `CabalSpecV3_8` already exists, so this is easily done. @Kleidukos could you open a follow-up pr with the necessary changes to the files I mentioned?

**Comment by gbaz** [comment]
for the record i have absolutely no insight as to the scripts.

**Pull request merged**
