### PR TITLE
Don't specify hs-libraries when none exists!

### PR DESCRIPTION
**Pull request by ezyang**
This fixes GHC bug
https://ghc.haskell.org/trac/ghc/ticket/13268

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@ezyang Should this go into `2.0`?

**Comment by ezyang** [comment]
Yes please.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also cherry-picked into `2.0`.

**Pull request merged**
