### PR TITLE
Implement `--allow-older`

### PR DESCRIPTION
**Pull request by hvr**
This provides the dual flag to `--allow-newer` for symmetry

### CODE REVIEW

**Comment by hvr** [comment]
TODO:

 - [ ] documentation
 - [ ] changelog
 - [ ] testsuite

**Comment by 23Skidoo** [comment]
Since this is targeted at `master`, why is it important to avoid API breakage?

Also seems to break Travis.

**Comment by 23Skidoo** [comment]
I think it's fine to break the API in this case. It's unlikely that this will break any setup scripts.

**Comment by hvr** [comment]
@23Skidoo do you have any preference for how to rename the current `AllowNewer` type? Also I'd do this in a separate `commit`, maybe even in a spearate PR, as this will likely touch a lot of code.

For reference, here's the affected types that would need renaming to become less specific to `Newer`:

```hs
-- | Policy for relaxing upper bounds in dependencies. For example, given
-- 'build-depends: array >= 0.3 && < 0.5', are we allowed to relax the upper
-- bound and choose a version of 'array' that is greater or equal to 0.5? By
-- default the upper bounds are always strictly honored.
data AllowNewer =

  -- | Default: honor the upper bounds in all dependencies, never choose
  -- versions newer than allowed.
  AllowNewerNone

  -- | Ignore upper bounds in dependencies on the given packages.
  | AllowNewerSome [AllowNewerDep]

  -- | Ignore upper bounds in dependencies on all packages.
  | AllowNewerAll
  deriving (Eq, Read, Show, Generic)

-- | Dependencies can be relaxed either for all packages in the install plan, or
-- only for some packages.
data AllowNewerDep = AllowNewerDep PackageName
                   | AllowNewerDepScoped PackageName PackageName
                   deriving (Eq, Read, Show, Generic)
```

**Comment by 23Skidoo** [comment]
@hvr I think that something like the following should work:

```
data RelaxDeps = RelaxDepsNone | RelaxDepsSome [RelaxedDep] | RelaxDepsAll

data RelaxedDep = RelaxedDep PackageName
                | RelaxedDepScoped PackageName PackageName

newtype AllowNewer = AllowNewer RelaxDeps
newtype AllowOlder = AllowOlder RelaxDeps
```

**Comment by dcoutts** [comment]
Seems reasonable.

**Comment by hvr** [comment]
@23Skidoo @dcoutts ok, so you want this typesafe via `newtype`s to reduce the risk of mixing up codepaths related to newer/older? :-)

**Comment by hvr** [comment]
@23Skidoo @dcoutts I've rebased this on top of #3476 and the testsuite still compiles... yay!

**Comment by kosmikus** [comment]
This PR is marked "solver", but the way it's implemented, it does not seem to touch solver code at all.

In principle, I'd prefer somewhat if both `--allow-newer` and `--allow-older` would actually be implemented by tweaking the solver rather than by tweaking the index, but that would be a major change.

From what I can see, this PR looks useful and ok, but it touches a lot of modules I don't know very much about.

**Comment by hvr** [comment]
rebased against latest master

**Comment by 23Skidoo** [comment]
@kosmikus 
> In principle, I'd prefer somewhat if both `--allow-newer` and `--allow-older` would actually be implemented by tweaking the solver rather than by tweaking the index, but that would be a major change.

One problem with that is that `./Setup.hs configure --allow-newer` won't be able to utilise the solver-based code path, so we'll have to maintain the current one anyway.

**Comment by hvr** [comment]
rebased one last time & added docs/changelog/tests... once travis passes I'm gonna merge this to get this PR out of my sight... :-)

**Pull request merged**
