### PR TITLE
Properly expand globs when looking for headers in extra-src-files.

### PR DESCRIPTION
**Pull request by quasicomputational**
This ought to be the right fix, but I'm not actually sure what the original code is achieving here. When would headers go in `extra-source-files` rather than `includes`?

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
The documentation says

> A list of header files to be included in any compilations via C. This field applies to both header files that are already installed on the system and to those coming with the package to be installed. The former files should be found in absolute paths, while the latter files should be found in paths relative to the top of the source tree or relative to one of the directories listed in include-dirs.

But I'm really unsure what that means. And if it should or should not affect `{-# LANGUAGE CPP #-}`

**Comment by quasicomputational** [comment]
Looking again, this PR is a strict improvement - the previous code was illegitimate - so I guess we can put off figuring out what it actually *should* be doing; I'll go ahead and merge now.

**Comment by phadej** [comment]
> Looking again, this PR is a strict improvement - the previous code was illegitimate - so I guess we can put off figuring out what it actually should be doing; I'll go ahead and merge now.

When "we" will figure it out? Did you add a comment in code, and issue for that (if anything else to alert people who might now something about).

---

And merging when CI is failing is :-1:, **never**. You could had a fix in this PR already. Be careful.

**Comment by phadej** [comment]
I'm enabling more required jobs for CI, i guess that's the only way to be sure there are no ninja-merges

**Comment by phadej** [comment]
The commit in this PR is reverted

**Pull request merged**
