### PR TITLE
Relax upper bounds on filepath

### PR DESCRIPTION
**Pull request by hasufell**
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies `cabal` behaviour**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]

**Review by ffaf1 — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Comment by Mikolaj** [comment]
I'm going to expedite the merge unless anybody objects. @hasufell suggests this should be backported, so we need to speed up things to get this on 3.10 branch before the 3.10.3. release.

**Comment by Bodigrim** [comment]
I checked that it is safe to allow `filepath-1.5` in the latest released packages for `Cabal-syntax` and `Cabal`:
```
cabal unpack Cabal-syntax && (cd Cabal-syntax-3.10.2.0 && cabal build -c 'filepath>=1.5' --allow-newer='Cabal-syntax:filepath')
cabal unpack Cabal && (cd Cabal-3.10.2.1 && cabal build -c 'filepath>=1.5' --allow-newer='Cabal-syntax:filepath,Cabal:filepath')
```
(There are no tests in these packages, so `cabal build` instead of `cabal test`)

**Comment by Mikolaj** [comment]
@Bodigrim: thank you. I will bring this up in today's dev's meeting and, if there are no objections, I will make the Hackage revision to the latest versions of the two packages (or to more versions if that's what we decide, given that Julian requested "To do revisions for the last 3 versions that were shipped with GHC").

**Comment by Mikolaj** [comment]
We have a new policy. The agreement in the meeting was to make the revision, exclusively to the versions our policy covers, despite not fully meeting the secondary prerequisites from the policy. I've revised both https://hackage.haskell.org/package/Cabal-3.10.2.1 and https://hackage.haskell.org/package/Cabal-syntax-3.10.2.0. Thank you Julian and Bodigrim again.

**Pull request merged**
