### PR TITLE
Move doc/ to the top-level of the repository

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by jhrcek** [comment]
@phadej This seems to have broken the references in [Cabal/Cabal.cabal](https://github.com/haskell/cabal/blob/7118ea03a947cee8763d7d538bff0351eaa40774/Cabal/Cabal.cabal#L26-L31)

I'm getting build errors when building cabal library locally
```bash
~/Devel/github.com/haskell/cabal> (cd Cabal; cabal install)
cabal: filepath wildcard 'doc/bugs-and-stability.rst' does not match any
files.
```

**Comment by phadej** [comment]
@jhrcek ok, so you hit an issue https://github.com/haskell/cabal/issues/6955 would caught. I took a note.

**Comment by phadej** [comment]
@jhrcek fixed

**Comment by jhrcek** [comment]
@phadej Thank you, the  `(cd Cabal; cabal install)` step for building cabal library now works fine for me.

But the build steps for users guide are still broken:
https://github.com/haskell/cabal/blob/master/doc/README.md#how-to-build-it

1. The `cd Cabal` should probably be removed
2. When I run `make  users-guide` at project's root it basically erases the contents of the `doc/buildinfo-fields-reference.rst`

It's not blocking me or anything, just wanted to make you aware of the effect this recent move of users guide had.
I'd do the PR myself, but I'm not sure how to fix 2.

**Comment by phadej** [comment]
@jhrcek that should be fixed now as well

**Pull request merged**
