### PR TITLE
Add flag to allow the dependency solver to install any package (issue #4209).

### PR DESCRIPTION
**Pull request by grayjay**
--install-base-libraries makes cabal ignore the list of packages that cannot be
installed or upgraded.

I haven't added documentation yet.

### CODE REVIEW

**Comment by grayjay** [comment]
@23Skidoo Thanks.  I added a line to the changelog and documented the flag in Cabal/doc/nix-local-build.rst.  Is there anything else I should update?

**Comment by 23Skidoo** [comment]
I think that's all. Let's merge!

**Comment by grayjay** [comment]
Thanks!

**Comment by hvr** [comment]
Sorry to chime in so late: do we consider `--install-base-libraries` a good name for the flag? I would have expected something like `--allow-reinstall=*` or something to be more in line with `--allow-{newer,older}` and avoid overloading the term "`base`" (we also refer to such libraries sometimes as boot libraries or maybe even core libraries; it's all rather vague)

**Comment by 23Skidoo** [comment]
Sure, the name can be changed.

**Comment by grayjay** [comment]
@hvr Thanks for the feedback.  I had a hard time coming up with a descriptive name, so I would be happy to change it to something better.  What about `--allow-boot-library-installs`?  I didn't want to use reinstall, because we already have `--avoid-reinstalls` and `--force-reinstalls`, which use reinstall to mean installing an existing version again.

**Comment by 23Skidoo** [comment]
> What about `--allow-boot-library-installs`?

I like it. This is a flag that is useful only in very special circumstances, so a long descriptive name is perfectly OK and makes it unlikely people will use it by mistake.

**Comment by hvr** [comment]
`--allow-boot-library-installs` sounds more consistent to me; sounds good to me!

**Comment by grayjay** [comment]
Thanks.  I made a PR: #4240

**Pull request merged**
