### PR TITLE
Oops! Forget to delete old PkgconfigDependency during refactor

### PR DESCRIPTION
**Pull request by Ericson2314**
And Travis still passed on the old one...huh.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM. Please merge once CI is green.

**Comment by Ericson2314** [comment]
Passed CI except for 2 travis timeouts.

**Comment by ezyang** [comment]
@Ericson2314 For future reference, if the OS X build times out, just restart those jobs (using the loopy arrow on Travis's interface). Usually, a timeout means we needed to repopulate the cache, which will get persisted on the next run.

**Comment by Ericson2314** [comment]
Oh right. Totally forgot about per-job restarts despite doing them yesterday.

**Pull request merged**
