### PR TITLE
backticks (.md files)

### PR DESCRIPTION
**Pull request by askeblad**
https://github.github.com/gfm/

This change is for coders using Gruber's Perl script.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by askeblad** [comment]
Where Markdown.pl is on your `$PATH`.

~/.emacs.d/init.el

```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/"))
(custom-set-variables
 '(markdown-command "Markdown.pl")
 '(package-selected-packages '(markdown-preview-mode)))
```

The GHC repository on GitLab contained solely these .md files which were using tildes for quoting.

**Comment by Mikolaj** [comment]
Where can one get `Markdown.pl` from? How are the tildes related to `Markdown.pl` (I understand they break Gruber's Perl script, but is that the script?)?

**Comment by askeblad** [comment]
> Where can one get Markdown.pl from?

https://daringfireball.net/projects/markdown/

Markdown 1.0.1 (18 KB) — 17 Dec 2004
Markdown_1.0.1.zip

> How are the tildes related to `Markdown.pl` (I understand they break Gruber's Perl script, but is that the script?)?

Tildes simply aren't allocated for fencing code blocks in the Perl script.

**Comment by Mikolaj** [comment]
Makes sense. Thank you.

**Comment by askeblad** [comment]
GHC Wiki

- [emacs](emacs)
  - [markdown preview](https://gitlab.haskell.org/ghc/ghc/-/wikis/markdown-preview)

**Comment by askeblad** [comment]
@supersven

Noting you've edited the GHC Wiki emacs page I send you a notice that a [markdown preview](https://gitlab.haskell.org/ghc/ghc/-/wikis/markdown-preview) page has been added.

[haskell mode tng](https://github.com/nurmi-labs/blogger/wiki/haskell-mode-tng) (blog Wiki page)

**Comment by Mikolaj** [comment]
@askeblad: why have you closed this PR? Are you discouraged by another reviewer not appearing promptly? That's normal, people are busy, something a PR waits for the first or the second review many days.

**Comment by askeblad** [comment]
I'm busy, closing had nothing to do with awaiting a second review.

**Comment by Mikolaj** [comment]
OK. Thank you for your contributions so far and I hope you will find time for some more in the future.

**Pull request closed without merging**
