### PR TITLE
Don't error if package index is missing (fix #10504)

### LINKED ISSUE #10504: "active-repositories: none" reportedly broken
It is reported on https://github.com/haskell/cabal/pull/8944 that this broke `active-repositories: none`. If so, that's very bad and we should fix it!

### PR DESCRIPTION
**Pull request by ulysses4ever**
Cherry picked https://github.com/MercuryTechnologies/cabal/commit/ec242b1cb21e450d5212efd5c445f0d70786092e

Would be great to have a test...

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by gbaz — APPROVED** [review]

**Comment by gbaz** [comment]
As per my comments in https://github.com/haskell/cabal/issues/10504 I've come around to seeing this as the correct fix. If the missing package index causes problems down the line we'll error anyway. If not, then this is intended behavior and warning is fine.

The semantics of active-repositories is that it picks which of the repositories cabal pulls from are _active_ and in what order -- it was not designed to choose which repositories cabal connects to entirely.

**Comment by ulysses4ever** [comment]
The [test failure](https://github.com/haskell/cabal/actions/runs/11668633937/job/32488748055?pr=10506) is interesting:

```diff
-Error: [Cabal-7160]
-The package list for 'repo.invalid' does not exist. Run 'cabal update' to download it.
+Warning: The package list for 'repo.invalid' does not exist. Run 'cabal update' to download it.
+Error: [Cabal-7100]
+There is no package named 'a-b-s-e-n-t'. 
+You may need to run 'cabal update' to get the latest list of available packages.
```
Arguably, failing earlier in this case is preferable because the reason we failed is not that something is inherently wrong with the `a-b-s-e-n-t` package but because our repository wasn't configured correctly in the first place, and no matter what package we'll try to get, we'll fail.

So, in this case, I'd argue that reverting the error mode makes the error message worse.

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
For posterity: on today's Cabal meeting people agreed that we want to revert it, if only temporarily, until a better solution is found, in the interest of releasing 3.14 without this overly strict behavior.

**Comment by ulysses4ever** [comment]
@mergify backport 3.14

**Pull request merged**
