### PR TITLE
Use ProjectFlags to define CleanCmd

### LINKED ISSUE #6816: Use ProjectFlags in CmdClean

### PR DESCRIPTION
**Pull request by shapr**
Reduce duplication of project flag handling, fixes #6816 

The nearly identical PR for #7439 was used as a guide for this PR.

---
* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
I get the impression `NamedFieldPuns` is not well liked here, but otherwise it's okay.

**Comment by exarkun** [comment]
> Thanks for the contribution!
> 
> I'm fine with field puns but it's strange to see it turned on together with wildcards -- their purpose largely intersects. Also, where are puns used? I couldn't spot it when skimming the text of the patch.

Just in the definition of `cleanAction`, unpacking `flagProjectName`.  Happy to remove the use of this extension if that's preferred, we just copied the style from CmdOutdated.hs

**Comment by ulysses4ever** [comment]
Oh, I see now. Yeah, **for consistency**, it'd make sense to replace it with wildcards, I think. But only because of that. I personally prefer puns to wildcards.

**Review by ulysses4ever — APPROVED** [review]
Thanks!

**Comment by exarkun** [comment]
Thanks for the reviews!

Per the contributor guide, now labeling for merge.

**Comment by ulysses4ever** [comment]
@exarkun thank you! ❤️

**Pull request merged**
