### PR TITLE
Only use -Werror in validate

### LINKED ISSUE #9866: -Werror being used always, not only on validate
In 0876e18 there was a refactor of cabal projects which introduced the following "regression":

Previously, we would only compile with `ghc-options: -Werror` when using the `cabal.project.validate{.libonly}` projects.
After 0876e18, we always compile with `ghc-options: -Werror`.

I don't think in-tree builds should use `-Werror`. It is valuable as a validation tool when the MR has to be finished and be validated by CI, but I don't think that when iterating on a patch one should care about all warnings, and `-Werror` makes this unnecessarily painful.

cc @philderbeast

### PR DESCRIPTION
**Pull request by alt-romes**
Reverts a change that made `-Werror` be applied when building in tree Cabal, even when just developing. Puts `-Werror` back in the `cabal.project.validate` validation project.

Fixes #9866

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by fendor — APPROVED** [review]

**Comment by Mikolaj** [comment]
@fendor, FYI, the merging process has changed since you made numerous contributions to cabal last time. It's now described in https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions

Setting the merge label would ensure mergify rebases and runs CI, if needed, so we'd avoid the non-linear history that sneaked in. This also incurs a 2 day delay, which I understand you wanted to avoid, given that devs are inconvenienced by this unintended change continuously. The informal process for avoiding the delay, as people on the Matrix channel would tell you, is to announce the intention in the ticket, ask for objections and wait for a few hours. If there are objections, escalate (e.g., on the Matrix channel), if no objections, merge and prepare for a discussion and a possible revert later on. If you want to wait even less, announce in the Matrix channel, PM interested parties (that would be @philderbeast in this case), etc. I hope that sounds fair?

**Comment by fendor** [comment]
I am terribly sorry, this was unintentionally against policy. I should have read the conventions more carefully and will make sure I do so before I try to merge a PR next time.

**Comment by philderbeast** [comment]
I'm good with this change, moving where the `-Werror` goes.

**Comment by Kleidukos** [comment]
@mergifyIO backport 3.12

**Pull request merged**
