### PR TITLE
Add wasm32-wasi to recognized arch/os

### PR DESCRIPTION
**Pull request by TerrorJack**
This patch adds `wasm32` to known archs, and `wasi` to known oss. It's a part of the work of adding webassembly support to ghc at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7632.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Thank you for the PR. Please kindly compare with the very recent https://github.com/haskell/cabal/pull/8065 and ask in either of the PRs if you need any help.

**Comment by TerrorJack** [comment]
@[Mikolaj](https://github.com/Mikolaj) Thanks for reminding; would you take another look now?

**Review by Mikolaj — APPROVED** [review]
LGTM. CI is borked independently (cache?).

**Comment by TerrorJack** [comment]
I also suspect a stale cache issue here; would you accept a patch that bumps cache name from `${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}` to `${{ runner.os }}-${{ matrix.ghc }}-0-${{ github.sha }}`? (And people can bump from `0` in the future in similar cases)

**Comment by Mikolaj** [comment]
> I also suspect a stale cache issue here; would you accept a patch that bumps cache name from `${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}` to `${{ runner.os }}-${{ matrix.ghc }}-0-${{ github.sha }}`? (And people can bump from `0` in the future in similar cases)

@fgaz: is this similar to what you proposed on #hackage?

**Comment by fgaz** [comment]
I proposed to add a workflow to fill (=> flush) the cache so we don't have to increase that number every time, but it doesn't seem to be working yet (#8097). Maybe pr and branch caches are separate?

**Review by fgaz — COMMENTED** [review]
Is it right to add the architecture to cabal before adding it to ghc? Shouldn't it be the opposite?

**Comment by fgaz** [comment]
https://github.com/haskell/cabal/pull/8097 didn't work, @TerrorJack could you open a pr with the workaround you mentioned?

**Comment by jneira** [comment]
I would use a date (`v20220416`) instead version number to make more evident the last time we had to bump it (as we will need to invalidate it regularly even without corruption issues until we redesign it)

**Comment by TerrorJack** [comment]
> could you open a pr with the workaround you mentioned?

I've added a commit in place to see whether the workaround works; if you think it is better to open a separate PR and merge that first, I'll also be fine to do that.

> Is it right to add the architecture to cabal before adding it to ghc? Shouldn't it be the opposite?

I'll open GHC MR to add the arch/os pair soon. But still, I'd like the Cabal PR to be opened and reviewed earlier, since it blocks other pending PRs of ghc boot libs, due to `cabal check` failure. It'll take time for this change to land into a `cabal` release, better sooner than later.

**Comment by TerrorJack** [comment]
> could you open a pr with the workaround you mentioned?

I've added a commit in place to see whether the workaround works; if you think it is better to open a separate PR and merge that first, I'll also be fine to do that.

> Is it right to add the architecture to cabal before adding it to ghc? Shouldn't it be the opposite?

I'll open GHC MR to add the arch/os pair soon. But still, I'd like the Cabal PR to be opened and reviewed earlier, since it blocks other pending PRs of ghc boot libs, due to `cabal check` failure. It'll take time for this change to land into a `cabal` release, better sooner than later.

**Comment by TerrorJack** [comment]
CI is now green 👀

**Pull request merged**
