### PR TITLE
Refactor ProjectConfig Arbitrary instances

### PR DESCRIPTION
**Pull request by bitrauser**
In response to #4044, begin using record syntax instead of positional arguments.

I think this can be improved so I am happy for any kind of feedback and/or tips, especially since a part still uses positional arguments, but this change should already make it a bit clearer.

### CODE REVIEW

**Comment by ezyang** [comment]
Great! You should merge when the build is green. OOC, why did you change the maps to fmaps?

**Comment by bitrauser** [comment]
I thought those were an inconsistency, will change them back if I am mistaken.

**Comment by 23Skidoo** [comment]
Since `fmap` is overloaded, it makes you stop and think about which `Functor` instance is used each time when you're reading the code. So I prefer using `map` in monomorphic context.

**Comment by bitrauser** [comment]
That does make sense, I was under the impression that fmap is generally preferred.

**Pull request merged**
