### PR TITLE
[cabal-9417] Fix cabal haddock --open on Windows

### LINKED ISSUE #9417: cabal haddock --open doesn't work on windows
On windows `findOpenProgramLocation` tries to use `start` in order to open a browser to show the documentation.

However, this doesn't work because `start` isn't an executable but a built-in command.

See: https://web.archive.org/web/20101030061633/http://frank.neatstep.com/node/84

```
The trick is that "start" isn't an executable. It is a built-in command of the Windows command line interpreter "cmd.exe". In Java (and other languages) if you try to create a process using the "start" command this will fail -- since there is no "start.exe" executable in the system.

Instead you have to invoke "start" through the "cmd.exe" interpreter. This can be done using the /C flag:

cmd /c "start readme.txt"
```

It seems this would have been caught if there had been a test added for the `haddock --open` option.

### PR DESCRIPTION
**Pull request by Kleidukos**
closes #9417

I've tested it locally, but Windows users are encouraged to provide feedback as well.

## QA Notes

On a Windows machine, build a haskell project with haddock enabled, and run `cabal haddock --open`. The default browser should be started with the index.html page

### CODE REVIEW

**Comment by mpickering** [comment]
Have you tested this? Do you mean `explorer.exe`? This seems different to the suggested solution from the ticket of running `cmd.exe /c "start index.html"`

**Review by ffaf1 — APPROVED** [review]

**Comment by Kleidukos** [comment]
@mpickering I'm testing on a windows VM right now, I just forgot to mark the PR as draft.

**Comment by Kleidukos** [comment]
> Have you tested this? Do you mean `explorer.exe`? This seems different to the suggested solution from the ticket of running `cmd.exe /c "start index.html"`


Reading [this manual page](https://ss64.com/nt/explorer.html), there seems to be an overlap of feature between `start` and `explorer`. `start` might be more interesting if we use its flags (https://ss64.com/nt/start.html), but I don't believe we have to do it.

**Comment by Kleidukos** [comment]
@Mistuke Do you have an opinion on this?

**Comment by geekosaur** [comment]
AIUI the difference between the two is that `explorer` is hardcoded, whereas `start` uses the primary application in the registry.

**Comment by Kleidukos** [comment]
@geekosaur well that's surprising because when trying it, this opens Firefox, which I've set as default

**Comment by ffaf1** [comment]
https://github.com/rightfold/open-browser/blob/1c862a6dc5943cdfe5860a743b9f545584156436/lib/Web/Browser/Windows.hs#L10-L18

`open-browser` apparently uses `open`.

**Comment by Mistuke** [comment]
> @Mistuke Do you have an opinion on this?

What @ffaf1 posted is the right way to do it. Calling shell execute will read the "open" verb in the registry for the given extension and open the default application.

**Review by ffaf1 — APPROVED** [review]

**Comment by jasagredo** [comment]
I wonder if I'm not understanding what is supposed to happen with this change, but `start` works for me and `open` does not, on PowerShell on Windows 11.

```
PS C:\Users\Javier> open a.txt
open : The term 'open' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ open install.sh
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (open:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Mistuke** [comment]
> I wonder if I'm not understanding what is supposed to happen with this change, but `start` works for me and `open` does not, on PowerShell on Windows 11.
> 
> ```
> PS C:\Users\Javier> open a.txt
> open : The term 'open' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + open install.sh
> + ~~~~
>     + CategoryInfo          : ObjectNotFound: (open:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```

Open is a verb not a command. https://learn.microsoft.com/en-us/windows/win32/shell/launch

**Comment by jasagredo** [comment]
MinGW does not open the haddocks:
```bash
❯ cabal haddock --open
...
Documentation created:
C:\Users\Javier\code\bifunctors-5.6.1\dist-newstyle\build\x86_64-windows\ghc-9.6.3\bifunctors-5.6.1\doc\html\bifunctors\
Error: [Cabal-7125]
Failed to build documentation for bifunctors-5.6.1. The exception was:
  open: createProcess: does not exist (No such file or directory)

~\code\bifunctors-5.6.1 via λ 9.6.3 took 40s
❯
```

Nor does PowerShell:
```powershell
PS C:\Users\Javier\code\bifunctors-5.6.1> cabal.exe haddock --open
...
Documentation created:
C:\Users\Javier\code\bifunctors-5.6.1\dist-newstyle\build\x86_64-windows\ghc-9.6.3\bifunctors-5.6.1\doc\html\bifunctors\
Error: [Cabal-7125]
Failed to build documentation for bifunctors-5.6.1. The exception was:
  open: createProcess: does not exist (No such file or directory)

PS C:\Users\Javier\code\bifunctors-5.6.1>
```

**Comment by ulysses4ever** [comment]
@jasagredo does it work in cmd.exe on your end, at least? It's a little hard to support both shell interpreters, it seems. Although maybe someone with more Windows expertise knows how to do it?

**Comment by Mistuke** [comment]
This is not terminal emulator related. But it requires shellexecute to be called. I haven't followed where the function ends up, but it needs to end up in a process call with shellexecute set to True. Otherwise it won't work and instead it'll look for a program callee `open` which won't work.

**Comment by ulysses4ever** [comment]
@Kleidukos should we close this as superseded by #9537?

**Comment by Kleidukos** [comment]
Yep!

**Pull request closed without merging**
