### PR TITLE
Parsec parser

### PR DESCRIPTION
**Pull request by phadej**
This WIP:

https://github.com/haskell/cabal/issues/2865

TODO:
- [ ] make new second stage using new parser
- [ ] verify that resulting GenericPackageDescription are the same (except the already known exceptions)
- [ ] more warnings in lexer (leading tabs)
- [ ] make a switch

Comments are welcome

### CODE REVIEW

**Comment by phadej** [comment]
On my machine
```
stack exec cabal-parser-perf perf-old 0   22.59s user 0.85s system 93% cpu 25.045 total
stack exec cabal-parser-perf perf-new 0   8.49s user 0.63s system 93% cpu 9.747 total
```

Though the performance isn't the goal, but it's nice that it is improved as well!

**Comment by phadej** [comment]
There are also bunch of issues, which this might or might not resolve:
- https://github.com/haskell/cabal/issues/366
- https://github.com/haskell/cabal/issues/1008
- https://github.com/haskell/cabal/issues/1509
- https://github.com/haskell/cabal/issues/2343
- https://github.com/haskell/cabal/issues/2804
- https://github.com/haskell/cabal/issues/2839
- https://github.com/haskell/cabal/issues/2832
- https://github.com/haskell/cabal/issues/2407

**Comment by 23Skidoo** [comment]
Good to see this finally being worked on. Besides CPU, you might also want to look at memory usage.

**Comment by phadej** [comment]
```
% time stack exec cabal-parser-perf -- perf-old 0 ~/Library/Haskell/repo-cache/hackage.haskell.org/00-index.tar +RTS -s
60872
  78,193,743,472 bytes allocated in the heap
   7,196,358,072 bytes copied during GC
     307,703,728 bytes maximum residency (59 sample(s))
      33,123,256 bytes maximum slop
             745 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     149740 colls,     0 par    6.776s   7.321s     0.0000s    0.0269s
  Gen  1        59 colls,     0 par    1.005s   1.152s     0.0195s    0.1376s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time   14.654s  ( 15.403s elapsed)
  GC      time    7.782s  (  8.473s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time   22.469s  ( 23.877s elapsed)

  %GC     time      34.6%  (35.5% elapsed)

  Alloc rate    5,335,938,426 bytes per MUT second

  Productivity  65.4% of total user, 61.5% of total elapsed

stack exec cabal-parser-perf -- perf-old 0  +RTS -s  22.56s user 0.74s system 96% cpu 24.083 total
```

```
% time stack exec cabal-parser-perf -- perf-new 0 ~/Library/Haskell/repo-cache/hackage.haskell.org/00-index.tar +RTS -s
60849
  35,629,246,056 bytes allocated in the heap
   1,285,198,392 bytes copied during GC
     279,760,096 bytes maximum residency (12 sample(s))
      35,124,400 bytes maximum slop
             636 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     68051 colls,     0 par    1.159s   1.290s     0.0000s    0.0029s
  Gen  1        12 colls,     0 par    0.258s   0.363s     0.0302s    0.1150s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    5.943s  (  6.213s elapsed)
  GC      time    1.417s  (  1.652s elapsed)
  EXIT    time    0.003s  (  0.029s elapsed)
  Total   time    7.405s  (  7.895s elapsed)

  %GC     time      19.1%  (20.9% elapsed)

  Alloc rate    5,994,938,780 bytes per MUT second

  Productivity  80.9% of total user, 75.8% of total elapsed

stack exec cabal-parser-perf -- perf-new 0  +RTS -s  7.52s user 0.52s system 98% cpu 8.158 total
```

**Comment by dcoutts** [comment]
Great stuff. When you make the final pull req (or update this one) it'd be good to rebase it to squish it into fewer logical patches. My original patch was just a snapshot of my hacking experiment.

**Comment by phadej** [comment]
superseeded by https://github.com/haskell/cabal/pull/2879

**Pull request closed without merging**
