### PR TITLE
Update to hackage-security-0.5.1

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by hvr** [comment]
@23Skidoo I haven't tested the bootstrap-script change yet, so be careful before merging

**Comment by hvr** [comment]
@23Skidoo another thing I noticed:

```
CABAL_VER="1.24.0.0";  CABAL_VER_REGEXP="1\.24\.[0-9]"
```

shouldn't that be 1.24.1.0 by now? (GHC 8.0 RC4 ships with 1.24.1.0 as well)

**Comment by dcoutts** [comment]
So this means we avoid the dep on cryptonite, both packages are using cryptohash-sha256.

**Comment by 23Skidoo** [comment]
LGTM.

> shouldn't that be 1.24.1.0 by now? (GHC 8.0 RC4 ships with 1.24.1.0 as well)

I was considering changing it back to 1.24.0.0 for the release. Do you think it's a bad idea?

**Comment by hvr** [comment]
@23Skidoo 

> I was considering changing it back to 1.24.0.0 for the release. Do you think it's a bad idea?

It's a bit weird... but I don't think it'd be a big deal if you decrement again... (this was mostly to workaround Travis/GHC8 issues, right?)

/cc @bgamari

**Comment by 23Skidoo** [comment]
Yep.

**Comment by 23Skidoo** [comment]
Confirmed that `bootstrap.sh` works.

**Pull request merged**
