### PR TITLE
Finish improvements to the CI configuration for documentation changes

### PR DESCRIPTION
**Pull request by BinderDavid**
The previous PR was #9355 which reconfigured the validate jobs to not run on documentation changes. This PR finishes the job with the following improvements:

- Previously we only considered changes to `docs/` as documentation changes. We now also recognize changes to  `README.md` and `CONTRIBUTING.md`.
- There is now a "Bootstrap post job" which succeeds if, and only if, all of the bootstrap jobs succeed. This is just copy-pasted from the validate.yml file which also uses this configuration to simplify the configuration of the GitHub repo.
- Documentation changes now also skip the bootstrap jobs.
- I added a small comment to CONTRIBUTING.md mentioning the improvements to the CI.

**VERY IMPORTANT:** This only works properly if we also change the configuration of the repository (which I cannot do in code) so that the bootstrap post job is required instead of the individual bootstrap jobs!

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]
Thanks!

I think Mikolaj noticed that we have a bunch of readme files in subdirectories, and they could also be skipped. Do you need to put `**/README.md` to make it work?

**Comment by BinderDavid** [comment]
> Thanks!
> 
> I think Mikolaj noticed that we have a bunch of readme files in subdirectories, and they could also be skipped. Do you need to put `**/README.md` to make it work?

I changed it to include all README.md files.

**Comment by geekosaur** [comment]
Reminder:

**VERY IMPORTANT**: This only works properly if we also change the configuration of the repository (which I cannot do in code) so that the bootstrap post job is required instead of the individual bootstrap jobs!

**Comment by Mikolaj** [comment]
Thank you for the reminder. I've just done the Settings change for branch master. Let's see in subsequent PRs if this works fine.

**Pull request merged**
