### PR TITLE
A terrible hack which solves #3545.

### PR DESCRIPTION
**Pull request by ezyang**
See the comment in the code.  I don't like it but it's BC!

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
@23Skidoo @phadej What do you think?

**Comment by phadej** [comment]
I don't think that re-arranging `dist` is breaking change as it's not clearly specified either. IIRC @dcoutts have commented about that somewhere.

Also e.g. https://github.com/ekmett/bound/blob/master/Setup.lhs doesn't rely on where stuff goes, as it asks `Cabal` where it puts stuff.

Also https://github.com/haskell/cabal/pull/3022 broke stuff already (for `cabal_macros.h`)

---

But if it helps for now, then LGTM

---

I'd propose to separate `dist/build` clearly per component, as we ultimately want to treat them fully independently apart that they come in single source package.

**Comment by 23Skidoo** [comment]
I'd prefer the solution originally proposed in #3545, i.e. rearranging the directories. Using `dist/build` for library files always felt wrong to me.

**Comment by ezyang** [comment]
This change is vetoed!

**Pull request closed without merging**
