### PR TITLE
Update SPDX license list to 3.0 (28 December 2017)

### PR DESCRIPTION
**Pull request by phadej**
Resolves https://github.com/haskell/cabal/issues/5145

(Note: the spec is 2.1 but license list version is 3.0 - they have different version numbers).

---

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Question: Should we include deprecated identifiers (e.g. now also `GPL-2.0`) in the list and what to do with them, warn in *cabal check*?

**Comment by 23Skidoo** [comment]
Do you want this included in 2.2?

**Comment by phadej** [comment]
@23Skdoo, yes that would be great. If we *want* to include deprecated identifiers too (say leaving out the very old one with trailing `+`), adding a cabal check would be a small thing to do. (matter of hours).

**Comment by phadej** [comment]
To clarify for now we can pretened older SPDX identifier lists never existed. At some point accepting also deprecated identifiers will be a must. The question is
- do we want to accept them all today
- accept only deprecated in 2.5&ndash;3.0 period (i.e. GPL-2.0), given list v3.0 is quite new
- or don't accept any deprecated identifiers

**Comment by 23Skidoo** [comment]
IMO accepting only 3.0+ identifiers makes sense, but we must make sure that entering `GPL-2.0` produces a good error message recommending the use of `GPL-2.0-only` or `GPL-2.0-or-later` instead. Perhaps we can use Levenshtein distance for that? Also, we should document somewhere which SPDX version corresponds to which Cabal spec version.

**Comment by 23Skidoo** [comment]
I'm going to create the 2.2 branch now, but will cherry-pick this to the release branch once it's ready.

**Comment by phadej** [comment]
@23Skidoo pushed an update

**Comment by phadej** [comment]
ping @23Skidoo travis is green

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also cherry-picked into 2.2.

**Pull request merged**
