### PR TITLE
Bump Cabal versions from 2.5 -> 3.0

### PR DESCRIPTION
**Pull request by hvr**
NOTE: This will most certainly fail at CI because of the `cabal-testsuite.cabal` requiring a bleeding edge lib:Cabal for its Setup.hs -- I can't find the ticket, but there's a a plan to decouple `cabal-testsuite` from requiring a bleeding edge lib:Cabal (UPDATE: see #5916)

Another (less ideal) workaround would be to use a `cabal` 3.0.* executable for building `cabal-testsuite`

Addressing #5819

### CODE REVIEW

**Comment by phadej** [comment]
`cabal-testsuite` indeed failed on appveyor

**Comment by bgamari** [comment]
On what sort of timeframe can we expect this to be merged? Perhaps it would make sense for GHC to just start tracking this branch?

**Comment by hvr** [comment]
@bgamari we could push the commit from this PR together with a instant-revert-followup-commit to `master`, and then you could refer to that; using this branch would be dangerous as there's no guarantee the commit  971f083 will remain reachable and then you'd end up with a broken gitlink in ghc.git

**Comment by bgamari** [comment]
@hvr, we could do that but we'll need to sort out [#16378](https://ghc.haskell.org/trac/ghc/ticket/16378) before we can do so.

**Comment by hvr** [comment]
@bgamari can that very backpack failure be reproduced with GHC 8.6? or is it really a function of the GHC version and specific to GHC 8.8?

**Comment by 23Skidoo** [comment]
This is green, time to merge?

**Pull request merged**
