### PR TITLE
Use tree-diff

### PR DESCRIPTION
**Pull request by phadej**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Oh dear.
```
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the packages are required by a dependency of one
of the other targets
```

That's probably because `tree-diff` has `build-type: Custom`?

**Comment by 23Skidoo** [comment]
> That's probably because `tree-diff` has `build-type: Custom`?

...and `tree-diff` ends up depending on Cabal via its custom setup. Probably, though the solver should've picked a different version of Cabal for `tree-diff`'s setup dependency... but `--only-dep` is likely too dumb to deal with that.

**Comment by hvr** [comment]
@phadej ...stating the obvious question: would it hurt if tree-diff became build-type:simple? you could still perform CI in tree-diff's git repo with a modified .cabal file...

**Comment by phadej** [comment]
@hvr, I'd need `extra-packages` to make development process smooth

**Comment by phadej** [comment]
`parsers` is `build-type: Custom`.

**Pull request merged**
