### PR TITLE
Add instruction for CI patches

### PR DESCRIPTION
**Pull request by ffaf1**
Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Brilliant.

**Comment by ffaf1** [comment]
We could indicate old-but-not-yet-retired branches in the template or in other parts of the documentation.

**Comment by Mikolaj** [comment]
Though is it obvious what "CI PR" is? That it's "a PR that fixes CI"?

**Review by ulysses4ever — APPROVED** [review]
It's the right direction to move in, thank you! 

3.10 is kinda problematic because it already has CI busted, I think. (@Kleidukos knows more.) But we need to start somewhere...

**Comment by ulysses4ever** [comment]
Maybe instead of mentioning the specific branch, we could say, "ask maintainers" for directions or something?

A more precise way to define a "CI PR" would be a PR touching anything in `.github` or `.readthedocs.yml`?

**Comment by ffaf1** [comment]
> Maybe instead of mentioning the specific branch, we could say, "ask maintainers" for directions or something?

I am not against but I tried to avoid it, as it feels yet some more friction to contribute.
What would be the rationale? Would only some PRs be backported (or backported to specific branches)?

> A more precise way to define a "CI PR" would be a PR touching anything in .github or .readthedocs.yml?

This PR touches `.github`, but is not CI! Current wording: "Is this a PR that fixes CI?"

**Comment by ulysses4ever** [comment]
>  What would be the rationale? Would only some PRs be backported (or backported to specific branches)?

Currently, this text mentions one particular branch (3.10). So, it will need maintenance: regular updates. If you don't name the branch, the maintenance is zero. And maintainers have to look into the PR anyway, most of the time.

But I don't feel strongly about it. If you like putting a specific branch, please do. It'd be good to have some plan as to when to update it and who is in charge of that.

> This PR touches .github, but is not CI! Current wording: "Is this a PR that fixes CI?"

Well, you can treat it as a necessary condition but not sufficient. I feel like "fixes CI" is a little too vague. But I don't have a good candidate that is not overly specific, so please go ahead with what you think will work best.

**Comment by ffaf1** [comment]
I have elminated references for a specific branch and left the first part untouched: if contributors are confused, we will change it.

**Review by jasagredo — APPROVED** [review]
Nice!

**Comment by Mikolaj** [comment]
> 3.10 is kinda problematic because it already has CI busted, I think. (@Kleidukos knows more.) But we need to start somewhere...

I do hope 3.10 CI is not busted yet. There is a problem with backporting PRs, due to the formatting change, but that normally should not affect CI fixes.

**Comment by ulysses4ever** [comment]
I guess I mixed it up with 3.8, sorry. 

Correct about CI fixes.

**Pull request merged**
