### PR TITLE
Fix --repl-options parsing

### PR DESCRIPTION
**Pull request by bacchanalia**
Bug #7867

### CODE REVIEW

**Review by jneira — COMMENTED** [review]
Hi, thanks for the standalone fix, it would need a regression test, but if you have tested manually and it is included in your main pr in some way it would be fine for me.
A changelog entry would be great.

**Comment by jneira** [comment]
As noted by @bacchanalia the bug is not in any release so the changelog would not be needed and the main pr is already testing it, could you add a brief note about what test is and how is testing the bug?

**Comment by bacchanalia** [comment]
In the latest design of #7851, I use replOptionsFlags to pass the script location between cabal-install and Cabal, so either `cabal-testsuite/PackageTests/NewBuild/CmdRepl/Script` or `cabal-testsuite/PackageTests/NewBuild/CmdRepl/ScriptRerun` would catch it because the repl would fail to load from the script file being passed multiple times.

**Comment by jneira** [comment]
The pr (#7578) by @sirlensalot had specific tests so i hope this change will not break the functionality added there

**Review by jneira — APPROVED** [review]
looks good to me given the notes about the changelog and tests, thanks for the fix!

**Comment by Mikolaj** [comment]
I think the backport of this bug is in 3.6.2 (#7593), ain't it so?

**Comment by jneira** [comment]
it seems #7593 the pr was closed wisely by @fgaz without merging it

**Comment by Mikolaj** [comment]
Wow, I missed it. Well done, team. :)

**Review by Mikolaj — APPROVED** [review]
Super.

**Comment by jneira** [comment]
no need for backport then (i was not sure if the bug was backported aftere the release)

**Comment by sergv** [comment]
Although I'm not the original author, I can confirm that the commit is correct. I did encounter this problem myself and did a bit of investigation.

The original commit (cf https://github.com/haskell/cabal/commit/785ea62d2b6c7d2e91654eb7a23cafccac3ec08c#diff-793c63febac9c808425678cd5535233aebb1aca838a829a665f85d4452f62346L1766) did the following change
<pre><code>
-replOptions :: ShowOrParseArgs -> [OptionField [String]]
-replOptions _ = [ option [] ["repl-options"] "use this option for the repl" <b>id</b>
-              <b>const</b> (reqArg "FLAG" (succeedReadE (:[])) id) ]
+replOptions :: ShowOrParseArgs -> [OptionField ReplOptions]
+replOptions _ =
+  [ option [] ["repl-no-load"]
+    "Disable loading of project modules at REPL startup."
+    replOptionsNoLoad (\p flags -> flags { replOptionsNoLoad = p })
+    trueArg
+  , option [] ["repl-options"]
+    "use this option for the repl"
+    <b>replOptionsFlags</b> <b>(\p flags -> flags { replOptionsFlags = p ++ replOptionsFlags flags })</b>
+    (reqArg "FLAG" (succeedReadE (:[])) id)
+  ]
</code></pre>

Note that what previously was `id` and `const` now became `replOptionsFlags` and a lambda `(\p flags -> ...)`. This is a getter and setter pair however previously the setter was not updating the old flags value. That's because ultimately during option parsing the appending of options will take place at https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Simple/Command.hs#L159 (notice the `mappend`).

So the short summary is that previously there were no `++` and it shouldn't have been added in the https://github.com/haskell/cabal/commit/785ea62d2b6c7d2e91654eb7a23cafccac3ec08c commit.

**Comment by Mikolaj** [comment]
@sergv: thank you for the analysis and confirmation. I think the merge is overdue. Thank you all!

**Comment by sirlensalot** [comment]
Sorry for the delay responding, but obviously I concur with it as the author of the bug! Clearly my tests didn't catch this.

Indeed my only comment would have been: coverage? Can we get the bugfix covered by a unit test. I wrote a test for my functionality, which clearly didn't cover so I'm assuming this broke other workflows. Can we get coverage for those in a follow-on PR please?

**Comment by sirlensalot** [comment]
Happy to help if somebody can give the use-case clearly

**Comment by bacchanalia** [comment]
I though this would be covered by the tests in the other PR (#7851) I was working on, but due to code changes in that pr the tests no longer cover this, so we do still need tests for it.

**Pull request merged**
