### PR TITLE
Fix "source-repository-package breaks 'cabal v2-install'"

### LINKED ISSUE #5643: source-repository-package breaks 'cabal new-install all'
Example minimal project: https://github.com/hasufell/example-cabal-project

```sh
$ cabal new-install all
Wrote tarball sdist to
/home/maerwald/git/example-cabal-project/dist-newstyle/sdist/example-cabal-project-0.1.0.0.tar.gz
cabal: The impossible happened: a local package isn't local
```

And `cabal new-install` on the contrary does **nothing**.

### PR DESCRIPTION
**Pull request by fommil**
Fix #5643 which is a bigger bug than original reported: `v2-install` currently does not work at all if there are git packages. // @hasufell 

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by fommil** [comment]
meh, this doesn't work. For a source dependency on `free`

```
/home/fommil/.../dist-newstyle/sdist/freer-0.2.4.1.tar.gz: openBinaryFile: does not exist (No such file or directory)
```

// @typedrat any ideas?

**Comment by 23Skidoo** [comment]
Would be nice if there was a test case.

**Comment by fommil** [comment]
@23Skidoo yeah, I would like that too. Where can I look to add one? I basically just need to run `v2-install` on a package definition that has a git source dependency.

**Comment by 23Skidoo** [comment]
I'd look at the existing VCS tests.

**Comment by fommil** [comment]
@23Skidoo could you please point me to them in the repo?

**Comment by fommil** [comment]
I can confirm that this fixes the exception for me, but unfortunately it causes a recompile of my project (e.g. the originally reported repro). I'm not sure if that is a side effect of this fix, or if it is another bug in cabal.

**Comment by quasicomputational** [comment]
A PackageTest should be able to exercise this code. I'd also suggest a test for `new-sdist` with a `source-repository-package`, which was also broken.

Is installing binaries from a `source-repository-package` the right thing to do, considering that regular dependencies off Hackage don't have binaries installed? Will this surprise users? See also #5586.

**Comment by fommil** [comment]
@quasicomputational adding a test seems to be the easy thing, but referencing a git repo that must permanently be available is another thing. Does one exist that I can use?

I think I've convinced myself to prefer a workflow based on `v2-build` rather than `v2-install` so I'm not sure what other people's expectations are. In my usecase I just want access to the binary, I don't care about sdists.

**Comment by quasicomputational** [comment]
I think we'll want to have a local git repository during testing, rather than hitting the network. Creating one as part of the test is probably the simplest route, so shell out to `git init` etc.

To be clear - you want to have a binary from the `source-repository-package` installed (i.e., copied to the `symlink-bindir` directory)? That's what the patch as written will do - i.e., it's treating the package from the git repo as local. I don't object to this exactly, but I just want to be clear on if this is desired behaviour or an implementation detail.

**Comment by fommil** [comment]
I'm travelling and won't be able to work on this PR for a few weeks.

**Pull request merged**
