### PR TITLE
Registered the NamedDefaults language extension

### PR DESCRIPTION
**Pull request by blamario**
This is a sibling PR to GHC's [!11853](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11853)
* GHC issue [#24305](https://gitlab.haskell.org/ghc/ghc/-/issues/24305)
* implementing GHC proposal [409](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0409-exportable-named-default.rst#effect-and-interactions)

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] N/A ~The documentation has been updated~, if necessary.
* [x] N/A ~[Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.~
* [x] N/A for a language extension ~Tests have been added.~

### CODE REVIEW

**Review by geekosaur — CHANGES_REQUESTED** [review]
You have a failing test that appears to need an updated hash?

**Comment by blamario** [comment]
That's been fixed with a manual push to https://gitlab.haskell.org/ghc/packages/Cabal/-/tree/wip/exportable-named-defaults?ref_type=heads

**Review by geekosaur — APPROVED** [review]

**Review by Mikolaj — DISMISSED** [review]
Thank you very much for the PR.

> That's been fixed with a manual push to https://gitlab.haskell.org/ghc/packages/Cabal/-/tree/wip/exportable-named-defaults?ref_type=heads

I'm afraid this is not a 2-way mirror, so the push did not get reflected on github. Could you push this to github?

May I also ask you to link to the relevant GHC issue that adds this extension and check the boxes in the PR template (that would involve adding a tiny changelog file, I presume)? Would it be too much to also ask you for a courtesy towards vim users by adding the extension to their configuration as in https://github.com/haskell/cabal/pull/9502 and https://github.com/haskell/cabal/pull/8854? Thank you in advance!

**Comment by Mikolaj** [comment]
Let me take the liberty of rebasing the branch in the hope CI fixes itself...

**Comment by Mikolaj** [comment]
@mergify rebase

**Review by Mikolaj — APPROVED** [review]
Thank you very much!

**Comment by Mikolaj** [comment]
I've set a label, so this should merge in 2 days if there are no further comments/conflicts.

**Comment by Mikolaj** [comment]
@blamario: Just to make sure: this extension is not going to be in GHC 9.10, right?

**Comment by Kleidukos** [comment]
We can't backport this one to 3.12 because of the new member in the ADT.

**Comment by ffaf1** [comment]
@mergify backport 3.14

**Pull request merged**
