### PR TITLE
regenerate bootstrap files without arch-native

### PR DESCRIPTION
**Pull request by geekosaur**
**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by geekosaur** [comment]
@mergify backport master

**Comment by TerrorJack** [comment]
Would automatic forward port work properly for `master`? Since `master` additionally contains 8.10.7 plan which doesn't seem to be in 3.12 branch

**Comment by geekosaur** [comment]
I think it's officially no longer supported for bootstrapping? Not sure how it's still on `master`; we've had some glitches due to conflicting changes to bootstrap-related things. @Mikolaj / @ulysses4ever ?

**Review by Mikolaj — APPROVED** [review]
I think it's fine to just delete the old bootstrap on master as a manual additional change to the forward port. We may have removed the old bootstrap with @ffaf1 (did we?) when releasing 3.12.0.0 in order to conserve our sanity. A couple of GHC versions is enough for bootstrapping (and we can generate more if users need them and tell us), so this old one can go.

**Comment by geekosaur** [comment]
Reminder, since the Mergify rules update hasn't been merged yet, this will need to be manually merged.

**Comment by geekosaur** [comment]
Huh. I wish mergify would be consistent about whether it's going to merge or not.

**Pull request merged**
