### PR TITLE
Generate Paths_ module with qualified Data.List.last import

### PR DESCRIPTION
**Pull request by alexbiehl**
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by Mikolaj** [comment]
@alexbiehl: this is great for a quickfix, but what do you think about trying not to use Prelude at all and then adding a test that indeed turns off Prelude and compiles Paths_ so that don't stumble into this problem again?

Also, whatever happend to the previous PR? :)

**Comment by phadej** [comment]
turning of prelude can be done with `NoImplicitPrelude` in the `Paths_` file (when such extension is available), and doing `import Prelude ()` otherwise.

**Comment by jneira** [comment]
[After some problems to build cabal from this commit](https://github.com/haskell/cabal/issues/7649), i've tried with the policeman package and it worked 👍

**Comment by jneira** [comment]
This is the minimum change (so minimum risk to break things) which fixes it so imo we could merge this and do the definitive fix in another one on top of it

**Comment by alexbiehl** [comment]
Thanks @jneira for trying it on the Kowainik packages!!

**Comment by Mikolaj** [comment]
> @alexbiehl: this is great for a quickfix, but what do you think about trying not to use Prelude at all and then adding a test that indeed turns off Prelude and compiles Paths_ so that don't stumble into this problem again?
> 
> Also, whatever happend to the previous PR? :)

@alexbiehl: ping? we should probably stick this into 3.6.2 RSN, so what's your recommendation about the wider context?

**Comment by alexbiehl** [comment]
@Mikolaj My recommendation is to merge as is. Refactoring the code to avoid Prelude will take more time and I'd need to spend substantial time on it.

**Comment by Mikolaj** [comment]
Got it. Let's do that.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.6

**Review by jneira — APPROVED** [review]
lgtm. many thanks for the fix

**Pull request merged**
