### PR TITLE
Enable cabal-install integration tests in appveyor.yml

### PR DESCRIPTION
**Pull request by grayjay**
This PR includes #3206. I also removed `--force-reinstalls` and ran Cabal's tests in a single command.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also cherry-picked into 1.24.

**Comment by grayjay** [comment]
Thanks!

**Pull request merged**
