### PR TITLE
[cabal-3.8 backport] stop cabal update generating dist-newstyle/

### PR DESCRIPTION
**Pull request by juhp**
Applies 
- https://github.com/haskell/cabal/pull/8358
- https://github.com/haskell/cabal/pull/8627

to cabal-3.8

See #8589

### CODE REVIEW

**Comment by juhp** [comment]
I already built these changes for Fedora 39

**Review by gbaz — APPROVED** [review]

**Comment by juhp** [comment]
Is anyone looking into the docs failure?

**Comment by ulysses4ever** [comment]
@juhp this issue was fixed on master and 3.10

**Comment by ulysses4ever** [comment]
In particular, iirc it's #9272 that you want to backport if you want the docs built...

**Comment by Mikolaj** [comment]
Unfortunately, there's a lot of work needed to bring back CI on branch 3.8 to life. At least backporting some more PRs, surely also some conflict resolution and maybe custom hacks as well. I think we have a better chance of keeping 3.10 alive for long, if somebody volunteers to attend to that, than of resurrecting 3.8.

**Comment by ulysses4ever** [comment]
3.8 looks beyond salvation. Should we close this?

**Pull request closed without merging**
