### PR TITLE
drop >= in CabalSpecV1_18 in checkCabalVersion

### LINKED ISSUE #7088: "To use ... the package needs to specify at least 'cabal-version: >= 1.18'" ◀ should drop >=
**Describe the bug**
If I have:

```
cabal-version: 1.10
```
`cabal check` complains

```
Warning: To use the 'extra-doc-files' field the package needs to specify at
least 'cabal-version: >= 1.18'.
Warning: Hackage would reject this package.
```

After changing to `cabal-version: >= 1.18` it then complains:

```
Warning: Packages relying on Cabal 1.12 or later should specify a specific
version of the Cabal spec of the form 'cabal-version: x.y'. Use
'cabal-version: 1.18'.
```

Okay, apparently Hackage would not reject `cabal-version: >= 1.18`,
but this is annoying, it should just suggest `cabal-version: 1.18` to the user in the first place.

**System information**
 - cabal-install 3.2 (but this is true for all recent releases in memory: 2.x etc)

**Additional info**
Seems it is determined in Cabal/src/Distribution/PackageDescription/Check.hs

### PR DESCRIPTION
**Pull request by JeremyScott-IO**
resolves: #7088

Resolved #7088 by dropping ">=".

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by phadej — CHANGES_REQUESTED** [review]
There are other occurences and versions, at least

```
% git grep '>= 1.18'
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ "To use this feature you must specify 'cabal-version: >= 1.18'."
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ "To use this feature you must specify 'cabal-version: >= 1.18'."
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ "at least 'cabal-version: >= 1.18'."

% git grep '>= 1.22'
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ "at least 'cabal-version: >= 1.22'."

% git grep '>= 1.24'
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ " at least 'cabal-version: >= 1.24'."
Cabal/src/Distribution/PackageDescription/Check.hs:           "Packages using 'cabal-version: >= 1.24' with 'build-type: Custom' "
Cabal/src/Distribution/PackageDescription/Check.hs:        ++ "for Custom setup scripts. Consider using cabal-version >= 1.24 and "
cabal-install/src/Distribution/Client/Dependency.hs:      -- Force Cabal >= 1.24 dep when the package is affected by #3199.
cabal-install/src/Distribution/Client/ProjectPlanning.hs:    -- GHC 8.0   needs  Cabal >= 1.24
````

**Comment by JeremyScott-IO** [comment]
Thanks for reviewing!

I saw these, but didn't want to change something not specified in #7088. For these other version '>=' examples, do we know that changing the cabal version gives the same secondary warning? 

Happy to test them myself if we don't know.

**Comment by phadej** [comment]
> do we know that changing the cabal version gives the same secondary warning?

Probably. `cabal-version: >= 1.18` (and for later versions) **should be** always warned about. If it doesn't, that's another bug.

**Comment by gbaz** [comment]
@JeremyScott-IO did you mean to mark this as a draft or is it pr-ready?

**Comment by ulysses4ever** [comment]
Superceded by #8205. Thanks @JeremyScott-IO!

**Pull request closed without merging**
