### PR TITLE
Fix getExecutablePath on *BSD.

### LINKED ISSUE #3512: "runInteractiveProcess: exec: does not exist" when invoking cabal with a relative path (OpenBSD)
On OpenBSD, with cabal-install 1.24, invoking the binary with a relative path gives an error:
```
$ .cabal/bin/cabal install parallel
Resolving dependencies...
Configuring parallel-3.2.1.0...
Failed to install parallel-3.2.1.0
Build log ( /home/maxim/.cabal/logs/parallel-3.2.1.0.log ):
cabal: Entering directory '/tmp/cabal-tmp-22828/parallel-3.2.1.0'
cabal: Leaving directory '/tmp/cabal-tmp-22828/parallel-3.2.1.0'
cabal: Error: some packages failed to install:
parallel-3.2.1.0 failed during the configure step. The exception was:
.cabal/bin/cabal: runProcess: runInteractiveProcess: exec: does not exist (No
such file or directory)

```
With an absolute path it's fine:
```
$ ~/.cabal/bin/cabal install parallel
Resolving dependencies...
Configuring parallel-3.2.1.0...
Building parallel-3.2.1.0...
Installed parallel-3.2.1.0

$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 

```
I could reproduce this issue only on OpenBSD. On Mac OS it seems to be fine. Also, 1.22 doesn't suffer from this.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #3512.

### CODE REVIEW

**Comment by oherrala** [comment]
👍 works in my OpenBSD system. Thanks!

**Comment by 23Skidoo** [comment]
Great, will merge once Travis is green.

**Comment by hvr** [comment]
@23Skidoo I'm afraid this one has introduced a serious regression on AIX (and I'd expect on BSD too):

...when `getExectuablePath` would have returned only `"cabal"`, because it was resolved via `$PATH`, then  canonicalizing adds `$CWD` which is obviously wrong.

**Comment by 23Skidoo** [comment]
@hvr You're right, this patch is incorrect. I was misled by @oherrala's suggestion to use `realpath(argv[0])`.

**Comment by oherrala** [comment]
@hvr @23Skidoo yep, patch is incorrect. :( I'm coming to conclusion that there's no robust way to determine the path of executable.

**Comment by hvr** [comment]
@23Skidoo  @oherrala fwiw, I'd workaround this at the use-site of `getExecutablePath` or introduce a new `getExecutablePathCanon`-wrapper, and canonicalize *only* if the returned string contains any `/`s as a heuristic.

But I'd leave `getExecutablePath` with the same semantics as base`s `System.Environment.getExecutablePath` as we surely want to get rid of Cabal's compat-layer sooner or later, and use `base`'s `getExecutablePath` at some point... :-)

**Comment by 23Skidoo** [comment]
According to the SO answer @hvr linked, the right way to implement this on *BSD is to use procfs, which appears to have been removed from OpenBSD.

**Pull request merged**
