### PR TITLE
Elaborate on XDG directories in users guide.

### PR DESCRIPTION
**Pull request by athas**
A minor documentation improvement (I hope).

### CODE REVIEW

**Comment by athas** [comment]
Unless this is a load-bearing piece of documentation, I assume CI is flaky.

**Comment by mouse07410** [comment]
> Yes, this is an unrelated problem. We'll try to handle it in due course, and this shouldn't block reviewing.

Since it directly impacts usability - I'd rather not relegate this "to the future/due course". _spell-checker tried to correct it to "due curse" - symbolic? ;-)_

**Comment by ulysses4ever** [comment]
@mouse07410 you're more than welcome to submit a fix at your earliest convenience.

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by mouse07410** [comment]
> @mouse07410 you're more than welcome to submit a fix at your earliest convenience.

Thank you for the suggestion - and how would one fix it, when it's not stated what the correct "fix" is, i.e., where to would `~/.cabal/store` actually go?

**Review by ulysses4ever — APPROVED** [review]

**Review by ffaf1 — APPROVED** [review]
oki doki

**Comment by ulysses4ever** [comment]
@athas you should feel free to apply the merge-me label whenever ready.

**Comment by Mikolaj** [comment]
> > @mouse07410 you're more than welcome to submit a fix at your earliest convenience.
> 
> Thank you for the suggestion - and how would one fix it, when it's not stated what the correct "fix" is, i.e., where to would `~/.cabal/store` actually go?

@mouse07410, @ulysses4ever was talking about a CI problem (I hope, fixed already).

**Pull request merged**
