### PR TITLE
Expose BuildFlags and ClientHaddockFlags

### LINKED ISSUE #8351: cabal-install BuildFlags is not exported?
In `Distribution.Client.CmdBuild` module, `BuildFlags` is defined but not exported.

https://github.com/haskell/cabal/blob/dd312ecc44b79945061a4cb45e15b90f26382be4/cabal-install/src/Distribution/Client/CmdBuild.hs#L4-L12

https://github.com/haskell/cabal/blob/dd312ecc44b79945061a4cb45e15b90f26382be4/cabal-install/src/Distribution/Client/CmdBuild.hs#L83-L85

### PR DESCRIPTION
**Pull request by kokobd**
This will fix #8351

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM. If you find anything else, feel free to add while the PR is still not merged.

**Comment by Mikolaj** [comment]
FYI: CI is borked right now (#8356), so the error probably has nothing to do with this PR.

**Comment by Mikolaj** [comment]
Let me rebase to see if the recent CI workaround unblocks your testing.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by kokobd** [comment]
This might be ready in my mind.

**Comment by Mikolaj** [comment]
Splendid. Let's wait for the mandatory second review.

**Review by ulysses4ever — APPROVED** [review]
Tiny change, makes total sense, so I'm on board. Thank you!

**Comment by ulysses4ever** [comment]
Someone has to apply the `squash+merge_me` label now.

**Comment by Mikolaj** [comment]
@kokobd: I've granted you Triage authorization so that you can set the squash+merge_me (or merge_me) label on this PR and behold the mergifyIO magic (which takes 2 todays to unfold, in order to give people time to comment).

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by kokobd** [comment]
what a strange error:
Screen Shot 2022-08-16 at 10 06 23

**Comment by Mikolaj** [comment]
> what a strange error:

Yes, I think something broke in our CI infrastructure. Due to that mergify can't merge automatically, so let me merge manually.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@kokobd: thank you!

**Comment by kokobd** [comment]
@mergify backport 3.8

Then let's backport this too, so that [cabal-hoogle](https://github.com/kokobd/cabal-hoogle/) can work with cabal 3.8

**Pull request merged**
