### PR TITLE
gitlab CI generates deb11 images

### PR DESCRIPTION
**Pull request by ulysses4ever**
It's a half of solution for #8376 (see https://github.com/haskell/cabal/issues/8376#issuecomment-1214450441). It's tested to at least [succeed on GitLab](https://gitlab.haskell.org/ulysses4ever/cabal/-/pipelines/55722).

---

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Does it need a changelog / documentation?

**Comment by Mikolaj** [comment]
> Does it need a changelog / documentation?

A quick grep in cabal repo including changelog.d/ content for the 3.8 release turns out nothing for deb10, so I guess we can pass.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify rebase

**Review by andreasabel — APPROVED** [review]
Approved, but I have no domain knowledge.

**Comment by ulysses4ever** [comment]
@Mergify refresh

**Comment by ulysses4ever** [comment]
@mergify refresh

**Comment by ulysses4ever** [comment]
@mergify refresh

**Pull request merged**
