### PR TITLE
CI: Attempt to enable tests for 9.6.3 windows

### PR DESCRIPTION
**Pull request by mpickering**
Here for testing whether these tests are still failing and hopefully debugging.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Oh yeah, I can remember that "ld.lld: error: undefined symbol: sayHi" message from last time we tried it.

**Comment by mpickering** [comment]
Note: both failing tests are already broken on ghc-9.4 and marked as such. So at least the way forward here is to extend that predicate to newer GHC versions.

I can see the `CCompilerOverride` test assumes that GHC uses a gcc based toolchain, so I attempt to fix that one. Looking into the other failure a little now.

**Comment by mpickering** [comment]
I fixed the `CCompilerOverride` test, the `ForeignLibs` test is a GHC bug I think, which I am investigating. So I will mark `ForeignLibs` as broken on 9.6 for now.

**Comment by Mikolaj** [comment]
Whatever you both did, it seems to run fine right now.

**Comment by Kleidukos** [comment]
I restarted the jobs, might have just been transien

**Comment by mpickering** [comment]
I need reviews please

**Comment by ffaf1** [comment]
Add the `attention: needs-review` label and people will know it needs reviews.

**Review by Kleidukos — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]

**Pull request merged**
