### PR TITLE
Test Trusty Travis builds.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@ezyang The build is green, what have we learned here?

**Comment by ezyang** [comment]
That... it works. We can switch over whenever, I think.

**Comment by 23Skidoo** [comment]
@ezyang Rationale for switching is a more up-to-date version of `gold`, right?

**Comment by ezyang** [comment]
The immediate reason I tested it out was because Travis sent a message saying that the current default dist is getting EOL'ed by Ubuntu.

**Comment by 23Skidoo** [comment]
OK. Anyway, let's merge.

**Pull request merged**
