### PR TITLE
Stop logging to file when build inplace

### LINKED ISSUE #9606: Stop logging to file when building inplace
In f70fc980dca50e7e62c5e803f56d2ef0c9fc7e18, while refactoring
buildInplaceUnpackedPackage and buildAndInstallUnpackedPackage, we
started logging into a file on both cases, instead of logging to a file
only for buildAndInstallUnpackedPackage.

When building a package inplace, it is much more useful to be able to
see the GHC invocation directly outside of a log file.

This is especially relevant for Cabal developers working inplace.

Fix incoming.

### PR DESCRIPTION
**Pull request by alt-romes**
In f70fc980dca50e7e62c5e803f56d2ef0c9fc7e18, while refactoring buildInplaceUnpackedPackage and buildAndInstallUnpackedPackage, we started logging into a file on both cases, instead of logging to a file only for buildAndInstallUnpackedPackage.

When building a package inplace, it is much more useful to be able to see the GHC invocation directly outside of a log file.

This is especially relevant for Cabal developers working inplace.

Fixes #9606

### CODE REVIEW

**Comment by alt-romes** [comment]
@ulysses4ever @Mikolaj, as the previous reviewers, could you swiftly review this fix that undoes my mistake?

**Review by geekosaur — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]

**Comment by alt-romes** [comment]
Thank you both. As I was debugging a tree on master I was very confused by not seeing the output of `-v`... it is an unfortunate mistake.

**Comment by alt-romes** [comment]
@Mikolaj @Kleidukos I suggest we skip the merge delay. I fear developer workflows may break because of my mistake in the meantime.

**Comment by ulysses4ever** [comment]
Happens to all of us. You don't make mistakes only if you don't do anything at all!

**Review by Mikolaj — APPROVED** [review]
Thank you for the prompt fix and the transparency. Let's skip the merge delay.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
Let me keep restarting CI until we hit the not-yet-affected macos containers.

**Comment by Mikolaj** [comment]
@mergify rebase

**Pull request merged**
