### PR TITLE
[ci skip] Update installing-packages.rst

### PR DESCRIPTION
**Pull request by hanshoglund**
Clarify that it is not necessary to provide `secure` or `root-keys` for the default repository.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
@hvr, is this true?

I'm pretty sure it isn't.

**Comment by hanshoglund** [comment]
Thanks for reviewing.

My understanding is that [`defaultRemoteRepo`](https://github.com/haskell/cabal/blob/f6e7cdd60d83d887cafa1385a6df85bd392cfc36/cabal-install/Distribution/Client/Config.hs#L645) is used if `repository` is not set, thus [`defaultHackageRemoteRepoKeys`](https://github.com/haskell/cabal/blob/f6e7cdd60d83d887cafa1385a6df85bd392cfc36/cabal-install/Distribution/Client/Config.hs#L695) are available. 

If this is not correct, then what is the behavior if `repository` is not set?

**Comment by phadej** [comment]
I see, `loadConfig` also calls `extendToEffectiveConfig`. This was a **surprise** to me, the `cabal` should log (as `info`) that it 
- rewrites the known old URI
- adds keys if there are none

There's an action which is invisible, nothing should be.

**Comment by hanshoglund** [comment]
It seems like this PR accurately describes behavior then. Can we merge it? Or should the behavior change (logging aside)?

**Comment by hanshoglund** [comment]
Ping.

**Comment by Mikolaj** [comment]
@hanshoglund: I've spun off the logging issue. Could you resolve the conflict and ping me? Then I'd merge ASAP not waiting for reviews to prevent even more delays. Thank you.

**Comment by hanshoglund** [comment]
Hello @Mikolaj. 

> Could you resolve the conflict and ping me? 

Done. Please sure this is absolutely correct before merging, given it is security-related :).

**Comment by Mikolaj** [comment]
@hanshoglund: thank you so much.

@gbaz: would you have a quick look?

**Review by gbaz — APPROVED** [review]

**Comment by Mikolaj** [comment]
MergifyIO backport 3.6

**Comment by Mikolaj** [comment]
Thank you @hanshoglund. Thank you everybody.

**Comment by Mikolaj** [comment]
@MergifyIO backport 3.6

**Pull request merged**
