### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by alang9**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by ezyang** [comment]
First off, @alang9, nice catch.

This bug is not nice, it means that Paths modules for relocatable libraries are completely broken in GHC 8.2.1. We should definitely merge this patch to the 2.0 branch. CC @23Skidoo 

Root cause is that, apparently, we don't have any tests for `relocatable` at all. Would be worth adding one of those. @alang9, would you be interested?

**Comment by bgamari** [comment]
What is the status of this? @ezyang opened a ticket ([#14054](https://ghc.haskell.org/trac/ghc/ticket/14054)) saying that we should ensure this fix makes it for 8.2.2, which I'm cutting the RC for now.

**Comment by 23Skidoo** [comment]
Thanks for the heads-up, I'll merge it once it's green and try to write a test tomorrow.

**Comment by 23Skidoo** [comment]
For some reason GitHub auto-closes PRs when I do a force push to the owner's repo...

**Comment by 23Skidoo** [comment]
@bgamari This is now merged.

**Pull request closed without merging**
