### PR TITLE
[3.8] Revert "Implement --prefer-oldest (#8261)"

### PR DESCRIPTION
**Pull request by fgaz**
It's a (library) breaking change:
https://github.com/haskell/cabal/pull/8261#discussion_r945548996

This reverts commit d8ad036d6fae073bb1e039e1006397d6efdc3637.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by gbaz** [comment]
I don't think we should revert. We can always give cabal-install-solver (but not cabal-install) a major version bump here. And if we do so that's still on the 3.8 branch of the cabal repo as a whole.

**Comment by fgaz** [comment]
do we really want to open the pandora vase of unsynced versions, and do we want to do that now? will a major cabal-install-solver release block stable distros from packaging cabal-install 3.8 point release? cabal-install-solver and cabal-install are tightly coupled and ideally they'd merge if multiple public libraries were available for use in cabal

**Comment by gbaz** [comment]
"will a major cabal-install-solver release block stable distros from packaging cabal-install 3.8 point release" -- i don't see why?

I'm suggesting that with 3.8.2.0 or whatever of cabal-install, we release 3.9 of the solver library.

There's no reason the major version of the solver library need correspond to the major version of cabal-install.

**Comment by fgaz** [comment]
> There's no reason the major version of the solver library need correspond to the major version of cabal-install.

No, but it can make things easier considering that the bound on `cabal-install-solver` is tight

> "will a major cabal-install-solver release block stable distros from packaging cabal-install 3.8 point release" -- i don't see why?

* distro packages cabal-install 3.8.1.0 and cabal-install-solver 3.8.1.0 as separate packages, one depending on the other
* distro branches off / freezes major versions
* cabal-install 3.8.2 gets released with build-depends: cabal-install-solver==3.9.*
* distro can't update cabal-install to the new minor version because doing so would require updating cabal-install-solver to a new _major_ version

of course this isn't a problem if global consistency isn't required, but even nixos of all things has a globally consistent haskell package set. as far as i know stackage lts should suffer from the same issue

**Comment by Bodigrim** [comment]
> do we really want to open the pandora vase of unsynced versions, and do we want to do that now?

But what was the point of splitting if resulting packages must nevertheless evolve in lock step? While `Cabal` is a boot package and it does not make much sense to release it more often than GHC, there is no reason why `cabal-install-solver` and/or `cabal-install` should not evolve at a different pace, including major versions. 

While `--prefer-oldest` is a feature and I understand the reluctance to go an extra mile for it, even relatively minor bug fixes are likely to change public API of `cabal-install` and `cabal-install-solver` and so qualify as breaking, because it is incredibly difficuly to fix something without changing observable behaviour of myriads of exposed functions. What's the plan about this?

**Comment by gbaz** [comment]
"distro branches off / freezes major versions" -- I confess I don't know enough about distros but I was not under the impression that a branching off led to a major version freeze (in our sense) in most distros.

"But what was the point of splitting if resulting packages must nevertheless evolve in lock step? While Cabal is a boot package and it does not make much sense to release it more often than GHC, there is no reason why cabal-install-solver and/or cabal-install should not evolve at a different pace, including major versions."

Agreed 100%. I think for cabal-install itself we decided that we would tend to stick to major versions = features and minor versions = bugfixes, which alleviates the issue of exporting its internals as a library. (And of course, is not going to be a hard rule, but a tendency). But there's no reason cabal-install-solver need stick to the same versions as cabal-install. And further, there's no reason either of them need stick to the same version as Cabal. Allowing their versions to evolve independently, afaik, was always part of the plan.

That said, even if the versions do stay in lock-step, the argument for splitting off the solver and syntax packages still holds -- it modularizes code and helps people who want to only work with certain portions of the overall api surface not need to drag in everything else to their dependency tree.

**Comment by andreasabel** [comment]
We could let all components evolve independently, with major version releases, but then sync them again when we release a new `cabal-install` for a new GHC, using the major-major version.  
For example, for GHC 9.6, we release `cabal-install-4.0.0.0` and bump all involved packages/components (like `Cabal, `cabal-install-solver`, ...)  also to `4.0.0.0`.
For GHC 9.8 (or whatever next) we bump to `5.0.0.0` etc.

**Comment by fgaz** [comment]
> "distro branches off / freezes major versions" -- I confess I don't know enough about distros but I was not under the impression that a branching off led to a major version freeze (in our sense) in most distros.

I'm not that knowledgeable either so this might be all wrong, but as far as I know
* nixos, arch (rolling so doesn't apply), stackage all have a globally consistent set of haskell packages, so cabal-install-solver will block cabal-install. i guess nix could package the executable separately, who knows
* i don't know if debian has a globally consistent set of _build_ packages (ie. the ones listed [here](https://packages.debian.org/source/sid/haskell-cabal-install) under `build-depends`), but from 3.8 cabal-install provides a library too, so it will become more like [pandoc](https://packages.debian.org/source/sid/pandoc), that produces `libghc-pandoc-dev`, and that one definitely has to be globally consistent. So a major cabal-isntall-solver release will block a cabal-install release i this case too

> there is no reason why cabal-install-solver and/or cabal-install should not evolve at a different pace, including major versions.

In general the problem isn't that the versions are unsynced as much as it is that the cabal-install:cabal-install-solver version bound is strict. _That_ is what makes a major cabal-install-solver release equivalent to a major cabal-install release from a distro perspective.

> While --prefer-oldest is a feature and I understand the reluctance to go an extra mile for it, even relatively minor bug fixes are likely to change public API of cabal-install and cabal-install-solver and so qualify as breaking, because it is incredibly difficuly to fix something without changing observable behaviour of myriads of exposed functions. What's the plan about this?

I did warn about this when we decided to expose the cabal-install library. Yes, we'll have to bump the major version more often, but given the above, doing that in a backport seems troublesome, especially since there are already important fixes queued up for a _minor_ release.

As a compromise, we could first do a minor cabal-install release with all the fixes included and #8261 reverted, and only then apply it again.

> And further, there's no reason either of them need stick to the same version as Cabal. Allowing their versions to evolve independently, afaik, was always part of the plan.

I agree that unsyncing Cabal and cabal-install would be a good thing, though that will require a fair bit more planning! Here ithe strict bound doesn't matter because Cabal releases are _slower_ than cabal-install.
On the other hand, I think splitting cabal-install and cabal-install-solver was less for that reason and more for this:

> That said, even if the versions do stay in lock-step, the argument for splitting off the solver and syntax packages still holds -- it modularizes code and helps people who want to only work with certain portions of the overall api surface not need to drag in everything else to their dependency tree.

In fact I think cabal-install-solver fits better as a public sublibrary of cabal-install. Though we cannot do that yet.

**Comment by Mikolaj** [comment]
> * i don't know if debian has a globally consistent set of _build_ packages

Debian uses an LTS snapshot from 30 years ago and then tweaks it (ensuring it all still has an install plan) whenever somebody expresses interest in a newer version of package and it doesn't change too many other packages.

**Comment by gbaz** [comment]
We had some discussion in the cabal call, and it seems there's really no fundamental obstacle to out-of-sync releases of -syntax and -install, but it is simpler to keep the versions in sync. So perhaps the simplest path here is to just have a relatively shorter path to a more feature-lite 3.10 release, instead of projecting a large series of 3.8 releases. However, if we do need a 3.8 release short term we can temporarily let the solver get out out of sync and have it bumped to 3.9.

**Comment by Mikolaj** [comment]
> We had some discussion in the cabal call, and it seems there's really no fundamental obstacle to out-of-sync releases of -syntax and -install, but it is simpler to keep the versions in sync. So perhaps the simplest path here is to just have a relatively shorter path to a more feature-lite 3.10 release, instead of projecting a large series of 3.8 releases. However, if we do need a 3.8 release short term we can temporarily let the solver get out out of sync and have it bumped to 3.9.

That's certainly conducive to me, while I'm the release manager, keeping a semblance of sanity.

**Comment by fgaz** [comment]
Closing as per above

**Pull request closed without merging**
