### PR TITLE
RFC: Put Arbitrary instances for Cabal types in their own package.

### PR DESCRIPTION
**Pull request by quasicomputational**
This is with the intention of the new package,
cabal-quickcheck-instances, being the blessed location for these
orphans, as QuickCheck acquiring a Cabal dependency or vice-versa
would be unsuitable.

This reduces some duplication (some presumably deliberate, and some
apparently accidental) and then some drift between the versions of
these instances.

Due to #1575, some tests have had to move from the Cabal package to
cabal-install.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by hvr** [comment]
So this is strictly a local/internal package *NOT* intended to be released to Hackage, right?

**Comment by phadej** [comment]
There are tests in `Cabal` which depends on this instances. Before we have per-component solving, I see this as blocked.

The tests **should** be inside `Cabal` package. `cabal-install` test-suite is too "far"; and developer experience wise increases feedback loop too much.

:-1:

---

Having a package which shares the sources with `Cabal` (a bit like `aeson` and `attoparsec-iso8601` could work).

**Comment by 23Skidoo** [comment]
IMO the existence of `cabal.project` makes the argument for moving all test suites to a single separate package more convincing.

**Comment by phadej** [comment]
FWIW, there is `Version: 3.3 2018-10-24` of SPDX license list. Try out how not nice it is to update now, when tests are mile away from `Cabal`.

**Comment by quasicomputational** [comment]
OK, I have pushed a v2 that shares its source between the new package and Cabal's test suite. (It also has the side benefit on actually working; I thought I'd tested the previous version, but travis disagreed...)

**Comment by phadej** [comment]
I'm trying to resurrect this in https://github.com/haskell/cabal/pull/6557 with a small first step.

**Comment by phadej** [comment]
The goal is achieved. There is `Cabal-QuickCheck` now.

**Pull request closed without merging**
