### PR TITLE
InstalledPackageId has constructor

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by Heather** [comment]
@23Skidoo is it my mistake even?

**Comment by ezyang** [comment]
InstalledPackageId got turned into a type synonym for backwards compatibility. I suppose for sufficiently recent GHC we could also add a pattern synonym so it really does look BC OK.

**Comment by 23Skidoo** [comment]
Going to close this for now, please send another PR when/if you incorporate @ezyang's feedback.

**Comment by ezyang** [comment]
@23Skidoo , this is not quite related to this PR, but maybe should we adopt a policy where we close PRs if it's not necessary for maintainers to look at it (so, open PR means, "Maintainer, look at me!" And closed PR means, "Don't look at me.")

**Comment by 23Skidoo** [comment]
I do want to get to Inbox 0 on Cabal PRs, but right now we're not there yet. Mostly because I don't want to close PRs that are (50/75/90 %)-complete because it makes easy to forget about them.

**Pull request closed without merging**
