### PR TITLE
Allow list for `repl --build-depends`

### PR DESCRIPTION
**Pull request by typedrat**
`cabal repl --build-dep base, lens` now works as promised.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Can I do `--build-depends="foo == 0.2, bar == 0.4"`?

**Comment by typedrat** [comment]
It's not done... For one, right now it only works if it is quoted.

**Comment by typedrat** [comment]
As in `cabal new-repl -b "base == 4.12.0.0, filepath == 1.4.2.1"`

**Comment by 23Skidoo** [comment]
That's all right, I don't think that other list options work without quotes either.

**Comment by hvr** [comment]
@23Skidoo btw, we should totally do this for `--constraint` as well

**Comment by phadej** [comment]
about quotes: you'll need quotes anyway, as my shell notices `>` and tries to redirect - if not quotes. So I do write `--constraint='lens ^>=4.17'` anyway already.

**Pull request merged**
