### PR TITLE
Check existence of packagedb before dumping it

### LINKED ISSUE #5516: new-install fails with empty store:  ghc-pkg: .../package.db: getDirectoryContents:openDirStream: does not exist (No such file or directory)
Invoking `cabal new-install` fails to initialize the respective store pkg-db if it didn't exist yet; this manifests as e.g.

```
$ cabal new-install -w ghc-8.6.1 hlint -vnormal+nowrap
cabal: ghc-pkg dump failed: dieVerbatim: user error (cabal: '/opt/ghc/bin/ghc-pkg-8.6.1' exited with an error:
ghc-pkg: /home/hvr/.cabal/store/ghc-8.6.0.20180810/package.db: getDirectoryContents:openDirStream: does not exist (No such file or directory)
)
```

cc @typedrat 

----

## WORKAROUND

For the respective `-w` argument, invoke

```
cabal new-repl -w ghc-8.6.1 --build-dep fail
```

for non-interactive environments, below seems to work:

```
echo "" | cabal new-repl -w ghc-8.6.1 --build-dep fail
```

this will build the trivial package `fail` and initialise the store pkg-db; after this `new-install` will work.

Yet another workaround suggested in https://github.com/haskell/cabal/issues/5516#issuecomment-424184066 is to create the folder `package.db` at the location mentioned in the error message.

### PR DESCRIPTION
**Pull request by fgaz**
Fixes #5516

To do:

* [x] Better commit message/comment explaining why not failing (even with a Maybe) is ok

/cc @hvr

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Can we perhaps stop in

**Comment by 23Skidoo** [comment]
Silently filtering invalid parameters out is a bit surprising, I'd prefer if it printed a warning at least. Why are we invoking this function incorrectly in the first place? Perhaps we can stop doing that?

**Comment by fgaz** [comment]
Well, since a non-existent pkgdb technically does not contain any package I thought returning an [] was ok.

The alternative is adding a pkgdb init abstraction and creating the pkgdb when running new-install. I'll open another pr

**Comment by typedrat** [comment]
> Well, since a non-existent pkgdb technically does not contain any package I thought returning an [] was ok.

That's the semantic meaning that I'd want here, perhaps with a warning printed.

**Comment by fgaz** [comment]
I added a warning, but note that since cabal-install uses a reduced verbosity version of getInstalledPackages, it will only show with -v2 or more (which may be what we want)

**Comment by 23Skidoo** [comment]
> Well, since a non-existent pkgdb technically does not contain any package I thought returning an [] was ok.

OK, makes sense, let's merge this, but add a Haddock comment.

**Comment by fgaz** [comment]
Cherry-picked on 2.4

**Pull request merged**
