### PR TITLE
Remove hashable dependency

### PR DESCRIPTION
**Pull request by jaspervdj**
See #10140

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by jaspervdj** [comment]
Removing hashable from the test suite nerd-sniped me into writing a bit of whacky arbitrary machinery, but I think it's not necessarily worse than abusing hashable for this.

**Review by ulysses4ever — APPROVED** [review]
Pretty cool, thank you!

I'd hope for a smaller diff if we just had some of the compat code added to some sort of Prelude or Compat module (which we already have in vast numbers!). So, like

```
type Hash = HashValue
readFileHash = readFileHashValue 
```

But maybe this grows the codebase unnecessarily, so I'm split on this. It just feels like a hash library is something that may change once in a while, and a little abstraction from it woudln't hurt.

**Comment by jaspervdj** [comment]
I added some minimal comments to the code as well.

> I'd hope for a smaller diff if we just had some of the compat code added to some sort of Prelude or Compat module

IMO, `Distribution.Client.HashValue` is this compat module.  It just wasn't used in `FileMonitor` yet...

**Comment by ulysses4ever** [comment]
This needs a manual rebase on top of `master`, sorry @jaspervdj. Do you have time for this or should we try to take care of it?

**Comment by ulysses4ever** [comment]
Actually, this was trivial, don't worry. Should merge soon.

**Comment by ulysses4ever** [comment]
@mergify backport 3.14

**Pull request merged**
