### PR TITLE
cabal-install: allow resolv-0.2

### PR DESCRIPTION
**Pull request by juhp**
Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Comment by andreabedini** [comment]
CI failure is completely unrelated

```
  Installing the following packages:
  cabal
  By installing, you accept licenses for the packages.
  A newer version of cabal (v3.10.1.1) is already installed.
   Use --allow-downgrade or --force to attempt to install older versions.
  
  Chocolatey installed 0/1 packages. 1 packages failed.
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
  
  Failures
   - cabal - A newer version of cabal (v3.10.1.1) is already installed.
   Use --allow-downgrade or --force to attempt to install older versions.
```

I notice we are usign a old version of `haskell/actions/setup@v1` I'll try to bump it.

**Comment by Kleidukos** [comment]
@andreabedini you mean like have this fix into 3.10? I thought that was already the case?

**Comment by andreabedini** [comment]
> @andreabedini you mean like have this fix into 3.10? I thought that was already the case?

I think @juhp intention was to relax that bound on cabal-install 3.8.1.0 which still has `resolv < 0.2` https://hackage.haskell.org/package/cabal-install-3.8.1.0/revision/3.cabal.

**Comment by Kleidukos** [comment]
Alright, cabal-install 3.8.1.0 has been revised on Hackage to allow resolv-0.2

**Comment by andreabedini** [comment]
I believe this can be closed now.

**Pull request closed without merging**
