### PR TITLE
Pass short path names to configure scripts on Windows.

### LINKED ISSUE #3185: Pass short path names to configure scripts on Windows
In #2946 we changed Cabal to use the standard mechanism when passing the gcc path to `configure` scripts. Unfortunately, it looks like this feature is still broken (at least on Windows) when the path contains spaces (a bug in Autoconf). A workaround that is confirmed to work is to use [short path names](https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx). We should change Cabal to do that automatically.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #3185.

### CODE REVIEW

**Comment by ezyang** [comment]
Given the use of preprocessor here, I feel like it would be a bit better if `getShortPathName` was put into a Compat module of its own?

**Comment by 23Skidoo** [comment]
Done.

**Comment by dcoutts** [comment]
LGTM.

I initially wondered if we shouldn't be quoting or something to handle spaces but given that the problem is (I assume) not that we incorrectly pass args with spaces to the external prog, but that autoconf being autoconf it mangles things even if we pass it correctly. So yes, fine.

**Comment by 23Skidoo** [comment]
> given that the problem is (I assume) not that we incorrectly pass args with spaces to the external prog, but that autoconf being autoconf 

Yes, see #1634. Additional quoting doesn't help here, the path is already passed correctly.

**Pull request merged**
