### PR TITLE
For ghc calls pass Cabal's build/ directory after user's src/ directory so that contents of src/ takes precedence

### PR DESCRIPTION
**Pull request by sergv**
A fix for #8689.

The fix is a one line change that changes order of directories where searches will be searched by the ghc. Cabal's internal build/ directory (e.g. `dist-newstyle/build/x86_64-linux/ghc-9.4.4/Cabal-3.9.0.0/build/`) now is passed after all source directories specified by the package in order to make sure that if there's a user-supplied file that corresponds to a particular module thet it will never be overshadowed by what's in the cabal's internal build/ directory. Autogenerated modules get written into the internal build/ directory so they have a real chance of shadowing one of user's modules as shown in the linked issue.

## Testsing methodology
I built GHC with Cabal that has this patch and run the test. It's tricky to run the added test because it relies on custom setup which can only access Cabal package bundled with GHC.

Custom setup is needed because autogenerated modules with a custom preprocessor (in this case identity preprocessor) are used.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Bodigrim — APPROVED** [review]
LGTM!

**Review by Mikolaj — APPROVED** [review]
Looks good, thank you. Please kindly set the merge (squash?) label.

**Comment by Mikolaj** [comment]
The GHA failure is hacked around; let me rebase to fix CI.

**Comment by Mikolaj** [comment]
mergify rebase

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify regresh

**Comment by Mikolaj** [comment]
silly computer

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@sergv: something locked on hard in CI for this PR. Could you kindly rebase manually? Then we'd run CI and I'd force-merge if needed.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@mergify requeue

**Comment by Mikolaj** [comment]
@mergify unqueue

**Comment by Mikolaj** [comment]
@mergify requeue

**Comment by Mikolaj** [comment]
doh

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
OK, mergify seems to have uncloged

**Comment by Mikolaj** [comment]
Phew, finally. @sergv: thank you again!

**Comment by andreasabel** [comment]
Causing
- #10060

**Pull request merged**
