### PR TITLE
Fix for issue #3932.

### PR DESCRIPTION
**Pull request by dagit**
For now require Cabal >= 1.20 in all new-builds. In the future we plan to relax
this to only Setup.hs dependencies.

Note for reviewers: I wasn't sure what to do with the [min cabal version constraint](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/ProjectPlanning.hs#L2410) in `defaultSetupDeps`. I left it at `1.18`, because I wasn't sure if it makes sense to bump it as well. For example, does that code only run for new-builds? If yes, then I think we can get rid of it because it's redundant with the constraint I added in `planPackages`. If no, then leaving it retains some backwards compatibility.

### CODE REVIEW

**Comment by ezyang** [comment]
> Note for reviewers: I wasn't sure what to do with the min cabal version constraint in defaultSetupDeps. I left it at 1.18, because I wasn't sure if it makes sense to bump it as well. For example, does that code only run for new-builds?

Nope, we don't want to bump because the legacy codepath uses it, and there's no reason to force a higher min-bound there (we don't use the buggy feature.)

**Comment by ezyang** [comment]
Looks great, let's merge when Travis goes green.

**Comment by dcoutts** [comment]
I'm not sure I'm convinced this is the right approach. It adds a constraint on Cabal globally irrespective of whether there's any setup script involved. For example it means nothing can ever build against an old version of the Cabal lib for any purpose, not just setup scripts.

I see that `defaultSetupDeps` does not quite cover it because it doesn't cover the case of a setup script with explicit deps. I think the better approach would be to handle that case.

**Comment by dcoutts** [comment]
So I've decided to go along with the constraint approach, see #4058.

**Pull request merged**
