### PR TITLE
implement new idea for fixed dependencies in bootstrap.sh

### PR DESCRIPTION
**Pull request by JakeWheat**
I changed the bootstrap.sh script in the following ways:

* the dependencies for each version of ghc are fixed and read from an external file
* all dependencies installed by bootstrap.sh and the cabal binary are installed to a 'sandbox', never to user or global package database and you can't change this without editing the .sh file
* the cabal-install binary and libraries are compiled with no shared, no haddock, no profiling, no tests, and you cannot change any of these options without editing the .sh file
* it uses -j when it can (see https://github.com/haskell/cabal/issues/2229)

It seems to work with ghc 7.10.0-x, 7.8.x, and 7.6.[23]. It hung on 7.6.1 when compiling stm, and I didn't make it work with ghc-7.4.x since the names of the ghc-pkg arguments changed (and maybe there would be other issues). I only tested on debian unstable.

I think it successfully ignores extra packages in the global or user package database (which can cause problems with the old bootstrap.sh?), although I think it could still fail with inconsistent dependencies in some extreme cases with a non-fresh install of ghc.

The dependency files (cabal-install/bootstrap-ghc-7.8.1-deps, etc.) were written by hand. It would be good to be able to generate them automatically using a working version of cabal-install. I'm not sure how to do this, perhaps by munging the output of 'cabal install . --dry-run -v3' or something equivalent.

I hope all this should make the bootstrap.sh more reliable and much more easy to maintain. I think you can get back all the interesting features removed from bootstrap.sh by bootstrap.sh-ing then reinstalling cabal-install with the bootstrapped cabal-install binary, which seems like a reasonable tradeoff. I'm not 100% sure I didn't remove anything important.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
GHC 7.4.2 came out in June 2012, so we still need to support it.

**Comment by JakeWheat** [comment]
I added support for ghc 7.4.2.

**Comment by dcoutts** [comment]
Is there anything left to do here or can we merge once the conflicts are resolved?

**Comment by JakeWheat** [comment]
I can take a look at it, should I base it on the master branch or another one?

**Comment by 23Skidoo** [comment]
Do we still want this (except the `-j` bit)? People might like those removed features.

I think Johan found a way to make the bootstrap script support `network`/`network-uri` split, which I believe was the main problem this patch was designed to fix. Splitting the dependency files makes it harder to update dependencies (I understand that it is part of the point of this patch).

**Comment by JakeWheat** [comment]
> Splitting the dependency files makes it harder to update dependencies

Can you elaborate on what you mean here, maybe there is something that can be fixed?

**Comment by 23Skidoo** [comment]
I meant that with this patch one'll have to update N different files instead of one.

**Comment by JakeWheat** [comment]
This can be easily fixed though right? I will do something.

**Comment by JakeWheat** [comment]
I updated to the latest master. Tested OK with 7.4.2, 7.6.3, 7.8.4, 7.10.0.20150123.

**Comment by bgamari** [comment]
Is the split dependencies the only objection to this?

If so, it seems like one easy solution would be to drop the dependency lists into a single sh script which could be sourced by `bootstrap.sh`,
```sh
ghc710_deps="
deepseq 1.4.0.0
binary 0.7.3.0
Cabal 1.23.0.0
mtl 2.2.1
network 2.6.0.2
...
"

ghc708_deps=...
```

**Comment by BardurArantsson** [comment]
... or one could just have a text file:

```
7.10:deepseq 1.4.0.0
7.1.0:binary 0.7.3.0
....
7.08:deepseq 1.3.0.0
....
```

and so on and just read it using the "read" shell command. Yes, there's some more duplication with the version numbers, but on the plus side independent non-shell programs can read it just as easily.

**Comment by BardurArantsson** [comment]
@JakeWheat Are you planning on doing anything further work on this?

Either my or @bgamari's suggestion would be an OK resolution, I think. Anyone with more experience who can chime in? AFAICT the only problem was the duplication, right?

**Comment by BardurArantsson** [comment]
(Btw, I can only apologize for the ridiculous delay. It should have been followed-up on much sooner, but... well, I won't try to make any excuses -- except that I'm not really well-versed in how to manage a large number of issues in GH Issues. Sorry.)

**Comment by JakeWheat** [comment]
The patch removes a lot of features from the bootstrap script (to help with maintainability). Is there a better place to ask if anyone would miss these features?

**Comment by 23Skidoo** [comment]
> Is there a better place to ask if anyone would miss these features?

The `cabal-dev` mailing list, I guess.

/cc @tuncer

**Comment by tuncer** [comment]
@23Skidoo, as long as the replacement doesn't depend on Bash or sacrifice portability in some other way, I like the premise of fetching and installing stuff privately. Given that Cabal is part of the same source tree, it might make sense for bootstrap to build the in-tree Cabal library first and use that, too. That said, if everything is sandboxed, I suppose it also makes sense to skip installing the cabal executable in ~/.cabal/bin and keep it local (or optionally in --prefix).

**Comment by tuncer** [comment]
Any progress?

**Comment by 23Skidoo** [comment]
We're testing `bootstrap.sh` with all supported compilers on Travis now, so IMO there's no longer any benefit with taking this approach and removing features. Closing.

Building in a sandbox with minimal settings (i.e. no profiling and no documentation) by default is probably still a good idea, though.

**Pull request closed without merging**
