### PR TITLE
Explicit export lists for Main

### LINKED ISSUE #9889: cabal init does not always generate explicit export lists
**Describe the bug**

cabal init does not always generate explicit export lists. Export lists can be important for performance. Especially the `Main` module should always have an explicit export list that just exports the `main` function.

**To Reproduce**

```
$ cabal init -mnq --exe
```

(`--libandexe` has the same problem)

That generates:

```
module Main where

main :: IO ()
main = putStrLn "Hello, Haskell"
```

**Expected behavior**

It should generate:

```
module Main (main) where

main :: IO ()
main = putStrLn "Hello, Haskell"
```

**System information**
 - NixOS 24.05pre606852.fd281bd6b7d3 (Uakari)
 - cabal-install version 3.10.2.1
 - compiled using version 3.10.1.0 of the Cabal library 
 - The Glorious Glasgow Haskell Compilation System, version 9.6.4

### PR DESCRIPTION
**Pull request by noughtmare**
Lack of explicit export list can degrade performance. The Main module in particular should always have an explicit export list that contains just the main function.

Fixes #9889 

---

**Template Α: This PR modifies `cabal` behaviour**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thanks!

**Review by geekosaur — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Wow, we missed this! Will merge soon.

**Comment by ulysses4ever** [comment]
Need a channeling, perhaps

**Comment by ulysses4ever** [comment]
@noughtmare it was mentioned on Cabal's Matrix that it's unnatural to merge something that says "Draft" on it. Do you think it's ready? It is in my opinion (modulo changelog, which you could add but if not I can do that).

**Comment by noughtmare** [comment]
I totally forgot about this. I was indeed probably thinking of the changelog and documentation when marking this as draft. Please merge if you think this is ready.

**Pull request merged**
