### PR TITLE
Bump time upper bound to acccomodate 1.14

### PR DESCRIPTION
**Pull request by bgamari**
Just as it says on the tin.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
Just did this in xmonad a couple days ago too. Note that, since it's a bootlib, you'll need a `--constraint` to test it.

**Comment by andreasabel** [comment]
Yes this is untested, CI passing says nothing here.
@bgamari Have you tested the build locally on your machine, with `-c `time >= 1.14'` ?

**Comment by geekosaur** [comment]
I'm running `validate.sh` locally with a `constraint:` in `cabal.project.validate`. Note that this also requires `allow-newer: time` because not all of our dependencies have been updated for `time` 1.14 yet.

**Comment by bgamari** [comment]
> @bgamari Have you tested the build locally on your machine, with `-c 'time >= 1.14'` ?

Yes, I tested it in my GHC tree.

**Comment by geekosaur** [comment]
Hm, actually this just updates `Cabal` and `Cabal-syntax` whereas I just validated the whole thing. Is a follow-up PR a good idea?

**Comment by bgamari** [comment]
I only bumped `Cabal` and `Cabal-syntax` as this is what I need to bump the `time` submodule in GHC.

**Comment by geekosaur** [comment]
That's fine, it's what I figured.

**Comment by andreasabel** [comment]
I wish we could get started to test cabal with GHC 9.10 in general, but we will run into `hashable` not being ready:
- https://github.com/haskell-unordered-containers/hashable/issues/292
- https://gitlab.haskell.org/ghc/head.hackage/-/issues/100

@bgamari Is there something to be done about that?  The maintainer does not seem to respond atm.  Maybe the GHC team is aware of `hashable` blocking the road and has a plan...?

**Comment by bgamari** [comment]
@andreasabel unfortunately I don't have any particular plan here. It would be very nice if we `cabal-install` provided a finer-grained variant of `--allow-newer` (e.g. https://github.com/haskell/cabal/issues/7896) since it would then at least be more likely that one could work around the issue with more specific constraints.

@phadej, perhaps you can comment here as `hashable`'s maintainer of record?

**Comment by phadej** [comment]
@bgamari comment on what?

`hashable` has specifically bitten by releasing / doing compatibility work for unreleased GHC and then redoing it, so I'm no in interest to support first alpha. If `head.hackage` doesn't work for you, it's not my problem.

**Review by andreasabel — APPROVED** [review]

**Comment by andreasabel** [comment]
@phadej wrote:
> `hashable` has specifically bitten by releasing / doing compatibility work for unreleased GHC and then redoing it, so I'm no in interest to support first alpha. If `head.hackage` doesn't work for you, it's not my problem. Isn't `head.hackage` there so you don't need to bother maintainers for GHC head / alpha testing?

Well, if I understand the problem correctly, it is primarily the incompatibility of `hashable` with `filepath-1.5` which causes the problem.  `filepath-1.5` is already released.  Not supporting it yet is just delaying the inevitable.  And it makes evaluating `filepath-1.5` much harder (so that most won't bother supporting it yet either).  Now it also makes evaluating GHC 9.10 much harder.  
`hashable` has 1000 users on Stackage alone, should they all do their own `source-package-repository` workaround?

**Comment by Bodigrim** [comment]
> `hashable` has 1000 users on Stackage alone, should they all do their own `source-package-repository` workaround?

I know two simple workarounds:

* Use `head.hackage` and force `-c 'hashable +os-string'`. 
* Or don't use `head.hackage` and force `-c 'filepath < 1.5'`.

**Comment by Mikolaj** [comment]
Let me try to verify if the CI failure is a fluke or not.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
@bgamari: do I understand right that this should be backported to 3.12? I guess, you already apply this patch to your checkout of Cabal 3.12 in GHC 9.10?

**Comment by Mikolaj** [comment]
@mergify backport 3.12

**Pull request merged**
