### PR TITLE
Add custom GHA markers in solver output

### PR DESCRIPTION
**Pull request by yvan-sraka**
This PR modifies `cabal` behavior by interleaving `::group::` and `::endgroup::` custom GitHub Actions markers in solver output logs to improve overall readability by allowing user to collapse/expand semantically levels of verbose (`-v3`) logs.

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-grouping-log-lines

This feature is only enabled if `GITHUB_ACTIONS` environment variable is set to `true` :)

https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

**Checklist:**

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

Bonus points for added automated tests!

### CODE REVIEW

**Comment by Kleidukos** [comment]
Lovely! That shouldn't be too hard to generalise in the future if other CI platforms have such a feature that we want to support

**Review by andreabedini — CHANGES_REQUESTED** [review]
I am uneasy with adding GitHub specific features to cabal-install.

I'd much prefer a JSON output that can be post-processed with a simple script into something that GitHub can use.

I terms of the implementation ... currentlyRunningInGHA appears everywhere! It cannot be a parameter to the solver, that, json or whatever other formate has to be a postprocessing of the solver output.
I know the situation is difficult but let's not make it worse. Have you tried lifting `foldProgress` out of `rebuildInstallPlan`? You could add more steps for remaining parts (e.g. `phaseElaboratePlan`).

**Comment by yvan-sraka** [comment]
An alternative to this PR would be this dirty bash script, to which one can just pipe the `cabal` output:
```bash
#!/usr/bin/env bash

declare -i last_lvl=-1
declare -i current_lvl=0

while IFS= read -r line; do
    if [[ $line =~ ^\[_*([0-9]+)\] ]]; then
        current_lvl="${BASH_REMATCH[1]}"

        while (( current_lvl > last_lvl )); do
            ((last_lvl++))
            echo "::group::$last_lvl"
        done

        while (( current_lvl < last_lvl )); do
            ((last_lvl--))
            echo "::endgroup::"
        done
    fi
    echo "$line"
done

while (( -1 < last_lvl )); do
    ((last_lvl--))
    echo "::endgroup::"
done
```

**Comment by grayjay** [comment]
What is the use case for this feature? Is it for debugging when CI fails to build cabal? Does it relate to implementing the tree structure in #8475?

**Comment by yvan-sraka** [comment]
> What is the use case for this feature? Is it for debugging when CI fails to build cabal? Does it relate to implementing the tree structure in #8475?

I was thinking it could be a quick hack for improving usability (in the special kind of GHA terminal where part of the output kind be hidden recursively), since the tree structure is really hard to keep concise and readable! But I will rather give a try to a more dynamic displaying like what https://github.com/maralorn/nix-output-monitor does :)

**Pull request closed without merging**
