### PR TITLE
Warn when external Setup uses old Cabal

### LINKED ISSUE #707: Inconsistent behavior between custom and simple build types
(Imported from [Trac #716](http://hackage.haskell.org/trac/hackage/ticket/716), reported by @j3h on 2010-07-23)

If a Custom build-type is used, Setup.hs may be built with a different version of Cabal than the one that cabal-install was built with. This can cause hard-to-find (seemingly random) build failures.

Perhaps cabal-install should warn when it runs Setup.hs with a different version of Cabal than the one that it was built with. Alternatively, it could fail if the version of Cabal that cabal-install was built with is not available when compiling the Setup script.

### PR DESCRIPTION
**Pull request by ttuegel**
Fixes #707.

### CODE REVIEW

**Comment by ezyang** [comment]
Looks good!

**Comment by dcoutts** [comment]
LGTM

**Comment by ttuegel** [comment]
This (apparently) exposes a bug on Linux with GHC < 8; I will investigate.

**Comment by ttuegel** [comment]
Turns out it's not a problem with GHC < 8, but rather with running the integration tests outside of `cabal test`: they pick up `Cabal-1.24` instead of the development version. Any ideas why?

**Comment by ezyang** [comment]
So, the situation is that when we call "cabal" from the custom/plain.sh test, it uses the default package databases (the global and the user). That means that when the setup script is built, it is built using the Cabal from the user database.

I tried some junky hack to get the database to the right place but for some reasons the GHC versions mismatched; not sure what's going on!

**Comment by ttuegel** [comment]
> So, the situation is that when we call "cabal" from the custom/plain.sh test, it uses the default package databases (the global and the user). That means that when the setup script is built, it is built using the Cabal from the user database.

Isn't that the correct database?

> I tried some junky hack to get the database to the right place but for some reasons the GHC versions mismatched; not sure what's going on!

How are you setting the database?

Also, is the problem that `cabal` looks in a different database (between the plain and bootstrap tests), or is the problem that Cabal is installed in a different database?

**Comment by ezyang** [comment]
> Isn't that the correct database?

Not when we use new-build to build the Cabal package. In that case, the inplace Cabal install is in dist-newstyle/packagedb (with dependencies on packages in .cabal/store). An inplace package is never installed to the user database. Note that package-tests (in Cabal) does some fancy footwork to compute where the inplace Cabal is, but that code isn't in integration-tests.

> How are you setting the database?

I tried passing cabal some `--package-db` flags. My noodling is here: https://github.com/ezyang/cabal/pull/4 (look at the end commits; master pointer is out of date.) It works locally for me but not on Travis; puzzling!

> Also, is the problem that cabal looks in a different database (between the plain and bootstrap tests), or is the problem that Cabal is installed in a different database?

Not sure what you mean by bootstrap tests, but I suspect plain.sh is the only test which has checked stderr, which is why it is failing. (In fact, one of the custom setup tests specifically makes sure that it picks up the system Cabal, and not some other Cabal that a user happens to have in the user database.)

**Comment by ttuegel** [comment]
> Not sure what you mean by bootstrap tests, but I suspect plain.sh is the only test which has checked stderr, which is why it is failing. (In fact, one of the custom setup tests specifically makes sure that it picks up the system Cabal, and not some other Cabal that a user happens to have in the user database.)

Yes, but it only fails when invoked directly, as in `travis-script.sh`. When running the integration tests through `cabal` as in `travis-bootstrap.sh`, the tests work. But, it sounds like this is due to the difference between `build` and `new-build`.

**Comment by ezyang** [comment]
> No, this can't merely be due to build vs. new-build. When I build with cabal build locally, but run the integration test directly, it still fails.

That's because the bootstrap strip also installs the Cabal library in the user database, which is why it gets picked up.

**Comment by ezyang** [comment]
Is there some alternate hacky fix we can do to get this PR unfrozen? @ttuegel

**Pull request closed without merging**
