### PR TITLE
Drop build and CI support for GHC < 8.0

### PR DESCRIPTION
**Pull request by andreabedini**
Replaces #7534.

Todo

* [ ] figure out the changes to the bootstrap plans.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by andreabedini** [comment]
@Mikolaj can you have a look? Do I need to update the bootstrap files?

**Comment by jneira** [comment]
many thanks for the cleaning up, love the +42−1,253

**Review by Mikolaj — APPROVED** [review]
Great job. No, I think it's enough if we update the bootstrap files before release (or earlier on request). That's in (an old portion of) the release checklist at https://github.com/haskell/cabal/wiki/Making-a-release

**Review by robx — APPROVED** [review]
Changes look good to me, and I like that this is a bit more limited in scope than #7534.

(Can't really speak to the backwards compatibility implications.)

**Pull request merged**
