### PR TITLE
add InstalledPackageId  synonym to UnitId

### PR DESCRIPTION
**Pull request by Heather**
related:
 - https://github.com/haskell/cabal/pull/2987
 - https://github.com/ekmett/distributive/pull/16

### CODE REVIEW

**Comment by ezyang** [comment]
Hi Heather, I don't want to add this pattern, it's not supported by enough GHCs and I don't want `InstalledPackageId` to be transparent to users, its representation is still in flux. Can you show me some Setup code which actually needs the constructor? Perhaps I can offer a BC compatible alternative which will work instead.

**Comment by Heather** [comment]
@ezyang yes, I wasted a lot of time trying to understand what's happening around and ended with global confusion and a lot of people who can really calrify things...

My exact problem is here: https://github.com/ekmett/distributive/issues/15

and actually this problem is gone suddenly (not sure when) but I still want attention to it

**Comment by ezyang** [comment]
The problem is gone be we fixed it! It was a brief bug for a few days.

On January 19, 2016 10:16:27 AM PST, Heather <notifications@github.com> wrote:
>@ezyang yes, I wasted a lot of time trying to understand what's
>happening around and ended with global confusion and a lot of people
>who can really calrify things...
>
>My exact problem is here:
>https://github.com/ekmett/distributive/issues/15
>
>and actually this problem is gone suddenly (not sure when) but I still
>want attention to it
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/haskell/cabal/pull/3067#issuecomment-172938908

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ezyang** [comment]
https://github.com/haskell/cabal/commit/ecdf65a3c1e01b798e9d073258a6d1c8ff63a6d8

**Pull request closed without merging**
