### PR TITLE
Specify Fourmolu version

### PR DESCRIPTION
**Pull request by ffaf1**
Fourmolu < 0.12 results in spurious suggestions, see #8976.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* N/A ~Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).~
* [x] The documentation has been updated, if necessary.
* ~Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.~

N/A ~Bonus points for added automated tests!~

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]
What a shameful omission on my part. Thank you for fixing it.

**Review by ulysses4ever — APPROVED** [review]
Good. Now we'll see how fast this info gets outdated :-)

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ffaf1** [comment]
Fails on [this](https://github.com/haskell/cabal/actions/runs/5249053256).

**Comment by ulysses4ever** [comment]
The latest run looks fine now, no? https://github.com/haskell/cabal/actions/runs/5249513323/jobs/9482387492?pr=8996

**Comment by ffaf1** [comment]
Yet I see a red slice:

CI ring graph, with a tiny but present red slice

shall I re-rerun CI?

**Comment by Kleidukos** [comment]
@ffaf1 oops, didn't see your question and re-ran the CI

**Pull request merged**
