### PR TITLE
remove duplicate LANGUAGE DeriveFoldable, minor improvements

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Compile error:

```
Distribution/Client/Dependency/Modular/PSQ.hs:52:28:

    Couldn't match type ‘k’ with ‘(d1, k)’

      ‘k’ is a rigid type variable bound by

          the type signature for map :: (v1 -> v2) -> PSQ k v1 -> PSQ k v2

          at Distribution/Client/Dependency/Modular/PSQ.hs:51:8

    Expected type: (k, v1) -> (k, v2)

      Actual type: (k, v1) -> ((d1, k), (d1, v1))

    Relevant bindings include

      xs :: [(k, v1)]

        (bound at Distribution/Client/Dependency/Modular/PSQ.hs:52:12)

      map :: (v1 -> v2) -> PSQ k v1 -> PSQ k v2

        (bound at Distribution/Client/Dependency/Modular/PSQ.hs:52:1)

    In the first argument of ‘fmap’, namely ‘second’

    In the first argument of ‘PSQ’, namely ‘(fmap second xs)’

Distribution/Client/Dependency/Modular/PSQ.hs:55:32:

    Couldn't match type ‘v’ with ‘(v, d0)’

      ‘v’ is a rigid type variable bound by

          the type signature for

            mapKeys :: (k1 -> k2) -> PSQ k1 v -> PSQ k2 v

          at Distribution/Client/Dependency/Modular/PSQ.hs:54:12

    Expected type: (k1, v) -> (k2, v)

      Actual type: (k1, v) -> ((k1, d0), (v, d0))

    Relevant bindings include

      xs :: [(k1, v)]

        (bound at Distribution/Client/Dependency/Modular/PSQ.hs:55:16)

      mapKeys :: (k1 -> k2) -> PSQ k1 v -> PSQ k2 v

        (bound at Distribution/Client/Dependency/Modular/PSQ.hs:55:1)

    In the first argument of ‘fmap’, namely ‘first’

    In the first argument of ‘PSQ’, namely ‘(fmap first xs)’
```

**Comment by Heather** [comment]
oh sorry I can reproduce it, was testing to build Cabal by mistake

**Comment by Heather** [comment]
@23Skidoo fixed

**Comment by 23Skidoo** [comment]
Can you please squash the bugfix commit with main one to avoid having broken commits in history?

**Comment by Heather** [comment]
@23Skidoo yes if that can wait for tomorrow

**Comment by Heather** [comment]
@23Skidoo done

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
