### PR TITLE
Cabal: don't use normalise for copyFile on Windows

### PR DESCRIPTION
**Pull request by Mistuke**
`normalise` from `System.FilePath` has an annoying behavior in that it doesn't simplify `FilePath`. The documented behavior on Windows is to normalise `Z://` into `Z:\\\\` which in the `Win32` namespace won't matter but since we're using the `device` namespace `\\?\Z:\\` is an invalid path to the filesystem.

This results in cabal throwing an illegal path exception for such cases which happen to be fairly common when building `GHC`.  This fixes it by inlining some more code from `System.Directory` which has a function which correctly preserves the semantics of a path when converted to a device path.

Tested with a full GHC bootstrap and testrun. Fixes https://gitlab.haskell.org/ghc/ghc/merge_requests/619

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Is there a corresponding patch to `filepath`?

**Comment by Mistuke** [comment]
No, because `FilePath` 's `normalise` doesn't claim to simplify paths and doesn't prepare paths for use in any namespace other than the `win32` one. So what it's doing is at least according to it's documentation.

Usually it won't matter as once the path hits the RTS we'll do any fixups needed.  The issues here is that we call the `Win32 CopyFile` API directly, in order not to go through the GHC I/O manager, so we have to deal with the path fixups.

**Comment by phadej** [comment]
If you put your explanation as a Note in the code, then this is good to go :+1:

**Comment by Mistuke** [comment]
All good @phadej?

**Comment by phadej** [comment]
Feel free to merge

**Comment by Mistuke** [comment]
Thanks!

**Pull request merged**
