### PR TITLE
Deprecate ProgramConfiguration et al.

### PR DESCRIPTION
**Pull request by 23Skidoo**
This stuff has been actually deprecated for ages, in 2.0 we can
finally mark it as such. Next up: removing all uses from
Cabal/cabal-install code.

~~WIP, please don't merge yet.~~

### CODE REVIEW

**Comment by ezyang** [comment]
OK, would be good if there was guidance on how to move to the new API written somewhere.

**Comment by 23Skidoo** [comment]
It's as simple as s/old/new/, we're just deprecating the synonyms.

**Comment by 23Skidoo** [comment]
The reason I didn't simply run a global search and replace is that I also want to change all instances of `conf` as a variable to `progdb`.

**Comment by 23Skidoo** [comment]
This should be now ready to go in.

**Comment by ezyang** [comment]
OK, merge it when it's green.

**Pull request merged**
