### PR TITLE
Mark 'ghc-boot-th' as non-installable.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by angerman** [comment]
Ah! I didn't even know we had this! Would this mean, that if I pushed flags through all dependencies, cabal would never try to rebuild those packages? (E.g. related to #4939).

Coincidentally there was a discussion on #hackage today with @sclv and @hvr where the question cam up if `ghc --info` should just list the non-reinstallable packages.

GHC basically knows about
```
wiredInUnitIds :: [UnitId]
wiredInUnitIds = [ primUnitId,
                       integerUnitId,
                       baseUnitId,
                       rtsUnitId,
                       thUnitId,
                       thisGhcUnitId,
                       dphSeqUnitId,
                       dphParUnitId ]
```
as being wired in packages.

Anyway, this is only tangential to this PR.

**Comment by 23Skidoo** [comment]
@angerman There's `--allow-boot-library-installs` that allows you to ignore the blacklist.

**Comment by 23Skidoo** [comment]
I discussed this with @hvr and we decided that it's better to keep the blacklist as small as possible. `ghc-boot-th` is only non-reinstallable because `template-haskell` depends on it, otherwise it could very well be.

**Comment by 23Skidoo** [comment]
I wouldn't mind if the blacklist was populated automatically. 

> ```
> dphSeqUnitId,
> dphParUnitId ]
> ```

Looks like those are not built by default, e.g. `ghc-pkg list` on my system doesn't list them.

**Comment by angerman** [comment]
I think dph is effectively dead

**Pull request closed without merging**
