### PR TITLE
Cabal: Bump time upper bound to allow 1.12

### PR DESCRIPTION
**Pull request by bgamari**
In service of [GHC #20547](https://gitlab.haskell.org/ghc/ghc/-/issues/20547).

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by Mikolaj** [comment]
I can see

   cabal-install/cabal-install.cabal:        time       >= 1.5.0.1  && < 1.11,

@bgamari: could you bump that as well so that we all test the same thing on branch master?

**Review by Mikolaj — APPROVED** [review]
Restarted CI seems to be fine.

I intend to backport this to 3.6 to give the GHC hackers the option of using either branch. I will also make a PR that bumps cabal-install similarly, but not backport it, so that we can dog-food on master ASAP without enddangering 3.6. Please discuss if that doesn't sound good.

**Comment by fgaz** [comment]
CI is not testing this change because time is included with ghc (what was the name for that? core/boot package?) and won't be upgraded...
@bgamari Did you test this?

**Comment by Mikolaj** [comment]
@fgaz: well spotted. So we'd need to change the bounds temporarily to only allow 1.12, to get this tested?

**Comment by fgaz** [comment]
or add time==1.12 to constraints. I don't know if previous maintainers had a faster way to test such changes

**Comment by bgamari** [comment]
> CI is not testing this change because time is included with ghc (what was the name for that? core/boot package?) and won't be upgraded... @bgamari Did you test this?

Yes, I tested it in a local GHC tree.

**Comment by bgamari** [comment]
> `cabal-install/cabal-install.cabal: time >= 1.5.0.1 && < 1.11,`

Historically we have bumped `cabal-install` and `Cabal` separately as the former is harder for me to test.

**Review by fgaz — APPROVED** [review]
> Yes, I tested it in a local GHC tree.

That's enough for me, and [the changelog](https://hackage.haskell.org/package/time-1.12/changelog) looks harmless

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.6

**Pull request merged**
