### PR TITLE
Fix #7582: add Ord to the derived instances of SymbolicPath

### LINKED ISSUE #7582: Add Ord (SymbolicPath a b) instance

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #7582: add `Ord` to the derived instances of `SymbolicPath`.

- Tested by checking compilation.
- Given the granularity of the changelog, this change is below the threshold.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Doh, I fully expected I lied that it's going to be a one-liner. @phadej: is that all you need?

**Comment by Mikolaj** [comment]
I will try squeezing. Not sure GHC-9.2, you'd need to ask them hairy GHC haxors.

**Comment by phadej** [comment]
It will be fine if it's bundled with GHC-9.2.2 (I doubt 9.2.1 will be the last in series), i.e. if you make `Cabal-3.6.1` release once it accumulates enough backports and before GHC-9.2.2

**Comment by Mikolaj** [comment]
Sounds plausible.

@mergifyIO: backport 3.6

**Comment by Mikolaj** [comment]
Doh. 

@Mergifyio backport 3.6

**Pull request merged**
