### PR TITLE
Enable 'make lexer' in travis-meta.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
The part where it differs apparently comes from `/usr/include/stdc-predef.h`. I can imagine that file being slightly different on my machine and on Travis for some reason. One solution is to squash repeated empty lines in the generated file.

**Comment by 23Skidoo** [comment]
Meta seems to pass now.

**Comment by 23Skidoo** [comment]
Pushbot failures are OOM:s, will need to look at these separately.

**Comment by phadej** [comment]
Btw, why @23Skidoo you removed generated `Lexer.hs`?

**Comment by phadej** [comment]
ah, sorry it's not removed, it just shrink a lot `-94 Lexer.hs` looked suspicious when I pulled `master`!

**Pull request merged**
