### PR TITLE
WIP: Fix stack travis build

### PR DESCRIPTION
**Pull request by themoritz**
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
This doesn't actually fix the `via-stack` build, but feel free to push the merge button once you get it working.

**Comment by ezyang** [comment]
We should also make the stack build "must pass", so we don't keep accidentally breaking it :)

**Comment by hvr** [comment]
@ezyang I don't have Stack installed, nor do I have the time, energy nor motivation to keep the Stack build working. If it breaks and it's not obvious w/o trial&error how to fix it, I will just demote it to "can fail" again.

**Comment by 23Skidoo** [comment]
Closing in favour of #4693.

**Pull request closed without merging**
