### PR TITLE
Carry package dbs into testsuite

### PR DESCRIPTION
**Pull request by enolan**
Prior to this patch, the testsuite used your global package db, and
sometimes, the inplace package db, which led to errors if you didn't
have old-time installed globally. They looked like this:

BuildDeps/SameDepsAllRound:          Cabal result was Result {successful = False, success = Failure, outputText = "\"/home/enolan/cabal/Cabal/tests/Setup configure --user -w  /home/enolan/.nix-profile/bin/ghc\" in PackageTests/BuildDeps/SameDepsAllRound\nConfiguring SameDepsAllRound-0.1...\nSetup: At least the following dependencies are missing:\nold-time -any\n"}

### CODE REVIEW

**Comment by enolan** [comment]
Fixed to compile on base<4.8.

**Comment by enolan** [comment]
Oops, deleted branch by accident

**Comment by 23Skidoo** [comment]
Hmm, is there a guarantee that old-time is installed in the in-place package DB?

**Comment by enolan** [comment]
The in-place package DB only includes the new Cabal library. The idea of this patch is to work in the case that you made a sandbox and ran `./Setup --package-db=.cabal-sandbox/foo`. If you did `cabal install --only-dependencies --enable-tests` everything necessary will be either in the global package db or the sandbox one. `old-time` is a dependency of `package-tests`.

**Comment by 23Skidoo** [comment]
OK, this looks good, merging. Thanks!

**Pull request merged**
