### PR TITLE
Migrate the test suite to Tasty.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by tibbe** [comment]
For large changes like this it would be nice with a motivation. I guess the reason is because test-framework isn't maintained anymore?

**Comment by 23Skidoo** [comment]
@tibbe Yes, the problem with `test-framework` is that it keeps breaking with new GHC releases. This PR doesn't fix [the most recent failure](https://github.com/haskell-infra/hackage-trustees/issues/4), though, since Tasty depends on `ansi-wl-pprint` itself (through its dependency on `optparse-applicative`).

**Comment by 23Skidoo** [comment]
This patch looks large, but the changes are mostly mechanical. Large part was done with an Emacs macro.

**Comment by tibbe** [comment]
:+1:

**Comment by hvr** [comment]
@23Skidoo well, `test-framework` was moved to https://github.com/haskell/test-framework where it's being kept updated to work with recent GHCs... otoh it's mostly in life-support mode, i.e. no new features, just bugfixes and the occasional support for new dependencies...

**Comment by 23Skidoo** [comment]
@hvr Yes, I know that it's not completely unsupported, but that often just means that I have to [fix it](https://github.com/haskell/test-framework/pull/5) [myself](https://github.com/haskell/test-framework/pull/6). I'm hoping that with Tasty I'll be able to avoid that.

**Pull request merged**
