### PR TITLE
Fix haddock open on windows

### LINKED ISSUE #9417: cabal haddock --open doesn't work on windows
On windows `findOpenProgramLocation` tries to use `start` in order to open a browser to show the documentation.

However, this doesn't work because `start` isn't an executable but a built-in command.

See: https://web.archive.org/web/20101030061633/http://frank.neatstep.com/node/84

```
The trick is that "start" isn't an executable. It is a built-in command of the Windows command line interpreter "cmd.exe". In Java (and other languages) if you try to create a process using the "start" command this will fail -- since there is no "start.exe" executable in the system.

Instead you have to invoke "start" through the "cmd.exe" interpreter. This can be done using the /C flag:

cmd /c "start readme.txt"
```

It seems this would have been caught if there had been a test added for the `haddock --open` option.

### PR DESCRIPTION
**Pull request by jasagredo**
A revisit of #9428. Closes #9417

Tested it on my Windows machine, seems to work both in MinGW shell and in PowerShell.

## QA Notes

On a Windows machine, build a haskell project with haddock enabled, and run `cabal haddock --open`. The default browser should be started with the index.html page

### CODE REVIEW

**Comment by jasagredo** [comment]
Ah, the license says:

```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
```

So probably we need to do what you mentioned about adding the license @Kleidukos ?

**Comment by ulysses4ever** [comment]
@jasagredo how about we just depend on `open-browser`? It's `cabal-install`, not Cabal the library, after all, so we don't need to be too modest about dependencies. On the plus side: we don't need to think about the license, and we don't need to maintain this functionality on our own --- the author of `open-browser` will do it for us!

**Comment by jasagredo** [comment]
> @jasagredo how about we just depend on `open-browser`? It's `cabal-install`, not Cabal the library, after all, so we don't need to be too modest about dependencies. On the plus side: we don't need to think about the license, and we don't need to maintain this functionality on our own --- the author of `open-browser` will do it for us!

Will do hopefully later today.

**Comment by Kleidukos** [comment]
> the author of `open-browser` will do it for us!

Unfortunately that might not be the case, look at their profile on GitHub: https://github.com/rightfold

> All of my repositories are abandoned.

**Comment by ulysses4ever** [comment]
Faire enough.

**Comment by jasagredo** [comment]
`cabal-install` now has a dependency on `open-browser`. Please check that it works on other systems. It does on Windows.

**Review by ulysses4ever — APPROVED** [review]
Support from me.

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
CI says something is missing a dependency on `open-browser` still.

**Comment by ulysses4ever** [comment]
Oh bootstrapping.. please, check out README in https://github.com/haskell/cabal/tree/master/bootstrap...

**Comment by jasagredo** [comment]
I updated the bootstrap jsons, but more than just `open-browser` changed. I hope it is fine

**Review by Kleidukos — APPROVED** [review]

**Comment by jasagredo** [comment]
I think it didn't need this last force-push 😄 , the pipelines passed in the previous one and mergify was about to start merging it I think

**Pull request merged**
