### PR TITLE
Bump package process dependency version to 1.6.15.0 and move from Cabal to cabal-install

### PR DESCRIPTION
**Pull request by Mikolaj**
This mimics #8279 and is needed due to https://github.com/haskell/cabal/pull/8279#issuecomment-1204599705

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]

**Review by Kleidukos — APPROVED** [review]

**Comment by robx** [comment]
Depending on non-GHC-bundled versions of `process` *might* lead to similar trouble as described here: https://discourse.haskell.org/t/why-does-ghc-9-2-4-require-process-1-6-13-2/4884/4.

It might be a better idea to do this only for `cabal-install` instead of `Cabal` the library.

**Comment by ulysses4ever** [comment]
No matter what version of process Cabal depends upon, there will be a version of GHC that is incompatible? In that case, people either update GHC or downgrade Cabal. And on Discourse, they’re saying that 9.2.5 will come with the newer process.

That said, if the idea to only bump cabal-install dependency solves the dreaded ctrl-c problem, maybe that’s the most robust way to go.

**Comment by Mikolaj** [comment]
> That said, if the idea to only bump cabal-install dependency solves the dreaded ctrl-c problem, maybe that’s the most robust way to go.

Well, I don't think in this case we'd build Cabal with old process and cabal-install with new. Rather both would use the new process. The only difference would be when somebody is using Cabal, but not cabal-install. 

Given that it sounds safer, let me move the bound from Cabal to cabal-install.

**Comment by robx** [comment]
> > That said, if the idea to only bump cabal-install dependency solves the dreaded ctrl-c problem, maybe that’s the most robust way to go.
> 
> Well, I don't think in this case we'd build Cabal with old process and cabal-install with new. Rather both would use the new process. The only difference would be when somebody is using Cabal, but not cabal-install.
> 
> Given that it sounds safer, let me move the bound from Cabal to cabal-install.

The potential problems arise for projects that depend on `Cabal` the library. E.g. using both `Cabal` and `hspec`, which seems quite likely to occur.

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Comment by Mikolaj** [comment]
Let me rebase to see if the recent CI workaround unblocks merging.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
This is rather important and our CI is currently broken (probably some infrastructure corruption), so I'm merging and then backporting manually.

**Comment by Mikolaj** [comment]
@mergify backport

**Comment by andreasabel** [comment]
Looks like we should release this fix rather soon, maybe as `Cabal-3.8.1.1`?

@robx wrote:
> Depending on non-GHC-bundled versions of `process` _might_ lead to similar trouble as described here: [discourse.haskell.org/t/why-does-ghc-9-2-4-require-process-1-6-13-2/4884/4](https://discourse.haskell.org/t/why-does-ghc-9-2-4-require-process-1-6-13-2/4884/4).

This potential trouble has turned to real trouble in:
- #8554

**Comment by Mikolaj** [comment]
Agreed. There is enough fixes already merged or in flight that 3.8.2.0 of all packages makes sense. If anybody volunteers as a release manager for 3.8.2.0, I will help to make the release soon. Otherwise, I will make the release at some point, but not necessarily right now (depending on the other fixes, their workarounds, etc.).

**Comment by andreasabel** [comment]
@Mikolaj  wrote:
> Agreed. There is enough fixes already merged or in flight that 3.8.2.0 of all packages makes sense. If anybody volunteers as a release manager for 3.8.2.0, I will help to make the release soon. Otherwise, I will make the release at some point, but not necessarily right now (depending on the other fixes, their workarounds, etc.).

A proper release would likely be taking a couple of months.  Alternatively, can we just release this one patch as `cabal-install 3.8.1.1`?  `Cabal 3.8.1.0` can be revised to make the conditional `process` constraint non-restrictive (`process -any`).

**Comment by Mikolaj** [comment]
Yes, absolutely. Release checklist is already mostly done (https://github.com/haskell/cabal/wiki/Making-a-release) and some points can be ignored for a minor release like that. I will help.

**Pull request merged**
