### PR TITLE
Give an explicit message when SIGSEGV happens.

### LINKED ISSUE #767: Give better error message when GHC/Setup script segfaults
(Imported from [Trac #777](http://hackage.haskell.org/trac/hackage/ticket/777), reported by philips on 2010-12-12)

I am getting `ExitFailure?` 11 when trying to install hledger on Debian and openSUSE. I reported this to the hledger author, Simon, and he said he is experiencing this on his machines too and for other packages, not just hledger.

Log file attached. Summary below:

<pre class="wiki">ledger:~/ $ cabal install -v3 hledger
Lots of debug output (see attached)...
hledger-0.13 failed during the configure step. The exception was:
ExitFailure 11
ledger:~/ $ cabal --version
cabal-install version 0.8.2
using version 1.8.0.2 of the Cabal library
ledger:~/ $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 6.12.1
</pre>

### PR DESCRIPTION
**Pull request by ezyang**
Fixes #767.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM.

**Comment by erikd** [comment]
:+1:

**Comment by ezyang** [comment]
Unfortunately, the patch doesn't work. Investigating.

**Comment by ezyang** [comment]
OK, found the bug.

**Comment by ezyang** [comment]
Heh, the Windows version of the test case explodes in an... interesting way. Let me see if I can tweak it.

**Pull request merged**
