### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by askeblad**
Cabal-syntax/src/Distribution/Fields/Parser.hs
Cabal-tests/tests/custom-setup/IdrisSetup.hs
Cabal/src/Distribution/Compat/Process.hs
Cabal/src/Distribution/Simple/Compiler.hs
cabal-install-solver/src/Distribution/Solver/Modular/PSQ.hs
cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
cabal-install/src/Distribution/Client/CmdInstall.hs
cabal-install/src/Distribution/Client/InstallPlan.hs
cabal-install/src/Distribution/Client/PackageHash.hs
cabal-install/src/Distribution/Client/ProjectBuilding.hs
cabal-install/src/Distribution/Client/Targets.hs
cabal-install/src/Distribution/Client/Types/ConfiguredId.hs

### CODE REVIEW

**Review by grayjay — APPROVED** [review]

**Comment by Mikolaj** [comment]
@askeblad; CI is reporting: "This pull request cannot be embarked for merge

The merge-queue pull request can't be update
Details: `Pull request can't be updated with latest base branch changes

Mergify needs the author permission to update the base branch of the pull request.
vaerksted needs to [authorize modification on its head branch](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
err-code: 32058`"

**Comment by askeblad** [comment]
would it be counterproductive to click Fetch upstream on my fork

**Comment by Mikolaj** [comment]
@askeblad: nope, that wasn't rebase, that was merge. Could you try to rebase instead? Or just make it possible to push to your branch, as in the help text linked.

**Comment by Mikolaj** [comment]
Or, actually, let me rebase&merge using my admin privileges. Thank you for the PR?

**Pull request merged**
