### PR TITLE
Organise cabal commands into subsections

### PR DESCRIPTION
**Pull request by ffaf1**
Requested in #8309 , #8315

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] I don’t believe reordering warrants a changelog
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by ffaf1** [comment]
[Rendered here](https://cabal--8332.org.readthedocs.build/en/8332/cabal-commands.html#). I really dislike that you cannot explode more than one subsection at once (on the left menu).

**Review by ulysses4ever — APPROVED** [review]
I absolutely love it.

One thing that could be improved is the granularity of the changes. Right now the diff is not particularly nice. Breaking it into several commits could improve our future experience (I find myself looking into the history of the docs pretty often). E.g. the top new section of the diff (Target Forms, etc) could be it's own commit. Updating the headers style may be another one. But more worrying is lower level +/- stuff that I'm not sure is easy to improve.

As for the expanding sections, in the description of #8196 I tried to review the state of this upstream (the sphinx_rtd_theme theme), and in short: it's not hopeful. The way forward would be to find a new theme, if you ask me. With the desired features and looking not very different from the current, perhaps. I'm not aware of anything like that currently, sadly.

**Comment by ffaf1** [comment]
Having a commit with `---` to `^^^` would alas be non atomic (you get an error then you are “jumping” levels). You can do it one by one, introducing a section for each commit, but that would mean having out-of-sync documentation (half in the old style, half in the new style).

I am far from an expert with git, so suggestions are welcome. The diff is indeed a mess that even a `rm` / `add` would be cleaner.

**Comment by ffaf1** [comment]
This is — I think — as much as I can factour out while keeping commits atomic.

Alas, if you were to invoke something like `git annotate` or similar you will indeed hit this commit wall; I wouldn’t know how to sidestep this.

**Review by andreasabel — APPROVED** [review]
I like the new structure!  Well done!

**Comment by ffaf1** [comment]
@ulysses4ever I wait for your feedback before putting a `merge me` label. If there is more I can do to make this granular I am ready to do it (or anything that facilitates you checking the history of the docs); if not, merge time it will be, as if this gets out of synch with master we are doubly screwed!

**Comment by ulysses4ever** [comment]
@ffaf1 looks good to me, thank you!

**Pull request merged**
