### PR TITLE
Set urllib.request.urlopen timeout in bootstrap.py to fix CI

### PR DESCRIPTION
**Pull request by Mikolaj**
Trying to fix bootstrap job currently broken on CI via explicitly setting a timeout.

### CODE REVIEW

**Comment by Mikolaj** [comment]
It seems one second timeout is enough. Doh.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
@ulysses4ever: thank you for the review. I'm emergency-merging after CI finishes.

**Comment by Mikolaj** [comment]
@mergify rebase 3.8

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
