### PR TITLE
Remove ordNub from IPI.depends.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Can we have some context? Also congrats on opening PR #4000.

**Comment by ezyang** [comment]
I'm going to be working on recording the ABI of each package we depend. For backwards compatibility I can't store this information directly in `depends`. So I was planning on making a parallel field `abi-depends` to record this information. And then I guess I made a bad assumption that I don't want to duplicate the unit IDs from depends in abi-depends, so I would just make it so you could zip these two fields together. But then depends needs to be a stable order, which it wouldn't be due to ordNub. And then I remembered that I was just working around a weird bug when I added the ordNub and maybe I accidentally fixed it. So I removed it. Maybe we don't have to.

**Comment by dcoutts** [comment]
I think this change is now included in #4008 where the context makes more sense. @ezyang so I assume we can close this one right?

**Comment by ezyang** [comment]
Yeah.

**Pull request closed without merging**
