### PR TITLE
Attempt to fix issue 4133

### PR DESCRIPTION
**Pull request by abooij**
It's only the last patch that does something, but it's based on @ezyang's work in order to see if it did anything.

DO NOT MERGE THIS - primarily this was the easiest way to run the tests on Windows.

### CODE REVIEW

**Comment by abooij** [comment]
CC @23Skidoo

**Comment by abooij** [comment]
The Windows test ran as expected (see https://ci.appveyor.com/project/23Skidoo/cabal/build/%232713%20(master) ).

So I've now based this patch on master. If the lights are green this should be mergeable.

**Comment by 23Skidoo** [comment]
Code looks somewhat hairy, but the complexity seems to be intrinsic, and (thankfully) confined to the Exec module.

**Comment by ezyang** [comment]
I don't think it's intrinsic complexity: I think the Program API may have made some bad life choices. But it's not altogether clear what the better design is so I'm OK with a workaround for now.

**Pull request merged**
