### PR TITLE
Require `type` field when spec < 3.8 (#8115)

### PR DESCRIPTION
**Pull request by cydparser**
Addresses changes requested in https://github.com/haskell/cabal/pull/8115#issuecomment-1122494025

---

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [X] The documentation has been updated, if necessary.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM.

**Review by jneira — APPROVED** [review]
lgtm thanks for fixing it

**Comment by Mikolaj** [comment]
Let's merge!

**Comment by Mikolaj** [comment]
@cydparser: you haven't made your branch read-write, so mergifyIO can't rebase and merge: https://github.com/haskell/cabal/pull/8138/checks?check_run_id=6448254990

If you don't mind, please mark the branch as writeable or just rebase and merge manually.

**Comment by Mikolaj** [comment]
Thank you!

**Pull request merged**
