### PR TITLE
Make 'cabal install' always show build logs

### PR DESCRIPTION
**Pull request by BardurArantsson**
The rationale here is that doing so

  - make compiler warnings in upstream code much more in-your-face and
    obvious, thus hopefully making them more likely to be reported to
    upstreams.

  - makes it a lot more convenient to work with sets of co-developed
    packages, e.g.

      cabal install ./Cabal ./cabal-install

    will actually show warnings.

---

This is the 80% solution I mentioned in #1062 -- it doesn't really address the other large-scale changes that could be done, but frankly I'd be a lot happier with just this (than not).

### CODE REVIEW

**Comment by BardurArantsson** [comment]
Here's an example of build output:

```
[...]
Creating package registration file:
/tmp/pkgConf-shake-0.1521184219931520223205.4
Installing library in
/home/bardur/wd/cqrs/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.1/shake_7a7wJ6jOrXKHiLNauacWgL
Installing executable(s) in /home/bardur/wd/cqrs/.cabal-sandbox/bin
Registering shake-0.15.4...
Installed scotty-0.10.1
Build log ( /home/bardur/wd/cqrs/.cabal-sandbox/logs/scotty-0.10.1.log ):
Configuring scotty-0.10.1...
Building scotty-0.10.1...
Preprocessing library scotty-0.10.1...
[1 of 6] Compiling Web.Scotty.Internal.Types ( Web/Scotty/Internal/Types.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty/Internal/Types.o )
[2 of 6] Compiling Web.Scotty.Util  ( Web/Scotty/Util.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty/Util.o )
[3 of 6] Compiling Web.Scotty.Action ( Web/Scotty/Action.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty/Action.o )
[4 of 6] Compiling Web.Scotty.Route ( Web/Scotty/Route.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty/Route.o )
[5 of 6] Compiling Web.Scotty.Trans ( Web/Scotty/Trans.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty/Trans.o )
[6 of 6] Compiling Web.Scotty       ( Web/Scotty.hs, dist/dist-sandbox-2bc1c660/build/Web/Scotty.o )
In-place registering scotty-0.10.1...
Creating package registration file:
/tmp/pkgConf-scotty-0.104528676211017679567.1
Installing library in
/home/bardur/wd/cqrs/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.1/scott_0qc9L72J4onGEmSS8kXpij
Registering scotty-0.10.1...
Configuring cqrs-example-0.10.0...
Building cqrs-example-0.10.0...
Installed cqrs-example-0.10.0
Build log ( /home/bardur/wd/cqrs/.cabal-sandbox/logs/cqrs-example-0.10.0.log ):
Configuring cqrs-example-0.10.0...
...
```
There's a bit of incongruity with the "Installed ..." bit coming before the log output... I'll be happy to switch that around.

In general the output is also quite "dense" since there are no newlines except in GHC/build output -- not sure if that should be added. We could also consider if a little slash of colour (e.g. green/red for "Installed..." vs. "Failed to install..." lines) would make sense, but I didn't want to mix that up with the basic functionality.

**Comment by BardurArantsson** [comment]
Apparently there are some (AFAICT) spurious Travis CI build failures. Not sure what should be done about that, if anything...?

**Comment by 23Skidoo** [comment]
Restarted the build, maybe it'll go away.

**Comment by 23Skidoo** [comment]
LGTM. I think this is a fine solution until multi-package projects are implemented.

**Comment by BardurArantsson** [comment]
Any other reviewers care to chime in with comments? Happy to hear suggestions.

(Esp. about the "Installed..." before "<log>" thing. I've been trying out my branch for Real Things(TM) I find that it can actually be quite confusing when reading the output. I'd love to hear opinions!)

**Pull request closed without merging**
