### PR TITLE
Rebase fixLinkDeps onto solver branch

### PR DESCRIPTION
**Pull request by grayjay**
All but the last two commits are from  #3359.

See #3357.  I rebased https://github.com/edsko/cabal/tree/pr/FixLinkDeps, except for the last commit, which handles a different issue.  I also removed my commits, because they weren't needed.

/cc @edsko

### CODE REVIEW

**Comment by edsko** [comment]
@kristen I'm somewhat confused. What is the status on #3327 now? Do we have a solution? Does the `solver` branch now have my fix for the incorrect link groups (the unqualifation-requalification thing) and your original solution to #3327? And the discussion at the end of https://github.com/haskell/cabal/pull/3357#issuecomment-211518643 we still don't have a good answer for? Is that correct?

**Comment by grayjay** [comment]
@edsko This PR only contains your solution to #3268, which uses `unqualifyDeps`.  I wasn't sure what to do about #3327.  I think that my PR is incomplete because it doesn't contain `GoalReasonChain`s, and we haven't decided what to do with `lgBlame` and `lgConflictSet`.

**Comment by edsko** [comment]
Yes, I think the answer to that isn't clear yet, but it would be good if we have have the test cases you have for #3327 available on this branch (where we expected them to fail right now).

**Comment by grayjay** [comment]
I cherry-picked that test case, but I think it is currently passing because of a different fix.

**Comment by edsko** [comment]
Aha, I see. That explains my confusion :) That's a little unfortunate.

**Comment by grayjay** [comment]
Yeah, there is a lot of overlap between conflict sets. I'll try to come up with a more specific test.

**Comment by grayjay** [comment]
I added a test in #3363.

**Pull request merged**
