### PR TITLE
Bump base bound to 4.21 for GHC 9.12

### PR DESCRIPTION
**Pull request by wz1000**
**Template B: This PR does not modify behaviour or interface**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

----

This needs to be backported to the 3.14 branch.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thanks!

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Comment by geekosaur** [comment]
@mergify backport 3.14

**Comment by geekosaur** [comment]
Correct branch this time, whoops

**Pull request merged**
