### PR TITLE
Solver Hackage benchmark: Explicitly initialize cabal config files

### PR DESCRIPTION
**Pull request by grayjay**
hackage-benchmark uses the environment variable CABAL_CONFIG to specify the location of the config file. cabal started requiring the config file to exist in that case in 6942e7e8da2579ce35f4d1a5634f2bb287dfd147, so this commit runs "cabal user-config init".

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
A little surprising that a thing like `runCabalCmdWithEnv` wasn’t defined anywhere before.

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by grayjay** [comment]
Thanks for the reviews!

> A little surprising that a thing like runCabalCmdWithEnv wasn’t defined anywhere before.

The Hackage benchmark doesn't depend on Cabal or cabal-install as libraries.

**Comment by ulysses4ever** [comment]
Oh, my bad, I should have double-checked. Thank you for explaining!

**Pull request merged**
