### PR TITLE
Try to fix CI/Meta-checks failure (backport of #7659)

### PR DESCRIPTION
**Pull request by Mikolaj**
Manual backport of #7659, because it touches CI.

### CODE REVIEW

**Comment by jneira** [comment]
```
cabal.exe: Unknown target 'cabal-install:memory-usage-tests'.
The package cabal-install has no component 'memory-usage-tests'.
```

it seems something is missing inthis version

**Review by jneira — APPROVED** [review]
LGTM, once ci is happy

**Comment by jneira** [comment]
this and #7663 are being blocking themselves

**Comment by jneira** [comment]
This pr has only errors in windows due to the network issue, so i am gonna merge this and hopefully will be able to merge 7652 and get a green ci

**Comment by Mikolaj** [comment]
> ```
> cabal.exe: Unknown target 'cabal-install:memory-usage-tests'.
> The package cabal-install has no component 'memory-usage-tests'.
> ```
> 
> it seems something is missing inthis version

It's not version, it's branch. Branch 3.6 has one more bug in CI than master. Two PRs were enough to fix CI on master, but their backports (both strengthened) are not enough for 3.6.

**Comment by Mikolaj** [comment]
> this and #7663 are being blocking themselves

You are right. Thank you for merging. This is good order: first CI, then a real bug fix, after it passes corrected CI tests (except for the CI bugs that are not yet corrected).

**Comment by jneira** [comment]
> 
> 
> > ```
> > cabal.exe: Unknown target 'cabal-install:memory-usage-tests'.
> > The package cabal-install has no component 'memory-usage-tests'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it seems something is missing inthis version
> 
> It's not version, it's branch. Branch 3.6 has one more bug in CI than master. Two PRs were enough to fix CI on master, but their backports (both strengthened) are not enough for 3.6.

yeah with version i wanted to mean 3.6

**Pull request merged**
