### PR TITLE
Fix #7469: broken link to "prefix independence" in docs

### LINKED ISSUE #7469: Dead link in "data-files:" documentation.
The [Accessing data files from package code](https://cabal.readthedocs.io/en/latest/cabal-package.html#accessing-data-files-from-package-code) section of the user guide has a dead link to a non-existent section about "prefix independence":

>  (see prefix independence)

Googling for it, it seems that section [formerly belonged](https://downloads.haskell.org/~ghc/7.0.4/docs/html/Cabal/builders.html#prefix-independence) to the GHC User Guide—but it isn't present in the current GHC User Guide.

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #7469: broken link to "prefix independence" in docs.

I tested this by building the documentation with sphinx and checking that the link now works.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
A good catch.

**Comment by andreasabel** [comment]
Is any of the workflows building the docs?  Meaning, is it worthwhile to run them on this PR that only changes docs?  (Atm, they are blocked, but I (or any maintainer) could unblock them.)

**Review by danidiaz — APPROVED** [review]

**Comment by fgaz** [comment]
> Is any of the workflows building the docs?

I don't think so. It'd be great to have one though.

> is it worthwhile to run them on this PR that only changes docs?

They're relatively cheap and there's no way to skip them anyway, except in the rare case of author = new contributor (ci does not start automatically) and merger = admin (can merge without running ci)

**Comment by fgaz** [comment]
@Mergifyio backport 3.6

**Pull request merged**
