### PR TITLE
Allow network 2.7

### PR DESCRIPTION
**Pull request by felixonmars**
Builds and works fine here.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

### CODE REVIEW

**Comment by phadej** [comment]
We shouldn't forget to update bootstrap script.

How to make that obvious?

**Comment by felixonmars** [comment]
Hrm, what should I update as well? Sorry didn't get it...

**Comment by 23Skidoo** [comment]
Rebased and pushed a couple of additional minor changes.

**Comment by felixonmars** [comment]
Oops. Understand now.

**Comment by 23Skidoo** [comment]
Ugh, seems like HTTP *still* haven't been updated to support new `network`.

**Comment by 23Skidoo** [comment]
Blocked by https://github.com/haskell/HTTP/pull/117.

**Comment by 23Skidoo** [comment]
New HTTP is out, this should be good to go.

**Comment by 23Skidoo** [comment]
And now `hackage-security` needs to be updated...

**Comment by 23Skidoo** [comment]
@hvr Can you please bump the upper bound on `network` in `hackage-security` to `< 2.8`? I checked that it still compiles.

**Pull request merged**
