### PR TITLE
Add Travis job to build cabal with solver debug flags enabled.

### PR DESCRIPTION
**Pull request by grayjay**
The job should detect issues like #3967.

### CODE REVIEW

**Comment by ezyang** [comment]
Re sandbox, is this fundamentally a problem with how new-build works (i.e., would new-build work if we did it with HEAD?) Can we do something about the deps?

**Comment by grayjay** [comment]
The dependencies' setup scripts don't compile with Cabal HEAD, so we would have to force an older Cabal version.  new-build at HEAD succeeds, because the dependencies lack custom-setup stanzas, and new-build adds a default setup dependency on Cabal < 1.25 (cabal-install 1.24 only constrains it to 2.0).  I think that the best solution would be to use qualified constraints (#3502) in cabal.project, once they are available.

**Comment by ezyang** [comment]
Heh, oh the pains of being Cabal (maybe this behavior makes sense for other people, but it definitely doesn't make sense for us!)

**Comment by grayjay** [comment]
Yeah, Cabal definitely seems like a special case.

**Comment by phadej** [comment]
(FWIW, similar issue as compiling with `-fparsec-struct-diff`... cannot do that with 1.24 `new-build`)

**Comment by grayjay** [comment]
> (FWIW, similar issue as compiling with -fparsec-struct-diff... cannot do that with 1.24 new-build)

Maybe we should apply #3939 to 1.24.

**Comment by 23Skidoo** [comment]
> Maybe we should apply #3939 to 1.24.

Done: 7ba7489c673e87a9a22ab892ede3faacafba8f9a.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by grayjay** [comment]
Thanks!

**Pull request merged**
