### PR TITLE
Use in-tree Cabal library for `cabal-install` tests with custom setup.

### LINKED ISSUE #9681: testsuite: Allow testing Cabal library via cabal-install tests
At the moment the testsuite has two kinds of tests.

* `Setup.hs` tests, which are built against the in-tree Cabal library
* `cabal-install` tests, which use the in-tree `cabal-install` library but the boot compiler `Cabal` library.

This has caused much confusion with people writing `cabal-install` tests to attempt to test things they have changed in Cabal and wondering why the test never runs (see #9425)

We should be able to have more control in the testsuite about which version of the Cabal library is used for cabal-install tests.

* Use the boot compiler Cabal library (like we do now)
* Use the intree library, for testing changes in master.
* Use a specific Cabal library.

### PR DESCRIPTION
**Pull request by mpickering**
Allow using different Cabal library versions for `cabal-install` tests with custom setup.
    
    The idea here is to pass a `--package-db` flag to `cabal-install` which
    contains just `Cabal` and `Cabal-syntax` of the specific version. This
    allows `cabal-install` tests to use the in-tree `Cabal` version,
    something which you can easily run into and get very confused about when
    writing tests.
    
    There are a few options which can be passed to `cabal-tests` executable
    to control which Cabal library you will test against.
    
    1. --boot-cabal-lib specifies to use the Cabal library bundled with the
       test compiler, this is the default and existing behaviour of the
       testsuite.
    2. --intree-cabal-lib=<root_dir> specifies to use Cabal and Cabal-syntax
       from a specific directory, and `--test-tmp` indicates where to put
       the package database they are built with.
    3. --specific-cabal-lib=<VERSION> specifies to use a specific Cabal
       version from hackage (ie 3.10.2.0) and installs the package database
       into --test-tmp=<DIR>
    
    The end result is that changes in the Cabal library can be tested with
    cabal-install tests in the testsuite.
    
    There have been a number of confusing issues with people writing tests
    for changes in the Cabal library which never ran because of
    cabal-install tests always used the boot Cabal library (see #9425
    for one).
    
    Fixes #9681

### CODE REVIEW

**Comment by Mikolaj** [comment]
This implements https://github.com/haskell/cabal/issues/9681.

**Comment by Mikolaj** [comment]
BTW is this ready for review (I don't see the label)?

**Comment by mpickering** [comment]
I have been concentrating so far on getting CI working for the normal CI configurations, which it now does. 

There are some further things I want to work on:

* Adding some more configurations of testing different Cabal versions to CI (ie 9.8.1 with Cabal 3.10.1.0 rather than 3.11.0.0)
* Going through the testsuite and checking that tests which query GHC version actually mean to query the GHC version or instead mean to query the Cabal library version.

But I think it would be good to merge this firstly.

**Comment by Mikolaj** [comment]
I see. Great. That's normally signalled by setting the review_needed labels, which is why I ask. Let me set it instead.

**Comment by mpickering** [comment]
I think by default, no there isn't. Because if you run the tests locally then the same behaviour will happen as before (using the boot Cabal version rather than the in-tree one). Perhaps that is confusing in itself.

You have to explicitly pass a flag to `cabal-tests` in order to get it to use a different `Cabal` version than the one you already have. You are right that I still need to document this feature in the documentation as well. I will try to do that this afternoon.

**Comment by mpickering** [comment]
I added some documentation now so I think this first step is ready to merge.

**Comment by ulysses4ever** [comment]
> synopsis: Clarify the semantics of the -package-db flag

Is it possible to update the PR title and description in accordance with the actual changes?

**Comment by ulysses4ever** [comment]
> I added some documentation now so I think this first step is ready to merge after https://github.com/haskell/cabal/pull/9671 is merged.

This is #9671.

**Comment by mpickering** [comment]
I have rebased and this patch is ready to merge.

**Review by alt-romes — APPROVED** [review]
This is a great improvement to the testsuite. I've been very confused myself regarding changes to Cabal not working as intended in the testsuite because of this (and going mad...). Thanks!

**Review by ulysses4ever — APPROVED** [review]
Terrific, thanks!

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
I'm afraid there are conflicts to solve before this can auto-merge.

**Comment by Kleidukos** [comment]
@mergify backport 3.12

**Pull request merged**
