### PR TITLE
Update solver Hackage benchmark for v2-install.

### LINKED ISSUE #6417: Update solver Hackage benchmark for v2 commands
The Hackage benchmark currently measures the performance of the solver by running the "cabal install" command with --dry-run.  Now that cabal uses v2 commands by default, "install" only works for executables.  The benchmark needs to be updated to run a command that can invoke the solver for any package on Hackage.

install command: https://github.com/haskell/cabal/blob/b46d7820009784a878ae89b6810f750e2fb733d3/solver-benchmarks/HackageBenchmark.hs#L175

### PR DESCRIPTION
**Pull request by grayjay**
Fixes #6417.

Changes in this commit:

- Set the --lib flag so that the benchmark works for packages with libraries or
  executables.
- Set --ignore-project to prevent cabal projects from affecting the results.
- Handle four types of cabal errors that were introduced by v2-install.
- Use +nowrap to simplify parsing of cabal errors.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Nice, `--ignore-project` immediately in use!

**Comment by grayjay** [comment]
I noticed your PR when I first pushed my branch.  Thanks for adding the flag!

**Comment by phadej** [comment]
When I try 

```
cabal run hackage-benchmark -- --cabal1 /opt/cabal/3.0/bin/cabal --cabal2 $(cabal-plan list-bin cabal) --packages tree-diff --print-trials
```

I get

```
trial/summary    package   result1        result2              mean1       mean2     stddev1     stddev2     speedup
trial            tree-diff Unknown        Solution            0.014s      5.325s
```

I think that `Unknown` is a failure, how can I check why it's unknown?

**Comment by phadej** [comment]
Oh, I know, because `cabal-install-3.0` doens't yet know about `--ignore-project`; that makes sense.

**Comment by phadej** [comment]
Another thing:

On my system, the `~/.cabal/store` is huge, which affects the solver "significantly", in the sense that the relative speedups are considerably less.

Is there some mechanism to prevent store from affecting the benchmarks?

Could we create some temporary directory, and use `--storedir=tempstore`, then `cabal` won't spend much time reading it.

**Comment by phadej** [comment]
Something like

```diff
diff --git a/solver-benchmarks/HackageBenchmark.hs b/solver-benchmarks/HackageBenchmark.hs
index 145b49f93..df79d361e 100644
--- a/solver-benchmarks/HackageBenchmark.hs
+++ b/solver-benchmarks/HackageBenchmark.hs
@@ -176,7 +176,7 @@ runCabal timeoutSeconds cabal flags pkg = do
     let timeout = "timeout --foreground -sINT " ++ show timeoutSeconds
         cabalCmd =
             unwords $
-            [cabal, "install", "--ignore-project", "--lib", unPackageName pkg, "--dry-run", "-vsilent+nowrap"] ++ flags
+            [cabal, "--store-dir=/tmp/store", "v2-install", "--ignore-project", "--lib", unPackageName pkg, "--dry-run", "-vsilent+nowrap"] ++ flags
         cmd = (shell (timeout ++ " " ++ cabalCmd)) { std_err = CreatePipe }
 
     -- TODO: Read stdout and compare the install plans.
```

- We should create temporary directory using [`temporary`](https://hackage.haskell.org/package/temporary), rather then hard coding one
- I'd also prefer `v2-install`.

**Comment by phadej** [comment]
In fact, we probably should specify some non-existing environment, as `--lib` reads the `default` one.

```
diff --git a/solver-benchmarks/HackageBenchmark.hs b/solver-benchmarks/HackageBenchmark.hs
index 145b49f93..ed2bdd5f8 100644
--- a/solver-benchmarks/HackageBenchmark.hs
+++ b/solver-benchmarks/HackageBenchmark.hs
@@ -176,7 +176,7 @@ runCabal timeoutSeconds cabal flags pkg = do
     let timeout = "timeout --foreground -sINT " ++ show timeoutSeconds
         cabalCmd =
             unwords $
-            [cabal, "install", "--ignore-project", "--lib", unPackageName pkg, "--dry-run", "-vsilent+nowrap"] ++ flags
+            [cabal, "--store-dir=/tmp/store", "v2-install", "--package-env=hackage-benchmarks-dont-use", "--ignore-project", "--lib", unPackageName pkg, "--dry-run", "-vsilent+nowrap"] ++ flags
         cmd = (shell (timeout ++ " " ++ cabalCmd)) { std_err = CreatePipe }
 
     -- TODO: Read stdout and compare the install plans.
```

note: `--package-env`; I think it's ok to hardcode one which is unlikely to exist, as far as it's not the `default`.

Sorry for the comment spam.

**Comment by grayjay** [comment]
@phadej Thanks for the suggestions!  I didn't realize that so much time was spent reading the store, so I definitely want to skip that.  I just specified a directory that shouldn't exist, because cabal shouldn't need to create the store with --dry-run.  I also added v2- and --package-env and documented the flags.

**Comment by phadej** [comment]
Merged in https://github.com/haskell/cabal/pull/6447, thanks!

**Pull request closed without merging**
