### PR TITLE
Issue 5977

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Added test to #6136. It fails in `master`, doesn't fail with Sandy's patch.

I hope this doesn't regress https://github.com/haskell/cabal/pull/5459 fixes.

**Comment by typedrat** [comment]
Was gonna merge, but needs changelog note.

**Comment by typedrat** [comment]
Also, glad to be out of the hospital. :)

**Comment by phadej** [comment]
Will add changelog entry separately.

**Comment by 23Skidoo** [comment]
Cherry-picked to `3.0`.

**Pull request merged**
