### PR TITLE
Remove support for root-cmd, fixes #3353.

### LINKED ISSUE #3353: Drop root-cmd support
Current recommended Cabal usage is users should ~never install into the global package database. It's just not done. So can we drop `--root-cmd` support?

If people do think `root-cmd` is really useful, we'll have to plumb out nix-local-build's registration logic (which involves overwriting the IPID in some cases) so that when we reexecute ourselves that logic is picked up as well.

### PR DESCRIPTION
**Pull request by ezyang**
Just the last commit.

### CODE REVIEW

**Comment by ezyang** [comment]
As far as I can tell, Appveyor failure is spurious.

**Comment by 23Skidoo** [comment]
Restarted the build on AppVeyor. Also added everyone belonging to the `haskell/cabal` team on GitHub to my team on AppVeyor, so you should also be able to do that yourself in the future if you log in to AppVeyor with your GitHub account.

**Comment by ezyang** [comment]
Thanks, confirmed I have access now. (So everyone should be able to restart Travis and AppVeyor builds!)

**Comment by ezyang** [comment]
I wonder, should we actually leave a message saying the option was removed and what a user should do instead?

**Comment by 23Skidoo** [comment]
That'd be nice, I think. Maybe we should also print a warning when installing with `--global`.

**Comment by dcoutts** [comment]
It's not obvious to me that it needs to be removed, but I'm not going to argue that it's important to keep. It's also not implemented in the new-build code path so one fewer thing to do :-)

It's perhaps true that `cabal install --global` is just always a bad plan (and certainly when executed as a user via sudo). That said, `cabal configure --global [--prefix=...]` is not wrong, provided one goes on to do `cabal copy --dest-dir=$image` or something like that. Though there's perhaps better ways to do that too, e.g. just using `--prefix=`.

**Comment by ezyang** [comment]
The factor which pushed me to remove is that Nix-style registration would be a bit of a pain to implement in this regime. Essentially, we need to add a new major mode to cabal-install which knows how to do a Nix style registration (as opposed to just calling Setup install --only as root, as the code does right now.) If we're willing to wade through that complexity we don't need to remove this, but that is the proximal cause for this patch.

**Comment by 23Skidoo** [comment]
I wonder if this can be fixed by making the Cabal library itself aware of `--root-cmd` instead of re-executing `cabal install --only`.

**Comment by dcoutts** [comment]
@23Skidoo I think if a root cmd exists at all then it belongs in cabal-install not Cabal lib. By rights we ought to call Setup copy --destdir=  as the user and then as root only copy over the files and do the ghc-pkg register ourselves.

**Comment by dcoutts** [comment]
> The factor which pushed me to remove is that Nix-style registration would be a bit of a pain to implement in this regime.

@ezyang so this raises a rather interesting issue actually. The current new-build code does (more or less) assume that it can control all the layout etc, so it does not currently support custom layouts of the kind you can do with `Setup configure --user/--global --prefix=...`. When someone is trying to construct an install image for a target deployment system, how do they go about it? They probably want `/opt` or `/usr/local` (or relocatable) or something and not the user's store paths of course. How do we accommodate this?

**Comment by ezyang** [comment]
Well, the obvious and conservative choice is to make sure nix-local-build is as backwards compatible as possible, so that when we switch build to use new-build we don't wantonly break existing scripts.

**Comment by 23Skidoo** [comment]
So before this goes in I want to make sure that we have a plan for what to do about `--global`. Since we seem to agree that it's always a bad idea and this patch basically breaks `cabal install --global`, I think we should at least deprecate `cabal install --global` for 1.26.

We can probably also deprecate it in other places in `cabal-install`, but someone needs to look into the current use cases in more detail. Currently I do not have time for that.

When it comes to Setup scripts, I think that we'll have to support the current interface indefinitely.

**Comment by ezyang** [comment]
Looking at the option parsing code, it doesn't look like there are any facilities for deprecating flags.

**Comment by 23Skidoo** [comment]
Yes, flag deprecation is currently done in an ad hoc way.

**Comment by ezyang** [comment]
OK, new patchset has a warning when you pass `--root-cmd`, and also deprecates `--global`.

**Comment by 23Skidoo** [comment]
Great, let's merge then.

**Pull request closed without merging**
