### PR TITLE
don't create a cache directory when the compiler isn't configured

### LINKED ISSUE #8550: `cabal repl -b ...` generates `dist-newstyle`
**Describe the bug**

`cabal repl -b ...` populates the `dist-newstyle` directory, even though it shouldn't.

**To Reproduce**

```
$ mkdir some-dir && cd some-dir
$ ls
$ cabal v2-repl -b base
> :q
$ ls # should be empty, but isn't
$ tree
.
└── dist-newstyle
    └── cache
        └── compiler

```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
No `dist-newstyle` should be created 

**System information**
 - Arch Linux
 - `cabal` 3.8.1.0
 - `ghc` 8.10.7

### LINKED ISSUE #8589: cabal update creates dist-newstyle folder in $PWD
**Describe the bug**
When `cabal update` is run this creates a new folder `dist-newstyle` in PWD.
This seems wrong as the command shouldn't pollute my PWD and will also
fail if ran in a read-only directory 

**To Reproduce**
```
PS C:\Users\WDAGUtilityAccount\Desktop> mkdir temp

    Directory: C:\Users\WDAGUtilityAccount\Desktop

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        11/13/2022   9:51 PM                temp


PS C:\Users\WDAGUtilityAccount\Desktop> cd .\temp\
PS C:\Users\WDAGUtilityAccount\Desktop\temp> cabal v2-update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date.
The index-state is set to 2022-11-13T17:52:14Z.
PS C:\Users\WDAGUtilityAccount\Desktop\temp> ls


    Directory: C:\Users\WDAGUtilityAccount\Desktop\temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        11/13/2022   9:51 PM                dist-newstyle

```

**Expected behavior**
I don't expect this folder to be created. `cabal update` updates global state, so I don't understand the need for local storage.

**System information**
 - Operating system: Windows 11
 - `cabal` 3.8.1.0

### PR DESCRIPTION
**Pull request by gbaz**
Resolves #8550
Resolves #8589 

This is almost the same fix as #8358 but that didn't go quite far enough -- it deferred the check, but not the cache directory creation for the check.

Refs:
- #8550 
- #8589 
- #8358

### CODE REVIEW

**Comment by Mikolaj** [comment]
@mergify rebase

**Review by fendor — APPROVED** [review]
LGTM, no way to write a test for this I presume?

**Review by andreasabel — APPROVED** [review]

**Comment by Mikolaj** [comment]
@gbaz: would you mind adding this PR number to the changelog file for the previous PR?

**Comment by ulysses4ever** [comment]
They are talks about another 3.8 release. Should this one be backported to 3.8? I say: yes. Regardless of a release, backports are cheap, and this looks like a bugfix to me. Any thoughts?

**Comment by andreasabel** [comment]
@ulysses4ever wrote:
> There are talks about another 3.8 release.

Yes, but this hasn't been decided yet, and there is no designated individual who would drive it.
The question is when backports should happen.  I'd say they should happen only once it is decided that a release will happen.
I'd say a released branch (like `3.8.`) should be kept release-ready, so that one can quickly publish a patched version.  Release-readiness would mean that only blessed and tested changes are on the branch, and that CI is up and running.  The latter seems unfortunately not the case atm.  Maybe first the CI changes have to be backported to `3.8`.

**Comment by juhp** [comment]
Delete the branch?

**Pull request merged**
