### PR TITLE
docs: move Configuration chapter to cabal-install reference

### LINKED ISSUE #8177: RFC: Ditch Section 3 (Configuration and Installing Packages) of the manual
Currently, [the section called "Configuration and Installing Packages"][doc] consists of two subsections: 
 - 3.1. Configuration
 - 3.2. Building and installing packages

3.1 describes various configuration parameters of cabal CLI in a rather reference-like style, and, as such, I argue, belongs to section 6 (cabal-install Commands).

3.2 is basically empty: it holds "To be written" and than drops a rather problematic statement that you should use `cabal install` to install a package: without specifying whether you talk about local or external package this statement may or may not be fair. I think this text can be removed altogether.

[doc]: https://cabal.readthedocs.io/en/3.6/config-and-install.html

### PR DESCRIPTION
**Pull request by ulysses4ever**
Fix #8177.
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by andreasabel** [comment]
Rendering here: https://cabal--8182.org.readthedocs.build/en/8182/cabal-commands.html

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
I think it should be like you said now: the renamed file (`installing-packages.rst` → `config.rst`) has the history preserved. 

I did do 3 commits but I think it could be one commit as well. At least the overall diff shown on github reflects the modest change in the renamed file + some links fixed up + the index file changed a bit.

The new file `cabal-config-commands.rst` includes `config.rst` (the renamed one) and `cabal-commands.rst` (an old one) — via RST's `toctree`. As a result, the section will show just a toc, and the two parts (config and commands) will be on separate pages. It looks reasonable, I'd say.

**Comment by andreasabel** [comment]
> I did do 3 commits but I think it could be one commit as well.

I seem to remember that `git` only recognizes a combination of file _delete and add_ as _rename_ __only__ if there were no other changes to the file.  Maybe the "only" can be relaxed a bit (there seems to be heuristics that detect a move: see e.g. https://www.reddit.com/r/git/comments/n6feao/renaming_a_file_while_maintaining_commit_history/gx7a84j/?utm_source=reddit&utm_medium=web2x&context=3), but doing nothing else in a commit than renaming is a guaranteed to work.

**Review by andreasabel — APPROVED** [review]
Excellent, thank you!

**Comment by ulysses4ever** [comment]
@Kleidukos thanks for attending to the labeling! Are you sure about squashing though? I think @andreasabel suggested to have separate commits to make sure that git tracks rename+change accurately (doesn't see it as delete old + create new).

**Comment by Kleidukos** [comment]
You're right, I'm at fault here. I can correct this when I'm back home tomorrow.

**Comment by ulysses4ever** [comment]
No problem!

Mergify hasn't actually merged it to master, so let's see if changing the label would just works...

**Comment by ulysses4ever** [comment]
Okay, it seems to have done the trick:: all three commits safely landed on `master`. Thanks everyone!

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
