### PR TITLE
add Cabal 3.6.1.0 entry changelog

### PR DESCRIPTION
**Pull request by emilypi**
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by emilypi** [comment]
@mergifyio backport 3.6

**Review by Mikolaj — APPROVED** [review]
This looks good, but is it really 4 changelog items form a couple dozen commits?

**Comment by Mikolaj** [comment]
This is the list of commits that go in, right? 

https://github.com/haskell/cabal/compare/Cabal-v3.6.0.0...3.6

**Comment by emilypi** [comment]
Looks about right @Mikolaj

**Comment by Mikolaj** [comment]
#7561 doesn't have changelog, so that explains one case. Two other cases are the solver speedups: #7532 and #7516. And then a couple of docs tweaks were we don't expect changelogs. I think all are accounted for; we are fine.

**Comment by emilypi** [comment]
Ah the prepositive one and the solver ones. Okay, thanks @Mikolaj

**Comment by Mikolaj** [comment]
I abused my privilege, given that these are only changelogs so little bugs are not lethal.

**Pull request merged**
