### PR TITLE
WIP: Parsec parser

### PR DESCRIPTION
**Pull request by phadej**
Superseeds https://github.com/haskell/cabal/pull/2866

### CODE REVIEW

**Comment by phadej** [comment]
@dcoutts, this is cleaned up version. It's only introduces parsec stuff into build tree, could you comment if it looks ok. I have to do few changes to your experiment and otherwise:
- we need to build `alex` from source to get `-Werror` clean build
- changed to lexer to accept nbsp (have to do the same to separate tabs and spaces), should we warn on any tab, everywhere?
- `LexWarning` (will rename to `LexerWarning`) has arbitrary `String`, should change to `LexerWarningCode` or sum type of different warnings?
- `Field`, `Name`, `FieldLine` and `SectionArg` are parametrised by arbitrary `ann`. Parser fills it with `Position`. I made this to be able to write tests (`() <$` makes data position invariant). Also this makes possible to do `ghc-exactprint` like magic if needed.
- Added `IfElseBlock ` as third constructor to `Field`. It isn't parsed, but constructed as additional pass with `elaborate`. `elaborate` never fails, as later stage will fail anyway if the structure is invalid.
  - I'm not sure if this is necessary at the end, but it made comparison easier. I might remove this step ("fuse" it into later stage).

Also, should we keep `Distribution.ParseUtils` around, but deprecate it?

**Comment by phadej** [comment]
@BardurArantsson [asked about "remove old parser"](https://github.com/phadej/cabal/commit/fabb218281a94064e9537682d5a73768713d349b#commitcomment-13907486)

My plan is to get rid of `D.ParseUtils` eventually. Is it ok to do, without deprecation cycle? /cc @dcoutts ?

**Comment by BardurArantsson** [comment]
@phadej I was basically just wondering if we avoid the amount of duplication of "setup" code. I realize travis has some limitations and features around caching of downloaded files and timeouts and whatnot, so it's probably not practical. Oh, well. It was just a crazy dream :).

**Comment by dcoutts** [comment]
@phadej re deprecation, that depends on whether we can implement [the thing I mentioned at the hackathon](https://github.com/haskell/cabal/wiki/Hackathon2015) about "Enabling Cabal library refactoring" in time for the next release.

**Comment by BardurArantsson** [comment]
@dcoutts That looks like a really interesting idea. Are there any further hints/links as to how to actually proceed and implement it? (Aside from IRC. I usually don't do well on IRC.)

**Comment by dcoutts** [comment]
@BardurArantsson I've got an implementation of this idea now in the nix-local-build branch. We ought to be able to do a bit of cherry-picking or manual merging to get it into the master branch.

@phadej so where are we with this now? Is there more stuff you need to do or do you need more review/input?

**Comment by phadej** [comment]
@dcoutts I'm currently writing `Distribution.PackageDescription.Parsec` module and trying to use it where `D.P.Parse` is used.

Are there soft/hard deadlines when this should be ready? I'm unfortunately quite busy at my day job atm.

**Comment by 23Skidoo** [comment]
We want to do a new Cabal release this month, but it's probably better for the new parser to wait for the next release.

**Comment by phadej** [comment]
I plan to work on this during ZuriHac, rebase to current master was surprisingly non-painful.

**Comment by ezyang** [comment]
I'll close this PR for now; open a new one when you get more progress! :)

**Comment by ezyang** [comment]
@phadej, are we going to try to land this for 2.0?

**Pull request closed without merging**
