### PR TITLE
The Cabal part for fully gcc-like response files

### PR DESCRIPTION
**Pull request by randen**
* Cabal/Distribution/Simple/Haddock.hs
  * VERY IMPORTANT! this feature depends on a particular
    version of haddock, that includes the corresponding
    support for these style of response files.  However,
    we do not really know that version number!  So, this
    change here must be co-ordinated with the haddock project.
This is intended to fix haskell/cabal#3004. The other half is haskell/haddock#379.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Looks like you've forgotten an import:

```
Distribution/Simple/Haddock.hs:531:29:
    Not in scope: ‘foldl'’
    Perhaps you meant one of these:
      ‘foldl’ (imported from Prelude), ‘foldl1’ (imported from Prelude),
      ‘foldr’ (imported from Prelude)
```

>  However, we do not really know that version number! 

OK, I'll wait until the Haddock patch is merged. And I guess this should also go into 1.22?

**Comment by bgamari** [comment]
I believe this should appear in Haddock 2.17.

**Comment by randen** [comment]
@bgamari , should I update this pull request with >= 2.17 for the supporting Haddock version?

**Comment by bgamari** [comment]
@23Skidoo I have merged the Haddock portion locally. Could you merge this, bumping the haddock version bound appropriately?

**Comment by bgamari** [comment]
I have merged the Haddock portion to both Haddock's `v2.16` and `master` branches. While I don't expect to release haddock-2.16.2 myself, this means that the bound currently in the Cabal pull request is nevertheless accurate.

**Comment by ezyang** [comment]
Don't forget to merge this with #3005.

**Pull request merged**
