### PR TITLE
Enable reasonable default profiling options

### LINKED ISSUE #193: Allow more convenient use of ghc profiling options -auto and -auto-all
(Imported from [Trac #200](http://hackage.haskell.org/trac/hackage/ticket/200), reported by guest on 2007-12-18)

Add Setup.(l)hs options that: 1) tells ghc to make a profiling library; 2) tells ghc to make a profiling executable 3) pass on the (a) -auto or (b) -auto-all option 4) Let you do (1)-(2)-(3a) or (1)-(2)-(3b) with a single option, instead of three.

### PR DESCRIPTION
**Pull request by ttuegel**
This fixes #193 by adding reasonable default profiling options. The defaults are `-fprof-auto-exported` for libraries and `-fprof-auto-top` for executables. There seems to be [some agreement](http://haskell.1045720.n5.nabble.com/ghc-prof-options-and-libraries-on-Hackage-td5756706.html) in the community that the former, at least, is a reasonable setting.

/cc @ocharles @23Skidoo 
You were both involved in #2162, do you have thoughts on this?

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM.

**Comment by bgamari** [comment]
@ttuegel any progress on the version check?

**Comment by puffnfresh** [comment]
:+1:

**Comment by dcoutts** [comment]
So I've rebased and added @23Skidoo's suggestions.

I'm also making it configurable since I'm not totally sure it is always a good idea to add more cost centers, even if the runtime cost isn't so high. But it also makes it easier to use higher levels if we want.

Not quite finished yet, but it'd look like this, rather than just `--enable-profiling` / `--enable-library-profiling`, we have an optional arg, `--enable-profiling=...` where the value can be: default, none, exported-functions, toplevel-functions, all-functions. The default value for libs and exes is as in @ttuegel's existing patch.

**Comment by dcoutts** [comment]
Ok, now available as #2695. Builds on top of @ttuegel's patches here and makes it configurable by adding --[library-]profiling-detail={none,default,exported-functions,toplevel-functions,all-functions}. The default is as before (exported-functions for libs, toplevel-functions for exes)

**Comment by 23Skidoo** [comment]
Closing in favour of #2695.

**Pull request closed without merging**
