### PR TITLE
backport: Find build-tool installed programs before programs in path

### PR DESCRIPTION
**Pull request by alt-romes**
A backport of 443c8906581e4a985185a9a32de2e6c7cc63dde1 (#9762)

### CODE REVIEW

**Comment by alt-romes** [comment]
@gbaz here it is

**Comment by geekosaur** [comment]
https://github.com/haskell/cabal/actions/runs/8116319454/job/22186060894?pr=9767#step:5:542

**Comment by alt-romes** [comment]
@geekosaur any chance you could drive this to completion? I don’t know when I will be able to get back to this.

**Comment by geekosaur** [comment]
So somehow this breaks `cabal-testsuite/PackageTests/PkgConfigParse`, which can't find its replacement `pkg-config` any more. I'm lost as to why; the code seems correct to me.

**Comment by geekosaur** [comment]
Also, testing with a newer Cabal causes other test failures, which I presume are related to #9671 not being backported.

**Comment by gbaz** [comment]
After some investigation, I think we should close. if @andreasabel feels otherwise, please speak up. But there's something subtle going on that involves other changes as well, and I we could get more regressions if we port this back without figuring out exactly how everything interacts.

**Comment by andreasabel** [comment]
It is not a new regression, it is already there in 3.10.1, so it is not a blocker for 3.10.3.  However, it would be good to fix it in 3.10 eventually.  Maybe 3.10.4 then?

**Comment by gbaz** [comment]
Ah, so on HEAD the _default path itself_ is also extended by extra-lib-dirs, which means that the extra-lib-dirs appear _three_ times in the build -- twice from the inclusion of default-path before and after the explicit extra-lib-dirs and once in the middle. You might say "this is absurd" and it is, but this is sort of necessary because we need the Configure.hs file to work with v1-build as well, in which case we don't have any extensions to the default path.

So we need to backport whatever is necessary to fix this, as well...

**Comment by gbaz** [comment]
ok i think I figured it out. #8972 was never backported at all, and that contained the additional necessary fix I was looking for.

**Comment by gbaz** [comment]
oh dear and now the 9762 test fails again. it really is ping-pong.

**Comment by Mikolaj** [comment]
@alt-romes, @geekosaur: could you have a look (ideally, review) now that Gershom cracked the nut?

**Comment by alt-romes** [comment]
Thanks @gbaz, this looks good. Glad you spotted it.

**Comment by alt-romes** [comment]
I can't approve the pull request because I opened it

**Review by geekosaur — APPROVED** [review]
Strictly speaking, I probably shouldn't be reviewing because I worked on it.

**Review by gbaz — APPROVED** [review]

**Comment by Kleidukos** [comment]
Looks like mergify didn't pick this one up. I am merging.

**Pull request merged**
