### PR TITLE
Generate Paths_ module with qualified Data.List.last import

### PR DESCRIPTION
**Pull request by alexbiehl**
TODO ideally not rely on Prelude at all. 

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by jneira** [comment]
This might fix https://github.com/kowainik/policeman/issues/65?

**Comment by alexbiehl** [comment]
Yeah, exactly!

**Comment by Mikolaj** [comment]
Any idea what CI is complaining about?

**Comment by phadej** [comment]
Z.hs is autogenerated file.

**Comment by alexbiehl** [comment]
> Z.hs is autogenerated file.

Interesting! Any idea where the input file to the generator is? I can only find a few unrelated zinza files.

**Comment by alexbiehl** [comment]
Ah, templates/Paths_pkg.template.hs it is

**Comment by alexbiehl** [comment]
Closed in favour of https://github.com/haskell/cabal/pull/7650

**Pull request closed without merging**
