### PR TITLE
Put full package name and version in library names, fixes #2437.

### LINKED ISSUE #2437: Cabal-1.22 keyed filepaths truncate library name and hide version
With current Cabal-1.22, library paths are now of the form:

    /usr/lib64/ghc-7.10.0.20141222/direc_3m6Ew9I164U5MIkATLCdb8/libHSdirec_3m6Ew9I164U5MIkATLCdb8-ghc7.10.0.20141222.so

Is the 5 character truncation of package names (and no version) necessary?
It makes it pretty hard to see at a glance what package a particular directory or file belongs to and seems there is no easy way to work out the package version without referring to the package.conf file/dir.

If possible I would prefer a filepath format like:

    /usr/lib64/ghc-7.10.0.20141222/directory-1.2.1.1_3m6Ew9I164U5MIkATLCdb8/libHSdirectory-1.2.1.1_3m6Ew9I164U5MIkATLCdb8-ghc7.10.0.20141222.so

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM. I think this should also go into 1.22.

**Comment by ezyang** [comment]
Please don't merge yet, this breaks GHC's build.

**Comment by ezyang** [comment]
OK, ready to merge. This does need a GHC patch, and will break package-key supporting GHC builds (not user visible because we always use a local copy to bootstrap and the bug only applies to GHC's build system.)

**Comment by 23Skidoo** [comment]
@ezyang Merged, thanks. Is it OK to also merge this into the 1.22 branch?

**Comment by ezyang** [comment]
Yes please!

**Comment by 23Skidoo** [comment]
Done.

**Pull request merged**
