### PR TITLE
Fix construction of conflict sets during check for single instance restriction (maybe)

### LINKED ISSUE #2843: Conflict set is too small when solver enforces the single instance restriction
Here is a test case where the solver can't find a solution:
https://github.com/grayjay/cabal/commit/2b4d0274d35ee8859d41a3ebf96dc84c6f90c8f4

    targets: A, B
    constraints: 
      stanzas A test (unknown source)
      stanzas B test (unknown source)
      stanzas C test (unknown source)
      stanzas D test (unknown source)
      stanzas D test (unknown source)
      stanzas E test (unknown source)
    preferences: 
    strategy: PreferLatestForSelected
    [__0] trying: 0.A-1.0.0 (user goal)
    [__1] next goal: 0.D (dependency of 0.A-1.0.0)
    [__1] rejecting: 0.D-2.0.0 (conflict: 0.A => 0.D==1.0.0)
    [__1] trying: 0.D-1.0.0
    [__2] trying: 0.C-1.0.0 (dependency of 0.A-1.0.0)
    [__3] trying: 1.B-1.0.0 (user goal)
    [__4] next goal: 1.D (dependency of 1.B-1.0.0)
    [__4] rejecting: 1.D~>0.D-1.0.0 (conflict: 1.B => 1.D==2.0.0)
    [__4] trying: 1.D-2.0.0
    [__5] trying: 1.B-1.0.0:-flagA
    [__6] trying: 1.B-1.0.0:-flagB
    [__7] next goal: 1.C (dependency of 1.B-1.0.0:-flagB)
    [__7] rejecting: 1.C~>0.C-1.0.0 (dependencies not linked: cannot merge {*1.D-2.0.0} and {*0.D-1.0.0}; conflict set: 0.D, 1.C, 1.D)
    [__7] rejecting: 1.C-1.0.0 (multiple instances)
    [__5] fail (backjumping, conflict set: 0.C, 0.D, 1.C, 1.D)
    [__4] rejecting: 1.D-1.0.0 (multiple instances)
    [__2] fail (backjumping, conflict set: 0.C, 0.D, 1.B, 1.C, 1.D)
    [__0] fail (backjumping, conflict set: 0.A, 0.C, 0.D, 1.B, 1.C, 1.D)

I think that both conflict sets at level 7 should contain the variables `flagA` and `flagB`, because those flags are responsible for B's dependency on C.

### PR DESCRIPTION
**Pull request by edsko**
If correct, this fixes #2843; the first commit is basically @grayjay 's detailed test case (for which many thanks!). However, this needs review by @kosmikus ; have sent a detailed email.

### CODE REVIEW

**Comment by dcoutts** [comment]
So I thought I had an "in the wild" test case for this. My notes were in cabal-install.cabal:

    -- TODO: bug in linking, this fails, doesn't try text with the same flags as the main one
    custom-setup
      setup-depends: text == 1.2.0.6

That is, adding a custom setup section to cabal-install and claiming it has a dep on that version of text. The solver log I saw made me think it was a problem with linking. It would consider some version of text with one set of flags, fail (legitimately) but then never try text with the different set of flags or with tests disabled. So in retrospect my suspicion is that it's not a linking bug but this bug about not having the right conflict sets so that backtracking does not let it consider the choice that would have worked.

However I now cannot reproduce the solver failure. I may be able to with a much older revision. I may find time to try that. The stash I had mentions commit ad6eed5, so that may be worth trying.

**Comment by dcoutts** [comment]
@grayjay BTW, well done on identifying this bug and isolating the test case.

**Comment by grayjay** [comment]
Thanks!

**Comment by grayjay** [comment]
@dcoutts The bug that you described sounds like #2834.

**Comment by 23Skidoo** [comment]
If @kosmikus won't have time to review this before the 1.24 release, this PR (and the other solver patches assigned to the 1.24 milestone) will have to wait until the next point release of `cabal-install` from the 1.24 branch (either 1.24.0.1 or 1.24.1).

**Comment by kosmikus** [comment]
@23Skidoo What is my current deadline for the 1.24 release?

**Comment by 23Skidoo** [comment]
@kosmikus I plan to make the 1.24 release simultaneously with GHC 8 final, which will be released around the end of March/beginning of April (I think).

**Comment by kosmikus** [comment]
@23Skidoo Ok, then I'm still somewhat hopeful that I will make it.

**Comment by kosmikus** [comment]
So I think this is a step in the right direction. The original code is clearly wrong. The new construction does still look strange, though.

In an SIR-disabled choice, there are two variables that contribute to the conflict, which is reflected by the original code. They're called `qpn` and `qpn'` in this scenario. The `qpn` variable is the direct parent, the `qpn'` describes the link target.

Now we cannot just add the two variables on their own, but we have to add their goal reason chains as well (because changing something that lead up to the introduction of a goal may mean the goal never gets introduced, and therefore may allow progress). The current PR adds `qpn` with its goal reason chain, but drops `qpn'` completely. I think we should add `qpn'` with its goal reason chain as well.

Unfortunately, it's probably quite tricky (or even impossible) to come up with a test case where the omission of `qpn'` and its goal reason chain fails, as long as everything else about the solver works ok. The reason is that an SIR-disabled choice only ever appears if there's a sibling that corresponds to the linking choice. These two options are closely related, and will typically fail for similar reasons, with similar conflict sets.

**Comment by edsko** [comment]
This has been merged into and subsumed by #3357 .

**Pull request closed without merging**
