### PR TITLE
allow network 2.8

### LINKED ISSUE #5639: Relax cabal-install constraint, allow network-2.8.*
https://github.com/haskell/cabal/blob/738a51148217885f797ea56af773b945469286b9/cabal-install/cabal-install.cabal.pp#L37

Can `cabal-install-2.4.0.0` be revised to allow building against `network-2.8.*`?

See also the `network` changelog: http://hackage.haskell.org/package/network-2.8.0.0/changelog

### PR DESCRIPTION
**Pull request by juhp**
fixes #5639

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [?] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by juhp** [comment]
It would be nice to have this for 2.4 branch too.

**Comment by 23Skidoo** [comment]
Merged, thanks! Also cherry-picked into `2.4`.

**Comment by juhp** [comment]
Thanks, @23Skidoo!
It would be nice to have a Hackage revision too. :-)

**Comment by hvr** [comment]
@juhp btw, I'm missing a justification for why this is considered a safe version relaxation; did you actually verify the changelog for what the breaking change was?

**Comment by juhp** [comment]
@hvr, to be honest I didn't, but looking over [it](https://hackage.haskell.org/package/network-2.8.0.0/changelog), it looks okay to me.
Maybe good to document such a process, if not already?

**Comment by 23Skidoo** [comment]
I did look at the changelog, it's nothing big.

**Pull request merged**
