### PR TITLE
Point out `validate.sh` more prominently in `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by 9999years**
The `CONTRIBUTING.md` makes it sound really hard to run tests locally, but actually `validate.sh` works fine!

`validate.sh` still needs work (see the list in #10320) for example, but it's a great starting point.

### CODE REVIEW

**Comment by ffaf1** [comment]
Pointing that `validate.sh` runs everything locally is fine, but it is far from a `tl;dr`, isn't it?

Adding a sentence or a paragraph feels better. Something like “You can also run all tests locally using `validate.sh`”.

**Review by ulysses4ever — APPROVED** [review]
to Francesco's point: I think it's good enough. But if someone feels strong about it, they should feel free to "request changes".

**Comment by geekosaur** [comment]
It might be worth pointing out that, especially with the `njobs` change, running validate locally can have a pretty significant impact on a personal machine. (Admittedly, not as much so as building ghc….)

**Comment by ffaf1** [comment]
Yes, my suggestion is to:

- add after “Running tests locally.”: “./validate.sh` runs all the test suites.”
- add “There are two ways to run tests, using GitHub Actions and running them locally” as first paragraph of “Running tests” heading.

This way we should be clear and immediate enough for all use cases.

**Comment by 9999years** [comment]
I've addressed comments & made the headings uniform. (Use the rich diff to see changes.)

**Review by ffaf1 — APPROVED** [review]
very good

**Pull request merged**
