### PR TITLE
Wordier explanation of the "active-repositories:" configuration field.

### PR DESCRIPTION
**Pull request by danidiaz**
A wordier version of the documentation for the `active-repositories:` field, reflecting the extra details given in #7450. Hopefully the rewording is accurate.

### CODE REVIEW

**Review by phadej — APPROVED** [review]

**Review by jneira — APPROVED** [review]
Looks great! thanks so much for improving docs

**Comment by jneira** [comment]
This closes #7450

**Comment by fgaz** [comment]
@Mergifyio backport 3.6

**Comment by fgaz** [comment]
@Mergifyio backport 3.4

**Review by emilypi — APPROVED** [review]

**Comment by jneira** [comment]
miss the `merge me` label to make mergify merge auto pr

**Comment by emilypi** [comment]
@jneira how do you set that up? I'd like to get that for us :)

**Pull request merged**
