### PR TITLE
WIP: Separate GenericPackageDescription from PackageDescription

### PR DESCRIPTION
**Pull request by Ericson2314**
Now, neither contains the other, and their common fields are contained in 'CommonPackageDependencies'.

I'll probably first merge a change adding lenses per components, so some stuff can be made `{Generic,}PackageDescription`-polymorphic in advance. (The lenses would of course preserve the cond tree structure.)

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

CC @kmicklas

### CODE REVIEW

**Comment by Ericson2314** [comment]
BTW, how do I get pems to cancel AppVeyor build?

**Comment by 23Skidoo** [comment]
AppVeyor has underdeveloped account structure that doesn't map to GitHub orgs, but I remember that @hvr managed to do it by logging in to AppVeyor using my user name somehow.

**Comment by ulysses4ever** [comment]
@Ericson2314 any thoughts on this PR of yours? Do you still plan to work on it? If not, do you think it'd be worthwhile for someone else to finish it? Or maybe it's not relevant at all anymore, and we should just close?

**Comment by Ericson2314** [comment]
@ulysses4ever it has been a long time, but yes I think it might be worthwhile for someone else to complete this. Unless my memory is faulty or something changes over the past few years, our data structures currently do a very bad job of making illegal states unrepresentable.

**Comment by Mikolaj** [comment]
This is badly bit-rotted. Let me close, but mark as worth reviving (probably in a new PR, given the state of the patch?).

**Comment by Ericson2314** [comment]
Sounds good.

**Pull request closed without merging**
