### PR TITLE
Fix construction of conflict sets during link validation

### PR DESCRIPTION
**Pull request by edsko**
**NOTE**: This commit contains four commits, not two; the first two are #3221.

In #2834 @grayjay points out another conflict set construction bug. Actually, this is almost the same bug that was present in the check for the single instance restriction: we were forgetting to call `simplifyVar` on some variables before adding them to the conflict set.

This PR first adds @grayjay 's test case (another excellent test, thank you very much! :) ) . The next commit just adds some comments to the test explaining what is going on. Commit number 3 just moves some code out of the `Modular.Dependency` module into two separate `Var` and `ConflictSet` modules; it does not make any actual changes to the semantics. The actual fix is in the final commit, which makes `ConflictSet` abstract and makes sure that whenever we add a variable to a `ConflictSet`, or check whether a variable is a member of a conflict set, that we call `simplifyVar` first. This fixes this particular test case and also makes me feel a lot less anxious about other such bugs still being present.

Pinging @kosmikus and @dcoutts .

### CODE REVIEW

**Comment by edsko** [comment]
Pushed commit to try to fix build error on 7.4.

**Comment by edsko** [comment]
New travis failure seems to be transient?

**Comment by 23Skidoo** [comment]
Restarted the build.

**Comment by 23Skidoo** [comment]
The remaining failure is due to `-Werror`:

```
Distribution/Client/Dependency/Modular/ConflictSet.hs:65:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord qpn
    • In the type signature for:
           filter :: Ord qpn =>
                     (Var qpn -> Bool) -> ConflictSet qpn -> ConflictSet qpn
```

**Comment by edsko** [comment]
Oh FFS :anguished: Final attempt :-)

**Comment by dcoutts** [comment]
I've merged these patches to the nix-local-build branch (along with all the other recent solver PRs).

**Comment by edsko** [comment]
This has been merged into and subsumed by #3357 .

**Pull request closed without merging**
