### PR TITLE
Refactor buildComponent and replComponent

### PR DESCRIPTION
**Pull request by sheaf**
This is a pure refactor that reduces code duplication, with the exception that it also fixes a bug in that `preprocessExtras` was not being called for foreign libraries in both functions.

### CODE REVIEW

**Review by andreabedini — APPROVED** [review]
This looks like an improvement but TBH I still find this code a bit hard to read :-/
I particularly do not like those invalid cases arising with `CTest`/`CBench`.

**Comment by andreabedini** [comment]
While I am ok with this going in as it is (as said, it is an improvement!) I am quite unhappy with the general pattern we seem to have through the codebase of pushing case-splits "down" the data flow. IMHO they should be pushed up instead.

**Review by Mikolaj — APPROVED** [review]
Thank you.

**Comment by Mikolaj** [comment]
Nobody commented in 2 weeks, so let me set the label for @sheaf not to delay the merge even more.

**Pull request merged**
