### PR TITLE
Update multiple remote-repos in parallel

### LINKED ISSUE #2227: 'cabal update': download index.tar.gz files in parallel
If the user has specified more than one `remote-repo`, it'd be nice if 'cabal update' could download the index files in parallel. Same for generating cache files.

### PR DESCRIPTION
**Pull request by abhinav**
Closes #2227

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM. Since there usually are not so many remote-repos (at most 2 in 99% cases, I think), having an option to control the number of threads is not so important. I'd also change the message from

```
Downloading the latest package list from $REPO0
Downloading the latest package list from $REPO1
...
Downloading the latest package list from $REPON
```

To

```
Downloading the latest package lists from $REPO0, $REPO1, ... $REPON
```

**Comment by abhinav** [comment]
Comma separated list looks weird with 79 character wrapping:

    Downloading the latest package lists from: stackage-nightly-2015-03-27,
    stackage-lts-1.14, hackage.haskell.org

Changed to print a list if the number of remote repos is greater than 1.

Single `remote-repo`:

    Downloading the latest package list from stackage-nightly-2015-03-27

Multiple `remote-repo`s:

    Downloading the latest package lists from:
    - stackage-nightly-2015-03-27
    - stackage-lts-1.14
    - hackage.haskell.org

**Comment by 23Skidoo** [comment]
> Comma separated list looks weird with 79 character wrapping:

Looks OK to me, but your solution is better.

**Comment by 23Skidoo** [comment]
OK, merging. Thanks for your contribution!

**Pull request merged**
