### PR TITLE
Backpack documentation in the user manual.

### LINKED ISSUE #4761: Backpack is undocumented
A user on Reddit [brought to my attention](https://www.reddit.com/r/haskell/comments/6z2gja/whats_new_in_cabalcabalinstall_20_improved/dmw6qzq/) that searching for "Backpack" in the user's guide [returns zero results](http://cabal.readthedocs.io/en/latest/search.html?q=backpack&check_keywords=yes&area=default#). It'd be nice if there was a Backpack section in the user's guide like we have for Nix integration, right now I have to refer people to posts on @ezyang's blog.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#7306 Backpack documentation in the user manual.**

Fixes #4761

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by cartazio** [comment]
Yay!   Is there a good way to look at a preview render?  
thus is great!

**Comment by ezyang** [comment]
I don't know! It's been a while. It looks like making this a stack diff also broke CI, so I might need to reopen this PR differently.

**Review by emilypi — DISMISSED** [review]
LGTM, thanks @ezyang. What's this stack diff you're talking about?

**Comment by emilypi** [comment]
It looks like there's a bad hyperlink in here. Building locally, i get the following: 

```
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/emilypi/haskell/cabal/.python-sphinx-virtualenv/bin/python3.7 -m pip install --upgrade pip' command.
Running Sphinx v3.1.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 6 changed, 0 removed
reading sources... [100%] setup-commands                                                                                                                                                                   
/Users/emilypi/haskell/cabal/doc/cabal-package.rst:2139: WARNING: invalid pair index entry '; package.cabal field'
/Users/emilypi/haskell/cabal/doc/cabal-project.rst:2: WARNING: Duplicate ID: "cfg-field-type".
/Users/emilypi/haskell/cabal/doc/file-format-changelog.rst:161: WARNING: Unknown target name: "backpack".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] setup-commands                                                                                                                                                                    
generating indices...  genindex cabal-projectindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 3 warnings.
```

The first warning is seen on `master`, but the rest are related to this PR. I sense a conflict.

**Comment by cartazio** [comment]
this alone is a great start! (thx for the render)

some questions: which parts of the linked ghc docs are "stable specs" of how things do or dont work across the matrix of ghc and cabal versions? (eg, whats the min version of cabal/ghc needed for various features we do have, and for various limitations/bugs to be avoided?)

**Comment by ezyang** [comment]
@emilypi I fixed them! Thanks for reminding me to run the local build.

@cartazio Fortunately, Backpack feature development has very much been "no more new features after I finished my PhD". So basically any version of GHC after Backpack was put in is good. There is a Cabal parser that was fixed later but it's already prominently called out in the documentation. Not sure if this is satisfying to you!

**Comment by emilypi** [comment]
@ezyang did you mean to close this?

**Comment by ezyang** [comment]
yeah, due to technical difficulties I can only land ghstack PRs by closing, not "merging"

**Comment by fgaz** [comment]
Can we delete the `gh/ezyang/1` branches?

**Comment by ezyang** [comment]
yeah (and I recently fixed ghstack to automatically delete the branches)

**Pull request closed without merging**
