### PR TITLE
Fix typo in import feature documentation

### LINKED ISSUE #8423: import stackage in cabal.project seems not to work in cabal 3.8.1
**Describe the bug**
I tried to add 
```
packages: .
import https://www.stackage.org/lts-19.2/cabal.config
```
to my cabal. profile file - per doc 3.8.  point 4.2.2
I copied the command and pasted. 
get error message: 

```
Error: cabal: Error parsing project file
/home/frank/Workspace11/u2giscore/uniform-field/cabal.project:2:
Parse of field '
unexpected ":"
expecting section parameter, "{", field or section name or end of file'
failed.
```

if I put `"` around the address, it runs past this point. 

1. please update the manual to include the quotes if they are necessary!

Now a second error occurs with the next line: 

```
packages: .
import https://www.stackage.org/lts-19.2/cabal.config

    ../../uBase/uniformBase

```

which builds fine without the `import ...`. 
The error is 
```
```
cabal v2-build
Error: cabal: Error parsing project file
/xxx/cabal.project:3:
Parse of field '
unexpected operator "../../"
expecting field or section name' failed.

frank@santafe:~/xxx$ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 
```

```
 
**System information**
 - Operating system : debian bullseye updated today
 - `cabal`, `ghc` versions 3.8.1.0 - ghc 9.0.2

**Additional context**

### PR DESCRIPTION
**Pull request by andreabedini**
Fixes #8423

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thank you!

**Review by Kleidukos — APPROVED** [review]

**Comment by Mikolaj** [comment]
Probably some random breakage in CI. Let me rebase.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by fgaz** [comment]
@Mergifyio backport 3.8

**Pull request merged**
