### PR TITLE
Clean up FIXMEs

### PR DESCRIPTION
**Pull request by BardurArantsson**
Some FIXMEs are downgraded to simple comments, some outright removed --
especially very old and non-severe-looking.

(All by my judgment of severity.)

---

This doesn't "handle" all the FIXMEs; this is mostly ones that are easy to judge the severity of. I might do a second round to eliminate all the remaining ones; perhaps creating real GitHub issues for them.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@dcoutts, what do you think?

**Comment by BardurArantsson** [comment]
Btw, I'd be very happy to file issues (if deemed necessary) for any of the "cleaned up" FIXMEs. I just don't think FIXMEs in source code are a viable issue tracking system. I don't think GitHub's is either (for a project of any substantial size), but that's a different matter :).

**Comment by dcoutts** [comment]
Yeah, I'm torn. There's several things there that it would be nice to clean up and not forget. But I totally accept the point that FIXMEs in the code are not all that great for things that are actually important.

**Comment by BardurArantsson** [comment]
Believe me, I understand the feeling. For my part it's very mild OCD that drives me to *eliminate* FIXMEs and TODOs and try to put them into some sort of system. I'm very happy with FIXMEs and/or TODOs in branches, but they should *never* be merged!

My reasoning is that if there's a "FIXME"[1] that hasn't actually been addressed in a long time (either via bug report or someone fixing it) then it's probably not as severe as originally imagined. In my experience, it's *usually* a case of not applying the YAGNI principle. (I'm aware that YAGNI *can* be abused for short-time gain, but "time elapsed" is another piece of evidence for applicability of the principle in this case.)

If you have qualms about any particular one of these, then I'd very much appreciate if you could point them out and we could try to convert them to GH issues.

[1] Is see "FIXME" as pretty aggressive and high-priority, usually. My perception could very well be atypical. ("TODO" might be a reasonable alternative. "XXX" is the lowest tier for me.)

**Comment by BardurArantsson** [comment]
Addendum: Even if you think *everything* needs to be converted to an issue, I'd be happy to do that. Let's *use* the system that exists (GH Issues) instead of hoping that someone stumbles upon the comments and happens to fix the issue. (Which... looking at the timestamps of some of these lines... is never going to happen.)

**Comment by BardurArantsson** [comment]
Ping?

**Comment by lspitzner** [comment]
What are the semantics of FIXME/TODO/XXX ? Do they mean

1) "stuff will break (crash) under certain uncommon circumstances"? or
2) "it does not handle case x properly, leading to soft failure with proper message to the user"? or
3) in the range of "the output of this operation might contain long lines, some better printing method might be preferable" or "this function is kinda inefficient, but it probably does not matter (for now) because.."?

I'd say instances of 1) should not be merged, while i'd be ok with 2) existing in the codebase. 3) may only deserve a simple comment, but there may be cases where a slight highlight (for a reminder like "if this function ever gets called with n>100, we need a better implementation") does make sense.

Turning 2) and 3) into issues does not make sense to me, as it seems to conflict with the "we delete inactive issues" policy.

Before any cleanup, the semantics should be defined by an entry in the development wiki, imo. (For me, too, "FIXME" looks like high priority and TODO below that.)

**Comment by BardurArantsson** [comment]
@lspitzner : I think you're right to point out that the semantics of these things should be "formalized", but all of the stuff I've cleaned up here is stuff that looks to me like it's basically "nice to have". (At least that was what my judgement was at the time, I think. I'll go through again just to check.) 

That said, I will probably just merge this. (After the second round of self-review, if you'd like to review, I'd be very happy to let this lie around for a few days to give you a chance to do so.)

To me, FIXME means "this *MUST* be fixed before merge" or "someone needs to argue damn convincingly that it should be let through and must follow up with a commit actually doing the FIXME within a reasonable timeframe". (It's pretty much equal to your your 1.) This seems to be a pretty universal interpretation IME and has been the norm for all projects that I've worked on. Personally, I use FIXME in my own pre-merge/PR code just to make sure I can quickly note deficiencies in implementation and have an easy-to-grep-for string for my branch-local "todo-list". I'm not sure it's possible, but I'd actually prefer if it became impossible to merge anything with "FIXME" in it without extra confirmation, but that may be too severe.

TODO is more like your 2, but to me, this means that it *should* have an issue if it's actually actionable and feasible to do anything about it. *However*, the issue should be filed *first* and then the TODO should refer to that issue. When an issue is closed, corresponding TODOs should either be addressed (if it's an actual fix) or removed. This may leave dangling TODOs if people forget this step, but it's an easy exercise to go through TODOs once in a while to see if the issues are still open or not. TODOs without issues files (and referenced!) should be removed outright. Basically the function of TODOs in this scheme is to function as two-way pointers between the issue tracker and the code in such a way that the pointers actually move along with the code (contrary to line number references, say).

I've never used XXX, and frankly I think it's unnecessary[1]. If there's something you'd like to note which is non-severe, just have it in a regular comment next to the function/whatever. Either it's severe enough to track as a TODO+issue (in which case: use that), or it's not severe enough to "track" (in which case: just use a comment in case someone who happens by the code during maintenance and is in a position to do something about it).

[1] I do use XXX for cabal development, but that's just because there's so much FIXME floating around in the existing code that I cannot use FIXME for my branch-local todo-list as described above.

@23Skidoo : Where do you think would be the appropriate place to start such a "formalization" such that others can see it? The mailing list?

**Comment by 23Skidoo** [comment]
@BardurArantsson 
> Where do you think would be the appropriate place to start such a "formalization" such that others can see it?

Yes, or maybe just add a "coding standard" section to `HACKING.md` and create a PR, we can discuss it there.

> Btw, I'd be very happy to file issues (if deemed necessary) for any of the "cleaned up" FIXMEs.

I'm a bit reluctant to spamming the issue tracker with old FIXMEs. Maybe we can archive them on the wiki?

**Comment by BardurArantsson** [comment]
@23Skidoo Re: HACKING.md: Will do, thanks for the suggestion.

I think there's about as much likelihood of anyone seeing them there as in the git history (i.e. "slim to none"), but I guess it can't hurt... I'll go through this again and re-triage to see if there's any of the stuff I've removed here that's worth preserving.

**Comment by lspitzner** [comment]
@BardurArantsson I've had a look at the diff and your changes seem completely reasonable.

**Comment by BardurArantsson** [comment]
@lspitzner Thank you. Based on that, I think I'll just merge this in a couple of days unless there are active objections.

I'll follow up with a PR for HACKING.md for discussion on general guidelines wrt. FIXME/TODO/etc.

**Comment by ezyang** [comment]
Let me offer a different view of a FIXME/TODO: these represent things that should be done the next time the code is modified/refactored. So, it's for some sort of issue which is too small to merit getting a full issue (especially when your issue tracker is overstuffed and not being managed in any good way), but should not be forgotten.

Good Samaritans, when they see TODOs in code they're interacting with, refactor the code to fix the TODO before making their change.

**Comment by BardurArantsson** [comment]
@ezyang I like using TODOs for that, but we should decide on *either* TODO or FIXME, not just use one of them randomly. However, I've seen *far* too many TODO issues in the Cabal-install code which would actually be large undertakings once you decide to probe into what would be requried. (I've only done a small non-scientific random sampling, but it was enough to convince me that we need some sort of guideline to avoid the current mess[1].)

[1] I realize that this is a mess that's organically grown, probably from since even before there was a bug tracker at all, etc. I don't think it's anybody's *fault* per se -- it's the sort of thing that just happens over time in a sort of [Broken Windiows](https://en.wikipedia.org/wiki/Broken_windows_theory) way.

I'll merge this a little later and get started on a HACKING.md pull request, so we can at least start having a proper discussion and hopefully end up with written-down guidelines. (And the *will* only be **guidelines** which people can point to in discussion on PRs and such.)

**Pull request merged**
