### PR TITLE
Fix deprecation warnings from containers

### PR DESCRIPTION
**Pull request by erikd**
This also bumps the lower bound on containers to `>= 0.5` which
should be fine since that was released in May 2012. This change
should work therefore fine with the last 4 major GHC releases.

### CODE REVIEW

**Comment by phadej** [comment]
We do test `Cabal` agains 7.4.2. ping @ezyang

**Comment by erikd** [comment]
Yeah, but the last 4 releases is 7.6, 7.8, 7.10 and 8.0. Also, 8.2 is just around the corner.

**Comment by ezyang** [comment]
We've had this discussion before; the current stance is, if it's not too much work to keep 7.4 support going, let's keep it. E.g., if 7.4 support is making our life hard, drop it, but otherwise, don't.

I don't know how compelling this particular patch is; I'll let you guys make a judgment on it.

**Comment by erikd** [comment]
My reason for submitting this patch is that this deprecation warning was coming up when building GHC from git with `-Werror`. I have also submitted patches for [hoopl](https://github.com/haskell/hoopl/pull/36) and [ghc itself](https://phabricator.haskell.org/D3036).

**Comment by 23Skidoo** [comment]
How hard would it be to preserve GHC 7.4 support? If we just need a new `.Compat` module, let's add one.

**Comment by erikd** [comment]
I'll see if I can come up with a .Compat module.

**Comment by erikd** [comment]
Just to make sure I get this right, we create a new module `Distribution.Compat.Map` that compiles with both containers `0.4.*` and `0.5.*` and then use that instead of `Data.Map` everywhere else or only where needed?

**Comment by ezyang** [comment]
I don't think it has to be that major. In this case, we just need un-deprecated versions of the functions we can access, right?

**Comment by erikd** [comment]
This issue is a little more subtle than just a name change. The code in cabal before this PR uses `insertWith'` from `Data.Map`, with the prime indicating that this version is more strict that the unprimed version. My initial change, which was only compatible with `containers >= 0.5`  was to switch to `Data.Map.Strict`. However `containers < 0.5` doesn't have `Data.Map.Strict`.

I therefore provide `Distribution.Compat.Map` which chooses `Data.Map.Strict` when `containers >= 0.5` is available. For `containers < 0.5`  we use`Data.Map` and export the strict version `insertWith'` in place of the less strict one.

Still not sure this is the best solution but at least Travis is happy.

**Comment by erikd** [comment]
@ezyang Happy with this solution?

**Comment by ezyang** [comment]
Shouldn't Strict be in the module name, in this case? (containers strict and lazy maps have historically been the same underlying type; it was just a matter of swapping names out.)

**Comment by erikd** [comment]
@ezyang You mean `s/Distribution.Compat.Map/Distribution.Compat.Map.Strict/` ?

**Comment by ezyang** [comment]
Yep!  (If you don't mind!)

**Comment by erikd** [comment]
Done! Hope travis agrees :).

**Comment by ezyang** [comment]
Good. One thing I'm a little afraid of is if someone imports this expecting all the functions to be strict but actually only insertWith is strict, and that leads to a leak, but I guess we can cross that bridge when we get there.

**Comment by erikd** [comment]
I looked at the possibility of importing this instead of `Data.Map` across the whole project, but that would have touched about 50% of the files.

**Comment by ezyang** [comment]
Yeah, not worth it, honestly.

**Pull request merged**
