### PR TITLE
Update the list of known GHC extensions to match GHC 9.2

### LINKED ISSUE #8168: Update the list of GHC extension for GHC 9.2 and 9.4
This should not be to hard, based on GHC release notes or user guide, and should go in file Cabal-syntax/src/Language/Haskell/Extension.hs. I don't know if any extensions from 9.2 are missing, or perhaps even 9.0, so worth checking all.

### PR DESCRIPTION
**Pull request by ffaf1**
Closes #8168 

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — COMMENTED** [review]
Thank you! I wonder if we need a little changelog file here. Just "update the list of known GHC extensions to match GHC 9.2" for both PRs (changelogs can refer to multiple PRs and issues).

**Review by jneira — APPROVED** [review]
lgtm, thanks for the changelog

**Comment by Mikolaj** [comment]
@ffaf1: let us know when ready for review (given that the PR was not marked by github as draft, so it's not obvious when the transition happens).

**Comment by ffaf1** [comment]
Sorry, did not know about drafts.

It is ready for review!

Il 30 maggio 2022 alle 00:58 Mikolaj Konarski ha scritto:

**Comment by Mikolaj** [comment]
BTW, what is your take on the remarks about instability of links and the proposal to link to the list of extensions instead of individual ones? These were in the other PR or the original issue.

**Comment by ffaf1** [comment]
I have [a patch](https://github.com/ffaf1/cabal/commit/68810c7b5dbbe2b7f894647ece61eddfd2ba3a2c) ready for that. I don’t think I can make a pull request until this is merged though.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
Oh, great. This PR LGTM. Please feel free to to set "merge_me" label so that it's rebased and --no-ff merged by mergifyIO.

**Comment by Mikolaj** [comment]
@mergifyIO backport 3.8

**Comment by Mikolaj** [comment]
@ffaf1: how much effort, do you think, would be required to update the test https://github.com/haskell/cabal/blob/master/Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs ?

**Pull request merged**
