### PR TITLE
haiku: add as known platform

### PR DESCRIPTION
**Pull request by jessicah**
---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Comment by fgaz** [comment]
The failure is expected, that test is supposed to fail with this kind of patch. To fix it you have to update the mismatched hash

**Comment by jessicah** [comment]
@fgaz ah thanks, have updated my commit to include the hash change, just couldn't find any documentation/comments on what it was, or how it should be generated to compare against.

**Comment by fgaz** [comment]
@Kleidukos this is a breaking change, we can't backport

**Comment by Kleidukos** [comment]
Ah, I had not realised.

**Comment by andreabedini** [comment]
@fgaz thanks for pointing this out. I was confused myself and had to double-check: adding entities is not a breaking change but changing data types (even by simply adding a constructor) is.

**Comment by jessicah** [comment]
Oops, I didn't see the merge conflict, updated :)

**Comment by jessicah** [comment]
@fgaz looks good to merge? :)

**Review by andreabedini — APPROVED** [review]
:+1:

**Review by geekosaur — APPROVED** [review]
Looks good to me

**Comment by ulysses4ever** [comment]
@andreabedini i changed the label to squash instead of just merge, as the second commit doesn't make sense separately.

**Comment by andreabedini** [comment]
Thank you @ulysses4ever

**Comment by jessicah** [comment]
Says it failed, but I can't see any actual failure?

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
@jessicah let me try to rebase and restart...

**Comment by jessicah** [comment]
Rebased and squashed the change log commit, hopefully it passes again now...

**Comment by jessicah** [comment]
Do you know approximately when 3.12 will be released? Projects run `cabal check` in CI, blocking upstreaming of all my other PRs, and also needing to get into hackage-server as well?

**Comment by jessicah** [comment]
@fgaz would it be possible to backport to 3.10/3.11 by using `OtherOS "haiku"`? It looks like it wouldn't be too hard to make the change work, just an extra check in `Check.hs` to not fail on `OtherOS "haiku"` for the `unknownOSs` list comprehension. Making hackage work would be extremely simple too... map `OtherOS "haiku"` to the same constant as `OS::Haiku` when can use Cabal 3.12. None of my other PRs currently seem to depend on `OSHaiku` as a value, just that `os(haiku)` currently isn't recognised in .cabal files.

**Pull request merged**
