### PR TITLE
Simplify bootstrap generation

### PR DESCRIPTION
**Pull request by robx**
There doesn't seem to be a particular point in checking in the `.plan.json` files,
and generation appears to work just fine on macOS.

If desired, we could check in per-GHC-version freeze files to make the bootstrap
generation more reproducible, but... seems fine without?

The regeneration commit could be left out; I included it to show that the diff is
largely trivial (there's a bit of reordering).

I've validated this change via PR #7929.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by Mikolaj — CHANGES_REQUESTED** [review]
I really don't know how bootstrapping works, but any simplification is welcome.

Could you add the mini-changelog file?

**Comment by robx** [comment]
Sure, will do! (Thought the change maybe wasn't relevant to users.)

**Comment by Mikolaj** [comment]
I'm thinking about "users" that actually use the bootstrap mechanisms to build cabal on new setups. I think it's fine to remove `plan.json` files if you think they are unneeded, but in case the users are surprised by the lack of the files, let's mark it in the changelog.

**Review by Mikolaj — APPROVED** [review]
Great. If the users need the .plan files for anything, they now know where to find us.

**Review by Kleidukos — APPROVED** [review]

**Comment by fgaz** [comment]
> and generation appears to work just fine on macOS.

the plans could be different though, couldn't they?

if we extend bootstrapping to macOS maybe we should provide separate jsons

**Pull request merged**
