### PR TITLE
Make --test-show-details=direct the default

### LINKED ISSUE #7817: Make `--test-show-details=direct` the default
**Description**
Currently, the default is `failures`, which is not a good default (more details below). IMO, the default should be `direct` instead, which  does the things a new user (or at least I) would expect.

**Comparison of the filters**
* `always`: only shows the results after the test suite has finished (this behavior is quite unintuitive and it had lead me and others to believe it was a bug, see https://github.com/haskell/cabal/issues/1581)
* `never`: doesn't show any results (this is obviously a bad default)
* `failures`: only shows failing test suites and only after they finished (this may be occasionally useful, but isn't a good default imo)
* `streaming`: shows the results in real time, but doesn't support colors
* `direct`: shows the results in real time and supports colors (in fact, it is the only filter supporting colors)

So in summary, I think `direct` is the best default option (and it also matches the default behavior of `stack test`).

### PR DESCRIPTION
**Pull request by ulysses4ever**
fix #7817, #8619

## QA Notes

`cabal test` on a simple package with a test suite should give more verbose results than under the previously released `cabal`s. Before, if there are no failures, you wouldn't see which tests have been run. Now you will. Bonus: if the package employs one of the testing frameworks (hspec, tasty, sidtest), you will enjoy colored output (unlike with previous `cabal` releases).

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]
At long last. Thanks for the docs.

**Comment by jneira** [comment]
does it no need automatic o manual tests? now it does not produce a log file by default it seems, and there is not broken test to update? 😢  

not sure if it worths add the `need test` label tbh

**Comment by ulysses4ever** [comment]
@jneira indeed, I was going to but forgot to address automated testing in the PR message. As it stands, i don't believe it's possible to use the current test suite to test this change, and the only way is Manual QA. 

I added a bit of notes for Manual QA but I could extend them, perhaps. I'm not very motivated to do that because I don't know if any manual QA will happen. I'd rather wait for a volunteer and see if they have particular questions. I'd be happy to answer.

Recently i saw many kinds of PRs that require extending the test suite in order to be tested, unfortunately. I don't think it's fair to require that much of an effort for either of those contributions. Otherwise we will just stall.

**Comment by ulysses4ever** [comment]
I'm fine with applying any labels that people think would be helpful, of course. I'm not sure what that should be.

**Pull request merged**
