### PR TITLE
Compat prelude

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM, let's fix the CI and merge errors and merge.

**Comment by ezyang** [comment]
Pro-tip if you're blocking on Travis, try enabling Travis on your own account's fork of Cabal; you'll get your own set of build slots that way.

**Comment by ezyang** [comment]
Sweet. I'll just register my minor objection against a Prelude which is "bigger" than GHC 8.0's that uses the implicit Prelude trick (`Prelude.hs`) on the grounds that it is confusing for people who don't realize we are shipping our own Prelude (why is this in scope?) but this is not a large enough objection to prevent us from merging this.

Re `<<>>`, is there any reason we CAN'T just define `Doc` to be a Monoid and hide `<>`? Then the operators coincide.

**Comment by phadej** [comment]
`Text.PrettyPrint.<>` and `Data.Semigroup.<>` has different associativity. Which matters when you do `foo <> bar <+> quux`...

**Comment by phadej** [comment]
I'm (obviously) :+1: for slightly bigger `Prelude`, some stuff is a bit on the edge (e.g. how much of `Data.List` to pull in), but I tried to pick functions which are used in many modules.

Also we could (later) make the Prelude smaller, i.e. remove `head`...

**Comment by ezyang** [comment]
Ugh, that bites. I'm so used to seeing `<>` in GHC's code base and it meaning put two SDocs together without a space. Grepping Cabal source code, it seems that the monoidal intepretation occurs more, but mostly in the boilerplate for defining semigroup/monoid instances; I bet if you exclude those the pretty print wins out. Not sure what's best. I guess the fact that semigroup/monoid is one of those BC headaches means that it should go into the Prelude, but that kind of sucks.

**Comment by phadej** [comment]
Well, in the outer world (where potential contributors are), semigroup/monoid `<>`  is more popular :)

BTW, after parsec is in, I'll probably refactor the pretty-printing, which could result into much less pretty-printing code. Instead of converting field values to `Doc`, we'd rather convert them to `[FieldLine ()]`, ping @dcoutts, and then render the `Field ()` structure. IMHO we don't need "find nice layout" `pretty` features that much...

**Comment by dcoutts** [comment]
I have to say I'm not a great fan of prelude replacements in general (no matter what is in them), and specifically they don't seem to work with ghci / cabal repl which is then really annoying. That said I've not looked at this carefully and could be persuaded.

**Comment by phadej** [comment]
I see, `cabal repl` is indeed broken. I'll revert to `Distribution.Compat.Prelude`

**Comment by phadej** [comment]
Seems this is going to be green any minute now. Can we merge this?

**Comment by dcoutts** [comment]
@phadej for purely selfish reasons I'd rather not rebase #3611 again :-)

**Comment by phadej** [comment]
@dcoutts hopefully your patch will go soon in. Don't want to wait for this too long either :)

**Comment by dcoutts** [comment]
Unfortunately travis has a big backlog so we're not getting builds at the moment.

**Comment by phadej** [comment]
Rebased on current master

**Comment by phadej** [comment]
Can I merge now?

**Comment by 23Skidoo** [comment]
Sure, please do.

**Pull request merged**
