### PR TITLE
Add rewriteFile' to revert rewriteFile changes

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
This looks like all the `Ex` methods in Windows apis, but `setup-depends` is not yet old enough feature to rely on :/

**Comment by phadej** [comment]
appveyor failure doesn't look legit

**Comment by 23Skidoo** [comment]
Looks like you need to rebase your branch against the latest 2.0.

**Comment by RyanGlScott** [comment]
Looks fine to me.

I'm not familiar with the motivations for changing `rewriteFile` in the first place—is the intention that `rewriteFile` should be deprecated in favor of `rewriteFile'`? Or will they coexist peacefully from here on out?

**Comment by phadej** [comment]
I'll change the name to `rewriteFileEx` and merge.

**Pull request merged**
