### PR TITLE
Update CONTRIBUTING.md to fix fourmolu version to 0.12

### PR DESCRIPTION
**Pull request by Kleidukos**

### CODE REVIEW

**Comment by ffaf1** [comment]
Thanks @Kleidukos. Having `fourmolu` change formatting at each release is suboptimal, I hope there is a way to enjoy bug fixes and have a stable behaviour otherwise.

If someone could point me to what `fourmolu-0.13` does differently on `cabal` codebase, I will open a ticket with fourmolu’s dev to highlight how this is a problem for us and ask for a solution.

**Review by ffaf1 — APPROVED** [review]

**Comment by Kleidukos** [comment]
@ffaf1 I believe that release is mostly an Ormolu backport without options to keep previous style. See https://flora.pm/packages/%40hackage/fourmolu/0.13.0.0/changelog

**Review by ulysses4ever — APPROVED** [review]
Much appreciated, thanks!

**Comment by ffaf1** [comment]
[I asked `fourmolu` devs for suggestions](https://github.com/fourmolu/fourmolu/issues/345).

**Comment by ffaf1** [comment]
Here is a bit of the diff (`fourmolu-0.13.0.0` on `cabal/master`), quite a lot of changes

``` diff
diff --git a/Cabal-syntax/src/Distribution/Parsec.hs b/Cabal-syntax/src/Distribution/Parsec.hs
index 4c6e31e5a..7fd479744 100644
--- a/Cabal-syntax/src/Distribution/Parsec.hs
+++ b/Cabal-syntax/src/Distribution/Parsec.hs
@@ -447,13 +447,13 @@ stringLiteral = lit
     lit =
       foldr (maybe id (:)) ""
         <$> P.between (P.char '"') (P.char '"' P.<?> "end of string") (many stringChar)
-        P.<?> "string"
+          P.<?> "string"
 
     stringChar :: m (Maybe Char)
     stringChar =
       Just <$> stringLetter
         <|> stringEscape
-        P.<?> "string character"
+          P.<?> "string character"
 
     stringLetter :: m Char
     stringLetter = P.satisfy (\c -> (c /= '"') && (c /= '\\') && (c > '\026'))
diff --git a/Cabal-syntax/src/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs b/Cabal-syntax/src/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
index d75466355..0911e3dc6 100644
--- a/Cabal-syntax/src/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
+++ b/Cabal-syntax/src/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
@@ -79,52 +79,52 @@ ipiFieldGrammar =
   mkInstalledPackageInfo
     -- Deprecated fields
     <$> monoidalFieldAla "hugs-options" (alaList' FSep Token) unitedList
-    --- https://github.com/haskell/cabal/commit/40f3601e17024f07e0da8e64d3dd390177ce908b
-    ^^^ deprecatedSince CabalSpecV1_22 "hugs isn't supported anymore"
-    -- Very basic fields: name, version, package-name, lib-name and visibility
-    <@> blurFieldGrammar basic basicFieldGrammar
-    -- Basic fields
-    <@> optionalFieldDef "id" L.installedUnitId (mkUnitId "")
-    <@> optionalFieldDefAla "instantiated-with" InstWith L.instantiatedWith []
-    <@> optionalFieldDefAla "key" CompatPackageKey L.compatPackageKey ""
-    <@> optionalFieldDefAla "license" SpecLicenseLenient L.license (Left SPDX.NONE)
-    <@> freeTextFieldDefST "copyright" L.copyright
-    <@> freeTextFieldDefST "maintainer" L.maintainer
-    <@> freeTextFieldDefST "author" L.author
-    <@> freeTextFieldDefST "stability" L.stability
-    <@> freeTextFieldDefST "homepage" L.homepage
-    <@> freeTextFieldDefST "package-url" L.pkgUrl
-    <@> freeTextFieldDefST "synopsis" L.synopsis
-    <@> freeTextFieldDefST "description" L.description
-    <@> freeTextFieldDefST "category" L.category
-    -- Installed fields
-    <@> optionalFieldDef "abi" L.abiHash (mkAbiHash "")
-    <@> booleanFieldDef "indefinite" L.indefinite False
-    <@> booleanFieldDef "exposed" L.exposed False
-    <@> monoidalFieldAla "exposed-modules" ExposedModules L.exposedModules
-    <@> monoidalFieldAla "hidden-modules" (alaList' FSep MQuoted) L.hiddenModules
-    <@> booleanFieldDef "trusted" L.trusted False
-    <@> monoidalFieldAla "import-dirs" (alaList' FSep FilePathNT) L.importDirs
-    <@> monoidalFieldAla "library-dirs" (alaList' FSep FilePathNT) L.libraryDirs
-    <@> monoidalFieldAla "library-dirs-static" (alaList' FSep FilePathNT) L.libraryDirsStatic
-    <@> monoidalFieldAla "dynamic-library-dirs" (alaList' FSep FilePathNT) L.libraryDynDirs
-    <@> optionalFieldDefAla "data-dir" FilePathNT L.dataDir ""
-    <@> monoidalFieldAla "hs-libraries" (alaList' FSep Token) L.hsLibraries
-    <@> monoidalFieldAla "extra-libraries" (alaList' FSep Token) L.extraLibraries
-    <@> monoidalFieldAla "extra-libraries-static" (alaList' FSep Token) L.extraLibrariesStatic
-    <@> monoidalFieldAla "extra-ghci-libraries" (alaList' FSep Token) L.extraGHCiLibraries
-    <@> monoidalFieldAla "include-dirs" (alaList' FSep FilePathNT) L.includeDirs
-    <@> monoidalFieldAla "includes" (alaList' FSep FilePathNT) L.includes
-    <@> monoidalFieldAla "depends" (alaList FSep) L.depends
-    <@> monoidalFieldAla "abi-depends" (alaList FSep) L.abiDepends
-    <@> monoidalFieldAla "cc-options" (alaList' FSep Token) L.ccOptions
-    <@> monoidalFieldAla "cxx-options" (alaList' FSep Token) L.cxxOptions
-    <@> monoidalFieldAla "ld-options" (alaList' FSep Token) L.ldOptions
-    <@> monoidalFieldAla "framework-dirs" (alaList' FSep FilePathNT) L.frameworkDirs
-    <@> monoidalFieldAla "frameworks" (alaList' FSep Token) L.frameworks
-    <@> monoidalFieldAla "haddock-interfaces" (alaList' FSep FilePathNT) L.haddockInterfaces
-    <@> monoidalFieldAla "haddock-html" (alaList' FSep FilePathNT) L.haddockHTMLs
-    <@> optionalFieldAla "pkgroot" FilePathNT L.pkgRoot
+      --- https://github.com/haskell/cabal/commit/40f3601e17024f07e0da8e64d3dd390177ce908b
+      ^^^ deprecatedSince CabalSpecV1_22 "hugs isn't supported anymore"
+        -- Very basic fields: name, version, package-name, lib-name and visibility
+        <@> blurFieldGrammar basic basicFieldGrammar
+        -- Basic fields
+        <@> optionalFieldDef "id" L.installedUnitId (mkUnitId "")
+        <@> optionalFieldDefAla "instantiated-with" InstWith L.instantiatedWith []
+        <@> optionalFieldDefAla "key" CompatPackageKey L.compatPackageKey ""
+        <@> optionalFieldDefAla "license" SpecLicenseLenient L.license (Left SPDX.NONE)
+        <@> freeTextFieldDefST "copyright" L.copyright
+        <@> freeTextFieldDefST "maintainer" L.maintainer
+        <@> freeTextFieldDefST "author" L.author
+        <@> freeTextFieldDefST "stability" L.stability
+        <@> freeTextFieldDefST "homepage" L.homepage
+        <@> freeTextFieldDefST "package-url" L.pkgUrl
+        <@> freeTextFieldDefST "synopsis" L.synopsis
+        <@> freeTextFieldDefST "description" L.description
+        <@> freeTextFieldDefST "category" L.category
+        -- Installed fields
+        <@> optionalFieldDef "abi" L.abiHash (mkAbiHash "")
+        <@> booleanFieldDef "indefinite" L.indefinite False
+        <@> booleanFieldDef "exposed" L.exposed False
+        <@> monoidalFieldAla "exposed-modules" ExposedModules L.exposedModules
+        <@> monoidalFieldAla "hidden-modules" (alaList' FSep MQuoted) L.hiddenModules
+        <@> booleanFieldDef "trusted" L.trusted False
+        <@> monoidalFieldAla "import-dirs" (alaList' FSep FilePathNT) L.importDirs
+        <@> monoidalFieldAla "library-dirs" (alaList' FSep FilePathNT) L.libraryDirs
+        <@> monoidalFieldAla "library-dirs-static" (alaList' FSep FilePathNT) L.libraryDirsStatic
+        <@> monoidalFieldAla "dynamic-library-dirs" (alaList' FSep FilePathNT) L.libraryDynDirs
+        <@> optionalFieldDefAla "data-dir" FilePathNT L.dataDir ""
+        <@> monoidalFieldAla "hs-libraries" (alaList' FSep Token) L.hsLibraries
+        <@> monoidalFieldAla "extra-libraries" (alaList' FSep Token) L.extraLibraries
+        <@> monoidalFieldAla "extra-libraries-static" (alaList' FSep Token) L.extraLibrariesStatic
+        <@> monoidalFieldAla "extra-ghci-libraries" (alaList' FSep Token) L.extraGHCiLibraries
+        <@> monoidalFieldAla "include-dirs" (alaList' FSep FilePathNT) L.includeDirs
+        <@> monoidalFieldAla "includes" (alaList' FSep FilePathNT) L.includes
+        <@> monoidalFieldAla "depends" (alaList FSep) L.depends
+        <@> monoidalFieldAla "abi-depends" (alaList FSep) L.abiDepends
+        <@> monoidalFieldAla "cc-options" (alaList' FSep Token) L.ccOptions
+        <@> monoidalFieldAla "cxx-options" (alaList' FSep Token) L.cxxOptions
+        <@> monoidalFieldAla "ld-options" (alaList' FSep Token) L.ldOptions
+        <@> monoidalFieldAla "framework-dirs" (alaList' FSep FilePathNT) L.frameworkDirs
+        <@> monoidalFieldAla "frameworks" (alaList' FSep Token) L.frameworks
+        <@> monoidalFieldAla "haddock-interfaces" (alaList' FSep FilePathNT) L.haddockInterfaces
+        <@> monoidalFieldAla "haddock-html" (alaList' FSep FilePathNT) L.haddockHTMLs
+        <@> optionalFieldAla "pkgroot" FilePathNT L.pkgRoot
   where
     mkInstalledPackageInfo _ Basic{..} =
       InstalledPackageInfo
diff --git a/Cabal/src/Distribution/Backpack/MixLink.hs b/Cabal/src/Distribution/Backpack/MixLink.hs
index b358612b2..3e4cc8d7c 100644
--- a/Cabal/src/Distribution/Backpack/MixLink.hs
+++ b/Cabal/src/Distribution/Backpack/MixLink.hs
@@ -61,11 +61,11 @@ linkProvision mod_name ret@(prov : provs) (req : reqs) = do
           text "Ambiguous module"
             <+> quotes (pretty mod_name)
             $$ text "It could refer to"
-            <+> ( text "  "
-                    <+> (quotes (pretty mod) $$ in_scope_by (getSource prov))
-                    $$ text "or"
-                    <+> (quotes (pretty mod') $$ in_scope_by (getSource prov'))
-                )
+              <+> ( text "  "
+                      <+> (quotes (pretty mod) $$ in_scope_by (getSource prov))
+                      $$ text "or"
+                        <+> (quotes (pretty mod') $$ in_scope_by (getSource prov'))
+                  )
```

Complete: https://pastebin.com/wCgJxa43

**Pull request merged**
