### PR TITLE
Resolve tar-entry masking in `packageListFromCache`

### PR DESCRIPTION
**Pull request by hvr**
This should address #2956 and is motivated by #3378

### CODE REVIEW

**Comment by hvr** [comment]
@23Skidoo @dcoutts what'ya think?

**Comment by 23Skidoo** [comment]
Code looks OK. Have you measured the effect of this patch on memory consumption?

**Comment by dcoutts** [comment]
I've not checked the code detail, but the principle of correctly resolving tar entry overriding is fine.

**Comment by hvr** [comment]
@23Skidoo in fact I did a quick non-scientific comparision of `/usr/bin/time -v cabal update` with new/old code, and the new code allocated only slightly more (just a few MiBs) more than before the change. Total mem-usage was about 115MiB iirc (so it was something in the order of 115MiB vs 117MiB). If you're interested I can do a more exact measurement via `+RTS -hT`

**Comment by 23Skidoo** [comment]
@hvr No, thanks, it's fine. I think I'll just go ahead and merge then.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
