### PR TITLE
update GH validate workflow to 9.2.8, 9.4.7, 9.6.3

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ffaf1 — APPROVED** [review]

**Comment by Mikolaj** [comment]
Wow. Did the tests fail, because the output changed or did something new break now?

**Comment by ulysses4ever** [comment]
Already part of #9330, but if it helps an immediate issue, I'm fine with rebasing.

**Comment by juhp** [comment]
@ulysses4ever ah okay - sorry I wasn't aware

Maybe good to get this first step in anyway?

**Comment by juhp** [comment]
Thanks!

**Comment by Mikolaj** [comment]
@juhp: BTW, a more delicate way of merging outright is via the merge_me and merge_delay_passed labels. Less risk of comitting something CI has not run and of causing git art via non-fast-foward merge commits. :)

**Comment by juhp** [comment]
Thanks @Mikolaj - I was wondering: should have checked - will do that next time

**Comment by Mikolaj** [comment]
Thank you. :)

**Pull request merged**
