### PR TITLE
Haddock: Use --package-{name|version} when available

### PR DESCRIPTION
**Pull request by bgamari**
This in conjunction with the next haddock release should fix https://github.com/haskell/cabal/issues/2297.

### CODE REVIEW

**Comment by bgamari** [comment]
This appears to work on my end.

**Comment by dcoutts** [comment]
Looks good.

**Comment by snoyberg** [comment]
I would like to confirm this fix with the current GHC 7.10 RC3. How would I go about doing so? Is any version of the fix available on Hackage, or should I just build master?

**Comment by 23Skidoo** [comment]
@snoyberg The fix is included in the version of Cabal library that ships with 7.10 RC3.

**Comment by snoyberg** [comment]
Thanks. I've confirmed by following these steps:

1. Unpacking latest cabal-install
2. Tweaking cabal file to allow filepath 1.4
3. Building against the Cabal provided with GHC 7.10 RC3
4. Running `cabal haddock --hoogle` using the resulting binary

**Comment by 23Skidoo** [comment]
> Tweaking cabal file to allow filepath 1.4

Or you could just use `--allow-newer=filepath` ;-).

**Comment by 23Skidoo** [comment]
Also, I bumped the upper bound in `cabal-install`'s dependency on `filepath` on Hackage, so it should now work out of the box after a `cabal update`.

**Pull request merged**
