### PR TITLE
 cabal-install: Remove support for building with GHC < 7.10.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Fun fact: we can also drop support for building with GHC 7.4.2 from `lib:Cabal` as well, since it was released > 5 years ago (Jun 2012).

**Comment by phadej** [comment]
hmm. dropping 7.4.2 sounds cool, as then we can `containers >=0.5`. Is there other good reasons? I'd rather remove the support where there's good reason to do so.

**Comment by 23Skidoo** [comment]
Any change that removes code is a good thing in my book, 7.4.2 is positively ancient, and we won't be breaking any promises. Note that we're still supporting `build -w` for old GHC versions back to 7.0 and there are CI tests for that.

Another fun fact: GHC 7.6.3 was released in April 2013, so we can remove support for building lib:Cabal with 7.6.* in the next+1 (i.e. 2.4) release. 7.8 will have to be supported until Dec 2019.

**Comment by hvr** [comment]
> hmm. dropping 7.4.2 sounds cool, as then we can containers >=0.5.

Otoh, you can still support GHC 7.4.2 while requiring containers >= 0.5 ... if you don't insist on `--constraints "containers installed"` :-)

**Comment by 23Skidoo** [comment]
Yep, we probably can support building lib:Cabal with old GHC:s as a setup script dependency for a longer period. This needs to be checked by CI, though...

**Comment by 23Skidoo** [comment]
There's some weird 7.8.4 failure, will investigate.

**Comment by 23Skidoo** [comment]
Yiss, looks like support for `ld.gold` was only added in 7.8: [1](https://ghc.haskell.org/trac/ghc/ticket/4862), [2](https://github.com/ghc/ghc/commit/668151c880f5662e59288a0884d8d3505c0ce7d7).

**Comment by 23Skidoo** [comment]
So `PackageTests/TestSuiteTests/ExeV10/setup-with-hpc.multitest.hs` is now failing in the 7.8.4+7.0.4 configuration. No idea how it can pass with 7.6.3+7.0.4 at the same time.

**Comment by 23Skidoo** [comment]
Looks like that test doesn't work with `hpc < 0.7`, but determines the version of `hpc` by just looking in `PATH` and not at the version the compiler we're configured with uses. And 7.6.3 just happens to use `hpc` 0.6, so the test passes.

**Comment by 23Skidoo** [comment]
Yay, it's green at last.

**Pull request merged**
