### PR TITLE
Added `cxx-options` and `cxx-sources` build info fields for separate compilation of C and C++ source files. 

### PR DESCRIPTION
**Pull request by recursion-ninja**
Added `cxx-options` and `cxx-sources` build info fields for separate compilation of C an C++ source files. This resolves issue #3700. If my memory is correct there were some related issues that this should solve in `cabal` and also in `stack`. I'll spend a bit of time trying to hunt the issues down and reference them here.

I tested the functionality against the following package: 

 - https://github.com/recursion-ninja/tcm-memo

Here's the requisite checklist:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [X] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [X] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

I think I probably need to update the documentation somewhere, but I'm not sure where it's located or how to go about that. Would appreciate a bit of help @ezyang.

### CODE REVIEW

**Comment by recursion-ninja** [comment]
It looks like the `cabal-testsuites/PackageTests/PreProcessExtraSources/setup.test.hs` test is failing.

I'm not sure how to replicate the failure. I did the following:

    $ cd cabal-testsuites/PackageTests/PreProcessExtraSources/
    $ cabal install --enable-tests --enable-benchmarks #this is the locally built cabal binary
    Resolving dependencies...
    Configuring PreProcessExtraSources-0.1...
    Building PreProcessExtraSources-0.1...
    Installed PreProcessExtraSources-0.1
    
Is there a different way Travis/appveyor is invoking the test suite?

**Comment by 23Skidoo** [comment]
Does the procedure described in https://github.com/haskell/cabal/tree/master/cabal-testsuite#how-to-run work for you?

**Comment by 23Skidoo** [comment]
Also you can try just running `cabal configure --enable-tests --enable-benchmarks` and `cabal build`, since that's what the test does.

**Comment by recursion-ninja** [comment]
@23Skidoo, the process described in https://github.com/haskell/cabal/tree/master/cabal-testsuite#how-to-run isn't working for me. I'm having issues with the instruction "Step 1: Build `cabal-tests` (`cabal new-build cabal-tests`)." When I run `cabal new-build cabal-tests` a module I didn't touch fails to compile. However `cabal-tests` does build when I run `stack install`.

I tried:
```
$ cabal-tests cabal-testsuites/PackageTests/PreProcessExtraSources
cabal-tests: Run the 'configure' command first.
```

I tried:
```
$ cd cabal-testsuites/PackageTests/PreProcessExtraSources
$ cabal configure --enable-tests --enable-benchmarks
Resolving dependencies...
Configuring PreProcessExtraSources-0.1...
$ cd ../../../
$ cabal-tests cabal-testsuites/PackageTests/PreProcessExtraSources
cabal-tests: Run the 'configure' command first.
```

I tried:
```
$ cd cabal-testsuites/PackageTests/PreProcessExtraSources
$ cabal configure --enable-tests --enable-benchmarks && cabal build
Resolving dependencies...
Configuring PreProcessExtraSources-0.1...
Saved package config file is corrupt. Re-run the 'configure' command.
```

So I'm not sure how to replicate the defect. I can keep changing things I suspect are the issue and pushing changes until Travis & AppVeyor confirm that I fixed the defect.

**Comment by recursion-ninja** [comment]
@23Skidoo, @ezyang I think AppVeyor failed with no fault from my pull request. It says it can't install `text`. Can I prompt it to rerun some how?

**Comment by 23Skidoo** [comment]
Restarted the AppVeyor build.

**Comment by 23Skidoo** [comment]
The `c-sources` field is documented [here](http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-c-sources), which is generated from [this file](https://github.com/haskell/cabal/blob/master/Cabal/doc/developing-packages.rst). I'd put documentation for `cxx-sources` in the same place.

**Comment by recursion-ninja** [comment]
Thanks very much for the guidance with the merge @23Skidoo, and thank you @ezyang for showing me where to start on adding this functionality!

**Comment by amigalemming** [comment]
I have tried to compile an executable that imports a library using Cxx-Sources.
GHCs ends with:
~~~~
/usr/bin/ld: haskell/llvm-ffi/dist/build/libHSllvm-ffi-3.8.1.1-8VXDnIFcppwCDsRtxP8bEJ.a(support.o): undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO aus der Kommandozeile fehlt
collect2: error: ld returned 1 exit status
~~~~
The trick for me so far was to use the g++ linker:
~~~~
GHC-Options: -pgmlg++
~~~~
But others may want a different C++ linker.

**Comment by amigalemming** [comment]
When compiling the C++ sources I get a warning about an inappropriate `-Wimplicit` option for g++:
~~~~
$ cabal-2.1 build -v
...
Building C++ Sources...
creating dist/build
/opt/ghc/bin/ghc -c -odir dist/build -Idist/build/autogen -Idist/build/global-autogen -Idist/build -Iinclude -I/usr/lib/llvm-3.8/include -optc-O2 '-optc-std=c++0x' '-optc-std=c++11' '-optc-DHS_LLVM_VERSION=308' -hide-all-packages -package-conf dist/package.conf.inplace -package-id enumset-0.0.4-Lj85qfShzo26XBfPyJGMlN -package-id base-4.5.1.0-6e4c9bdc36eeb9121f27ccbbcb62e3f3 cbits/support.cpp
cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++
~~~~

**Comment by thoughtpolice** [comment]
The "right way" to link to `libstdc++` is probably to instead use

```
extra-libraries: stdc++
```

(This is generally better since Cabal expects to list libraries for GHC in certain situations, like using the linker and/or GHCi)

**Comment by amigalemming** [comment]
Extra-libraries works for me on Linux. I have heard, though, that Extra-libs alone fails on MacOS X. Can someone check?

**Comment by angerman** [comment]
I can give https://github.com/recursion-ninja/tcm-memo a test on macOS tomorrow, lest I forget. But that one uses stdc++ in the extra-libs as well.

**Comment by angerman** [comment]
If it fails, maybe we can fix it ;-)

**Comment by recursion-ninja** [comment]
@angerman,  I tested the `tcm-memo` library on my Linux machine and my colleague’s macOS machine. I don't recall which version of macOS my colleague’s machine was running at the time I tested it though. Please give it another test on macOS and let me know the results.

@thoughtpolice, the build info field `extra-libraries: stdc++` is probably necessary for most (all?) C++ projects.

@amigalemming, Hopefully the `extra-libraries: stdc++` build info field provides a portable solution to your linking error. Could you give me a bit more context as to your project was using the C++ sources? I don't remember encountering a `-Wimplicit` warning during my _limited_ testing. It might be symptomatic of passing the wrong default flags to `gcc`.

**Comment by angerman** [comment]
Apart from
```
src/Data/TCM/Memoized/FFI.hsc:85:10: error:
    Duplicate instance declarations:
      instance Arbitrary CULong
        -- Defined at src/Data/TCM/Memoized/FFI.hsc:85:10
      instance Arbitrary CULong -- Defined in ‘Test.QuickCheck.Arbitrary’
   |
85 | instance Arbitrary CULong where
   |          ^^^^^^^^^^^^^^^^
cabal: Failed to build tcm-memo-1.0.0.0 (which is required by exe:use-the-code
from tcm-memo-1.0.0.0).
```

this built with `new-built` just fine on macOS Sierra (10.12.6) with GHC (The Glorious Glasgow Haskell Compilation System, version 8.2.1)

Seems to work as well:
```
$ use-the-code 1 2        
Cost:
1
Result:
T [3]
```

**Comment by amigalemming** [comment]
@angerman The `-Wimplicit` warning seems to be caused by my rusty GHC-7.4.2 compiler. Starting with GHC-7.6.3 they do not appear anymore. So, you do not have to take any action for Cabal.

**Comment by recursion-ninja** [comment]
@angerman Thanks for pointing out the fragile build error. 

I have added a proper lower version bound to the `QuickCheck` dependency of the [`tcm-memo`](https://github.com/recursion-ninja/tcm-memo) toy project to prevent that in the future.

@amigalemming Glad to hear that the `-Wimplicit` warning isn't an actionable issue. For sanity's sake, I also added a lower version bound to the `base` dependency of the [`tcm-memo`] project to ensure that it is built with at least GHC-7.6.3.

**Pull request merged**
