### PR TITLE
Update HACKING.md: Add --allow-newer=Cabal

### PR DESCRIPTION
**Pull request by lspitzner**

### CODE REVIEW

**Comment by lspitzner** [comment]
Also, the Setup.hs stuff has become unnecessary, hasn't it?

**Comment by 23Skidoo** [comment]
> Also, the Setup.hs stuff has become unnecessary, hasn't it?
You still need it to run the test suite.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Related: https://github.com/well-typed/hackage-security/pull/151.

**Comment by dcoutts** [comment]
So you should be able to drop this suggestion now. We tweaked hackage-security's constraints.

**Comment by 23Skidoo** [comment]
> So you should be able to drop this suggestion now.

Done in 243e8eb1f13de96e4ba690ac158a08ca1f17313b.

**Pull request merged**
