### PR TITLE
CI: remove cabal-head before updating it (fix #10537)

### LINKED ISSUE #10537: cabal-head prerelase date and commit are not updated
Follow-up on https://github.com/haskell/cabal/issues/10515

The new release action doesn't update the date on the prerelease itself nor the commit it says was used to create the prerelease. It only updates the binaries and that's it...
photo_2024-11-07_11-20-44
(https://github.com/haskell/cabal/commit/0d80d5232fe6ff7a4eb4c6e5a42d643fad4ea98f is from October 3rd.)

We probably should explicitly remove the old prerelease before calling the release action (e.g. via https://github.com/marketplace/actions/delete-a-release).

### PR DESCRIPTION
**Pull request by TeofilC**
This PR is https://github.com/haskell/cabal/pull/10540 rebased.

It should fix https://github.com/haskell/cabal/issues/10537 and its duplicate https://github.com/haskell/cabal/issues/10652

----
*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [n/a] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — CHANGES_REQUESTED** [review]
Can this be applied to `prerelease-lts` as well? (Not that that is currently functional; it needs to move to a nightly, because when a PR doesn't need to be rebased Mergify pushes it in without running the workflow so it never gets a chance to run.)

**Review by ulysses4ever — APPROVED** [review]
Thank you!

**Comment by TeofilC** [comment]
> Can this be applied to `prerelease-lts` as well? (Not that that is currently functional; it needs to move to a nightly, because when a PR doesn't need to be rebased Mergify pushes it in without running the workflow so it never gets a chance to run.)

Done

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
Do we want to expedite this in the name of getting the prereleases properly back in action?

**Comment by ulysses4ever** [comment]
Sure, we can do that.

**Comment by geekosaur** [comment]
Something's wrong, `validate.yml` isn't being run. I wonder if your indentation change broke it.

**Comment by geekosaur** [comment]
```
Invalid workflow file: .github/workflows/validate.yml#L468
You have an error in your yaml syntax on line 468
```

**Comment by TeofilC** [comment]
Good spot. I've fixed the indention now (I think)

**Comment by geekosaur** [comment]
```
Invalid workflow file: .github/workflows/validate.yml#L497
You have an error in your yaml syntax on line 497
```
I hate YAML-as-code…

**Comment by TeofilC** [comment]
Yeah right. :crossed_fingers: that it works this time

**Comment by ulysses4ever** [comment]
As an anecdote: when I wrote this patch I also had to fix it up about 4 times because of incorrect indentation in YAML. Maybe it wasn't correct after all...

**Comment by geekosaur** [comment]
The indentation gave me a fair amount of pain when doing the CI rewrite as well, in part because it was so inconsistent between jobs. I think I made it all consistent as part of it.

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Pull request merged**
