### PR TITLE
testsuite: remove file generated by autoheader

### PR DESCRIPTION
**Pull request by andreasabel**
Testsuite: remove file generated by autoheader.

After running the cabal-testsuite, I found changes in this file, so I suppose it is a generated file and can (and should) be removed from the source tree.

It actually says so:
```c
/* include/HsZlibConfig.h.in.  Generated from configure.ac by autoheader.  */
```

### CODE REVIEW

**Comment by andreasabel** [comment]
Ok, now CI fails, i have to investigate...

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
I wonder if it fails because the `include` directory will cease to exist after this change (it may seem like the change only removes the file but it was the only one in that dir, and git doesn’t like empty dirs…).

**Comment by ulysses4ever** [comment]
That was it.

**Review by ulysses4ever — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@andreasabel, are you ready to mergify-merge?

**Comment by Mikolaj** [comment]
Let me step in and add the label...

**Comment by andreasabel** [comment]
Thanks, @ulysses4ever, for finishing this!

**Comment by andreasabel** [comment]
@ulysses4ever : Here, it claims that I forced-pushed.  ;-)

**Pull request merged**
