### PR TITLE
Cabal: Allow time-1.9

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by hvr** [comment]
@bgamari shouldn't this rather be against master? Btw, we try to avoid extending bounds to include releases of dependencies we don't cover in CI

**Comment by bgamari** [comment]
> shouldn't this rather be against master?

I wanted to keep the bump minimal so I applied the 

> Btw, we try to avoid extending bounds to include releases of dependencies we don't cover in CI

I'm not sure what you mean. `time-1.9` has been available on Hackage for nearly a year. Why wouldn't this be covered in CI?

**Comment by 23Skidoo** [comment]
Merged, thanks! Also cherry-picked into `master`.

**Comment by bgamari** [comment]
Thanks!

**Pull request merged**
