### PR TITLE
Do not check PVP on internal targets

### PR DESCRIPTION
**Pull request by ffaf1**
Internal targets: test-suites or benchmarks.
See #8361 for rationale.

Note that this patch is quite ugly (duplicating allBuildInfo, using list comprehensions, etc.) but we don’t care as everything will be overwritten by a much more sensible reimplementation in #8427.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] ~The documentation has been updated, if necessary.~ N/A, since no warning-specific docs in master, but they have been updated in #8427.
* [x] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

---

## QA Notes

1. fetch any cabal package with a test-suite, say `cabal get lentil`
2. `cd` into it
3. in the `build-depends` section of the `test-suite` stanza, add an unbounded dependency
4. run `cabal check`, it should *not* complain about missing upper bounds

### CODE REVIEW

**Comment by Mikolaj** [comment]
So, is it a good idea to include this in cabal 3.10.2.0? Gershom also says it would be useful for Hackage. Any problems with this idea?

**Review by gbaz — APPROVED** [review]

**Comment by Kleidukos** [comment]
And it needs a change to Cabal as well in order for Hackage to benefit from it.

**Review by Kleidukos — APPROVED** [review]

**Comment by Mikolaj** [comment]
So, do we backport now? If so, let's do `mergify backport 3.10`. Actually, this could have been done instead of the backport label and, with some luck, mergify would create the backport after merge, automatically.

**Comment by ffaf1** [comment]
@mergify backport 3.10

**Comment by Mikolaj** [comment]
Uhoh, a merge conflict in the backport. Is it because we should have backported another PR first or is it due to the formatting PR or something yet different?

**Pull request merged**
