### PR TITLE
Docs: guide on profiling: fix the title

### PR DESCRIPTION
**Pull request by ulysses4ever**
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N/A] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by Kleidukos** [comment]
@malteneuss Does this align with the vision you had for this guide?

**Comment by jasagredo** [comment]
I would be a bit less succinct and say something like "How to configure a project for profiling" or "Configuring a project for profiling".

**Review by jasagredo — APPROVED** [review]

**Comment by ulysses4ever** [comment]
> I would be a bit less succinct and say something like "How to configure a project for profiling" or "Configuring a project for profiling".

Thanks, I'm open for options. I am not a fan of the first because it's a little lengthy, and the second deviates from the pattern that's established in the guide section: everything starts from "How to" (maybe not a great decision but it should be applied or unapplied consistently). Let's see what @malteneuss and others has to say.

> Seems like the file should be renamed as well….

I was being lazy, sorry! Fixed.

**Comment by malteneuss** [comment]
The title was chosen to be more beginner friendly and to be immediately understandable even when someone doesn't know the correct technical term "profiling", i.e. people who are more likely to need a guide. Imagine what you would search if you didn't know that term: probably "measure haskell performance" or similar. Still, the guide uses the term "profiling" enough times to be locatable via Google easily for someone who knows.

While "analyze .. performance" isn't technically correct yet, (e.g. we don't explain how to to interpret results), that could be added later (even by just referencing the optimization book or GHC guide). It's also a relatively short title. Alternatives could have been "How to setup Cabal to measure Haskell performance" if it wasn't so long.

**Comment by ulysses4ever** [comment]
>  While "analyze .. performance" isn't technically correct yet, (e.g. we don't explain how to to interpret results), that **could be added later**

Let's not get ahead of ourselves. Only when and if such an addition is implemented can we discuss a title that reflects that new content. Besides, @jasagredo and I argued that it's not Cabal Guide's job to teach people to interpret GHC profiles. So, I am doubtful that such an addition will even happen. Of course, others may rule otherwise.

> The title was chosen to be more beginner friendly and to be immediately understandable even when someone doesn't know the correct technical term "profiling", i.e. people who are more likely to need a guide. Imagine what you would search if you didn't know that term: probably "measure haskell performance" or similar. Still, the guide uses the term "profiling" enough times to be locatable via Google easily for someone who knows.

I think Cabal Guide shouldn't be targeted at CS freshmen. The average reader is not very familiar with Haskell but is somewhat familiar with computer programming. So, I'd expect them to be aware of the notion of "profiling".

How about:

> How to enable collection of performance statistics (profiling)
 
for the title?

**Comment by ulysses4ever** [comment]
(question for all)

**Comment by jasagredo** [comment]
I'm in favor of:
> How to enable collection of performance statistics (profiling)

**Comment by malteneuss** [comment]
Good enough for me

**Comment by Kleidukos** [comment]
Good enough for me too

**Review by Kleidukos — APPROVED** [review]

**Comment by Kleidukos** [comment]
@ulysses4ever Is everything alright with this PR? It blocks https://github.com/haskell/blog.haskell.org/pull/9

**Comment by ulysses4ever** [comment]
Oh, I totally forgot about it. Let's fast-track.

**Comment by ulysses4ever** [comment]
Actually, after re-reading the thread: it needs one more fixup, which I can do later today

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
"Title underline too short." really???

**Comment by geekosaur** [comment]
Sounds like the Sphinx version of what I went through while trying to bend GHA to my will.

**Pull request merged**
