### PR TITLE
Display class

### PR DESCRIPTION
**Pull request by phadej**
WIP

contains commits from https://github.com/haskell/cabal/pull/2862

ping @dcoutts, is this what you had in mind?

### CODE REVIEW

**Comment by dcoutts** [comment]
@phadej  yes exactly.

I'm slightly unclear now what github merge will do, now that #2862 is merged.

@23Skidoo FYI ^^ this Display stuff is a direction I'd like to move in, as part of replacing ReadP with Parsec. Other patches use parsec for the outline parser, and this Display class is part of using parsec for the field contents. Ultimately the plan is to retire and eliminate the Text class, keeping just Display (at which point we'll move the disp method into the Display class).

**Comment by phadej** [comment]
@dcoutts I'll probably include this in outline pr as I need to parse conditional expression, which are lista of SecArguments and not plain string. Thus would require parametrising Display in stream too. Is that ok?

**Comment by dcoutts** [comment]
@phadej I'm not 100% sure if I follow.

I thought at first you meant that the Display class would have a parsec method that is polymorphic in the Stream class, so that they'd all be able to parse both String and ByteString/Text? That'd be useful.

But actually it sounds like you want some instances to work with non-Char token streams, and that's not easily going to work with a class.

Can you describe the issue? Perhaps some parts just can't be an instance of Display. But anything that's currently in Text should be able to be.

BTW note that the Stream instance for parsec does not use UTF8, so we would not be able to parse most of our things from ByteString, just from Text. Or we'd need to use a newtype wrapper to give a different parsec Stream instance that does UTF8 decoding.

**Comment by dcoutts** [comment]
So I think we should update and merge this once 1.24 is branched.

**Comment by phadej** [comment]
I'll try to find time ASAP to this (and parsec parser)

**Comment by 23Skidoo** [comment]
@phadej Is this PR obsolete?

**Comment by phadej** [comment]
It is.

**Pull request closed without merging**
