### PR TITLE
Remove "'-main-is' is not portable" check

### LINKED ISSUE #8646: 'cabal check' warns that 'ghc-options: -main-is' is not portable
## Summary

When a package has an executable, test suite, or benchmark where main module has a name distinct from `Main` the `-main-is` flag should be passed to GHC to tell it how the main module is called. However `cabal check` complains about this with following error message

```
Warning: These warnings may cause trouble when distributing the package:
Warning: 'ghc-options: -main-is' is not portable.
```

My question is why is it not portable? The flag is specific to GHC yet it's listed under `ghc-options` field which should theoretically make any alternative Haskell compilers ignore it. Practically there's, on the one hand, pretty few alternative Haskell compilers to go around and on the other hand even if one manages to find such a compiler there's whole lots of non-portable things a package could do (e.g. use `import GHC.Exts` or use extensions)  that said compiler will probably not support and are hence are not portable as well. It feels strange to issue non-portability warning specifically for a command-line flag which has been around for quite a while.

Perhaps the warning about `-main-is` flag should be removed?

Little investigation revealed that warning was added in commit `39c03860055116afa365cc5e6610f85b4e4116df` in 2008. No specific justification for checking `-main-is` was mentioned.

At the time the warning probably made sense but now, in my opinion, any realistic altervative Haskell will most likely have to strive to be compatible with GHC in terms of flags to have any chance of getting traction.

## Steps to reproduce

Sample inputs that make `cabal check` produce the warning above:
`test.cabal`
```
cabal-version: 3.0

name: test
version: 0.1
build-type: Simple
category: Test
maintainer: Joe
synopsis: Input to 'cabal check'
description: Input to 'cabal check'.
license: BSD-3-Clause

executable test
  main-is: ExeMain.hs
  build-depends: base > 4 && < 5
  default-language: Haskell2010
  ghc-options: -main-is ExeMain
```

`ExeMain.hs`
```haskell
module ExeMain (main) where

main :: IO ()
main = putStrLn "Hello, world"
```

### PR DESCRIPTION
**Pull request by sergv**
Fix #8646. I've checked that cabal doesn't complain about presence of `-main-is` whereas it does complain if I revert the commit. 

Please let me know if you'd like to add a test for this.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thanks! Regarding a test: the rule of thumb, I believe, is that if it's not too cumbersome to add a test, then just add it. I expect it to be trivial in this case.

**Comment by sergv** [comment]
Looks like there're tests for `cabal check` but specifically for the `Cabal` package so I added a test there.

**Review by ffaf1 — COMMENTED** [review]
Very good

**Review by ffaf1 — APPROVED** [review]

**Comment by ffaf1** [comment]
You may now add a `squash+merge me` label.

**Pull request merged**
