### PR TITLE
Fix compilation on old GHCs (fixes #8371)

### LINKED ISSUE #8371: Bump lower bound on base
It seems that Cabal-syntax doesn't compile with GHC 7.10.3 and other old GHCs (complains about unknown flags or extensions; seen on hackage-security CI). If so, we should bump the bound on base accordingly so that people don't need to add hacky conditions to the same effect to their package, e.g., see https://github.com/haskell/hackage-security/pull/281/commits/737ad614ddf63d2506d8f0e141f8c44625c0d611

I think it's fine if we bump to the same range that we have in CI. It may make sense to revise the bound on Hackage for 3.8.1.0, too.

### PR DESCRIPTION
**Pull request by Mikolaj**
Would simplify https://github.com/haskell/hackage-security/pull/281 and fix similar errors for others. More delicate than bumping lower bounds on base.

Fixes https://github.com/haskell/cabal/issues/8371

### CODE REVIEW

**Review by jneira — APPROVED** [review]
lgtm, thanks for the firefighting

**Review by robx — APPROVED** [review]
LGTM

**Review by Kleidukos — APPROVED** [review]

**Comment by Mikolaj** [comment]
A few validates passed; let me emergency-merge.

**Comment by Mikolaj** [comment]
@mergify backport 3.8

**Pull request merged**
