### PR TITLE
travis.sh cleanup

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
@23Skidoo, as discussed.

**Comment by tuncer** [comment]
Let's see if keeping the dirs will improve CI times.

**Comment by tuncer** [comment]
@23Skidoo, keeping the dirs got us the following error:
```
In order, the following would be installed:
Cabal-1.25.0.0 (reinstall)
cabal: The following packages are likely to be broken by the reinstalls:
hackage-security-0.5.1.0
Use --force-reinstalls if you want to install anyway.
```

**Comment by tuncer** [comment]
@23Skidoo, should I omit 7872bcc?

**Comment by tuncer** [comment]
I'll omit 7872bcc for now, and we can tackle it separately from the other commits.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
