### PR TITLE
Check.hs catMaybes . map -> mapMaybe

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Can you please fix the Travis failure?

**Comment by Heather** [comment]
@23Skidoo sorry, I didn't checked that it's running with `Werror` - I should test my requests locally with same option

**Comment by Heather** [comment]
@23Skidoo how can I re-run jenkins? it shows my old errors :)

**Comment by 23Skidoo** [comment]
Just rebase against current master and do `push -f`.

**Comment by Heather** [comment]
@23Skidoo reopen did the job seems like and Travis should test merged results as far as I understand, not just sources from request

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
