### PR TITLE
Add MultilineStrings extension

### PR DESCRIPTION
**Pull request by brandonchinn178**
* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ulysses4ever — APPROVED** [review]
Hooray! 

Although, `Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs` will probably have to be updated.

**Comment by brandonchinn178** [comment]
That's... annoying 🫤 Any reason why it's not just a golden test? It would be more auditable and easier to update.

Presumably CI will fail with the new hash, right? I'll update when that happens.

**Comment by ulysses4ever** [comment]
Hey @brandonchinn178! Thanks for your contribution! Please, check out our contributing guidelines w.r.t. GitHub PR lifecycle: https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions We don't merge manually and rather defer to a bot, which implements a cooldown period among other things. A PR author is supposed to apply a merge label when they are ready to hand the PR over to the bot.

**Comment by brandonchinn178** [comment]
ah sorry! Happy to do any revert operations, just let me know

**Comment by ulysses4ever** [comment]
No, that's fine. Just for the future reference.

**Pull request merged**
