### PR TITLE
Comment optional post-install field in the ghcup metadata script and fix typos

### PR DESCRIPTION
**Pull request by Kleidukos**

### CODE REVIEW

**Comment by Kleidukos** [comment]
@geekosaur A second look would be appreciated

**Comment by Kleidukos** [comment]
cc @arjunkathuria

**Review by geekosaur — APPROVED** [review]
Okay as far as I can tell, but I'm not really an expert in ghcup's YAML metadata.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Kleidukos** [comment]
@geekosaur any idea about https://github.com/haskell/cabal/actions/runs/12418397255/job/34675419181?pr=10643 ?

**Comment by geekosaur** [comment]
I'm going to be trying a different release action, since Artem's rewiring of the delete-release action https://github.com/haskell/cabal/pull/10662 (which you don't seem to have in your roll-up) isn't working. The likely one is nightly-release which I found in the Marketplace.

**Comment by geekosaur** [comment]
Also you may not have my final fix of the LTS prerelease, which included some debug cleanup that turned off the initial steps always running,

**Comment by geekosaur** [comment]
Sorry, wrong button, I'm barely awake

**Comment by Kleidukos** [comment]
I rebased on `master` 10mn ago, it should be good?

**Comment by geekosaur** [comment]
> I rebased on `master` 10mn ago, it should be good?

"Should be", but that was definitely the LTS prerelease that was running, meaning you were missing the final cleanup (https://github.com/haskell/cabal/pull/10655) that put the guards back on it.

**Comment by Kleidukos** [comment]
@mergifyIO backport 3.14

**Pull request merged**
