### PR TITLE
Avoid deduplication of GHC options that can break builds (rebase of #5368)

### PR DESCRIPTION
**Pull request by 23Skidoo**
This is #5368, but rebased against `master` to make history cleaner.

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by qnikst** [comment]
It seems that `ghcOptGHCiScripts` are affected by this problem as well, should I prepare PR for that?

**Comment by 23Skidoo** [comment]
@qnikst Sure, please do. I think you should be able to push directly to this branch.

**Comment by qnikst** [comment]
I've added a commit with the fix for `-ghci-script`

**Comment by 23Skidoo** [comment]
So CI failed because GHCs < 7.10 don't support `-trust`... fixing.

**Comment by 23Skidoo** [comment]
@roman-kashitsyn Merged, thanks!

**Pull request merged**
