### PR TITLE
Miscellaneous improvements to cabal-install test suite

### PR DESCRIPTION
**Pull request by ezyang**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
LGTM.

**Comment by BardurArantsson** [comment]
I don't pretend to understand *everything* that's going in in a437c7b, but it looks reasonable to me.

**Comment by BardurArantsson** [comment]
@ezyang I'd be happy to press the Big Green Button for you if you adress the minor questions/quibbles :).

**Comment by ezyang** [comment]
GitHub ate the comments. IIRC, it was just renaming `PKGTEST` to `CABAL_PKGTEST`? For future reference, if you comment on the "Files changed" tab rather than on an individual commit, the comments get associated with the PR, otherwise if I rebase you lose them.

**Comment by 23Skidoo** [comment]
Comments seem to be still accessible here: https://github.com/ezyang/cabal/commit/a437c7bfd1c065f5895c1f239e836c8cdf6b7f68

> IIRC, it was just renaming `PKGTEST` to `CABAL_PKGTEST`?

Yes, looks like it.

**Comment by ezyang** [comment]
OK, should be all addressed.

**Comment by 23Skidoo** [comment]
@ezyang 
OK, so I think I've fixed `travis-diff-files.sh`. Can you please rebase this PR against `master` to check that it now triggers a failure on Travis?

**Comment by ezyang** [comment]
Confirmed failing, now I'll fix it...

**Comment by 23Skidoo** [comment]
Thanks. Confirmed that it [fails correctly](https://travis-ci.org/haskell/cabal/builds/106402757) now.

**Comment by 23Skidoo** [comment]
Restarted the build, the connectivity issue is now resolved.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Pull request merged**
