### PR TITLE
Use `--io-manager=native` in `lib-suite` on Windows

### LINKED ISSUE #9571: Running the test-suite terminates abruptly with `fd:5: hGetLine: end of file` in MSYS2 Windows
**Describe the bug**
The test-suite terminates non-deterministically with:
```
cabal-tests.exe: fd:5: hGetLine: end of file
```

**To Reproduce**

```
$ ./validate.sh -v -s build -s lib-suite
...
=== Cabal: cabal-testsuite =================================================== 00:10:15 ===
C:\Users\Javier\code\cabal\dist-newstyle-validate-ghc-9.6.3\build\x86_64-windows\ghc-9.6.3\cabal-testsuite-3\build\cabal-tests\cabal-tests.exe --builddir=/c/Users/Javier/code/cabal/dist-newstyle-validate-ghc-9.6.3/build/x86_64-windows/ghc-9.6.3/cabal-testsuite-3 -j4 --with-ghc=ghc
threads: 4
tests to run: 509
PackageTests\TestSuiteTests\ExeV10\cabal-with-hpc.multitest.hs                                                    SKIP no cabal-install (4.38s)
PackageTests\AllowOlder\cabal.test.hs                                                                             SKIP no cabal-install (4.45s)
PackageTests\AllowNewer\cabal.test.hs                                                                             SKIP no cabal-install (4.45s)
PackageTests\AutoconfBadPaths\cabal.test.hs                                                                       SKIP no cabal-install (0.53s)
PackageTests\AutogenModules\Package\setup.test.hs                                                                 OK (1.51s)
PackageTests\AutogenModules\SrcDist\setup.test.hs                                                                 OK (2.23s)
PackageTests\Backpack\bkpcabal01\cabal.test.hs                                                                    SKIP no cabal-install (0.54s)
...
SKIP no cabal-install
END Test.Cabal.Server
GHCi exited with ExitFailure (-1073741510) (use -v for more information)
cabal-tests.exe: fd:4: hGetLine: end of file
```

Turns out that annotating the `readUntilEnd` and `readUntilSigil` calls to `hGetLine` shows that non-deterministically, one of them fails. If I also print the `script_path` provided, it is different each time, even sometimes it refers to tests which are marked as `skipIfWindows`.

I don't know how the `Test.Cabal.Server` is setup, maybe we are leaving the GHCi session in a zombie state?

**Expected behavior**
The test-suite should just run normally, as it does on CI.

**System information**
 - MINGW64_NT-10.0-22621 3.4.10.x86_64 Msys
 - cabal 3.10.2.0, ghc 9.6.3

### PR DESCRIPTION
**Pull request by jasagredo**
Closes #9571

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by Kleidukos** [comment]
> cabal-tests.exe: Most RTS options are disabled. Link with -rtsopts to enable them.

**Comment by jasagredo** [comment]
This PR fails consistently in CI with a Mingw error. 
```
Mingw-w64 runtime failure:
  VirtualProtect failed with code 0x5afrealgcc.exe: internal compiler error: Aborted signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
`gcc.exe' failed in phase `C Compiler'. (Exit code: 4)
...
realgcc.exe: fatal error: cannot execute 'C://tools//ghc-9.0.2//mingw//bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
`gcc.exe' failed in phase `C Compiler'. (Exit code: 1)
...
realgcc.exe: out of memory allocating 65536 bytes
`gcc.exe' failed in phase `C Compiler'. (Exit code: 1)
...
Unable to start C:\tools\ghc-9.0.2\mingw\bin/realgcc.exe (error code: 1455)
`gcc.exe' failed in phase `C Compiler'. (Exit code: 1)
...
*** Exception: dieVerbatim: user error (Error: <interactive>: 'C:\tools\ghc-9.0.2\bin\ghc.exe' exited with an error:
ghc-9.0.2.exe: osCommitMemory: VirtualAlloc MEM_COMMIT failed: The paging file
is too small for this operation to complete.
)
```

However I cannot reproduce it locally, `cli-suite` works with GHC 9.0.2:
```
=== cabal-install: cabal-testsuite =========================================== 17:03:41 ===
C:\Users\Javier\code\cabal\dist-newstyle-validate-ghc-9.0.2\build\x86_64-windows\ghc-9.0.2\cabal-testsuite-3\build\cabal-tests\cabal-tests.exe --builddir=/c/Users/Javier/code/cabal/dist-newstyle-validate-ghc-9.0.2/build/x86_64-windows/ghc-9.0.2/cabal-testsuite-3 --with-cabal=C:\Users\Javier\code\cabal\dist-newstyle-validate-ghc-9.0.2\build\x86_64-windows\ghc-9.0.2\cabal-install-3.13.0.0\x\cabal\build\cabal\cabal.exe -j4 --with-ghc=ghc --hide-successes --intree-cabal-lib=/c/Users/Javier/code/cabal --test-tmp=/c/Users/Javier/code/cabal/testdb +RTS --io-manager=native
...
PackageTests\Regression\T9756\cabal.test.hs                                                                       SKIP Windows (1.03s)
PackageTests\RequireExplicit\FlagInProject\cabal.test.hs                                                          SKIP Windows (0.79s)
PackageTests\RequireExplicit\MultiPkg\cabal.test.hs                                                               SKIP Windows (0.80s)
PackageTests\ShowBuildInfo\Complex\single.test.hs                                                                 SKIP needs ghc >= 9.2 (1.22s)
PackageTests\TemplateHaskell\dynamic\setup.test.hs                                                                SKIP no shared libs; no shared libs (1.64s)
PackageTests\VersionPriority\0-local.test.hs                                                                      SKIP Windows (1.78s)
PackageTests\VersionPriority\1-local.test.hs                                                                      SKIP Windows (1.54s)
PackageTests\VersionPriority\1-web.test.hs                                                                        SKIP Windows (1.64s)
PackageTests\VersionPriority\2-local.test.hs                                                                      SKIP Windows (1.65s)
PackageTests\VersionPriority\2-web.test.hs                                                                        SKIP Windows (1.54s)
PackageTests\VersionPriority\3-web.test.hs                                                                        SKIP Windows (1.51s)
PackageTests\WarnEarlyOverwrite\clean-install-by-copy.test.hs                                                     SKIP Windows (0.84s)
PackageTests\WarnEarlyOverwrite\clean-install-by-symlink.test.hs                                                  SKIP Windows (0.90s)
PackageTests\WarnEarlyOverwrite\dirty-install.test.hs                                                             SKIP Windows (0.99s)
GHCi exited with ExitFailure (-1073741510) (use -v for more information)
GHCi exited with ExitFailure (-1073741510) (use -v for more information)
GHCi exited with ExitFailure (-1073741510) (use -v for more information)
GHCi exited with ExitFailure (-1073741510) (use -v for more information)
555 tests, 104 skipped, 0 unexpected passes, 0 unexpected fails.
OK
<<< C:\Users\Javier\code\cabal\dist-newstyle-validate-ghc-9.0.2\build\x86_64-windows\ghc-9.0.2\cabal-testsuite-3\build\cabal-tests\cabal-tests.exe --builddir=/c/Users/Javier/code/cabal/dist-newstyle-validate-ghc-9.0.2/build/x86_64-windows/ghc-9.0.2/cabal-testsuite-3 --with-cabal=C:\Users\Javier\code\cabal\dist-newstyle-validate-ghc-9.0.2\build\x86_64-windows\ghc-9.0.2\cabal-install-3.13.0.0\x\cabal\build\cabal\cabal.exe -j4 --with-ghc=ghc --hide-successes --intree-cabal-lib=/c/Users/Javier/code/cabal --test-tmp=/c/Users/Javier/code/cabal/testdb +RTS --io-manager=native (933/951 sec)
```

Perhaps due to my machine having plenty of RAM memory? I don't really know where this comes from

**Comment by Mikolaj** [comment]
If that was a random CI failure after runner images get updated, I'd advocate disabling these tests on Windows. But since the trigger seems to be this PR, I'm worried there may be some disastrous interaction of the added feature with some strange OS settings that some users may have too (or they may have them on their github CI). In which case, are they going to have a similar problem if this PR gets merged?

**Comment by mpickering** [comment]
I suspect that WinIO is just broken on 9.0.2 and nothing more can be done about that.

**Comment by jasagredo** [comment]
> I suspect that WinIO is just broken on 9.0.2 and nothing more can be done about that.

However it doesn't fail on my local machine 🧩, only on CI.

**Comment by Mikolaj** [comment]
If that's always only 9.0.2 , disabling the tests on Windows only on 9.0.2 seems fine to me, regardless of whether we can reproduce it locally.

**Comment by ulysses4ever** [comment]
I'd prefer disabling individual tests over the whole configuration (Windows/GHC 9.0) if that's not too much trouble. But if it is, then it's fine too imo.

**Comment by Kleidukos** [comment]
My suggestion is that the validate script doesn't include this option in the GitHub CI environment. We can read environment variables just fine to take this decision.

**Review by Kleidukos — APPROVED** [review]

**Comment by geekosaur** [comment]
I think this only works by accident:
```
validate.sh: 332: [[: not found
```
See for example https://github.com/haskell/cabal/actions/runs/9757762049/job/26944807720?pr=10167#step:13:13.
(`[[` is a bash/ksh-ism; POSIX shells are not required to support it.)

**Comment by geekosaur** [comment]
@mergify backport 3.12

**Pull request merged**
