### PR TITLE
More consistently pass --package-db flag to tests

### PR DESCRIPTION
**Pull request by mpickering**
Previously `--package-db` was only passed to test which used the `v2-` prefix.

Now we pass `--package-db` to things which use the `v2-` prefix, not things which use the `v1-` prefix and by default assume that unprefixed commands are v2 commands.

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by alt-romes — APPROVED** [review]
Thanks! I've been bitten by this previously a couple of times... it's really not great for the testsuite behaviour of
`cabal "build" []` to differ from `cabal "v2-build" []`, and leads to quite incomprehensible failures 🚨

**Comment by Mikolaj** [comment]
Is this ready for merge? If so, @mpickering could you mark it so by setting one of the merge labels? Thank you.

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
@Mergify backport 3.12

**Pull request merged**
