### PR TITLE
Always use new hackage URI

### PR DESCRIPTION
**Pull request by bennofs**
This addresses the issue #1839.
As noted in the commit message, it also fixes a small bug in the upload URI generation when
the repo URI does not end with a slash.

### CODE REVIEW

**Comment by bennofs** [comment]
Oops, please don't merge this right now, I just found out that `relativeTo` also doesn't have the right behavior (it just discards the old uriPath).

**Comment by 23Skidoo** [comment]
Please also fix the Travis errors while you're at it.

**Comment by bennofs** [comment]
Ok, mistake and travis build fixed.

**Comment by 23Skidoo** [comment]
LGTM, merging. Thanks!

**Pull request merged**
