### PR TITLE
Switch from criterion to tasty-bench

### PR DESCRIPTION
**Pull request by Bodigrim**
**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

I've recently got frustrated by long CI build times. The patch improves them by eliminating 10 transitive dependencies:

* base-compat-batteries
* binary-orphans
* cassava
* code-page
* criterion
* criterion-measurement
* Glob
* js-chart
* microstache
* Only

As an author of `tasty-bench` I'm obviously biased, so feel free to ignore this shameless act of self-promotion ;) But otherwise `criterion` and `tasty-bench` have compatible APIs; `tasty-bench` capabilities seem sufficient for Cabal purposes, but dependency footprint is much smaller.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Anyone up to review? (I'm fine to be told that this is undesirable / unwanted / unsolicited)

**Review by geekosaur — APPROVED** [review]

**Comment by Kleidukos** [comment]
Wow, that's a nice replacement that you've got! Thank you @Bodigrim :)

**Review by Kleidukos — APPROVED** [review]

**Comment by Kleidukos** [comment]
@Bodigrim You can set the merge label and the bot will take care of the rest :+1:

**Comment by philderbeast** [comment]
> I've recently got frustrated by long CI build times.

I compared the CI run for this PR with that of #9615. The longest run for this PR was 100m for `Validate macos-latest ghc-8.8.4` while the longest run for #9615 was 105m for `Validate macos-latest ghc-8.6.5`. This PR ran 84m for `Validate macos-latest ghc-8.6.5` while #9615 ran 81m for `Validate macos-latest ghc-8.8.4`. Not sure I can take anything from those numbers other than they vary quite a bit.

Great to see the transitive dependencies reduced. Did you use `cabal freeze` to show those?

**Comment by Bodigrim** [comment]
> Great to see the transitive dependencies reduced. Did you use `cabal freeze` to show those?

That would be an easier approach ;) I compared `dist-newstyle/cache/plan.json` before and after.

**Pull request merged**
