### PR TITLE
Add manual workflow for flushing CI cache

### PR DESCRIPTION
**Pull request by fgaz**
This is a massive hack but it looks like it's the best available option?!?

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by jneira** [comment]
wow, thanks for the workaround but I really hope there could be another way to evict a corrupted cache

did it happened recently?

**Comment by fgaz** [comment]
> did it happened recently?

yes, see #8089 and #8096

> I really hope there could be another way to evict a corrupted cache

the other way is adding a version number to the cache key and raising it every time we want to "clear" the cache. and it looks like we will have to do that, because the cache isn't getting flushed (or it isn't getting flushed fast enough)!

```
$ curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/haskell/cabal/actions/cache/usage
{
  "full_name": "haskell/cabal",
  "active_caches_size_in_bytes": 41083004757,
  "active_caches_count": 45
}
```

**Comment by jneira** [comment]
unfortunately those pr logs seems to be inaccesible
Anyways, if cache corruption is improbable, I would evict it via version bump. We need to bump it to clean unused entries in the cabal store sooner or later anyways
It it becomes a regular problem we would need to tackle the root cause I suppose

**Comment by fgaz** [comment]
> We need to bump it to clean unused entries in the cabal store sooner or later anyways, as you have detected

Actually 40 GB of the 41 come from this pr 😅

**Pull request closed without merging**
