### PR TITLE
Set -Wno-prepositive-qualified-module in Paths_*.hs

### PR DESCRIPTION
**Pull request by matthewbauer**
This is based on / similar to https://github.com/haskell/cabal/pull/7219

We used import qualified M in Paths_*.hs, which might be disallowed in
GHC 8.10 when -Wprepositive-qualified-module is set.

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
Maybe it would be easier to use https://downloads.haskell.org/ghc/latest/docs/html/users_guide/using-warnings.html?highlight=w#ghc-flag--w

```haskell
{-# OPTIONS_GHC -w #-}
```

**Comment by Mikolaj** [comment]
I guess it would be easier and more future proof, though a bit less safe. @matthewbauer, what do you think?

**Comment by matthewbauer** [comment]
Yeah, that's fine with me - I've updated with this change. I suppose there could be warnings in Paths_*.hs that we do want to know about, but then again it's pretty small and I don't think it will hurt to ignore those warnings.

**Comment by Mikolaj** [comment]
I didn't *quite* pass the checks. Warnings turned into errors, probably.

**Comment by Mikolaj** [comment]
@matthewbauer: ping! :)

**Comment by matthewbauer** [comment]
ok! updated with what I think fixes the issue...

**Comment by Mikolaj** [comment]
@matthewbauer: thank you, the checks passed. @phadej: does it look good to you?

**Comment by Mikolaj** [comment]
No objections from @phadej, but he is busy, so I've added myself to reviewers instead. LGMT. Merging.

**Review by Mikolaj — APPROVED** [review]

**Comment by Mikolaj** [comment]
@emilypi: what's our etiquette, do I hit 'merge' now or ask the esteemed contributor to do so or seek yet another approval?

**Comment by emilypi** [comment]
@Mikolaj we generally want 2 approvals before merging. I'll have a review in today.

**Review by emilypi — APPROVED** [review]

**Comment by Mikolaj** [comment]
Thank you @matthewbauer, @phadej and @emilypi!

**Comment by jkachmar** [comment]
Are there plans to backport this to 3.4?

**Comment by emilypi** [comment]
@mergify backport 3.6

**Comment by emilypi** [comment]
@mergify backport 3.4

**Comment by emilypi** [comment]
@jkachmar good call. Backporting.

**Comment by jkachmar** [comment]
Thanks so much!

**Pull request merged**
