### PR TITLE
Add traceM and traceShowM

### PR DESCRIPTION
**Pull request by ffaf1**
Cabal codebase has its fair share of Applicatives/Monads. Adding traceM and traceShowM to the Compat.Prelude is quite convenient for testing purposes.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
What a fruitful weekend!

**Review by andreasabel — APPROVED** [review]
LGTM!

**Comment by Mikolaj** [comment]
@mergify unqueue

**Comment by Mikolaj** [comment]
@mergify unqueue

**Comment by Mikolaj** [comment]
@mergify unqueue

**Comment by Mikolaj** [comment]
@mergify unqueue

**Pull request merged**
